### ISSUE TITLE
[Bug]: Refresh problem using plugins

### ISSUE THREAD

**Issue by zk118** [apertureless/vue-chartjs#1009]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

When I have a computed chartOptions propety like this:

`
computed: {
 chartOptions () {
return { 
 ...
  plugins: {
   zoom: {...}
  }
 }
}
`

all the time the computed property is refreshed, the options are refreshed and the chart is updated, but it also resets the zoom plugin as it passes the plugins config to the chart, is there a way to pass the plugins config as a static object that doesn't refresh on chart update() and the others options as computed property ?

### Reproduction

none

### chart.js version

4

### vue-chartjs version

4.1.2

**Comment by evenmind** [comment]
Also when I have a custom plugin like that:

```
{
    id: 'myplugin',
    afterEvent: (chart, args) => {
    	console.log('event')
    }
}
```

the afterEvent callback is firing on each chart.update() with the last occurred event.
For example if I have a mousedown event firing just before chart.update(), then each chart.update() will fire mousedown event.
