### ISSUE TITLE
How to change momentjs locale for time scale?

### ISSUE THREAD

**Issue by hotrush** [apertureless/vue-chartjs#101]

**Comment by apertureless** [comment]
Well, thats not really related to vue-chartjs .
However according to the moment.js docs with `moment.locale(locale)`

According to the [Chart.js docs](http://www.chartjs.org/docs/#scales-time-scale) you can then pass in the formats in the options object.

**Comment by wopian** [comment]
Chart.js will use the globally defined moment locale if its set before the chart's added, according to https://github.com/chartjs/Chart.js/issues/3108#issuecomment-238104810
