### ISSUE TITLE
[Bug]: Can't update the chart

### ISSUE THREAD

**Issue by Aymeric-Tremoulet** [apertureless/vue-chartjs#1031]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Hello,

First of all, I am not entirely sure it's a bug or I'm using the library incorrectly.

I have a Bar chart, where the labels will never change but the datasets will.
When I say the datasets, i don't mean the data (values), I really do mean the datasets.

When i initially load the Barchart, there's 12 datasets with 48 data values in each.

After some filtering (triggered by multiple checkboxes), i need to TOTALLY replace the datasets.
In the first case, I'll only have 3 datasets, in the second 4 datasets.

Note that these 3 or 4 datasets doesn't match any of the 12 datasets originally filled in.

From what I've understood, I'm supposed to put the "data" object (containing both labels and datasets) as a computed method so modifying the data.datasets array would re-render the chart.

Not only this doesn't do anything but I can't figure out what's wrong (no errors in console). I've read the whole documentation a few times and all the related issues here. I'm clueless on how to troubleshoot that.

Thanks in advance for your help!

Side note: i've referenced my chart and tried to update() it using the Chart.js method, did nothing. Tried using the renderChart() method, and was told it didn't exist.

NB: Using JavaScript and not using Composition API (using VueX but not for this matter)

### Reproduction

https://stackblitz.com/edit/github-h9glhv?file=src/App.vue

### chart.js version

v4.3.0

### vue-chartjs version

v5.2.0

**Comment by fuschini** [comment]
I was having the same issues and altering the `:key` of the chart did the trick: [https://stackoverflow.com/questions/47459837/how-to-re-mount-a-component-in-vuejs](https://stackoverflow.com/questions/47459837/how-to-re-mount-a-component-in-vuejs)

**Comment by Aymeric-Tremoulet** [comment]
Insane. Did the trick, indeed. Thanks!
