### ISSUE TITLE
[Bug]: Security Issues warning from browser, can something done about it?

### ISSUE THREAD

**Issue by prakhartiwari0** [apertureless/vue-chartjs#1036]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

| Image 1 | Image 2|
| --- | --- |
| ![image](https://github.com/apertureless/vue-chartjs/assets/65062036/c20630ab-6808-45e4-9cd0-2d6051b0f374) | ![Screenshot from 2023-05-19 13-51-17](https://github.com/apertureless/vue-chartjs/assets/65062036/f3bca5d2-f1e1-443b-a76a-8641ad6ab56b) |

### Reproduction

Go to the main website

### chart.js version

v4.3.0

### vue-chartjs version

v5.2.0

**Comment by apertureless** [comment]
Which Browser are you using? Any extension?

**Comment by prakhartiwari0** [comment]
> Which Browser are you using? Any extension?

It's Brave v1.51.118

**Comment by prakhartiwari0** [comment]
I am not sure about the extensions part, but I don't think that popup can be due to an extension. And it's very much possible that it isn't shown to everyone.

**Comment by apertureless** [comment]
Interesting. I have the same version of brave and do not see it. 
It seems to be a "security" feature of chrome. That it detects urls that are looking like others. I guess the hyphen is the problem. 
It seems that it triggers mostly if you have app.example.com and your domain is app-example.com So it looks like a phishing domain to trick the user. 

However there seems to be no way to report this to chrome / brave to whitelist it.

**Comment by prakhartiwari0** [comment]
> Interesting. I have the same version of brave and do not see it. It seems to be a "security" feature of chrome. That it detects urls that are looking like others. I guess the hyphen is the problem. It seems that it triggers mostly if you have app.example.com and your domain is app-example.com So it looks like a phishing domain to trick the user.

Yep you are right

> However there seems to be no way to report this to chrome / brave to whitelist it.

That's unfortunate. Will brave bug report work in this case?
What exactly they are looking for to differentiate between a secure/authentic URL and a fake one, we may research more about this to know more. I don't have any web security knowledge so can't do much.
Maybe contacting the brave support mail shed some light on this issue.

**Comment by prakhartiwari0** [comment]
I also tried opening a guest window, there is no issue with that. I don't know why it's showing to me only (possibly I am the only one who cared and report). Or maybe they are testing this functionality on some users, not sure about that.
