### ISSUE TITLE
Standalone page support

### ISSUE THREAD

**Issue by christian-judt** [apertureless/vue-chartjs#1038]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

Both Vue and Charts.js support using their respective systems globally for a standalone browser page via standard (non-module) header script tag (<script type="text/javascript" src="..."/>) using the corresponding downloadable files https://cdn.jsdelivr.net/npm/vue@3.3.4/dist/vue.global.prod.js respectively https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.js.

vue-chartjs on the other hand seems to not support this way of itself being loaded into a standalone browser page. At least the file '/vue-chartjs/dist/index.js' at https://www.npmjs.com/package/vue-chartjs?activeTab=code doesn't offer a similar support.

### Describe the solution you'd like

My preferred solution would be to add support for simply adding the file '/vue-chartjs/dist/index.js' at https://www.npmjs.com/package/vue-chartjs?activeTab=code (or an alternative with an actual URL) to a  standalone browser page via standard header script tag below the corresponding tags for the code for Vue and Chart.js.

### Describe alternatives you've considered

I got the file '/vue-chartjs/dist/index.js' at https://www.npmjs.com/package/vue-chartjs?activeTab=code to behave as required by copying it and manually modifying it's header (the import statements) and footer (the export statement) to fit the requirements for standalone page usage.

**Comment by silane** [comment]
I've got it to work directly on browser using [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) and [esm.sh](https://esm.sh/). All you have to do is adding few lines in the header.

```html
<script type="importmap">
  {
    "imports": {
      "vue": "https://unpkg.com/vue@3.3.4/dist/vue.esm-browser.js",
      "chart.js": "https://esm.sh/chart.js@4.4.0",
      "vue-chartjs": "https://unpkg.com/vue-chartjs@5.2.0/dist/index.js"
    }
  }
</script>
```

Then use it inside `<script type="module">` and it totally worked.

```html
<div id="app">
  <chart-bar v-bind:options="{responsive: true}" v-bind:data="{
    labels: [ 'January', 'February', 'March' ],
    datasets: [ { label: 'foo', data: [40, 20, 12] } ]
  }"></chart-bar>
</div>

<script type="module">
import { createApp, ref } from 'vue';
import { Bar } from 'vue-chartjs';
import { Chart as ChartJS, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale } from 'chart.js';
ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale);

const app = createApp({
  components: { ChartBar: Bar },
});
app.mount('#app');
</script>
```
