### ISSUE TITLE
[Bug]: Error with package version

### ISSUE THREAD

**Issue by Rednas83** [apertureless/vue-chartjs#1046]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

yarn check returns an error (v1.22.19 classic) after migrating from prettier to "@antfu/eslint-config": "^0.39.5"
`error "vue-chart-3#chart.js@=> ^3.1.0" doesn't satisfy found match of "chart.js@4.3.0"`

Tried:
* Downgrading "chart.js" from "^4.3.0" to "^4.1.1" (same version as in vue-chart-3 package)
* yarn clean
* yarn install (after removing node_modules and yarn.lock)

### Reproduction

https://codesandbox.io/p/sandbox/nuxt3-vue-chart-qf6mvf

### chart.js version

v4.1.1 | v4.3.0

### vue-chartjs version

v3.1.8

**Comment by apertureless** [comment]
vue-chart-3 package is not vue-chartjs.

**Comment by Rednas83** [comment]
Thanks for the quick response.

Migrating vue-chart-3 to vue-chartjs indeed fixed the problem.

I only have 1 warning left
`warning chart.js@4.3.0: The engine "pnpm" appears to be invalid.`

But I understood the fix for that is to migrate yarn v1 to v2.

Thanks for the support on this.
