### ISSUE TITLE
[Bug]: Fill property is ignored in Line Chart

### ISSUE THREAD

**Issue by maxchak** [apertureless/vue-chartjs#1077]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Current behavior is: 
![image](https://github.com/apertureless/vue-chartjs/assets/77059246/d3efb3f8-1aa0-4547-a939-a5d58372912f)

However, the expected behavior is that the area below the graph will be filled with the passed backgroundColor:
![image](https://github.com/apertureless/vue-chartjs/assets/77059246/035d56e2-ee74-421f-befc-d3a1b664c32e)

### Reproduction

Pass this object to a line chart: {   labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],   datasets: [{     label: 'My First Dataset',     data: [65, 59, 80, 81, 56, 55, 40],     fill: true,     borderColor: 'rgb(75, 192, 192)',     backgroundColor: 'rgb(75, 192, 192, 0.5)',   }] }

### chart.js version

v4.4.1

### vue-chartjs version

v5.3.0

**Comment by maxchak** [comment]
My bad, had to import Filler from Chart JS

**Comment by maxchak** [comment]
My bad, had to register Filler from Chart JS

**Comment by stephanfriedrich** [comment]
@maxchak thanks for this hint.

i couldn't find this anywhere in the current documentation, but maybe i've got tomatoes on my eyes.
@apertureless  otherwise, this could be included in the documentation.

have a wonderful, cosy day
