### ISSUE TITLE
Seems like there is no way to use chartjs-gauge library with vue-chartjs. Is there a workaround?

### ISSUE THREAD

**Issue by kostadin-t** [apertureless/vue-chartjs#1081]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

Cannot integrate chartjs-gauge with vue-chartjs

### Describe the solution you'd like

It would be nice to be able to use chartjs-gauge the same way as the other chartjs components.

Here is the stackoverflow question: https://stackoverflow.com/questions/77880634/how-to-use-chartjs-gauge-with-vue-chartjs

**Comment by apertureless** [comment]
Well chartjs-gauge seems to be deprecated and not maintained anymore. As the last commit is 3 years ago.
So it does not support chartjs v4 it seems. https://github.com/haiiaaa/chartjs-gauge/issues/40

So I would say it wont work.
However as it exports itself https://github.com/haiiaaa/chartjs-gauge/blob/master/src/index.js#L16

You should be able to just import it.

```
import Gauge from 'chartjs-gauge`
```

And it should be registered. But like I said I doubt that it will work the the latest vue-chartjs version. As it does not seem to support the current chart.js version

**Comment by kostadin-t** [comment]
Thank you for the explanation.
