### ISSUE TITLE
[Bug]: Decimation is not applied

### ISSUE THREAD

**Issue by hanmarco** [apertureless/vue-chartjs#1102]
### Would you like to work on a fix?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Decimation of Chart.js is not applied in vue-chart.js

### Reproduction

https://stackblitz.com/edit/github-nadtmk?file=src%2FApp.vue

### chart.js version

4.4.3

### vue-chartjs version

5.3.1

**Comment by hanmarco** [comment]
I solved this problem by myself.
Thank you.

**Comment by wcheek** [comment]
How did you solve the problem?

**Comment by hanmarco** [comment]
@wcheek  Since my dataset wasn't larger than the `threshold` value, decimation wasn't being applied. So I explicitly set a smaller `threshold` value in the options.
