### ISSUE TITLE
[Bug]: Chart size not responsive

### ISSUE THREAD

**Issue by susanne99** [apertureless/vue-chartjs#1105]
Good Chart:
![goodchart](https://github.com/user-attachments/assets/a969b9ae-3d98-40d6-af5e-97e65781d202)

Good Chart: with narrow menu
![goodchart1](https://github.com/user-attachments/assets/6196f162-2f1e-496f-a50e-3fb93d504476)

Bad Chart: This happens when you make the left menu narrow and then wide again
![badchart](https://github.com/user-attachments/assets/be31cd98-a8c7-4bef-8920-3570b5e48d10)
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

i use vue3 with bootstrap vue next

I have a row with 2 columns. 
This is a detail view, which means that a menu is displayed in the left column and the details about it in the right. 
You can make the left column very narrow so that only icons can be seen to save space. 
I use this several times in my program - it works perfectly. only not with vue-chartjs. 
After reducing the size of the left column, the right side that contains the chart is no longer to the right of it but below it. 
I assume that height and width are not recalculated. 
the row is a flex container. 
What is the solution so that the two columns are still next to each other after changing the width of the left column.

### Reproduction

Unfortunately I don't have any code for reproduction because the program is already too big

### chart.js version

4.4.4

### vue-chartjs version

v5.3.1

**Comment by apertureless** [comment]
Check out the documentation of responsive charts in chart.js https://www.chartjs.org/docs/latest/configuration/responsive.html
