### ISSUE TITLE
[Bug]: vue chart watcher is not deep !!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by susanne99** [apertureless/vue-chartjs#1106]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

vue chart watcher is not deep !!!!!!!!!!!!!!!!!!!!!!!!!
if a i change the label of an existing dataset - nothing happens !!!!!!!!!!

### Reproduction

no

### chart.js version

lastest

### vue-chartjs version

lastest

**Comment by apertureless** [comment]
Yes because the chartjs data object is very huge with multiple attributes changing, thus `deep: true` will result in infinite watcher!!!!!!!!!!!!!!!
