### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by OmgImAlexis** [apertureless/vue-chartjs#111]
http://vue-chartjs.org/#/home?id=reactive-data

This is missing a backtick.
> Please keep in mind, that you have to set responsive: false to be able to set a fix width and `height.

**Comment by apertureless** [comment]
Thanks! Will fix it in the next iteration.

**Comment by apertureless** [comment]
🔨 Fixed with https://github.com/apertureless/vue-chartjs/commit/5da4b6165ed332cb00231d512933ff1336002572
