### ISSUE TITLE
Cannot switch off legend

### ISSUE THREAD

**Issue by mapsi** [apertureless/vue-chartjs#114]
Hello there,

Great work with this library! 👍 
Unfortunately, I don't seem to be able to set legend.display: false, like it's being overridden.

Is this a bug or a feature?

Cheers!

**Comment by apertureless** [comment]
Can you provide a jsfiddle or codepen for reproduction?

For me it is working https://codepen.io/apertureless/pen/qmZjrV

**Comment by mapsi** [comment]
You are absolutely right!
I had set the options in both data and computed. It's been a very long day.

So accept my apologies... On a different note, the codepen was really informative. 👍
