### ISSUE TITLE
Bar chart, barPercentage in X axis

### ISSUE THREAD

**Issue by xiclopex** [apertureless/vue-chartjs#119]
How can I modify the width of each bar (in a Bar Chart), I know in chartjs you can modify the barPercentage, but I cannot do it in vue-chartjs. Sorry if my question is stupid, I'am novice.

### Environment
- vue.js version: 2.1.10
- vue-chart.js version: development

**Comment by apertureless** [comment]
Hello @xiclopex 

well you actually do it the same way as in chart.js simply pass in the options.

```javascript
// first argument is the data, second argument the options
this.renderChart(data, {
  scales: {
    xAxes: [ {    
       categoryPercentage: 0.9,
       barPercentage: 0.5
    }]
  }
})

```

**Comment by apertureless** [comment]
🔐  Closed due to inactivity.
