### ISSUE TITLE
vue-chartjs height was 0 when i set v-show

### ISSUE THREAD

**Issue by ZengTianShengZ** [apertureless/vue-chartjs#120]
vue-chartjs height was 0 when  set v-show=‘true’
```
<div class="chart-bg"  v-show="true_or_false">
               <line-chart :options="{responsive: false, maintainAspectRatio: false}"
                                :width="674"
                                :height="400"
                                :lineData="lineData">
                 </line-chart>
</div>
```
i console log <line-chart components when mounted:
![image](https://user-images.githubusercontent.com/15622519/27167783-1d55e10a-51d5-11e7-965a-911aea29b52b.png)

 

### Environment

```
   "chart.js": "^2.6.0",
    "vue": "^2.3.3",
    "vue-chartjs": "^2.6.5",
     npm:3.3.6
```

**Comment by apertureless** [comment]
Hey @ZengTianShengZ 

can you please provide a minimal codepen or jsfiddle for reproduction?

It is working fine for me:

https://codepen.io/apertureless/pen/BZKBdX?editors=1010

**Comment by ZengTianShengZ** [comment]
sorry,i Can not reproduce the problem,but it can work now, thank you ！！！
