### ISSUE TITLE
Combination of Bar and Line Chart 

### ISSUE THREAD

**Issue by alokpandeyrc** [apertureless/vue-chartjs#123]
Is it possible to achieve combination of Bar and Line chart ?

### Environment
- vue.js version: <2.0>
- vue-chart.js version: <latest>
- npm version: <latest>

**Comment by apertureless** [comment]
Sure! Check out the docs for that: http://www.chartjs.org/docs/latest/charts/mixed.html

You only need to create chart from the bar basechart

```javascript
import {Bar} from 'vue-chartjs'

export default Bar.extend({....})
```

And in your dataset array you can change specific datasets to line.

**Comment by alokpandeyrc** [comment]
Thanx @apertureless....it worked...

**Comment by riksnelders** [comment]
Doesnt seem to work for me..

_WEBPACK_IMPORTED_MODULE_0_vue_chartjs__.a.extend is not a function

``` 
import {Bar} from 'vue-chartjs'

    export default Bar.extend({
 
        data(){
            return {
                options: {
                    responsive: true,
                    maintainAspectRatio: false
                }
            }
        },
        mounted () {
            this.renderChart({
                labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
                datasets: [
                    {
                        type: 'bar',
                        label: 'Bar Component',
                        data: [10, 20, 30],
                    },
                    {
                        type: 'line',
                        label: 'Line Component',
                        data: [30, 20, 10],
                    }
                ]
            }, this.options)
        }
    })

```

**Comment by apertureless** [comment]
Yeah with `v3` the syntax for chart creation has changed.

**Comment by mkstix6** [comment]
Could anyone post a full example of a mixed Bar and Line chart with separate axes here for `v3`? I'm struggling with this a little. I have managed to get lines to appear but not a bar at the same time.
