### ISSUE TITLE
Error in callback for watcher "chartData": "TypeError: Cannot read property 'data' of undefined"

### ISSUE THREAD

**Issue by alokpandeyrc** [apertureless/vue-chartjs#126]
The example is mentioned in this url:-
http://vue-chartjs.org/#/home?id=example
I was trying to do the same then found Reactive Data. After implementing the code mentioned in the url , I gor the warning mentioned in the Title and Error as Cannot read property 'data' of undefined.
Please help me to resolve it.

### Environment
- vue.js version: <2.8>
- vue-chart.js version: <latest>
- npm version: <latest>

**Comment by blackst0ne** [comment]
Did you fix this problem?

**Comment by wannymiarelli** [comment]
still having this issue using 3.3.1, is said fixed in 2.7
