### ISSUE TITLE
Ticks not working with reactive props

### ISSUE THREAD

**Issue by joe642** [apertureless/vue-chartjs#127]
### Expected Behavior
The Y axis scale should be returned as a formatted string with a £ sign.

### Actual Behavior
The callback works, but only when the data is loaded when the graph is loaded up empty

![image](https://user-images.githubusercontent.com/9432541/27429883-9f61bb6a-573e-11e7-920b-60cae69ddc94.png)

When the data is added in, the callback is not executed at all

![image](https://user-images.githubusercontent.com/9432541/27429906-b1d3d080-573e-11e7-9905-64de2e5599c1.png)

###
```
<script>
  import { Line, mixins } from 'vue-chartjs'
  import functions from '../../functions';

  export default Line.extend({
    mixins: [mixins.reactiveProp],
    methods: {
      render() {
        console.log(this.chartData);
        if (this.chartData) {
          this.renderChart(
            this.chartData, 
          {
            responsive: false,
            maintainAspectRatio: false,
            scales: {
              yAxes: [{
                ticks: {
                  callback: function(value, index, values) {
                    console.log(value)
                    return functions.moneyFormat(value);
                  },
                },
              }],
            },
          });
        }
      },
    },
    mounted() {
      this.render();
    },
  });
</script>
```

### Environment
- vue.js version: 2.2.1
- vue-chart.js version: 2.6.3
- npm version: 3.10.3

**Comment by apertureless** [comment]
Can you please post a jsfiddle or codepen for reproduction?

It is working fine more me:
https://codepen.io/apertureless/pen/BZKBdX?editors=1010

**Comment by joe642** [comment]
Thanks for getting back so quickly! I passed the options in as a prop as you did in your pen, rather than having it on the child component (like in my code above). It now works as expected.

**Comment by apertureless** [comment]
Oh yeah, thats because you passed the options directly to the renderChart method.
Which does not work with the reactivePropMixin. 

Because the reactiveProp mixin checks for updates and then call either `update()` or `this.renderChart(chartData, options)` 

So it required a prop or data model named options.
