### ISSUE TITLE
Generating Chart after clicking submit button

### ISSUE THREAD

**Issue by alokpandeyrc** [apertureless/vue-chartjs#128]
Hi,
i want to generate my chart @click submit ...i have included the files with it....Please help me out.

Chart document is my vue file and Mixchartss is my js file.
[Chart.txt](https://github.com/apertureless/vue-chartjs/files/1096232/Chart.txt)
[Mixchartss.txt](https://github.com/apertureless/vue-chartjs/files/1096234/Mixchartss.txt)

Actually after it i need to do an api call so i need to change it dynamically...can this be done?

### Environment
- vue.js version: <2.8>
- vue-chart.js version: <latest>
- npm version: <latest>

**Comment by apertureless** [comment]
Hey, I've wrote some tutorials about APIs and vue-chartjs. You can check them out here:

- [Let’s Build a Web App with Vue, Chart.js and an API Part 1](https://hackernoon.com/lets-build-a-web-app-with-vue-chart-js-and-an-api-544eb81c4b44)
- [Let’s Build a Web App with Vue, Chart.js and an API Part 2](https://hackernoon.com/lets-build-a-web-app-with-vue-chart-js-and-an-api-part-ii-39781b1d5acf)
- [Vue, Chart.js and WordPress](https://medium.com/@apertureless/wordpress-vue-and-chart-js-6b61493e289f)

Also also open source.
