### ISSUE TITLE
The page is blank？

### ISSUE THREAD

**Issue by wanghaixu** [apertureless/vue-chartjs#13]
### Actual Behavior
npm i => npm run dev => The page is blank

### Environment
- OS: Write here
- NPM Version: Write here
^1.1.3

**Comment by apertureless** [comment]
Hello @wanghaixu 

yes, the page is blank, because the entrypoint [index.js](https://github.com/apertureless/vue-chartjs/blob/master/src/index.js) contains only the exports of all modules. 

If you want to see the example charts you would have to create a vue instance and import the app component under the examples folder.

```javascript
import Vue from 'vue'
import App from './examples/App.vue'

/* eslint-disable no-new */
new Vue({
  components: { App }
}).$mount('#app')

```

**Comment by wanghaixu** [comment]
ok

**Comment by apertureless** [comment]
I will maybe change the webpack conf for develeopment so it does not use the index.js as an entry point, but a dev.js or main.js with the imported app.

**Comment by wanghaixu** [comment]
I want to apply to the mobile devices, but the effect is not very good。

**Comment by wanghaixu** [comment]
![image](https://cloud.githubusercontent.com/assets/15867133/19475970/44a48a00-9569-11e6-8ca4-196664515dab.png)

**Comment by apertureless** [comment]
You should check the [Chart.js documentation](http://www.chartjs.org/docs/)

There are two options for responsiveness:

- `responsive`
- `maintainAspectRatio`

If you set `responsive` to true, the chart will always fill the whole div in which the canvas is. If you set it to false, the canvas will set the width and height to the value which you set over the `width` and `height` props. And it resizes the chart, if the div resizes.

And with `maintainAspectRatio` you maintain the original canvas aspect ratio (width / height) when resizing

You can try to play around with this settings to get a better responsive view.
However you will have to apply styles etc. to the containing div.

**Comment by wanghaixu** [comment]
Thank you for your guidance
