### ISSUE TITLE
Update to webpack@3

### ISSUE THREAD

**Issue by apertureless** [apertureless/vue-chartjs#134]
May be a good idea to upgrade to webpack 3 to utilize some of the new features.

**Comment by nulty** [comment]
I'm using webpack 3, is there has the library been tested against it and is there known regressions?

**Comment by apertureless** [comment]
It should work without problems with webpack 3. 

This issue aims more for the build process as I am using an old vue cli template with webpack 1

**Comment by murilodag** [comment]
Hello @apertureless, could I work on it?

**Comment by imcvampire** [comment]
@apertureless Can I take this issue?

**Comment by apertureless** [comment]
Sure
