### ISSUE TITLE
where can i get the demo sources code? thanks

### ISSUE THREAD

**Issue by DarwinniwraD** [apertureless/vue-chartjs#143]
### Expected Behavior
where can i get the demo sources code? 

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Well, you have examples in the `src` folder https://github.com/apertureless/vue-chartjs/tree/develop/src/examples

However, if you mean the demo page, which is online, you can find the source here: https://github.com/apertureless/vue-chartjs-demo

**Comment by DarwinniwraD** [comment]
thank you very much, I've found the way to install it :)
