### ISSUE TITLE
legendCallback() doesn't render a custom legend

### ISSUE THREAD

**Issue by MOKuper** [apertureless/vue-chartjs#144]
### Expected Behavior
The legendCallback() as explained here [chartjs docs html legend](http://www.chartjs.org/docs/latest/configuration/legend.html?h=html%20legends)
should generate a custom legend

### Actual Behavior
The new chart options, of which legendCallback() is one, is being fired, but the legend doesn't end up in the chart

I made a codepen with a little example
https://codepen.io/MOKuper/pen/QgVmNq

### Environment
- vue.js version: 2.3.4
- vue-chart.js version: 2.7.1

### Do I love chart.js
yes I do

**Comment by k-rumi** [comment]
I think that is because legend.display is set to false.
If set to true, I see legends. See this URL(https://codepen.io/kutrumi/pen/eRPmNa?editors=1111). 

And legendCallback does not automatically substitute the default legends.
See this issue will help.
https://github.com/chartjs/Chart.js/issues/3262

Did I answer your question?

**Comment by MOKuper** [comment]
Not really, but I took a better look at the implementation, and the legend should be set to false, but indeed you need to generate the legend in a separate div. For me this isn't apparent from the documentation, and replacing the default legend seems more obvious to me.

Anyways, I am going to try out the new method and will post my findings :-)

**Comment by ssuess** [comment]
@MOKuper any updates on your findings? I need to generate a custom legend to but am having some problems getting it to work...

**Comment by jhaenchen** [comment]
I think he's basically saying that you have to declare and style the legend beforehand and then in the callback populate it using data from the provided chart instance. With document.getElementById and everything.

**Comment by apertureless** [comment]
You can generate a complete custom legend, if you want.

In the `options` you can set `legendTemplate` but you have to set `legend.display: false`

```js
scaleBeginAtZero: true,
          legendTemplate: '<ul class="<%=name.toLowerCase()%>-legend"><% for (var i=0; i<segments.length; i++){%><li class="chapter__item"><span style="background-color:<%=segments[i].fillColor%>"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>',
          legend: {
            display: false,
            position: 'left',
            fullWidth: true,
            labels: {
              fontSize: isXsScreen ? 13 : 18,
              fontFamily: "'Open Sans', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif"
            }
          },
```

Then you can generate it and save if in a local var

```js
this.legendMarkup = this.$data._chart.generateLegend()
```

And in your template you can do

```html
<div class="legend__list" ref="legend" v-html="legendMarkup"></div>
```

**Comment by alexisraca** [comment]
@apertureless where in the docs says that? when are the owners going to update the docs

**Comment by jgalindez2** [comment]
Yeah, you need to use the `legendCallback` but don't forget to call `this.$data._chart.generateLegend()`

**Comment by simonwebdev000000001** [comment]
iam using with react 
```
<Line
            ref={(chart: any) => {
              if (chart && chart.chartInstance) {
                chart.chartInstance.generateLegend();
              }
            }}
options={{
legendCallback(chart ) {
   return `<h1>Test</h1>`
}}
```
and i am not able to see generated dom legend. Any thoughts?

**Comment by codeBasePlusPlus** [comment]
legend: {
                            display: false,
                        },
                        legendCallback: function(chart) {
                            return `<p>hellos</p>`;
                        },
 .....
 thisComponent.$nextTick(() => {
                let d = bubbleExample.generateLegend();
                document.getElementById('scatterLegend').innerHTML = d;
            });
....
where 'scatterLegend' is a div id u manually create in template.
This works.
