### ISSUE TITLE
Custome label y axis

### ISSUE THREAD

**Issue by whitehorse0** [apertureless/vue-chartjs#147]
### Expected Behavior
Hi sir, i want to ask is it possible to custom scales yAxis ticks label?

### Actual Behavior
.....
ummm, if I want the scales yAxis ticks to be a value with percentage or dollar $. Is it possible?

many thank you, sir

**Comment by claide** [comment]
Yes tried that by inserting this option inside your `yAxes`.

```
ticks: {
   callback: function(label, index, labels) {
	 return '$'+label/1000;
   }
}
```

**Comment by apertureless** [comment]
Yep like @claide said, 
you have to create a custom callback for the xAxis ticks in your options object and pass it.

http://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats
