### ISSUE TITLE
Uncaught TypeError: Cannot read property 'draw' of null

### ISSUE THREAD

**Issue by bglaz** [apertureless/vue-chartjs#15]
### Expected Behavior
Chart will re-render when data is changed using `reactiveProp`

### Actual Behavior
`Uncaught TypeError: Cannot read property 'draw' of null`

### Description
Hello, I am trying to use the `reactiveProp` mixin to update a line chart.

When I do the following, I receive the error listed above.

```
this.chartData.datasets =
[
              {
                label: 'New Label',
                backgroundColor: '#f87979',
                data: [40, 20, 42, 20, 20, 20, 20, 20, 20, 20, 22, 21]
              }
            ]
```
From the below image, it looks the `_meta` object is being cleared out, but I don't know if this is related or not.

<img width="278" alt="screen shot 2016-10-31 at 12 00 46 pm" src="https://cloud.githubusercontent.com/assets/1025513/19861112/bc5d1ca4-9f61-11e6-842d-0684d980ad15.png">

### Environment
- OS: OSX
- NPM Version: 3.8.7

**Comment by apertureless** [comment]
Hey,

can you provide a bigger code snippet? 
I can't reproduce the issue.

**Comment by apertureless** [comment]
closed due to inactivity.
