### ISSUE TITLE
Accessibility - Add unique titles to frames

### ISSUE THREAD

**Issue by frankspin89** [apertureless/vue-chartjs#150]
### Expected Behavior
Frames must have unique title attribute
https://dequeuniversity.com/rules/axe/1.1/frame-title

### Actual Behavior
```
<iframe class="chartjs-hidden-iframe" tabindex="-1" style="display: block; overflow: hidden; border: 0px; margin: 0px; top: 0px; left: 0px; bottom: 0px; right: 0px; height: 100%; width: 100%; position: absolute; pointer-events: none; z-index: -1;">
```

### Environment
- vue.js version: <2.3.4>
- vue-chart.js version: <2.7.1>
- npm version: <4.2.0>

**Comment by apertureless** [comment]
Hey @frankspin89 

thanks for the issue.
However this is nothing I can fix. You should create this issue on the [Chart.js](https://github.com/chartjs/Chart.js) repository as the iframe comes from chart.js itself.

**Comment by frankspin89** [comment]
@apertureless done. https://github.com/chartjs/Chart.js/issues/4534
