### ISSUE TITLE
Fails to dynamically change height.

### ISSUE THREAD

**Issue by iamvitali** [apertureless/vue-chartjs#158]
I assign the height to `this.someVariable` and put it into `<..... :height="someVariable"></.....>`
I change the value of `this.someVariable` when I change the content of the chart (adding/removing things, basically a data filter that allows the user to add/remove things from the chart and as some labels can be very long I adjust the `this.someVariable` height accordingly).

### Expected Behavior
The chart size should change to the new height (everywhere where it has the height specified).

### Actual Behavior
The chart sort of changes the height in some places (like the height attribute in `<canvas>`, but in others, like the height in style attribute of `<canvas>` it's the old value).

P.S. I'm using `responsive: true` and `maintainAspectRatio: false` as I need the chart to be responsive but to have a fixed height (which is set by the `this.someVariable`).

So far I think what fixes the glitches for me is if (in the browser when it happens) I remove the `height: 100%;` from the `<iframe>` and remove `height: 400px;` from `<canvas>` (400px is the minimum number I assign to `this.someVariable`, that may be the reason why it's 400px there (though at the time when the `this.someVariable` is not `400` anymore). Although even if I re-add the the `height: 100%;` to the `<iframe>` back (once the `height: 400px;` is removed from `<canvas>`) it works fine. :/

Hope that makes sense? :)

### Environment
- vue.js version: 2.4.1
- vue-chart.js version: 2.7.1
- npm version: 3.10.10

**Comment by apertureless** [comment]
AFAIK the width and height attributes will only work with `responsive: false`. Because with `responsive: true` the canvas will be resized accordingly to it's container.

They updated their docs on this part http://www.chartjs.org/docs/latest/general/responsive.html#responsive-charts

The canvas can't detect resize changes. 
I will try to move out the `height` and `width` attributes from the canvas to the surrounding div. 
Maybe this could fix it.

**Comment by apertureless** [comment]
Okay, this seems to be working. If you set the width and height on the surrounding div, it will resize the canvas even if you have `responsive: true`.

Just thinking about a good api for that. As the width and height will be inline styles, I guess a styles object will the the way to go.

So you could do something like this:

```javascript
<template>
   <line-chart :styles="myStyles"/>
</template>

<script>
export default {
  data () {
    return {
          height: 100
    }
  },
  computed: {
    myStyles () {
      return {
        height: `${this.height}px`,
        position: 'relative'
      }
    }
  }
}
</script>
```

**Comment by apertureless** [comment]
Will be released in the next version. 👍
