### ISSUE TITLE
Base Charts' height: 200%

### ISSUE THREAD

**Issue by bdeanindy** [apertureless/vue-chartjs#164]
This is a question, feel free to close after answering...

### Expected Behavior

I believe that the base height of charts should be `100%` by default of containing element, not `200%`...right?

### Actual Behavior

[Vuestic](https://github.com/epicmaxco/vuestic-admin) just released an admin dashboard repo which uses this library and has example chart definitions within the dashboard. I opened [this issue](https://github.com/epicmaxco/vuestic-admin/issues/5) on the Vuestic repo, but while tracking down the CSS which might be causing this, I see that all of your Base Charts have their **default style height** set to `200%` (which I believe is what might be causing the issue I reported).

### Environment
- vue.js version: ^2.3.0
- vue-chart.js version: ^2.7.1
- npm version: 5.0.4

**Comment by wildpixeldesign** [comment]
+1 Was about to report this too

**Comment by apertureless** [comment]
Ups! You're right! Will be fixed ASAP

**Comment by apertureless** [comment]
It's fixed with `2.8.1`
