### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by leonardoEbert** [apertureless/vue-chartjs#167]
I'm having trouble on installation with the npm. It return a error that requires Vue on the version 2.4.2, and i have Vue 2.8.2 installed, how to solve this??

### Environment
- vue.js version: 2.8.2
- vue-chart.js version: 2.8.1
- npm version: 3.10.10

**Comment by apertureless** [comment]
Thats interesting. As the current vue.js version is 2.4.2 https://github.com/vuejs/vue/releases

So I don't know how you can have 2.8.2 :P

**Comment by leonardoEbert** [comment]
I forced the application to use Vue 2.4.2 and the error persisted. I checked the Vue version on my computer using the command prompt by typing `vue --version` and returned `2.8.2`

**Comment by wopian** [comment]
The `vue` CLI command is [`vue-cli`](https://github.com/vuejs/vue-cli) and not vue itself 😉

**Comment by apertureless** [comment]
Hey!

Well I guess, we have some confusing here.

If you type `vue --version` into your terminal, you will the the `vue-cli` version. [vue-cli](https://github.com/vuejs/vue-cli) is to scaffold your projects. 

You will need to install vue.js as a npm project dependency. 

So `yarn add vue` or `npm i vue -s` will fix your problem. ;)
