### ISSUE TITLE
how to get click on point in bar chart?

### ISSUE THREAD

**Issue by hekmatinasser** [apertureless/vue-chartjs#175]
hi 
how to get click on point in bar chart?

**Comment by apertureless** [comment]
Hey @hekmatinasser 

don't really get what you are wanting. 
You can check out the chart.js docs:

http://www.chartjs.org/docs/latest/configuration/tooltip.html

You have callbacks for the tooltips for example.

**Comment by apertureless** [comment]
close due to inactivity

**Comment by mushzak** [comment]
options: {
                scales: {
                    yAxes: [{
                        stacked: true
                    }],
                    xAxes: [{
                        stacked: true
                    }]
                },
                legend: {
                    display: true
                },
                responsive: true,
                maintainAspectRatio: true,
                onClick: function(evt) {
                    console.log(evt);
                }
            }
