### ISSUE TITLE
Entire Lodash Library Is Loaded!! 200kb chunk! 

### ISSUE THREAD

**Issue by DmacMcgreg** [apertureless/vue-chartjs#179]
You are loading the entire lodash library which is added 200kbs to my webpack bundle.
Can you not just use the lodash.merge library or even use lodash-es library?

![untitled_clipping_082317_040720_pm](https://user-images.githubusercontent.com/3266023/29636033-26ee0994-881d-11e7-8203-d3e12ad1e5bd.jpg)

**Comment by apertureless** [comment]
Oh I will check this. I am actually using `import merge from 'lodash/fp/merge'` and thought this will only load the merge function 🤔

**Comment by DmacMcgreg** [comment]
There are 3 options, we can use the lodash.merge librar

1. Use the lodash.merge library
2. Use the lodash-es library
3. Use another merge algorithm

I'll investigate and make a PR today!

Cheers!

**Comment by rriemann** [comment]
Please be aware of this issue. Maybe it is related.

```
s/app.js 2.85 kB 13 [emitted] app
js/manifest.js 1.73 kB 14 [emitted] manifest
app.85248a3e60a89725a8ca01782364614a.css 157 kB 13 [emitted] app
index.html 1.09 kB [emitted]

ERROR in ./node_modules/vue-chartjs/es/helpers/options.js
Module not found: Error: Can't resolve 'lodash/fp/merge' in '/opt/build/repo/node_modules/vue-chartjs/es/helpers'
@ ./node_modules/vue-chartjs/es/helpers/options.js 8:13-39
@ ./node_modules/vue-chartjs/es/BaseCharts/Scatter.js
@ ./node_modules/vue-chartjs/es/index.js
@ ./src/components/PieChart.js
```

**Comment by apertureless** [comment]
Will be fixed in the next release.

Lodash removed entirely as a dependency and replaced with `Object.assign()`

**Comment by coremyslo** [comment]
lodash.merge still a dependency in vue-chartjs@2.8.7

**Comment by apertureless** [comment]
Yes because object.assign does not work for deep nested objects. And the chart options can have deep nested objects.

However now `lodash.merge`  is a dependency and not `lodash` . Which results in smaller bundle size.
