### ISSUE TITLE
Responsive Width, Fixed Height

### ISSUE THREAD

**Issue by alexsasharegan** [apertureless/vue-chartjs#180]
### Expected Behavior

I would like to render a chart width a `100%` width, but a fixed height (e.g. `500px`). I would also like the chart to resize according to those constraints (without maintaining aspect ratio).

### Actual Behavior

Currently, I'm having trouble working with the `responsive`/`maintainAspectRatio` options. Regardless of my styling & options, the height seems to grow beyond it's containing elements (I believe it's using a `1:1` aspect ratio).

I can easily get something working when I feed the chart numeric width/height as a landscape ratio `w:h` (e.g. `<line-chart :chart-data="chartData" :width="5" :height="1" />`). Since the prop validation expects a number, I'm wondering if my desired behavior is possible with the current api.

![image](https://user-images.githubusercontent.com/16269252/29642119-cddfeeb8-881b-11e7-8a8f-fced4a4049d7.png)
![image](https://user-images.githubusercontent.com/16269252/29642270-b51f404e-881c-11e7-9f42-2a0f9fc76a3f.png)

### Environment

- vue.js version: `2.4.2`
- vue-chart.js version: `2.8.2`
- npm version: `5.3.0`

**Comment by apertureless** [comment]
With `responsive: true` the canvas will ignore the width and height parameters and grow always 100% of the outer container.

With the `@2.8` release you can pass two additional props. 
One is the `css-classes` for the outer div and the other is a `styles` object which gets applied as inline styles to the outer div.

https://github.com/apertureless/vue-chartjs/releases/tag/v2.8.0

So I would not go over the `width` and `height` props, because they are applied directly to the cnavas. You can try to either pass a style object with 

```js
{
    height: '500px',
    width: '100%',
    position: 'relative'
}
```

Or you can make a css class with that properties and pass it.

**Comment by wannymiarelli** [comment]
Using the styles as follow
`<sale-chart :styles="{height: '250px', position: 'relative'}"></sale-chart>`
the chart does not respect the given size of 250px

**Comment by apertureless** [comment]
Do you have `maintainAspectRatio` set to true or false?

Can you maybe post a minimal codepen for reproduction?

**Comment by alexsasharegan** [comment]
Here's a fiddle: https://jsfiddle.net/alexsasharegan/v6dj7qr3/

It appears to be working in here. I'll double back on my setup and see what I spot that's off.

**Comment by alexsasharegan** [comment]
Interesting... in your Line Chart render function, I don't see the code that would propagate the style object down on the canvas like I'm seeing in the fiddle repro:

```js
export default Vue.extend({
  render: function (createElement) {
    return createElement(
      'div', {
        style: this.styles,
        class: this.cssClasses
      },
      [
        createElement(
          'canvas', {
            attrs: {
              id: this.chartId,
              width: this.width,
              height: this.height
            },
            // Wouldn't there be a copy of the style obj here?
            ref: 'canvas'
          }
        )
      ]
    )
  },
}
```

**Comment by alexsasharegan** [comment]
# Fixed

Switching my component definition to the following solved my problem. This makes me think that somewhere in the chain my `maintainAspectRatio` setting was getting merged with the default `true` in a way that merged the truthy value. Maybe, maybe not. But this works nicely now, so feel free to close this or keep it open for @wannymiarelli .

```vue
<script>
import { Line, mixins } from "vue-chartjs"
import { plainObj } from "@/core/object"

export default Line.extend({
  mixins: [mixins.reactiveProp],
  props: {
    options: {
      type: Object,
      default: plainObj
    }
  },
  mounted() {
    this.renderChart(this.chartData, this.options)
  },
  data() {
    return {
      defaultOptions: {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            },
            gridLines: {
              display: true
            }
          }],
          xAxes: [{
            gridLines: {
              display: false
            }
          }]
        }
      },
      plugins: []
    }
  },
})
</script>
```

**Comment by DespertaWeb** [comment]
Perhaps having : `maintainAspectRatio` set to true would be a good way to go.

**Comment by apertureless** [comment]
@DespertaWeb 

As this issue is quite old (nearly 2 years), there are no default options anymore.
With `vue-chartjs` v3 all stylings and options made by me were removed. The reason is that you now have a *clean*  chart component, as you would use chart.js directly.

**Comment by AwesomeDude78** [comment]
The height rerenders with promises.
<script>
import { Bar, mixins } from 'vue-chartjs';

const { reactiveProp } = mixins;

export default {
  extends: Bar,
  mixins: [reactiveProp],
  props: ['chartOptions'],
  mounted() {
    this.renderChart(this.chartData, this.chartOptions);
  },
  watch: {
    chartData() {
      // eslint-disable-next-line no-underscore-dangle
      this.renderChart(this.chartData, this.chartOptions);
    },
  },
};
</script>

The watcher rerenders the chart with changes in the chartData

**Comment by varlen** [comment]
I had the same problem and fixed it by adding the renderChart call in a chartData watcher... However, isn't it kinda weird having to use this solution while using the reactiveProp mixin? Shouldn't the mixin already do all the work by itself?
