### ISSUE TITLE
[Best Practices❓] Usage of Private Data

### ISSUE THREAD

**Issue by alexsasharegan** [apertureless/vue-chartjs#182]
### Expected Behavior

Rather than dynamically setting a _private_ data property `_chart` on the chart instance after creation, use standard `data` method to define property.

### Actual Behavior

Currently the Chartjs `_chart` is set at the time `renderChart` is called. Ideally, this would be stubbed out in the data method. This will keep Vue from ever overwriting `_chart`, however unlikely. The gotcha is that Vue's data proxy goes away for props beginning with `$` & `_`. They must be referenced instead like so: `this.$data._chart`.

Of course, using the private notation _"the right way"_ for Vue means Vue will now reactively watch those props. This may not be the desired effect. In any case, this is just a question. It is not currently affecting the library in any negative way that I can see.

### Environment
- vue.js version: 2.4.2
- vue-chart.js version: 2.8.2
- npm version: 5.3.0

**Comment by apertureless** [comment]
Hm thats interesting.

I will check if it would have any side effects. In the beginning I did not think about exposing the chart.js instance, however it was proven to be a good idea, as people could modify a lot of stuff this way.

It way actually only [introduced](https://github.com/apertureless/vue-chartjs/pull/3/commits/998b190007ebe917024dcab44491b8c3e1449375) to properly cleanup the chartjs object and destroy the instance :D 

But this seems to be a good idea to make it more future proof. ✌️
