### ISSUE TITLE
Access canvas object from parents

### ISSUE THREAD

**Issue by HiepVu511** [apertureless/vue-chartjs#184]
Hi,
Sorry if this is a noob question. 
Basically, I want to add gradient background color to a bar chart which receive data from a parent component, so I guess I have to pass the backgroundColor property from parent component too.
So how can I access the canvas object of a chart from the parent component?

**Comment by apertureless** [comment]
You can access the canvas over the `refs` . Inside your chart component you can access it over `this.$refs.canvas`.

**Comment by HiepVu511** [comment]
That work great, Thanks !!!
