### ISSUE TITLE
Rounded corner for Bar chart

### ISSUE THREAD

**Issue by HiepVu511** [apertureless/vue-chartjs#185]
Hi,
I did some google and find that if you want to make a Bar chart with rounded corner in Chartjs
, you will have to extend the default one.
So how can I do that with your awesome library ?

**Comment by apertureless** [comment]
Hey @HiepVu511 

mh how would you normally do the rounded corners in chartjs?

**Comment by apertureless** [comment]
Okay, I saw this https://github.com/chartjs/Chart.js/issues/3072

So it seems you would have to edit the global `Chart.elements.Rectangle.prototype.draw = function() `

However I think this is not possible right now as you don't have access to the Chart package inside the base class.
