### ISSUE TITLE
Regression in 2.8.3

### ISSUE THREAD

**Issue by Tirke** [apertureless/vue-chartjs#190]
Since you replaced lodash `_.merge` by a custom `Object.assign` call, you have a pretty bad regression on default styles because lodash `._merge` does more than `Object.assign` (it works recursively on nested objects).

#### Consequence  
Default styles are not correctly merge and many of my graphs look different after update. I will do my own merge for the moment but you should fix that 😄

**Comment by apertureless** [comment]
Oh yeah did not thought about nested object.
Will fix it.

**Comment by wernerm** [comment]
+1 I'm also working around it at the moment by using `deepmerge` (https://github.com/KyleAMathews/deepmerge)

**Comment by apertureless** [comment]
Will with fixed with #191 

Replaced object.assign with `deepmerge` as it seems to be a nice small and lightweight lib :3

**Comment by apertureless** [comment]
Fixed with version `2.8.4`
