### ISSUE TITLE
deepmerge

### ISSUE THREAD

**Issue by f** [apertureless/vue-chartjs#194]
### Expected Behavior
Load correctly.

### Actual Behavior
deepmerge not installed.

```
This dependency was not found:

* deepmerge in ./node_modules/vue-chartjs/es/helpers/options.js
```

### Environment
- vue.js version: 2.4.2
- vue-chart.js version: 2.8.5
- npm version: 5.3.0

**Comment by f** [comment]
Interestingly, you removed deepmerge dep. and it doesn't use anywhere. This shouldn't happen. Will try to clean yarn cache.

**Comment by f** [comment]
Nothings changed. I cannot understand why this happens:

This is the source of build output of `es/helpers/options.js`
```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.mergeOptions = mergeOptions;

var _deepmerge = require('deepmerge');

var _deepmerge2 = _interopRequireDefault(_deepmerge);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function mergeOptions(obj, src) {
  return _deepmerge2.default.all(obj, src);
}
```

**Comment by apertureless** [comment]
Okay... that... is really weird. I will make a new publish on npm. I guess something went wrong there 🤔 

Please check `2.8.6`
