### ISSUE TITLE
Unmet Peer Dependency

### ISSUE THREAD

**Issue by leonardoEbert** [apertureless/vue-chartjs#196]
### Actual Behavior
I apologize for opening one more issue, but I have the same problem with the previous issue, as far as the Vue.JS version is concerned.
 I have it installed in the latest version on my computer, and the library is still giving warning about needing version 2.3.4 of Vue. 
I also tried running the project by installing and using Vue version 2.3.4, but it did not solve the problem.
The other dependencies are all right, only the one that does not let the code compile ...

### Environment
- vue.js version: 2.4.4
- vue-chart.js version: 2.8.6
- npm version: 3.10.10

**Comment by apertureless** [comment]
Can you show your package.json?

**Comment by leonardoEbert** [comment]
![capturar](https://user-images.githubusercontent.com/29580196/30481369-88e69d3a-99f4-11e7-854e-0d85e362a87d.PNG)

**Comment by apertureless** [comment]
What does the error exactly say? 
Normally it should be a `warning` because right now the `peerDependency` is Vue@2.4.2` however it should work with others versions too.

**Comment by leonardoEbert** [comment]
![capturar2](https://user-images.githubusercontent.com/29580196/30496082-bd27c6ac-9a24-11e7-8843-e9bc2ad20233.PNG)
![dependencias](https://user-images.githubusercontent.com/29580196/30496081-bd1386ce-9a24-11e7-8e15-e7e9d687dffc.PNG)

I've just created a new Quasar project and only installed these dependencies and return these errors

**Comment by apertureless** [comment]
You have to `npm install chart.js vue-chart.js`, because `chart.js` is also a peerDependency.

You should also run an `npm install`or `yarn install` first. So that vue gets installed.

I am only getting a warning that the Vue peerDependency has a version mismatch. Which is not a big deal. As vue-chartjs should be compatible with older versions of vue, too.

<img width="700" alt="bildschirmfoto 2017-09-15 um 22 06 23" src="https://user-images.githubusercontent.com/4975917/30501320-4d4897ec-9a62-11e7-82eb-c18cec9954e4.png">

<img width="530" alt="bildschirmfoto 2017-09-15 um 22 04 03" src="https://user-images.githubusercontent.com/4975917/30501326-5051a938-9a62-11e7-8d9e-f47de8bb1b49.png">

**Comment by leonardoEbert** [comment]
I will try to run the project here, thanks for your help and your attention. And congratulations for the lib

**Comment by leonardoEbert** [comment]
Hi, my component it's not rendering, could you show me a sample or the code that you used to create the example you used above??

**Comment by apertureless** [comment]
Sure

https://github.com/apertureless/vue-chartjs-quasar

**Comment by leonardoEbert** [comment]
Hello, sorry to bother again, but I still have problems rendering the component. 
I downloaded all the Quasar project that you created and executed it, and that screen that you showed in the example worked. 
However, using the same component, but importing it into a component that I created it does not render in any way, I am there hours trying to figure out what the problem is but I did not succeed

![capturar](https://user-images.githubusercontent.com/29580196/30596421-68c4b102-9d2a-11e7-946e-266d688adcb0.PNG)

**Comment by apertureless** [comment]
You need to import it without the brackets. 

Vue components have an `export default` which is an unnamed export.  So you could also say `import A from '../charts/Chart.vue` and it would work.

The brackets are for ES6 named module exports like

```js

export const Alpha = () => { console.log('alpha') }
export const Beta = () => { console.log('beta') }

```

And then you could 

```js
import { Alpha } from './foobar'

```

or 

```js

import { Alpha, Beta } from './foobar'
```

or

```js

import * as Versions from './foobar'

// and then use it

Version.Alpha()

Versions.Beta()
```

**Comment by leonardoEbert** [comment]
Now it works perfectly...
Thanks man, again
