### ISSUE TITLE
🔥 Remove Vue.extend()

### ISSUE THREAD

**Issue by apertureless** [apertureless/vue-chartjs#201]
## Current state

The [Base Charts](https://github.com/apertureless/vue-chartjs/blob/develop/src/BaseCharts/Bar.js) are using the [Vue.extend()](https://vuejs.org/v2/api/#Vue-extend) which creates a subclass of the base vue constructor.

This way if you create your own components, you can `extend` the base component.

```js
import {Line} from 'vue-chartjs'

export default Line.extend({
 mounted () {
    this.renderChart(data, options)
  }
})
```

I really liked the concept back then ( Jun 2016 first commit 😄  ). However it creates **a lot** of confusion to people new to Vue.js

And it is not really nessasary.

## Proposal

To clean up the API and usage the `Vue.extend()` should be removed. And extending the base component should be done with either [extends](https://vuejs.org/v2/api/#extends) or [mixins](https://vuejs.org/v2/guide/mixins.html)

This way, your component would look like this:

```js
import {Line} from 'vue-chartjs'

export default {
 extends: Line,
 mounted () {
    this.renderChart(data, options)
  }
}
```

or

```js
import {Line} from 'vue-chartjs'

export default {
 mixins: [Line],
 mounted () {
    this.renderChart(data, options)
  }
}
```

This way own components would be standard vue component style. 
It is a breaking change, but without much efford to fix. 

Scheduled for `v3`

Another benefit would be the decreased size, as the old version needs the base vue constructor, and bundle vue into it.

## Todo

- [x] Remove `Vue.extend()`
- [x] Update docs
- [x] Update examples
- [x] Rewrite private data #182 

## Testing

`yarn add vue-chartjs@next`

**Comment by kimuraz** [comment]
May I take this one @apertureless ?

**Comment by apertureless** [comment]
Hey @kimuraz 

well it's already done. https://github.com/apertureless/vue-chartjs/tree/feature/v3

But needs some testing and I need to update the docs. Thats why this issue is still open.

**Comment by kimuraz** [comment]
That's ok, if I can be useful in any of these tasks, let me know.

I can also update the docs translation (pt-br) for the new version. Is it ok?

**Comment by huangche007** [comment]
this change is so cool

**Comment by amitmeghare** [comment]
its cool...
