### ISSUE TITLE
Commit the final dist js files to github

### ISSUE THREAD

**Issue by mika76** [apertureless/vue-chartjs#202]
### Expected Behavior
js and min.js files should be in /dist folder

### Actual Behavior
We use vue, chartjs and vue-chartjs from within an older c# asp.net mvc site and do not use babel or webpack so we depend on the final js files to include in our projects. We currently pick them up from the cdn, but I think they should be officially in the github repo as well. We shouldn't have to depend on cdn for finding required files.

**Comment by apertureless** [comment]
Hey @mika76 

So you're also not using npm ?

**Comment by mika76** [comment]
Heh not currently. All manual.

**Comment by apertureless** [comment]
Oh okay, I see. I will re-add the dist files ✌️

**Comment by apertureless** [comment]
Readded :)

**Comment by mika76** [comment]
Thanks a mill! 🙇
