### ISSUE TITLE
Last release is causing problems with Firefox

### ISSUE THREAD

**Issue by mika76** [apertureless/vue-chartjs#203]
### Expected Behavior
Line chart and pie chart

### Actual Behavior
In firefox (Chrome works fine) we get a "SyntaxError: nothing to repeat" error.

We are using the min.js file directly so I cannot be more helpful than that with details...

![screen shot 2017-09-18 at 10 34 14](https://user-images.githubusercontent.com/229311/30535584-1f801e04-9c63-11e7-9fac-ba9af25fb920.png)

vue-2.4.4
vue-chart-js 2.8.6

**Comment by mika76** [comment]
PS: Going back to 2.8.1 works fine.

**Comment by apertureless** [comment]
Are you using a build system? 
I've tried the [Codepen Example](https://codepen.io/apertureless/pen/vxWbqB) in Firefox and it works fine. Are you using the vue-chartjs.full.min.js ?

**Comment by mika76** [comment]
Yes vue-chartjs.full.min.js

**Comment by apertureless** [comment]
Please try the v3 version.
