### ISSUE TITLE
使用动态数据时报错

### ISSUE THREAD

**Issue by wxh2013** [apertureless/vue-chartjs#204]
### Actual Behavior

![image](https://user-images.githubusercontent.com/7362131/30549528-98b90d20-9c5a-11e7-885b-0650474ae400.png)

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Code ?

**Comment by apertureless** [comment]
closed due to inactivity
