### ISSUE TITLE
Mixed chart

### ISSUE THREAD

**Issue by maziarz** [apertureless/vue-chartjs#206]
Hi there. I was looking through the docs and wondering if it is possible to use [mixed](http://www.chartjs.org/docs/latest/charts/mixed.html) chart?

**Comment by apertureless** [comment]
Sure

Check out https://github.com/apertureless/vue-chartjs/issues/123  https://github.com/apertureless/vue-chartjs/issues/29

Use the Bar Chart as default and in your data define the line chart.

**Comment by maziarz** [comment]
Works like a charm. Cheers!
