### ISSUE TITLE
typescript definition?

### ISSUE THREAD

**Issue by schoening** [apertureless/vue-chartjs#207]
Can we add a typescript definition please :)

**Comment by apertureless** [comment]
Well I guess this will be a bit hard, as the typescript definition should be provided directly by chart.js or am I wrong?

Otherwise feel free to submit a PR. As I am not using typescript and don't know how to make it :P

**Comment by schoening** [comment]
I made a very basic one that just makes TypeScript go "yeah whatever" :p 

You are probably right about chart.js needing one instead. There already is one.. I will give that a try and see if it is enough.

**Comment by jayalakshmis** [comment]
Is there a sample that uses typescript anc vue-chartjs that i can possibly look at?

**Comment by juanbrujo** [comment]
> @schoening Is there a sample that uses typescript anc vue-chartjs that i can possibly look at?

https://github.com/apertureless/vue-chartjs/issues/495#issuecomment-663034152
