### ISSUE TITLE
Upgrading from 2.8.2 to 2.8.3 breaks charts

### ISSUE THREAD

**Issue by huysamen** [apertureless/vue-chartjs#209]
### Expected Behavior

That charts render as normal.

### Actual Behavior

Nothing renders.  No errors.

### Environment
- vue.js version: 2.4.4
- vue-chart.js version: 2.8.3, 2.8.4, 2.8.6, 2.8.7
- npm version: 5.4.2

**Comment by huysamen** [comment]
Might be an issue with the reactive properties.  When using a computed property as the chart data, nothing renders.  Changing some files so that the hot reload module reloads the application causes the chart to be rendered (albeit it being rendered in the incorrect position outside of its div).

**Comment by wernerm** [comment]
Also experiencing the same problem, but I have failed to reproduce outside of the project. However, in my case the problem was introduced in 2.8.5 (2.8.4 works fine).

**Comment by apertureless** [comment]
Can you post a codpen/jsfiddle/webpackbin for reproduction?

**Comment by tesarwijaya** [comment]
this env works well
chart.js: 2.7.0,
vue: 2.4.2,
vue-chartjs: 2.8.7

**Comment by apertureless** [comment]
Closed due to inactivity
