### ISSUE TITLE
Error in rendering

### ISSUE THREAD

**Issue by achintverma** [apertureless/vue-chartjs#21]
### Expected Behavior
Based on the examples the graph should render when provided data. 

### Actual Behavior

Error: [Vue warn]: Failed to mount component: template or render function not defined. 

### Environment
- OS: Mac
- NPM Version: 3.10.8

**Comment by apertureless** [comment]
Which Version of vue are u using ?

Am 19.12.2016 03:36 schrieb "Achint Verma" <notifications@github.com>:

**Comment by achintverma** [comment]
Hi, Thanks for your reply. I figured the issue was not having the exclusive <script> tag. Although file was js extension, I see Vue requires it's components to have exclusive <script> and <template> tags (if template is not defined already).
