### ISSUE TITLE
this demo is not support, is it because version older?

### ISSUE THREAD

**Issue by llccing** [apertureless/vue-chartjs#210]
### Expected Behavior

![image](https://user-images.githubusercontent.com/12945329/31005098-d4c156e2-a529-11e7-8713-ab658c1f1659.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/12945329/31005114-e78fa2ba-a529-11e7-887c-814bf1ca0553.png)

this is demo from [Echarts Examples](http://echarts.baidu.com/demo.html#pie-nest)

### Environment
- vue.js version: 2.4.2
- vue-chart.js version: 2.4.1
- npm version: 5.3.0

**Comment by apertureless** [comment]
😕  Well I guess you're wrong here. Your example is about EChats. This repo is a wrapper für Chart.js 

That are two different charting libraries.

**Comment by llccing** [comment]
@apertureless ,sorry, not Echarts let me ask this question

**Comment by apertureless** [comment]
In Chart.js you don't have this kind of charts in your example.
