### ISSUE TITLE
Some Error

### ISSUE THREAD

**Issue by huangche007** [apertureless/vue-chartjs#217]
When i click the same tab more time，the view become smaller and smaller,

[1]: /img/bVWmJT
[2]: /img/bVWmKk
[3]: /img/bVWmKn

some code as follow:
`options: {
          tooltips: {
            intersect: false // default: true. if true, the tooltip mode applies only when the mouse position intersects with an element. If false, the mode will be applied at all times.
          },
          animation: {
            duration: 1000  // 动画时长单位:ms
          },
          responsive: true, // 长宽，100%.如果要单设长和宽的话，要将responsive 设为false
          maintainAspectRatio: false // 保持长宽比
        },`

**Comment by apertureless** [comment]
Which tab? 
Do you have a codepen exmaple for reproduction?

**Comment by huangche007** [comment]
sorry you can close it，That is my problem。
