### ISSUE TITLE
How to achieve this effect?

### ISSUE THREAD

**Issue by huangche007** [apertureless/vue-chartjs#218]
I want to achieve like this:
[http://vue-chartjs.org/assets/line.png](http://vue-chartjs.org/assets/line.png)，how can i make it？

**Comment by apertureless** [comment]
You can check out the tutorial: 
https://hackernoon.com/creating-stunning-charts-with-vue-js-and-chart-js-28af584adc0a

**Comment by huangche007** [comment]
I can not access to this website，some code 

`label: '稀土日均价',
              data: [],
              //设置图标显示的颜色
//              backgroundColor: '#f87979',
              fillColor : "rgba(151,187,205,0.5)",
              strokeColor : "rgba(151,187,205,1)",
              pointColor : "rgba(151,187,205,1)",
              pointStrokeColor : "#fff",
              borderWidth: 1`

But not work

**Comment by huangche007** [comment]
@apertureless

**Comment by apertureless** [comment]
You can try it here: https://dev.to/apertureless/creating-stunning-charts-with-vuejs-and-chartjs

The "trick" is, that chart.js uses the normal html canvas. So you can use for example [createLinearGradient](https://developer.mozilla.org/de/docs/Web/API/CanvasRenderingContext2D/createLinearGradient)

So you can do for example:

```js
this.gradient = this.$refs.canvas.getContext('2d').createLinearGradient(0, 0, 0, 450)
this.gradient.addColorStop(0, 'rgba(255, 0,0, 0.5)')
this.gradient.addColorStop(0.5, 'rgba(255, 0, 0, 0.25)');
this.gradient.addColorStop(1, 'rgba(255, 0, 0, 0)');
```

And in your dataset you can simply add it as a background color

```
 backgroundColor: this.gradient
```

Like here in the demo page: https://github.com/apertureless/vue-chartjs-demo/blob/master/src/components/BarExample.js

**Comment by huangche007** [comment]
@apertureless Thanks a lot
