### ISSUE TITLE
在图表上左右滑动会出现数据错乱的问题

### ISSUE THREAD

**Issue by huangche007** [apertureless/vue-chartjs#222]
这里有一个tab，当我从一月切换到三月，然后左右滑动的时候，发现三月显示的数据会出现错乱(会显示一月的时候)
我录制了一份gif图，大佬们可以看看.
[效果图](http://img.blog.csdn.net/20171011150653325?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMDYyNDk4Ng==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

**Comment by apertureless** [comment]
Hey @huangche007 
sorry I don't really understand the issue :o

**Comment by huangche007** [comment]
@apertureless I mean, when the left and right slides, the data of the X axis and the Y axis will be deranged

**Comment by apertureless** [comment]
Hm, can you post some reproduction? (jsfiddle, codepen, minimal repository) It never happend for me tho.

**Comment by huangche007** [comment]
you can access to [http://m.ciyigou.com/mobile/#/pricedetail/10230](http://m.ciyigou.com/mobile/#/pricedetail/10230)，when you switch to March,and move right and left,the data of the X axis and the Y axis will be deranged

**Comment by apertureless** [comment]
How your tabs are working? With `v-if` Looks like the chart instance isn't destroyed properly and the charts are overlapping. 

Are you using the current version?

**Comment by huangche007** [comment]
some code as follow:
`<div class="sort" id="sort">
        <div class="col-xs-3 col on">一月</div>
        <div class="col-xs-3 col">三月</div>
        <div class="col-xs-3 col">半年</div>
        <div class="col-xs-3 col">一年</div>
      </div>` 

`$('#sort .col').click(function(event) {
        $(this).addClass('on').siblings().removeClass('on');
        switch ($(this).html()){
          case "一月":
            _this.month = "1";
              break;
          case "三月":
            _this.month = "3";
            break;
          case "半年":
            _this.month = "6";
            break;
          case "一年":
            _this.month = "12";
            break;
        }
        _this.getMonthMoreData(_this.month,_this.mPriceData.name,_this.mPriceData.specifications);
      });`

``

**Comment by apertureless** [comment]
Okay, I understand. And then after `getMonthMoreData()` is called, you re re-rendering the chart?
Do you re-create the whole chart instance / chart-component ?

**Comment by huangche007** [comment]
i just re-rendering the chart

**Comment by huangche007** [comment]
How can i  re-create the whole  chart-component？

**Comment by huangche007** [comment]
@apertureless Thank you very much，I solved this problem like this:
`import {Line} from 'vue-chartjs'
export default {
  extends: Line,
  props: ['chartData', 'options'],
  mounted () {

    this.renderChart(this.chartData, this.options)
  },
  watch: {
    options () {
      this._chart.destroy();
      this.renderChart(this.chartData, this.options);
    },
    chartData () {
      this._chart.destroy();
      console.log("或得到的监视数据chartData:",this.chartData);
      this.renderChart(this.chartData, this.options);
    }
  }
}`
