### ISSUE TITLE
Maxin with multiple chartData

### ISSUE THREAD

**Issue by shtse8** [apertureless/vue-chartjs#231]
I am using `reactiveProp` to update my chart when props are changed. But I don't know how to config for multiple chartData as my chart is multiple lines. Any help? Thanks.

**Comment by apertureless** [comment]
Can you show your code or provide a codepen ?

**Comment by elanvelazquez** [comment]
I have this code 
`<script>
import Vue from 'vue'
import {mixins} from 'vue-chartjs'
var chart
Vue.component('chartTest', {
  props: ['labels', 'type','chartData'],
  mixins:[mixins.reactiveProp],
  template: '<canvas height="400" id="chart-0" width="400"></canvas>',
  mounted: function() {
    this.chart=new Chart(this.$el, {
      type: this.type,
      data: {
        labels: this.labels,
        datasets: [{
          label: 'Sensor value',
          data: this.chartData
        }]
      },
      options: {
       scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        }
      }
    });
  },
    watch:{
        chartData:function(){  
            //this update the chart, but with issues
           this.chart.update()
        }
    }
});

export default {
  name: 'charts',
  //components: {LineExample },
    data (){
        return{
            chartData:{
                labels: [' ', ' ', ' ', ' ', ' ', ' ', ' '],
      datasets: [
        {
          label: 'Data One',
          backgroundColor: '#f87979',
          data: [40, 39, 10, 40, 39, 80, 40]
        }
      ]
            },
        options:{responsive: true, maintainAspectRatio: false}
//            chartData:null
        }
    },
    created(){

    },
    methods:{
        changeValues:function(e){
            
                this.chartData.labels.push(' ')
                //when this is the line that i have the issue
                /*
                 1. Error in callback for watcher "chartData": "TypeError: Cannot read property 'map' of undefined"
                 2. Cannot read property 'map' of undefined
                */
                this.chartData.datasets[0].data.push(Math.floor(Math.random() * 80))
            //setTimeout(this.changeValues,Math.floor(Math.random() * 1000) + 2000)

        }
    }
}
</script>
`

and this is how i implement it

`<div class="card-block">
          <div class="chart-wrapper">
              <chart-test :labels="chartData.labels"  type="line" :chart-data="chartData.datasets[0].data"/> 
          </div>
          <input type="button" value="click" @click.prevent="changeValues($event)">
        </div>`

but i have this errors: 
`vue.esm.js?65d7:434 [Vue warn]: Error in callback for watcher "chartData": "TypeError: Cannot read property 'map' of undefined"` and `TypeError: Cannot read property 'map' of undefined`

**Comment by elanvelazquez** [comment]
this is my vue file
[Charts.zip](https://github.com/apertureless/vue-chartjs/files/1408726/Charts.zip)

and this is my error:
![image](https://user-images.githubusercontent.com/10780854/31912042-8e8573da-b7f7-11e7-90de-1202cca91cad.png)

how can i solve this?

**Comment by shtse8** [comment]
```
// MonthlyIncome.js
import { Line, mixins } from 'vue-chartjs'

export default {
  extends: Line,
  mixins: [mixins.reactiveProp],
  props: ['chartData', 'options'],
  mounted () {
    this.renderChart(this.chartData, this.options)
  }
}
```
Once `this.chartData` is mixed chartData as follow:
```
{
    datasets: [{
          label: 'Bar Dataset',
          data: [10, 20, 30, 40]
        }, {
          label: 'Line Dataset',
          data: [50, 50, 50, 50],

          // Changes this dataset to become a line
          type: 'line'
        }],
    labels: ['January', 'February', 'March', 'April']
  }
```
How can I config for this case?

**Comment by apertureless** [comment]
So you adding the type dynamically?

**Comment by shtse8** [comment]
I got the concept of `chartData` now. I need to put the whole object into the component instead of just the data.
