### ISSUE TITLE
How to access Chart.defaults.global

### ISSUE THREAD

**Issue by egorzekov** [apertureless/vue-chartjs#234]
Hello Jakub.

First of all, thanks a lot for such handy package. I appreciate your work a lot!

I easily integrated it to my project, but unfortunately faced one problem (didn't find an answer in docs/created issues). 

I want to set up global settings that can change all of the fonts on the chart (http://www.chartjs.org/docs/latest/general/fonts.html).

I tried to do it with Chart.js object (http://vue-chartjs.org/#/home?id=chart-js-object), but didn't success.

Could you please clarify if it's possible to do using your package?

Many thanks in advance.

**Comment by apertureless** [comment]
The `this.$data._chart` is the current chart instance. Which is created on the first renderChart call. [1](https://github.com/apertureless/vue-chartjs/blob/develop/src/BaseCharts/Bubble.js#L81-L87)

Right now there is no way to access the global settings.

**Comment by apertureless** [comment]
@urvi2429 No. Like I said and mentioned in the docs http://vue-chartjs.org/#/home?id=chart-js-object

You can access the chart instance over `this.$data._chart`.

**Comment by CamilaNiebles** [comment]
@apertureless Hi! I'm trying something and I want to know if it is possible. I want to change my doughnut chart when the user make a click over it i.e, I want to show the detail about some region, is it possible?
Congratulations for your work! (:
