### ISSUE TITLE
Reactively change chart properties

### ISSUE THREAD

**Issue by Ortix92** [apertureless/vue-chartjs#237]
Is there a way to reactively change the chart properties? More specifically the y axis?

**Comment by apertureless** [comment]
Just add a watcher to your objects object and re-render the chart.

```js
watcher: {
  options ()  {
    this.renderChart(this.chartData, this.options)
  }
}
```

**Comment by kJamesy** [comment]
Seems solution can also be applied to chartData and make it reactive (as an alternative to the documented method). 
![vuechart](https://user-images.githubusercontent.com/4100964/32445678-6ee4c780-c2fe-11e7-8343-e893ce84ef5a.jpg)
