### ISSUE TITLE
Is it possible to create an callback on the onAnimationComplete option

### ISSUE THREAD

**Issue by smgjreinieren** [apertureless/vue-chartjs#240]
What I try to do is to create an callback on the onAnimationComplete option to set percentage in the bar chart. So how does that look:

```js
options: {
	responsive: false,
	maintainAspectRatio: false,
	legend: { display: false },
	scaleShowVerticalLines: false,
	scales: {
		yAxes: [{
			display: false,
			    ticks: {
				display: false
			    }
		}],
		xAxes: [{
			barPercentage: .5
		}]
	},
	onAnimationComplete: function(){
		console.log('test');
	},
}
```

But this property is not getting picked up is there a simple way to create this callback or to simply show the percentage of the bar inside the bar like this: [FIDDLE](http://jsfiddle.net/uh9vw0ao/)

I'll hope somebody could help me out on this.

### Environment
- vue.js version:  "vue": "^2.1.10",
- vue-chart.js version:   "vue-chartjs": "^3.0.0",
- npm version: 3.1010

**Comment by apertureless** [comment]
http://www.chartjs.org/docs/latest/configuration/animations.html?h=animation

You can use the chartjs callbacks http://www.chartjs.org/docs/latest/configuration/animations.html#animation-callbacks
