### ISSUE TITLE
presets es2015 

### ISSUE THREAD

**Issue by yanzhandong** [apertureless/vue-chartjs#242]
ERROR in ./~/vue-chartjs/es/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory

**Comment by apertureless** [comment]
Please provide at least the minimal required information.

vue version, vue-chartjs version, your environment (webpack 1? webpack 2? webpack 3? browser? etc?

**Comment by shtse8** [comment]
@yanzhandong try to install babel-preset-es2015

**Comment by apertureless** [comment]
Will be fixed in `3.0.1`
