### ISSUE TITLE
Customise individual Axis Labels

### ISSUE THREAD

**Issue by akau40** [apertureless/vue-chartjs#243]
Is it possible to customise individual Axis labels in vue-chart. Something like this:
```
fonstStyle:function (value, index, values) {
                                        var data= this.data[index];
                                        console.log(data.groupdescription);
                                       return data.groupdescription.length > 0 ? "normal" : "bold";      
}
```
if I just do fontStyle: "bold" , it works fine but applies to all labels
or apply similar logic to set individual colors for labels.

**Comment by apertureless** [comment]
Well if it's possible with [Chart.js](https://github.com/chartjs/Chart.js) it should be possible with vue-chartjs. ;)
There are some [scriptable options](http://www.chartjs.org/docs/latest/general/options.html?h=scriptable) however I am not sure if this applies to fontStyle.

However I guess you better ask in the Chart.js repo, as it's more relevant there.
