### ISSUE TITLE
[Suggestion]Loose package dependencies

### ISSUE THREAD

**Issue by ultraN** [apertureless/vue-chartjs#245]
### Expected Behavior
npm install vue-chartjs@latest

### Actual Behavior
npm install vue-chartjs@latest
npm ERR! peer dep missing: vue@2.5.2, required by vue-chartjs@3.0.0
npm WARN vue-chartjs@3.0.0 requires a peer of chart.js@2.7.0 but none is installed. You must install peer dependencies yourself.

### Environment
- vue.js version: 2.5.3
- vue-chart.js version: 2.7.1
- npm version: 5.5.1

Suggest use loose package version control. So you don't have to update this package's dependencies after vue or chart.js update.

**Comment by apertureless** [comment]
What do you exactly mean with loose package version control?

**Comment by ultraN** [comment]
@apertureless I mean it doesn’t need to be exact match. For example, like vue@2.5.x or chart.js@2.7.x

**Comment by apertureless** [comment]
Will be available with `vue-chartjs@3.0.1` 
I cleaned up the dependencies and versions.

Removed vue as a peerDependency, as it is not longer needed with the 3.0 release.
And set the chart.js peerDependency to 2.7.x to prevent breaking changes.
