### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by IneoO** [apertureless/vue-chartjs#247]
Hi,
I would like to know if it's possible to have the browser list support in the doc, or at least someone tell me.

### Expected Behavior
Have the list of browser support in the doc

### Actual Behavior
Can't find any comment about browser support in the doc

**Comment by apertureless** [comment]
Sure,.... its... pretty up high in the readme...

https://github.com/apertureless/vue-chartjs#install
and
https://github.com/apertureless/vue-chartjs#browser

**Comment by apertureless** [comment]
Well the browser support is based on Vue.js and Chart.js. However I think Chart.js is the limiting factor.

[Chart.js Browser Support](http://www.chartjs.org/docs/latest/developers/#browser-support)

- Chrome 50+
- Firefox 45+
- Internet Explorer 11
- Edge 14+
- Safari 9+
