### ISSUE TITLE
Creating mixed charts with double or triple Y-axis support

### ISSUE THREAD

**Issue by Saif03** [apertureless/vue-chartjs#248]
**1.** I am trying to replicate something like attached screenshot which provides double y-axis support plus overlapping bar charts series, Is it do able via vue-chartsjs? I didn't find anything in the docs.

[charts with double Y-axis support](https://i.imgur.com/S8bwdGQ.png)

Currently I am trying something like this:

```
import Chart from 'vue-chartjs';

export default {
    extends: Chart.Bar,
    data: function () {
        return {
            options: {
                responsive: true,
                maintainAspectRatio: false
            },
            ASeies:{
                type: 'bar',
                label: 'A',
                backgroundColor: '#348cd1',
                data: [],
            },
            BSeries:{
                type: 'bar',
                label: 'B',
                backgroundColor: '#43b5d8',
                data: [],
            },
            CSeries:{
                type: 'line',
                label: 'C',
                backgroundColor: '#5ed470',
                data: [],
            }
        }
    },
    props: {
        labels: Array,
        AData: Array,
        BData: Array,
        CData: Array
    },
    mounted () {
        this.ASeies.data =  this.AData;
        this.BSeries.data = this.BData
        this.CSeries.data =  this.CData;

        this.renderChart({
            labels: this.labels,
            datasets:[
                this.ASeies,
                this.BSeries,
                this.CSeries
            ]
        }, this.options)
    }
}
```
this creates something like this; [image](https://i.imgur.com/8gAjq4N.png). As you can see due to lack of double Y-axis functionality my third series isn't properly visible.

**2.** Secondly Is there any way to format Y-axis labels so large numbers would be displayed with thousand(K) or million(M) post-fix short hands. Or introduce something like thousand separators for better visibility?

### Environment
- vue.js version: latest
- vue-chart.js version: latest
- npm version: latest

**Comment by apertureless** [comment]
https://stackoverflow.com/questions/38085352/how-to-use-two-y-axes-in-chart-js-v2

https://stackoverflow.com/questions/37028536/chart-js-line-chart-with-two-yaxis-typeerror-yscale-is-undefined
