### ISSUE TITLE
Reduce bundle size by removing chart.js source code

### ISSUE THREAD

**Issue by nbonamy** [apertureless/vue-chartjs#249]
### Expected Behavior
Final webpack bundle should not have chart.js source code (and propbably momentjs but I saw related issues and this is not a big problem for me (see below)):

<img width="493" alt="screen shot 2017-11-11 at 14 56 19" src="https://user-images.githubusercontent.com/956207/32690073-963bad80-c6f0-11e7-983a-b4eb1a00f29a.png">

To to this I did an experiment by replacing all imports to `'chart.js'` by `'chart.js/dist/Chart.min.js'` in vue-chartjs source code.

I am not sure this will not break vue-chartjs usage outside of my webpack3 configuration though so I am not doing a fork/PR for now.

BTW, I am using momentjs elsewhere in my application, and ended up having moment twice in my final bundle. I removed moment from my own dependencies and do import moment from 'chart.js/node_modules/moment' when I need to use it.

Those two actions reduced my vendor.js file from 1.4MB to 976KB (300K zipped). Still big and investigating other libraries :)

### Actual Behavior

Source code of chartjs is included in final webpack bundle

<img width="585" alt="screen shot 2017-11-11 at 14 51 07" src="https://user-images.githubusercontent.com/956207/32690061-415a88ae-c6f0-11e7-89bf-5c811f10e65b.png">

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 3.0.2
- npm version: 5.3

**Comment by apertureless** [comment]
Well the lib bundle does *not* contain chart.js sourcecode.
Chart.js is set as a peerDependency and as external in the webpack config.

`vue-chartjs.js`  is *88.3 kB* big and
`vue-chartjs.min.js` is *25.3 kB* big.

**Comment by nbonamy** [comment]
OK sorry. Then I must have made up the two screenshots.

**Comment by apertureless** [comment]
Chart.js gets bundled in your application, you Install it as a dependency for your project. So is ends up in your final application bundle. 

You can define it in your webpack config to be vendored out with CommonChunk
