### ISSUE TITLE
Setting global defaults

### ISSUE THREAD

**Issue by bathyscaaf** [apertureless/vue-chartjs#258]
I'm trying to find a way to set and use the Chart.defaults.global, but have been unsuccessful.
Ideally it would work as intended: you set global defaults that can be overridden by the options object.
Is this possible with the current vue-chartjs?

### Environment
- vue.js version: 2.5.6
- vue-chart.js version: 3.0.0
- npm version: 5.5.1

**Comment by apertureless** [comment]
You need to import the Chartjs object first. And then you can set the globals.

```js

import Chart from 'chart.js'
Chart.defaults.global

```

**Comment by bathyscaaf** [comment]
That's one of the first things I tried.  I must have missed something.
