### ISSUE TITLE
Implementing of the "begin-zero" option

### ISSUE THREAD

**Issue by ddydeveloper** [apertureless/vue-chartjs#262]
### Expected Behavior
When I have some positive data I want to see zero value on values axis:

### Actual Behavior
![image](https://user-images.githubusercontent.com/28873881/33275963-35609324-d3a5-11e7-856e-d0faf5ef5a51.png)

Use HorizontalBar in this way: 
 `<vue-horizontal-bar-chart :chart-data="ordersChartData" :beginzero="true"></vue-horizontal-bar-chart>  `

### Environment
- vue.js version: "^2.5.8"
- vue-chart.js version: "^3.0.2"
- npm version: "5.5.1"

**Comment by apertureless** [comment]
I don't really get the problem.
Why don't you pass just the 

```js
ticks: {
  beginAtZero: true
 },
```

to your options?

**Comment by ddydeveloper** [comment]
@apertureless sorry, it is my mistake, I just forgot pass the begin zero option like a property of the ticks object and done it in this way:

```
options: {
   responsive: false,
   beginAtZero: true
}
```

and I was confused by result. Thank you for help. Close the issue.

**Comment by icangku** [comment]
I did something like this,

<bar-chart :chart-data="barData" :height="100" :options="{responsive: false, maintainAspectRatio: false, ticks : {beginAtZero : true}}"></bar-chart>

But it goes for nothing, help me please

**Comment by AndreaRylander** [comment]
I have the same problem. I have tried 
`:options="{maintainAspectRatio: false, ticks : {beginAtZero : true}}"`
and
`:options="{maintainAspectRatio: false, beginAtZero : true}"`
but the y-axis still starts at the value of the lowest data point. How can I get it to start at zero?

**Comment by miguel-rod** [comment]
@icangku @AndreaRylander 
you have to put it in the y or x axis option 
see this post 

https://github.com/apertureless/vue-chartjs/issues/272#issuecomment-349903067
