### ISSUE TITLE
Can't find the oppurtunity to configure axis of values 

### ISSUE THREAD

**Issue by ddydeveloper** [apertureless/vue-chartjs#263]
### Expected Behavior
I want to display just simple numbers, but I didn't find the opportunity to configure this. Is it possible to implement this feature? Maybe I just can't find the good solution. 
If I have to configure this It would be great. 

### Actual Behavior
![image](https://user-images.githubusercontent.com/28873881/33276150-bc64a446-d3a5-11e7-95bc-85cb37ec9406.png)

There are a lot of fractional numbers which can't be hidden.

### Environment
- vue.js version: "^2.5.8"
- vue-chart.js version: "^3.0.2"
- npm version: "5.5.1"

**Comment by apertureless** [comment]
Hi @ddydeveloper 

you have custom callbacks in the xAxis object. 
Check out the chart.js docs for this:

http://www.chartjs.org/docs/latest/axes/#callbacks

And you can create your own custom ticks formats mentioned in issue #147 

http://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats

**Comment by ddydeveloper** [comment]
@apertureless as you said, it is duplicate. Thanks for help! Close the issue.

**Comment by ergonomicus** [comment]
@ddydeveloper Well, how to do it? Can you paste some example?
