### ISSUE TITLE
Chart width not updated on resize window width

### ISSUE THREAD

**Issue by mojtabamoosavi** [apertureless/vue-chartjs#264]
### Actual Behavior
VueJS Chart not update on resize window width
my option object : 
{
    responsive:true,
    maintainAspectRatio: false
}

### Environment
- vue.js version: 2.5.9
- vue-chart.js version: 3.0.2
- npm version: 5.5.1

**Comment by apertureless** [comment]
Please provide a minimal reproduction. 
Codepen / Jsfiddle

**Comment by mojtabamoosavi** [comment]
Thanks for your comment
https://jsfiddle.net/mojtabamoosavi/b6jrr3qh/

in this jsfiddle worked !
My problem was  for page direction (RTL)

**Comment by apertureless** [comment]
👍
