### ISSUE TITLE
Positioning of image in canvas is not vertically aligned

### ISSUE THREAD

**Issue by El4a** [apertureless/vue-chartjs#265]
### Expected Behavior
The image is vertically aligned.

### Actual Behavior
Okay this might be (surely is) nitpicking but when rendering a graph the vertical alignment seems off. There is more space at the top than at the bottom. 

As you can see, the graph sticks to the bottom of the canvas, but leaves room on top:

![image](https://user-images.githubusercontent.com/15727732/33380382-3037f8d4-d51b-11e7-9af8-2a3d143aea28.png)

### Environment
- vue.js version: 2.9.1
- vue-chart.js version: 3.0.2
- npm version: <version here>

Is this something I'm doing wrong? 
Both "responsive: true" and "maintainAspectRatio: true" are on default values, I tried playing with these but doesn't make a difference.

**Comment by apertureless** [comment]
Do you have a small codepen for reproduction?

**Comment by apertureless** [comment]
Well this may be a bug directly in chart.js or expected behaviour or a css thing. But due to the lack of reproduction and inactivity we may never know 🤖

**Comment by El4a** [comment]
@apertureless  Yes you are absolutely right, it should have had a repro from the start! Just been a very busy week and I haven't found the time yet, sorry! Will do as soon as possible, bear with me :)

**Comment by apertureless** [comment]
Well, I can't reproduce this.
I tried here

https://codepen.io/apertureless/pen/jaoRjm

However it fits perfectly into the div.
So it might be related to some of your css.
