### ISSUE TITLE
UNMET PEER DEPENDENCY chart.js@2.7.x

### ISSUE THREAD

**Issue by poppabear8883** [apertureless/vue-chartjs#267]
### Expected Behavior
All dependencies are being met ?

### Actual Behavior
UNMET PEER DEPENDENCY chart.js@2.7.x

### Environment
- vue.js version: 2.5.3
- vue-chart.js version: 3.0.2
- npm version: 3.10.10

Assuming issue with `package.json`

```json
"devDependencies": {
    "chart.js": "2.7.0",
  },
```

**Comment by apertureless** [comment]
Have you installed chart.js ? Like mentioned in the [README](https://github.com/apertureless/vue-chartjs#install)

```bash
yarn add vue-chartjs chart.js
```
Chart.js is only a peerDependency. So you have to install it by your own.

**Comment by poppabear8883** [comment]
Must have missed that. So it appears that this is the behavior by design. However I guess I don't understand. I do see the `peerDependency` now ...

```json
"peerDependencies": {
    "chart.js": "2.7.x"
  },
```

Thanks for the response!

**Comment by apertureless** [comment]
@poppabear8883 

Well `chart.js` is defined as a `peerDependency` in `vue-chartjs`. This means that it depends on chart.js but don't bundle / install it, if you install vue-chartjs.

If it were a direct dependency it would automatically ship with vue-chartjs if you install it. Like lodash.merge.

However it has some benefits to define it as a peerDependency. This way you can decide which version of chart.js you are running. If for example a new version of chart.js ships you can install it and vue-chartjs will be working with it. (Expect there are some api breaking changes)

If it were a direct dependency if an update would ship you had to wait for me, to update vue-chartjs.

I hope this helps to understand the behavior .
