### ISSUE TITLE
how to use themes in v-charts

### ISSUE THREAD

**Issue by jackieveev** [apertureless/vue-chartjs#268]
### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
I dont Unserstand what you mean with themes

**Comment by apertureless** [comment]
Well you can add styling over the chart.js options if you mean that.
Otherwise.... close due to inactivity 🤖

**Comment by jackieveev** [comment]
sorry, I'm mess up with v-charts and vue-chartjs
