### ISSUE TITLE
Add horizontal grid lines in a bar chart

### ISSUE THREAD

**Issue by sylvaincaillot** [apertureless/vue-chartjs#272]
Hi, 
I have tried several options in order to draw grid lines to ease the reading of my bar chart.
Currently i have this:
![without_line](https://user-images.githubusercontent.com/4845910/33703247-70d764ae-db7b-11e7-8899-cf7737103061.png)
but i would like to get that:
![with_line](https://user-images.githubusercontent.com/4845910/33703260-7dec4d94-db7b-11e7-9e1a-86d6edb09eaa.png)
with the horizontal lines

I tried
```
drawTicks
gridLines
beginAtZero
etc..
```
but can't find the option parameter to do so.

Thank you for your help

**Comment by apertureless** [comment]
It's in the scale object.
```js
const options = {
scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            },
            gridLines: {
              display: false
            }
          }],
          xAxes: [ {
            gridLines: {
              display: true
            },
          }]
        }
}
```

**Comment by nadavjulius** [comment]
where did you put that peice of code? thanks

**Comment by apertureless** [comment]
It is the second argument you pass to `this.renderChart(data, options)`
