### ISSUE TITLE
import chart with vue-cli?

### ISSUE THREAD

**Issue by matbz** [apertureless/vue-chartjs#273]
When I try 

import ChartNetWorth from './ChartNetWorth.js';  (this include a basic chart from the documentation)

I get the following error: 

https://google.com/#q=import%2Fextensions  Unexpected use of file extension "js" for "./ChartNetWorth.js"
  src\components\Report\ReportNetWorth.vue:26:27
  import ChartNetWorth from './ChartNetWorth.js';
                             ^

Then I tried:

import ChartNetWorth from './ChartNetWorth'

Error -> 

Module build failed: Error: ENOENT: no such file or directory, open 'xxx\Report\ChartNetWorth.vue'

What can I do to fix this? I tried making ChartNetWorth a .vue file. This way I get it to compile, but the chart isn't shown in the browser.

-> Error: Failed to mount component: template or render function not defined.

Thanks!

**Comment by apertureless** [comment]
I don't understand your question.
vue-cli is for bootstrapping boilerplate templates, like the webpack one or the pwa one.
It has nothing to do with dependency management or vue-chartjs.

You can install vue-chartjs over npm / yarn
