### ISSUE TITLE
Prop for plugins

### ISSUE THREAD

**Issue by daniel-shuy** [apertureless/vue-chartjs#274]
I think plugins should be added using an Array **prop** instead of calling `addPlugin()`.

For example, I have a base `LineChart` component that all my Line charts composes:
```javascript
// LineChart.js
import {Line, mixins} from 'vue-chartjs'

export default {
  mixins: [Line, mixins.reactiveProp],
  props: {
    options: Object
  },
  mounted () {
    this.renderChart(this.chartData, this.options)
  }
}
```

```vue
// SomeLineChart.vue
<template>
  <LineChart :height="height" :width="width" :chartData="chartData" :options="options" :plugins="plugins"></LineChart>
</template>

<script>
  import LineChart from 'LineChart'

  export default {
    props: {
      // ...
    },
    computed: {
      chartData () {
        // ...
      },
      options () {
        // ...
      },
      plugins () {
        // ...
      }
    }
  }
</script>
```

I cannot directly mixin `Line` and `reactiveProp` into `SomeLineChart.vue` because I want it to be reactive, yet without exposing the `chartData` prop. Instead, `chartData` is computed from `SomeLineChart.vue`'s props.

However, the issue arises when I need to add **plugins** for `SomeLineChart.vue`. Calling `addPlugin()` during `SomeLineChart.vue`'s `mounted` event doesn't work because it occurs after `LineChart`'s `mounted` event (at this point, `renderChart()` is already called).

My initial idea was to add a `plugins` **prop** to `LineChart.js`, however that clashes with the `plugins` **data** property in the base charts.

```javascript
// LineChart.js
import {Line, mixins} from 'vue-chartjs'

export default {
  mixins: [Line, mixins.reactiveProp],
  props: {
    options: Object,
    plugins: Array // throws "The data property "plugins" is already declared as a prop. Use prop default value instead."
  },
  mounted () {
    if (this.plugins) {
      this.plugins.forEach(plugin => {
        this.addPlugin(plugin)
      })
    }

    this.renderChart(this.chartData, this.options)
  }
}
```

For backwards compatibility with `addPlugin()`, my suggestion is to rename the `plugins` **data** property to `_plugins` (which also follows the same principle of prefixing all local data properties with '_', eg. `_chart`), and then add a `plugins` **prop**. Unfortunately this is a breaking change for people directly accessing the `plugins` **data** property.

If you agree with the idea, I can submit a Pull Request for it.

**Comment by apertureless** [comment]
Hey @daniel-shuy 

your change sounds reasonable. 
Feel free to make a PR 👍
