### ISSUE TITLE
VueChart.js with  inline plugins example

### ISSUE THREAD

**Issue by winou75** [apertureless/vue-chartjs#277]
Hi guys, it might not be the place to ask this kind of question, but as a newbie, I don't really understand how to use plugins ...

I'd like to add this [plugin PieceLabel](https://github.com/emn178/Chart.PieceLabel.js) to my component below.

```
export default {
  name: 'pie-chart',
  mixins: [reactiveProp],
  extends: Pie,
  props: {
    options: Object,
    chartData: Object,
  },
  mounted() {
    const { options, chartData, renderChart } = this

    this.addPlugin({
    id: 'pieceLabel',
      beforeInit: function (chart) {
        console.log(chart)
      }
    })

    options: {
      pieceLabel: {
        mode: 'label',
        precision: 1
      },
   }
    renderChart(chartData, params)
  },
}
```
The issue is how does it recognize the id ?? 
Thanks a lot

**Comment by apertureless** [comment]
Well, I guess you have to install the plugin over npm
```npm install chart.piecelabel.js```

Then import or require it

```js
import * as PriceLabel from 'chart.piecelabel.js' 
// If the import is not working you could try to require it
const PriceLabel = require('chart.pricelabel.js')
```

and then add it as a plugin

```
this.addPlugin(PriceLabel)
```

This would be the approch for a per chart basis. To register it globally for all charts (that are supported by that plugin)

You have to import the chart instance fist.

```js
import Chart from 'chart.js'
Chart.plugins.register(PriceLabel)
```

**Comment by winou75** [comment]
you are a marvellous person.

**Comment by ebisbe** [comment]
I think this should be in the docs. And also how to pass configuration to the plugin

**Comment by apertureless** [comment]
@ebisbe not sure what you mean. 
There is a section how to add inline plugins in the docs:

https://vue-chartjs.org/#/home?id=inline-plugins

And also the plugins prop if you want to pass it to your chart:

https://vue-chartjs.org/#/home?id=props

**Comment by apertureless** [comment]
I guess you are using this one? https://github.com/chartjs/chartjs-plugin-annotation

Well, they say: 

> To configure the annotations plugin, you can simply add new config options to your chart config.

So have you tried this?

```js

const options = {
	responsive: true,
	title: {
		display: true,
		text: 'Put your other options in here'
	}
	annotation: {
		events: ['click'],
		annotations: []
	}
}
```

**Comment by ebisbe** [comment]
Yes, I figured it out. There's an issue with using array labels `[['lable','text'],['label2','text2']]`. I've just switched to `['label', 'label2']`.

thanks, anyway

**Comment by mreduar** [comment]
> @ebisbe not sure what you mean. There is a section how to add inline plugins in the docs:
> 
> https://vue-chartjs.org/#/home?id=inline-plugins
> 
> And also the plugins prop if you want to pass it to your chart:
> 
> https://vue-chartjs.org/#/home?id=props

Greetings, this is no longer available and is already on V5, how to add inline plugins now? I would like to add to do this:
```js
plugins: [{
   beforeInit: function(chart) {
      chart.data.labels.forEach((e, i, a) => {
         if (/\n/.test(e)) {
            a[i] = e.split(/\n/);
         }
      });
   }
}]
```

**Comment by apertureless** [comment]
@mreduar 
You can still pass plugins over the `plugin` prop to the chart. https://vue-chartjs.org/api/#props
Should work pretty much the same way.
