### ISSUE TITLE
Prop data is not getting updated

### ISSUE THREAD

**Issue by gj1118** [apertureless/vue-chartjs#279]
Hi,
In my following vue component code I am trying to get the data from the backend rest api . 

```javascript
<template>
	<div>
		<h3 class="title">
			Chart Title
		</h3>
		<line-chart :chart-data="mydata" :options="{responsive: true, maintainAspectRatio: false}"></line-chart>
	</div>
</template>

<script>
	import axios from 'axios';
	import LineChart from '../graphComponents/LineChart'
	export default {
	     components: {LineChart},     
	     data: () => ({
	       mydata: null,
	      }),
	      async created () {
			let result = await axios.get('backend api');
			console.log({result})
			let data = result.data

	       this.mydata =  {
			    labels: Object.keys(data),
			    datasets: [
			      {
			        label: 'Errored Out',
			        backgroundColor: '#f87979',
			        data: Object.keys(data).map((key)=> (data[key].number_erred))
			      }, {
			        label: 'Failed Tests',
			        backgroundColor: '#f87979',
			        data: Object.keys(data).map((key)=> (data[key].number_failed))
			      }
			    ]
			  }
			
			console.log(JSON.stringify(this.mydata));

	      }
	   };
	
</script>

<style scoped>
	.title {
		text-align:center;

	}
</style>
``` 
And I have a line chart component as follows

```javascript
import {Line} from 'vue-chartjs'
// const { reactiveProp } = mixins

export default {
	extends: Line,
	props:['chartData','options'],
	mounted() {
		console.log("rendering graph")
		console.log(JSON.stringify(this.chartData))
		console.log(JSON.stringify(this.options))
		this.renderChart(this.chartData, this.options)
	}
}
```
However that said, it seems that after I get the update ```mydata``` , that change is not getting reflected. Please see below for the end result which also shows the appropriate log statements. 

<a href="https://cl.ly/oN74" target="_blank"><img src="https://d1ax1i5f2y3x71.cloudfront.net/items/1i3t0z1i3R2q3q3c1t0y/Image%202017-12-16%20at%204.32.22%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

Can you please help me out with this?

Thanks
Gagan

**Comment by gj1118** [comment]
Thanks , I got it working.

**Comment by apertureless** [comment]
Generally when working with APIs and chart.js you should be sure that your data arrived before your chart is drawn.

Because of the async nature of api calls your chart will be initialized with empty data.

So you could do something like this

```html
<line-chart v-if="mydata" :chart-data="mydata" :options="{responsive: true, maintainAspectRatio: false}" />
```

Or use the `reactiveProp` mixin, which is a watcher on chartdata, which updated and rerenders the chart if new data arrives.
