### ISSUE TITLE
Responsiveness not working well when adding plugins

### ISSUE THREAD

**Issue by winou75** [apertureless/vue-chartjs#280]
So i've imported this plugin as cited:

[`import * as OutLabel from 'chartjs-plugin-piechart-outlabels'` 
](https://piechart-outlabels.netlify.com/)

it basically adds description outside the pie.

The issue is that it crops accordingly to the 'responsive original size" without taking into account the plugin

here it is without the legend: 
![capture d ecran 2017-12-18 a 12 51 23](https://user-images.githubusercontent.com/15017949/34107535-e53ff0b6-e3fc-11e7-8efb-42719baba10c.png)

here it is with the legend: 

![capture d ecran 2017-12-18 a 14 10 38](https://user-images.githubusercontent.com/15017949/34107627-4bbbed22-e3fd-11e7-9bdd-aef897306708.png)

How can it take account the plugins added width and length?

thanks a lot as always

**Comment by apertureless** [comment]
Hi @winou75 
well I don't think the issue is related to vue-chartjs.
It is rather a Chart.js problem. Or you maybe need to tweak your options.

**Comment by metrey** [comment]
Vue-ChartJS should have a way to handle other plugin.

Anyway, above issue can be solved by layout configuration, see here: https://ask.osify.com/qa/11579

**Comment by apertureless** [comment]
@metrey 
What do you mean by "handle other plugins"?
We have a prop where you can pass in plugins and a method for registering local plugins.

However a lot of the chart.js plugins are working in the global space, so nothing I could do about it.
