### ISSUE TITLE
Importing via main.js

### ISSUE THREAD

**Issue by albertleao** [apertureless/vue-chartjs#281]
I don't know if I'm missing something but is there no way to import vuecharts via the main.js so that { Bar, Line, Pie, Doughnut } are available to be extended inside a component or do I have to import the VueCharts in each individual component?

**Comment by apertureless** [comment]
I don't know if I understand your question correctly. 
You can import the individual modules or the whole module via

`import VueCharts from 'vue-chartjs'` and then reference it over `VueCharts.Line` etc.
However you can have only one chart type per component.
