### ISSUE TITLE
Question: Cartesian Axis

### ISSUE THREAD

**Issue by badcom** [apertureless/vue-chartjs#282]
I couldn't find anything in the documentation, therefore I think that the answer is no, but thought I'd ask:

Does it support Time Cartesian Axis? Otherwise, do you intend to implement this?
http://www.chartjs.org/docs/latest/axes/cartesian/time.html

**Comment by apertureless** [comment]
Never used them to be honest. But, as `vue-chartjs` is only a wrapper with some abstractions, it should support them. Have to tried to pass the options and data? 

Keep in mind, that the reactive mixin will not work with the altered data structure.

**Comment by Carl-Binneman** [comment]
No idea how to get this working.
Would be great if this package had an example for linear data.
Seems impossible to plot an X,Y value. the X is always snapped to label index regardless of its value
