### ISSUE TITLE
Bug: 2 doughnut charts on the same page, chartData overwrites by the latest value

### ISSUE THREAD

**Issue by duyhung85** [apertureless/vue-chartjs#286]
Hi, 
I try to setup multiple doughnut charts on the same page by using v-for and passing in :chart-data. Unfortunately, all generated charts are the same as only the last data got applied.

Thanks

**Comment by apertureless** [comment]
Can you post a link for reproduction?
You should maybe provide unqiue ids to the chart-id prop.
http://vue-chartjs.org/#/home?id=props


```js
<line-chart chart-id="some-uqniue-id" >
```

But without reproduction / code it's hard to say where the problem is.

**Comment by duyhung85** [comment]
Thank you, I add unique ids in and fix my data binding and its working now

**Comment by lucianoreis** [comment]
I implemented the prop chart-id
```
<template>
  <div>
    <div v-for="(grupos, index) in data">
      <grafico-item :chart-id="'chart' + index" :height="150" :data="grupos"></graficoitem>
    </div>
  </div>
</template>
```
```
  watch: {
    data: {
      handler: function (val, oldVal) {
        console.log('Id => ' + this.chartId)
        this.updateGrafico()
      },
      deep: true
    }
  }
```
In a case with 4 iterations only the updateGrafico () method is applied in the last chart.

The variable **this.chartId** is printed 4 times, but the method is only applied on the last chart

**Comment by aron-l1988** [comment]
I have added chart-id prop to Bar chart but first chart is not working as expected.
When I click legends, chart is refreshing and sometimes it's completely disappeared.
Anyone, please help me.
