### ISSUE TITLE
Dynamic data render does not work

### ISSUE THREAD

**Issue by muhammetakkus** [apertureless/vue-chartjs#289]
### Behavior
I want to render with dynamicly. When button click and push data everything looks just data object does not seem.

```javascript
this.chartData.labels.push('test-A')
// 
this.chartData.datasets.push({label: 'test-B', data: value, backgroundColor: 'red'})
// or
this.chartData.datasets.push({label: 'test-B', data: [42], backgroundColor: 'red'})
this.renderChart(this.chartData, this.chartOptions)
```
![111 png](https://user-images.githubusercontent.com/11074932/34813246-3fbe6426-f6ba-11e7-8e65-130100afb971.png)

### Environment
- vue.js version: <2.4.2>
- vue-chart.js version: <version here>
- npm version: <3.5.2>

**Comment by apertureless** [comment]
Please provide some reproduction.

**Comment by apertureless** [comment]
closed due to inactivity
