### ISSUE TITLE
Chart not redrawn on parent dataset change

### ISSUE THREAD

**Issue by jjmusi05** [apertureless/vue-chartjs#293]
### Expected Behavior

In https://jsfiddle.net/janman05/8mvk7y8s/, pressing the button makes a change to the parent app's dataset (changing the value for the January column).

Expected behavior is that the dataset change takes place in the parent, is propagated to the component, and then the chart is redrawn.

### Actual Behavior

Dataset change is visible in the parent app, the dataset change appears to propagate to the component, but the chart is not redrawn.

The above jsfiddle has a commented-out watcher in the component, which will show that the component's dataset has also changed. However, I don't know if means that the data was actually sent, or that the sent data only shows up due to the added watcher.

As far as I can see, everything is done correctly, per the tutorials on the vue-chartjs website - but it's possible I'm missing something. Any help would be greatly appreciated.

### Environment
- vue.js version: 2.5.13
- chart.js version: 2.7.1
- vue-chart.js version: 3.1.0

**Comment by apertureless** [comment]
Well, your example breaks Chart.js after clicking the button. It throws an error.
The vue watcher can't detect mutations of your data.
👉 http://vue-chartjs.org/#/home?id=limitations

And the mixin is also not made for that. It is a simple solution if you're adding new datasets / data.

Mutating existing data indexes is rather complicated to watch in the mixin.

If you really rely on mutating individual data points you should take control of the re-rendering / updating by yourself.

You have access to the chart.js / chart instance over `this.$data._chart`

And you can call `this.$data._chart.update()` after mutating your data.
You can send an event over an event bus, pass in a boolean prop like `isChanged` and watch on this prop or event and then call the update method.

There are also a few other solutions here in the issues.
