### ISSUE TITLE
Always show tooltip on doughnut chart

### ISSUE THREAD

**Issue by smgjreinieren** [apertureless/vue-chartjs#294]
### Expected Behavior
What I try to achieve is to always show the tooltips not only on hover.

something like this: https://jsfiddle.net/c8Lk2381/

### Actual Behavior
I know there is an callback on the tooltip but I can't add some custom html to it to make it always show.

Could somebody help me out here to show the tooltips as default?

### Environment
- vue.js version: ^2.5.13
- vue-chart.js version: ^3.0.0
- npm version: 5.6.0

**Comment by apertureless** [comment]
Don't really know whats the problem.
You have your solution in your jsfiddle. 

Or register this function as a plugin like here https://stackoverflow.com/questions/36992922/chart-js-v2-how-to-make-tooltips-always-appear-on-pie-chart
