### ISSUE TITLE
Doughnut background-color?

### ISSUE THREAD

**Issue by kylawamg** [apertureless/vue-chartjs#300]
### Actual Behavior
Hi guys, 

Im trying to set a default background for non-data space on the doughnut chart, but I can not find the way to do this... What I'm trying to achieve:

![image](https://user-images.githubusercontent.com/18372506/35556171-d72eae24-05a1-11e8-83ad-0f58bb81cafa.png)

Thanks in advance for the help.

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Hey @kylawamg 
mh I think this is not possible per default.

But as chart.js uses the canvas and exposes the canvas api, you could maybe write a plugin for that.

You could check out the [Chart.js issues](https://github.com/chartjs/Chart.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) or stackoverflow. Maybe you find someone who wrote a plugin for that.
