### ISSUE TITLE
Latest release causing problems with my barchart

### ISSUE THREAD

**Issue by smgjreinieren** [apertureless/vue-chartjs#304]
What is seems to do is that it is not picking up the options correctly, the barchart labels are falling off the chart. Here is what my barchart component looks like 

`<script>
	import VueChartjs from 'vue-chartjs'

	export default {
		extends: VueChartjs.Bar,
		props: ['data', 'barWidth'],
		data() {
			return {
				options: {
					plugins: {
						datalabels: {
							color: "white",
							display: function(context) {
								return context.dataset.data[context.dataIndex] > 0;
							},
							font: {
								weight: 'bold',
								size: '14'
							},
							formatter: Math.round
						}
					},
					responsive: false,
					maintainAspectRatio: false,
					tooltips: false,
					legend: {
						display: false
					},
					scaleShowVerticalLines: false,
					scales: {
						yAxes: [{
							display: false,

							ticks: {
								display: false
							}
						}],
						xAxes: [{
							barPercentage: this.barWidth
						}]
					}
				}
			}
		},
		mounted() {
			this.renderChart(this.data, this.options)
		}
	}
</script>`

If I log this.options it returns me everything, recently I had the same issue deleting the node_modules and yarn install solved it but not it seems not to work..

Here you see an result of what i describe above:

![image](https://user-images.githubusercontent.com/12531305/35614529-b2c2452c-066f-11e8-820d-95dd006effab.png)

### Environment
- vue.js version: ^2.5.2
- vue-chart.js version: ^3.0.0
- npm version: 5.6.0

**Comment by apertureless** [comment]
Have you tried updating to `3.1.0` ?

**Comment by smgjreinieren** [comment]
@apertureless Yes i tried it but it seems not to solve anything

**Comment by apertureless** [comment]
Can you create a minimal jsfiddle / codepen for reproduction?

**Comment by yuens1002** [comment]
just curious.... what is calling this function
`display: function(context) {
  return context.dataset.data[context.dataIndex] > 0;`
in your code?  not sure it would return a value otherwise....

**Comment by smgjreinieren** [comment]
@apertureless I will try later today. @yuens1002 you'r right the function isn't called, first I thought it was from 'chartjs-plugin-datalabels' to return the numbers of percentage.

**Comment by neculaesei** [comment]
I have the exact same issue, strangely enough it only occurs in macOS (both Chrome and Safari).

**Comment by smgjreinieren** [comment]
What I did to fix it: 
						```
yAxes: [{stacked: true}]
```
