### ISSUE TITLE
release 3.2.0 not available on npm registry

### ISSUE THREAD

**Issue by ecaldwell** [apertureless/vue-chartjs#309]
### Expected Behavior
`npm install vue-chartjs@3.2.0` should install. 

### Actual Behavior
`No matching version found for vue-chartjs@3.2.0`

### Environment
- vue.js version: N/A
- vue-chart.js version: `3.2.0`
- npm version: `5.6.0`

**Comment by apertureless** [comment]
Ups 🙈 
Published it :)
