### ISSUE TITLE
 ReferenceError: LIB_VERSION is not defined

### ISSUE THREAD

**Issue by bharathvaj1995** [apertureless/vue-chartjs#311]
### Expected Behavior
Should not throw error. 

### Actual Behavior
Throws this error. Please release a patch update ASAP.
![image](https://user-images.githubusercontent.com/16360498/36140464-5eb5f12e-10c7-11e8-8d1c-ec2d5f8e430b.png)

### Environment
- vue.js version: 2.5.13
- vue-chart.js version: 3.2.0
- npm version: 5.3.0

**Comment by apertureless** [comment]
#310
