### ISSUE TITLE
Props width and height should accept String

### ISSUE THREAD

**Issue by ianclever** [apertureless/vue-chartjs#314]
When I need to use height or width in percentage I get the warning saying it should be Number.
Just add [Number, String] to the type of these props.

**Comment by apertureless** [comment]
The HTML Canvas accepts only pixel values as width and height 
👉 https://www.w3schools.com/tags/att_canvas_width.asp

If you want your chart width and height in relative values, you need to add it over the container

👉 http://www.chartjs.org/docs/latest/general/responsive.html#responsive-charts
