### ISSUE TITLE
2 BarCharts on same page are not working correctly.

### ISSUE THREAD

**Issue by aron-l1988** [apertureless/vue-chartjs#315]
Several BarCharts on same page are not working correctly.

### Expected Behavior
All should work fine.

### Actual Behavior
Only last one is working fine, when I click legend on other charts, chart is often refreshed and sometimes it is completely disappeared.

### Environment
- vue.js version: <2.5.2>
- vue-chart.js version: <2.5.6>
- npm version: <4.3.0>

**Comment by aron-l1988** [comment]
P.S.: I have passed different chart-id to each bar chart but got same result.

**Comment by apertureless** [comment]
¯\_(ツ)_/¯

Please provide a reproduction link (codepen / jsfiddle)

**Comment by aron-l1988** [comment]
https://codepen.io/apertureless/pen/vxWbqB

For HTML

<div class="app">
    {{ message }}
  <bar-chart chart-id="bar1"></bar-chart>
  <bar-chart chart-id="bar2"></bar-chart>
</div>

For JS


Vue.component('bar-chart', {
  extends: VueChartJs.Bar,
  mounted () {
    this.renderChart({
      labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
      datasets: [
        {
          label: 'Data One',
          backgroundColor: '#f87979',
          data: [40, 39, 10, 40, 39, 80, 40]
        }
      ]
    }, {responsive: true, maintainAspectRatio: false})
  }
  
})

var vm = new Vue({
  el: '.app',
  data: {
    message: 'Hello World'
  }
})

And please click legend of first chart.
You may find it is refreshed several times.

**Comment by aron-l1988** [comment]
Sorry, mistyped.

For HTML

<div class="app">
    {{ message }}
  <bar-chart chart-id="bar1"></bar-chart>
  <bar-chart chart-id="bar2"></bar-chart>
</div>

**Comment by aron-l1988** [comment]
```<div class="app">
    {{ message }}
  <bar-chart chart-id="bar1"></bar-chart>
  <bar-chart chart-id="bar2"></bar-chart>
</div>```

**Comment by apertureless** [comment]
Can not reproduce this.
It is working fine for me

📺 [Demo](https://codepen.io/apertureless/details/vprOpj/)



![vue-chartjs-mutliple-charts](https://media.giphy.com/media/B36TS7aMumQqlJGYI5/giphy.gif)

**Comment by aron-l1988** [comment]
Hmm...
It's weird.
It 's not working on my side.
Could you please provide me your code snippet?

**Comment by apertureless** [comment]
Just click the demo link above. Its a public codepen.

**Comment by aron-l1988** [comment]
![screen shot 2018-02-19 at 5 29 40 pm](https://user-images.githubusercontent.com/26144654/36388417-15f9dc50-159c-11e8-965c-858b8ce5eb7c.png)

**Comment by aron-l1988** [comment]
It works fine on safari but not working chrome.

**Comment by apertureless** [comment]
It's working on my chrome.
Whats your environment?
Browser Version / OS etc.

**Comment by aron-l1988** [comment]
I have upgraded vue-chartjs package.
"vue-chartjs": "^3.2.1"

Chrome Browser Version: Version 64.0.3282.167 (Official Build) (64-bit)
OSX: El Capitan 10.11.6

**Comment by apertureless** [comment]
Well I can **not** reproduce this.

I've tested it on 

## Mac OSX 10.12.6

- Chrome 66.0.3354.0
- Chrome 64.0.3282.167
- Safari 11.0.3
- Firefox 58.0.2
- Firefox 59.0b12

## Windows 7

- Chrome 66.0.3354.0
- Chrome 64.0.3282.167

And all worked fine for me.

--- 

Does it only occur on chrome?
Have you tested firefox ? And have you tested it in chrome ingognito mode? 
Maybe it is due to some browser addons you are using.
