### ISSUE TITLE
Display blank without piechart when there is only zero data for all labels

### ISSUE THREAD

**Issue by DeepakAryal** [apertureless/vue-chartjs#316]
![vuechart](https://user-images.githubusercontent.com/17777925/36470129-f6720570-1711-11e8-922a-ad96a5120992.png)
### Expected Behavior
In my project i have used a pie chart. When all the data for available labels is 0, i want to display some message that no records available or some visual clue.
### Actual Behavior
But nothing displays. only legend labels are visible. i can't see pie chart anymore.

### Environment
- vue.js version: 2.4.4
- vue-chart.js version: 3.2.1
- npm version: 3.10.10

**Comment by apertureless** [comment]
Thats normal behaviour of chart.js
If there is no data, no chart will be shown.

You can simple check it by checking your chartData.

```js
<template>
<chart v-if="chartData.datasets[0].data.length > 0" />
<p v-else>
no data available
</p>
</template>
```

**Comment by DeepakAryal** [comment]
it replaces the whole legend labels and chart too. i just want to replace the blank chart with some text only. i need to see legend label as it is even there is no data

**Comment by apertureless** [comment]
I don't think this is possible.
But you can check out either the [Chart.js Docs](http://www.chartjs.org/docs/latest/) or the [Chart.js Issue Board](https://github.com/chartjs/Chart.js/issues) as it is not really related to `vue-chartjs` and a more general chart.js question.
