### ISSUE TITLE
Chart rerenders without any data changes

### ISSUE THREAD

**Issue by Lasergunspewpew** [apertureless/vue-chartjs#317]
Hey guys, 
Not sure if this is a bug in vue-chartjs or not but I'm not able to find a solution. 
I would appreciate any points in the right directon to fix this if this problem is caused by my own stupidity. Thanks.

### Expected Behavior
I'm trying to update the chart over a select field. Whenever the user select another option, i.e. year, the chart should fetch the needed data and update the chart. 
I've implemented my own watcher, because I'm not developing with seperate files and I couldn't get the responsiveProp to work. 

### Actual Behavior
Well, the chart rerenders when it should. But also when it shouldn't. I.e there are *no* changes made to the dataset, but it still rerenders the chart. It also killed my chrome after some time (So beware when you open the pen) 

Created a pen which reproduces the behaviour: https://codepen.io/anon/pen/NyBGBy

### Environment
- vue.js version: 2.5.13
- vue-chart.js version: newest from unpkg
- npm version: does not apply here
- chartjs version: 2.7.1

### Tried solutions
I was thinking I could solve this issue with not rerendering the chart, but only updating it. 
But `this._chart.update()` just tells me that _chart is not defined... 
Also tried to use the reactiveProp Mixin, but I couldn't get it to work with my setup. 

Any help is greatly appreciated. I'm actually pretty sure I made some / several mistakes. 
If this is the case feel free to close this Issue. 

Thanks, 
Lasergunspewpew

**Comment by apertureless** [comment]
I will take a look if I find some time.

🚨 `this._chart.update()` is now `this.$data._chart.update()` 

Have you tried to remove the `deep: true` attribute?

**Comment by Lasergunspewpew** [comment]
Thanks for your time! 

Good to know!  but `this.$data._chart.update()` keeps triggering the watcher multiple times per second as well, thus leading to a crash. 

I tried to remove the `deep: true` attribute, but the watcher doesn't get triggered that way. 
Not sure if this might be an issue within the chart object. 
I would like to remove the `deep: true` nevertheless because i know which data will change, but i haven't found an option to create the watcher only for i.e. `this.chart.datasets[0].data`. 

Right now I'm rerendering the chart by toggling a button which hide/show the chart. Not the best UX :P

**Comment by apertureless** [comment]
Well, as I see you have not read the docs 🙊 

There is a passage about the reactivity system and its [limitations](http://vue-chartjs.org/#/home?id=limitations)

Thats why the watcher does not get triggered, if you remove the `deep:true` property. And thats also the reason why the mixin is not working.

---

So you actually should replace your whole data object.

Take a look at [ARK Explorer](https://explorer.ark.io/) they also fetched new data on a time select. It's btw. [Open Source](https://github.com/ArkEcosystem/ark-explorer/blob/master/src/components/ChartWrapper.vue)
