### ISSUE TITLE
Context menu on click on Individual Bar graph area

### ISSUE THREAD

**Issue by Suvojit-tapadar** [apertureless/vue-chartjs#318]
Context menu on click on Bar graph

Hi,
I want to get a context menu on (single click or right click) on individual bar graph. In context menu there will be some option that i need to perform on that particular bar graph.
any help?

![screen shot 2018-02-24 at 2 03 22 pm](https://user-images.githubusercontent.com/20398710/36627674-2e085852-196c-11e8-8a05-b7465ec4732c.png)

So Here is the above screenshot where i want to show my own menu item that will perform on that particular Bar graph.
Example: Suppose i want to check hidden cost option on that bar graph.

### Environment
- vue.js version:  2.5.13
- vue-chart.js version: 3.2.1
- chart.js: 2.7
- npm version: 2.0

**Comment by apertureless** [comment]
Not sure if this is possible. 
You could however check if theres a plugin for it or you can write your own [Plugin API](http://www.chartjs.org/docs/latest/developers/plugins.html)

Chart.js exposes a lot of its API, so you can create plugins and your own chart types. 

However I think you should either ask on the [Chart.js](https://github.com/chartjs/Chart.js/) repo or stackoverflow. As this is not really vue-chart.js specific.
