### ISSUE TITLE
Update Chart.js docs to include link to vue-chartjs

### ISSUE THREAD

**Issue by etimberg** [apertureless/vue-chartjs#32]
Hey @apertureless,

I'm one of the maintainers of Chart.js. I came across your plugin and I'd love for you to PR it into our docs. The docs list some popular extensions [here](https://github.com/chartjs/Chart.js/blob/master/docs/10-Notes.md#popular-extensions) and I think vue-chartjs would fit in well there.

Cheers,
Evert

**Comment by apertureless** [comment]
Thanks for the suggestion!
[PR](https://github.com/chartjs/Chart.js/pull/3834) is on its way
