### ISSUE TITLE
How to change values format

### ISSUE THREAD

**Issue by oswaldofreitas** [apertureless/vue-chartjs#321]
### Expected Behavior
allow to change values format

### Actual Behavior
I'm trying to change a Pie chart values format to currency, but after I add the `scales` option it throws an error:

<img width="937" alt="screen shot 2018-03-01 at 10 18 09" src="https://user-images.githubusercontent.com/10772835/36846552-e689c30e-1d39-11e8-840c-16499dc9609c.png">

and this is the code:

```
import { Pie, mixins } from 'vue-chartjs'
// import { toCurrency } from 'utils/formatter.util'

const { reactiveProp } = mixins

export default {
  extends: Pie,
  mixins: [reactiveProp],
  props: ['options'],
  mounted () {
    // Overwriting base render method with actual data.
    this.renderChart(this.chartData, {
      responsive: false,
      maintainAspectRatio: false,
      legend: {
        display: false
      },
      scales: {
        yAxes: [{
          ticks: {
            callback: function (value, index, values) {
              console.log(value, index, values)
              return '' + value
            }
          }
        }]
      }
    })
  }
```

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 3.2.1
- npm version: 5.6.0

**Comment by apertureless** [comment]
Working fine for me

https://codepen.io/apertureless/pen/BZKBdX?editors=1010

**Comment by oswaldofreitas** [comment]
could you show me an example with Pie?

https://codepen.io/anon/pen/paXPdR?editors=1010

**Comment by oswaldofreitas** [comment]
oh, thank you very much. I didn't find that in docs.

**Comment by apertureless** [comment]
@oswaldofreitas 
Well its not in the docs per se,
but it's kind of clear that the doughnut and pie charts, do not have X / Y axis. As their data is neigher linear nor logarithmic nor time based.

So there is no X or Y scale to style there.
