### ISSUE TITLE
how to add shadow for stroke?

### ISSUE THREAD

**Issue by craigcosmo** [apertureless/vue-chartjs#323]
I want to add shadow for the line in my chart.

My code is like so

 

       import { Line } from 'vue-chartjs'
        import Chart  from 'chart.js'
    
        let draw = Chart.controllers.line.prototype.draw;
        Chart.controllers.line.prototype.draw = function() {
           draw.apply(this, arguments);
           let ctx = this.chart.chart.ctx;
           let _stroke = ctx.stroke;
           ctx.stroke = function() {
               ctx.save();
               ctx.shadowColor = '#aaa';
               ctx.shadowBlur = 10;
               ctx.shadowOffsetX = 0;
               ctx.shadowOffsetY = 4;
               _stroke.apply(this, arguments);
               ctx.restore();
           }
        };
    
        const BasicLineChart = {
          extends: Line,
          props: ['data', 'options'],
          mounted () {
            const options = this.options || {
                responsive: true, 
                maintainAspectRatio: false,
                borderWidth: 1,
                legend: {
                    display: false
                },
                scales: {
                    yAxes: [{
                        position: 'right',
                        scaleLabel: {
                            display: false,
                            labelString: 'Pris',
                            fontFamily: 'apercu-light',
                        },
                        gridLines: {
                            display:true,
                            color: 'rgba(255, 255, 255, 0.6)'
                        },
                        ticks: {
                            beginAtZero:false,
                            mirror: true
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            display: true,
                        },
                        scaleLabel: {
                            display: false,
                        },
                        gridLines: {
                            display:true,
                            color: 'rgba(255, 255, 255, 0.6)'
                        }
                    }]
                }
            }
    
            this.renderChart(this.data, options)
        }
    }
    
        export default {
            props: ['id'],
            components: {
                BasicLineChart,
            },
            created() {
                this.draw()
            },
            data() {
                return {
                    chartData: {},
                    showChart: false
                }
            },
            methods: {
                draw() {
                    axios.get('url/' + this.id).then(({ data })=> {
                        this.showChart = true;
                    })
                } 
            }
        };

With that code I was able to add the shadow for line. However the grids for added blue shadow as well, which is not desired behavior. The grids should not have any shadow.

The screen shot of the shadow on grids and line. Notice the slighly blue shade along the grids line? I want to get rid of it

![screen shot 2018-03-08 at 4 44 18 pm](https://user-images.githubusercontent.com/538657/37203992-2e3fae14-23c2-11e8-923b-4e85c285e447.png)

What could be done to get rid of the shadow on the grids ?

**Comment by apertureless** [comment]
Hey @craigcosmo 
I guess you should ask this on either stackoverflow or the main [chart.js](https://github.com/chartjs/Chart.js) repo. As it is not really related to vue-chartjs.
