### ISSUE TITLE
width ignored in flexbox (Bulma)

### ISSUE THREAD

**Issue by aviv1233** [apertureless/vue-chartjs#325]
I'm using `Bulma v0.6.2` CSS framework with `vue-chartjs 3.2.1`, trying to put a Line chart inside a Box container. My `chartjs` options are all correct and as advised for achieving responsiveness:

    responsive: true,
    maintainAspectRatio: false

I also use a container for my chart as advised (the `chart-container` **class** property):

    <UserActivity
    v-bind:chart-data="datacollection"
    v-bind:options="graphOptions"
    class="chart-container"
    />

with the following `chart-container` CSS:

    .chart-container {
        position: relative;
        height: 40px;
    }

but it seems like the chart ignores the parent element's width:

[![enter image description here][1]][1]

I looked around and found some hints that the issue may be related to Bulma and Flexbox.

This jsfiddle reproduces the issue.
https://jsfiddle.net/c6tu3qgx/

  [1]: https://i.stack.imgur.com/HgTCI.png

**Comment by apertureless** [comment]
Hey @aviv1233 

eeh, you are **not** using `vue-chartjs` in your example 🙈 Just chart.js. So I guess you need to check the [chart.js repo](https://github.com/chartjs/Chart.js)

If you're using `vue-chartjs` it can be quite easily done.
Here is a pen with vue-grid-layout https://codepen.io/apertureless/pen/jZOBeV
as you see the chart is fully responsive in width and height.
