### ISSUE TITLE
Problems with latest version

### ISSUE THREAD

**Issue by prsolucoes** [apertureless/vue-chartjs#327]
### Expected Behavior
Render the graph

### Actual Behavior
Error on console

![image](https://user-images.githubusercontent.com/395096/37373319-dd8fd1d4-26f4-11e8-9c8c-0958caf6040f.png)

### Environment
- vue.js version: 2.5.15
- vue-chart.js version: 3.2.1
- npm version: 5.6.0

**Comment by prsolucoes** [comment]
Im using now:
"vue-chartjs": "2.8.7",

That the problem dont happen

**Comment by apertureless** [comment]
Can you please provide a link for reproduction? jsfiddle / codenpen?

**Comment by prsolucoes** [comment]
I have only the project as open-source:
https://github.com/prsolucoes/gohc-web-app

To check the problem, clone the project, change the version in package.json file and:

```
npm install
npm run start
```

Thanks.

**Comment by apertureless** [comment]
👉 [How to use](https://github.com/apertureless/vue-chartjs#how-to-use)

I follow semver, so version 3 is a breaking change. Just check the [Release Notes](https://github.com/apertureless/vue-chartjs/releases/tag/v3.0.0), they contain a migration guide.
