### ISSUE TITLE
How to add new custom axes?

### ISSUE THREAD

**Issue by sgoess** [apertureless/vue-chartjs#328]
### Expected Behavior
I'd like to create a new custom axis, as explained in the Chart.js docs: http://www.chartjs.org/docs/latest/developers/axes.html

It basically uses 
`let MyScale = Chart.Scale.extend({ ` ...
and
`Chart.scaleService.registerScaleType('myScale', MyScale, defaultConfigObject);`

However, I can't get this working with my vue-chartjs implementation.

### Actual Behavior

I'm currently using this wrapper for my charts - somere here the new axis definition and registration should probably be included. But where?

```javascript
import { Bar, mixins } from 'vue-chartjs'

export default {
  extends: Bar,
  mixins: [mixins.reactiveProp],
  props: ['chartData', 'options'],
  watch: {
    'options': {
      handler (newOption, oldOption) {
        this.$data._chart.destroy()
        this.renderChart(this.chartData, this.options)
      },
      deep: true
    }
  },
  mounted () {
    this.renderChart(this.chartData, this.options)
  }
}
```

Can you please point me in the right direction? I guess it's really simple.

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 3.2.1
- npm version: latest

**Comment by apertureless** [comment]
You should be able to just copy & paste the example code above.
You have to make sure to import the chart.js instance before.

```js

import Chart from 'chart.js'
import { Bar, mixins } from 'vue-chartjs'

const MyScale = Chart.Scale.extend({})
Chart.scaleService.registerScaleType('myScale', MyScale, defaultConfigObject);

export default {
....
}

```

**Comment by sgoess** [comment]
Works like a charm, thank you so much!

**Comment by netocervantes98** [comment]
How can I extend TimeScale? I just want to change just one method from that class.
