### ISSUE TITLE
How to set the font and font size?

### ISSUE THREAD

**Issue by nkbem** [apertureless/vue-chartjs#329]
### Expected Behavior
Can anyone guide me how to change the font to 'Open Sans' for instance.

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Depends on where you want to set this font. Labels / Tooltips and so on.
However, it is all documented:

http://www.chartjs.org/docs/latest/general/fonts.html?h=font

**Comment by sinavali** [comment]
vue: 3.3.11
vite: 5.0.8

currently adding this to option prop:
defaults: {
            font: {
                family: "my custom font"
            },
        }

and not working at all.
i've test the code in the doc you referred and it's not working too.

is there any way vue-chart handling this? chart is rendering a canvas so i can't (or i don't know how) to change the font the elements inside. i need to change the font of everything to one font.

**Comment by sinavali** [comment]
i managed to do so by: 
import {Chart as ChartJS} from 'chart.js'
ChartJS.defaults.font.family = "my custom font";
