### ISSUE TITLE
something about tree-shaking

### ISSUE THREAD

**Issue by SunnySnail** [apertureless/vue-chartjs#332]
when I use ``mainfields: [jsnext:main, main]`` for tree-shaking, something is wrong with this.

It says

 ```javascript
Error in mounted hook: "Error: Chart.js - Moment.js could not be found! You must include it before Chart.js to use the time scale
```

### Environment
- vue.js version: <2.5.16>
- vue-chart.js version: <3.2.1>
- npm version: <5.6.0>

**Comment by apertureless** [comment]
well, but you have chart.js installed ?

**Comment by SunnySnail** [comment]
yes, I install chart.js with npm

**Comment by apertureless** [comment]
What is your build enviroment? Are you using webpack?
Can you post some reproduction?

**Comment by SunnySnail** [comment]
I use webpack to build my project
- some warning tips
```
[WDS] Warnings while compiling.
warnings @ webpack-internal:///./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:147
webpack-internal:///./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:153 ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'D:\project-fed\ecloud\client-web\node_modules\moment\src\lib\locale'
```
- some wrong tips
```
vue.esm.js?efeb:591 [Vue warn]: Error in mounted hook: "Error: Chart.js - Moment.js could not be found! You must include it before Chart.js to use the time scale. Download at https://momentjs.com"

found in

---> <Monitor> at src\components\chart\monitor.vue
       <InstanceChart> at src\pages\cloud\chart.vue
         <Instance> at src\pages\cloud\instance.vue
           <App> at src\App.vue
             <Root>
````

```
```

### Environment
vue.js version: <2.5.16>
vue-chart.js version: <3.2.1>
npm version: <5.6.0>
webpack: <3.11.0>

**Comment by apertureless** [comment]
Does not seem to be related to treeshaking.
It seems more a moment.js problem.

Have you set an alias to use the Chart.js standalone version?
You could try to set an alias to the bundled version.
http://www.chartjs.org/docs/latest/getting-started/installation.html#bundled-build

Or import the bundled version before `vue-chartjs` or maybe install moment.js

**Comment by apertureless** [comment]
closed due to inactivity

**Comment by Lekha30** [comment]
Hi there, I face this issue. Can someone shed some light? I have installed moment.js too
