### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [apertureless/vue-chartjs#335]
### Expected Behavior
When i use search all results go to 404
### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Hey @dmitry-vakhnenko 
thanks for finding this.

I guess something with algolias docsearch plugin is not working properly.
Will check this.

**Comment by apertureless** [comment]
The documentation page is now fixed.
