### ISSUE TITLE
export 'generateChart' was not found in 'vue-chartjs'

### ISSUE THREAD

**Issue by devduke** [apertureless/vue-chartjs#336]
### Expected Behavior

Using:
`import { generateChart } from 'vue-chartjs'` as described in the example here: [http://vue-chartjs.org/#/home?id=custom-new-charts](http://vue-chartjs.org/#/home?id=custom-new-charts)

### Actual Behavior

Using it this way throws a warning:
`export 'generateChart' was not found in 'vue-chartjs'`

### Environment
- vue.js version: 2.5.13
- vue-chart.js version: 3.3.0
- npm version: 5.6.0

**Comment by apertureless** [comment]
Gotcha! 
Thanks for this. Fixed in `3.3.1`
