### ISSUE TITLE
Code Sample for scatter charts

### ISSUE THREAD

**Issue by vigorem** [apertureless/vue-chartjs#337]
I've looked around the docs for a fiddle/code sample of Scatter charts usage but couldn't find any. Does anyone can share an example?

Many thanks

Sébastien

**Comment by apertureless** [comment]
If someone else is looking for it:

https://github.com/apertureless/vue-chartjs/blob/develop/src/examples/ScatterExample.js

**Comment by vigorem** [comment]
Many thanks for this

**Comment by naor10** [comment]
The above example shows the Scatter as single unconnected points.
How can I produce a connected Scatter chart?

Like this:
![image](https://user-images.githubusercontent.com/41241989/53943088-0483eb00-40c5-11e9-9b1d-6d7f267b1d16.png)
