### ISSUE TITLE
Labling does not support

### ISSUE THREAD

**Issue by danishsaber** [apertureless/vue-chartjs#339]
### Expected Behavior
In vue-chartjs we cant not explicitly mention axis label.
like, as i use to show amount on Y-axis,there is no way to show label "Amount" on Y-axis.

### Actual Behavior

There showed be away to Add labling on axis 

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Hey @danishsaber 
I don't really understand what you are trying to do.
Can you give a small example?

**Comment by apertureless** [comment]
closed due to inactivity
