### ISSUE TITLE
style chart

### ISSUE THREAD

**Issue by Rustem81** [apertureless/vue-chartjs#348]
### Expected Behavior
Add paragraph style to  manual

### Actual Behavior
No description found, how to add CSS properties to charts

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
You find all styling related properties in the official chart.js docs.

http://www.chartjs.org/docs/latest/


I don't really understand what you want to style. However you can add custom styles to the tooltips, legend etc.

http://www.chartjs.org/docs/latest/configuration/tooltip.html

**Comment by Rustem81** [comment]
many thanks.
these links to documents written by you, what I need)
I'm a beginner) web is my hobby)
