### ISSUE TITLE
Horizontal Chart  direction

### ISSUE THREAD

**Issue by medmedchiheb** [apertureless/vue-chartjs#349]
### Expected Behavior
i want to use the Horizontal Chart in direction of rtl (Right to left ) but i could not achieve it 
can you help me 

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 3.3.1
- npm version: 5.5.1

**Comment by apertureless** [comment]
Hey @medmedchiheb 

Do you mean real RTL support? So reverse the text of the scales ? Or just the direction of how the bars are rendered?

**Comment by medmedchiheb** [comment]
thank you
