### ISSUE TITLE
Chart loading before data() loads

### ISSUE THREAD

**Issue by drew-sullivan** [apertureless/vue-chartjs#353]
### Expected Behavior

Chart loads after data() loads

### Actual Behavior

Chart loads before data() loads and renders an empty chart, but on initial save, the chart and data load fine. I must be missing something basic. Is there something in the docs that references this? 

The data is retrieved from a database, so it's async, and the chart is trying to load before data() is ready. Is there a way to make it wait to load? Thanks for the help!

### Child Component Script
```
<script>
import { Line } from 'vue-chartjs'

export default {
  extends: Line,
  props: [ 'sortedStats' ],
  data () {
    return {
      datacollection: {
        labels: this.sortedStats.map(stat => stat.date).reverse(),
        datasets: [
          {
            label: 'Out of 10',
            fill: false,
            borderColor: 'rgba(111, 38, 61, 1)',
            backgroundColor: 'rgba(111, 38, 61, 0.4)',
            pointBackgroundColor: 'rgba(255, 184, 28, 1)',
            pointBorderColor: 'rgba(4, 30, 66, 1)',
            pointBorderWidth: 3,
            data: this.sortedStats.map(stat => stat.of10).reverse()
          }
        ]
      }
    }
  },
  mounted () {
    this.renderChart(this.datacollection)
  }
}
</script>
```

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 3.3.1
- npm version: 5.6.0

**Comment by apertureless** [comment]
Well you need to save your state and then render the chart only if your data is loaded.

```js
<your-chart v-if="loaded" sortedStats ="data" />
```

Because your data is async, the template evaluation and rendering in vue.js is finished before your data arrives. 
So you need the conditional rendering.

**Comment by drew-sullivan** [comment]
I knew it was something simple! Thanks for the help!

**Comment by jonathanbroderick** [comment]
drew-sullivan, did you ever get this to work?
