### ISSUE TITLE
this.renderChart is not a function when using default example

### ISSUE THREAD

**Issue by tiriwo** [apertureless/vue-chartjs#355]
What other configurations or imports do I need to make, i get TypeError: this.renderChart is not a function when I use the example given as, 

```
import { Bar } from 'vue-chartjs'

export default {
  extends: Bar,
  mounted () {
    // Overwriting base render method with actual data.
    this.renderChart({
      labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      datasets: [
        {
          label: 'GitHub Commits',
          backgroundColor: '#f87979',
          data: [40, 20, 12, 39, 10, 40, 39, 80, 40, 20, 12, 11]
        }
      ]
    })
  }
}
```
do i need to define the function or what?

**Comment by apertureless** [comment]
Are you using the latest version of `vue-chartjs` ?

**Comment by tiriwo** [comment]
As per the last the commit, yes i'm using the latest version

**Comment by apertureless** [comment]
Can you post a reproduction? 
Generally this seems right.

You are extending the `Bar` component and like a mixin you have all methods and props defined in there. So `this.renderChart()` should be available.

You could try `mixins: [Bar]` instead of `extends`

**Comment by tiriwo** [comment]
`mixins: [Bar]` works thanks,

**Comment by johngoben-righteye** [comment]
I am having the same error and mixins also do not work.

**Comment by LenKIM** [comment]
I found how to solve this problem. I added `BaseCharts.js` in example packages on project and then It works.

![image](https://user-images.githubusercontent.com/22192085/89618882-efb61300-d8c7-11ea-8eae-de99e2ec7393.png)

![image](https://user-images.githubusercontent.com/22192085/89618897-f6dd2100-d8c7-11ea-8898-e1fe93e00758.png)

hope to solve the problem you have
