### ISSUE TITLE
Chart doesnt load when I used it in vuejs app with data from rest api

### ISSUE THREAD

**Issue by amazintesla** [apertureless/vue-chartjs#356]
### Expected Behavior
I want to add simple bar chart to show expenses in my app. 

### Actual Behavior

I try to do this but i think that I do something wrong with mapping the response data or with the options of chart, because i dont see a chart. Once it loaded, and when i refreshed chart dissapear

Can anyone help me with my issue? 

This is my BarChart.vue component
`<script>
   
    import { Bar } from 'vue-chartjs'
 
    export default{
       
        extends: Bar,
 
        props: {
            chartData: {
                type: Array,
                required: false
            },
            chartLabels: {
                type: Array,
                required: true
            }
        },
       
        data(){
            return {
                options : {
                    scales: {
                        yAxes: [{
                            ticks: {
                                begintAtZero: true
                            },
                            gridLines: {
                                display: true
                            }
                        }],
                        xAxes: [{
                            gridLines: {
                                display: false
                            }
                        }]
                    },
                    legend: {
                        display: false
                    },
                    responsive : true,
                    maintainAspectRatio: false
                }
            }
        },
 
        mounted() {
            this.renderChart({
                labels: this.chartLabels,
                datasets: [
                    {
                        label: 'wydatki',
                        backgroundColor: 'blue',
                        data: this.chartData,
                        borderWidth: 1
                    }
                ]
            },this.options)
        }
}
</script>`

And Home.vue component:
`<script>
   
    import axios from 'axios';
    import addExpense from './addExpense.vue';
    import BarChart from './BarChart.vue';
   
    export default {
        components: {
            'add-expense': addExpense,
            'bar-chart' : BarChart
        },
        data() {
            return {
                expenses: [],
                labels: []
            }
        },
        mounted(){
            this.requestData()
        },
        methods: {
            requestData() {
                axios.get('http://localhost:3000/expenses')
                .then(response => {
                    console.log(response.data)
 
                    this.expenses = response.data.map(expense => expense.amount)
                    this.labels = response.data.map(expense => expense.date)                   
                })
                .catch(error => {
                    console.log(error)
                })
            }
        }
    }
</script>`

### Environment
- vue.js version: ^2.5.11
- vue-chart.js version: ^3.3.1
- npm version: <version here>

**Comment by apertureless** [comment]
https://github.com/apertureless/vue-chartjs/issues/341
https://github.com/apertureless/vue-chartjs/issues/322

**Comment by amazintesla** [comment]
ok , thank you very much. One question why my chart doesnt start at zero?

**Comment by amazintesla** [comment]
thank you very much 👍
