### ISSUE TITLE
Question - make Line not so rounded

### ISSUE THREAD

**Issue by OlegFromOmsk** [apertureless/vue-chartjs#357]
Hello
How can I make Line not so rounded? I need Line with acute angles
Thanks
![image](https://user-images.githubusercontent.com/32164733/39979924-09d9c492-576b-11e8-87a6-8369303758d6.png)

**Comment by apertureless** [comment]
Please check the official [Chart.js docs](http://www.chartjs.org/docs/latest/charts/line.html). You can control it over the `lineTension` option.
