### ISSUE TITLE
vue-chart.js does not respect partial imports

### ISSUE THREAD

**Issue by moustachedelait** [apertureless/vue-chartjs#359]
### Expected Behavior
When I create a new chart by
`  import {Line} from 'vue-chartjs'`
I expect that my total package will not include parts from chart.js that I am not using, like controller.bar.js

### Actual Behavior
the complete chart.js package is included in my build

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 3.3.1
- npm version: 6.0.0

**Comment by apertureless** [comment]
Hello @moustachedelait 

thanks for the issue.
However what you are describing is currently not possible. As chart.js has no es6 exports thus tree shaking will not work. 

Furthermore chart.js only exports their whole lib as one so there is no way to only import parts that you need.

**Comment by VasekProchazka** [comment]
Hello, 
I found in chartjs doc (https://www.chartjs.org/docs/master/getting-started/v3-migration/) something about tree shaking.
