### ISSUE TITLE
Chart inside a table cell.

### ISSUE THREAD

**Issue by hifall** [apertureless/vue-chartjs#362]
Is it possible to chart inside a table cell? I am using Bootstrap-Vue at: https://bootstrap-vue.js.org/.

My code looks like this:
```
<template>
    <b-table id="domain-table" :items="myProvider" :fields="fields"></b-table>
</template>
<script>
    export default {
        data: () => {
            return {
            items: [],
            fields: [
              {key: 'Name'},
              {key: 'PassFail'}
            ],
            currentPage: 1,
            perPage: 5,
            totalRows: 0
          }
        },
        methods: {
          getRowCount (items) {
        return items.length
      },
      myProvider (ctx, providerCB) {
        Axios.get('example.com/data.php')
          .then((response) => {
            providerCB(response.data)
          }, (error) => {
            console.log(error)
            return []
          })
      }
    }
    }
</script>
```

The above code retrieves data from example.com, then displays the rows in a table with 2 columns: Name and PassFail, like this:
'John Doe'  80/20
which indicates that the person 'John Does' passes 80% of the time, and fails 20% of the time.

Now I'd like to use vue-chartjs to render this 80/20 into a horizontal bar chart (or pie chart), how would I do this?

Thanks!

**Comment by apertureless** [comment]
This is rather a question about vue-bootstrap.
If you can pass in vue components into the table component, you can pass in a chart component with the data as props.

However I never used vue bootstrap. So you better ask the question there
