### ISSUE TITLE
Axis labels?

### ISSUE THREAD

**Issue by murbanowicz** [apertureless/vue-chartjs#368]
I cannot find any examples how to apply axis labels.
E.g. http://www.chartjs.org/samples/latest/charts/line/basic.html you can see MONTH for X and VALUE for Y.
How can I apply this labels with Vue-ChartJS ?

**Comment by apertureless** [comment]
Well you can just check out the official chart.js repository. As all samples are open source.

You can set it over the [scaleLabel](http://www.chartjs.org/docs/latest/axes/labelling.html#scale-title-configuration)

Just pass the object as your options.

```js
scales: {
  xAxes: [{
    display: true,
    scaleLabel: {
      display: true,
      labelString: 'Month'
    }
  }],
  yAxes: [{
    display: true,
    scaleLabel: {
      display: true,
      labelString: 'Value'
    }
  }]
}
```

**Source:** https://github.com/chartjs/Chart.js/blob/master/samples/charts/line/basic.html
