### ISSUE TITLE
Since last update bar chart will no longer stack

### ISSUE THREAD

**Issue by tttwb** [apertureless/vue-chartjs#38]
I just ran npm update and I am now running the  latest version of vue-chartjs.

Before the update the bar chart I have with two data sets was stacking on top perfectly (on the x axes).
However now that I have updated the bars of the two data sets are next to each other instead of on top of one another.

I have tried adding stacked: true etc to the chart options x axes however nothing now seems to work.

Is anybody else having this issue with stacking bar charts?

**Comment by apertureless** [comment]
This is weird. The latest update, only changed some stuff in the reactiveProp mixin.

**Comment by tttwb** [comment]
I just deleted the node modules folder for vue-chartjs and then ran npm install vue-chartjs@2.3.2
and they are now stacking as they should again.

So not sure what the issue is here but guess I'll just have to not update until it is fixed.

Thanks

**Comment by tttwb** [comment]
Just deleted the folder again and reinstalled the latest version, now appears to be working as it should.

Very strange indeed.

**Comment by apertureless** [comment]
Maybe it was a missmatch or conflict with peer dependencies. As I updated chart.js in vue-chartjs@2.3.4 

But good, that it's working now.
