### ISSUE TITLE
options.legend.labels.filter not working

### ISSUE THREAD

**Issue by jaimesanz** [apertureless/vue-chartjs#383]
### Expected Behavior
Using [filter in legend](https://www.chartjs.org/docs/latest/configuration/legend.html#legend-label-configuration) should hide some labels.

I defined options like this:

```
options: {
                legend: {
                    display: true,
                    labels: {
                        filter: (legendItem, data) => {
                            return false; // this should hide all legends
                        }
                    }
                },
            }
```

And my datasets look like this:

```
datasets: [
                    {
                        data: this.data1,
                        label: 'label1',
                    },
                    {
                        data: this.data2,
                        label: 'label2',
                    },
                    ]
```

chartData looks like this:

```
chartData: {

    datasets: datasets,
    labels: this.labels,

}
```

My chart component looks like this:

```
import { Bar, mixins } from 'vue-chartjs';

export default {
    extends: Bar,
    mixins: [mixins.reactiveProp],
    props: ['chartData', 'options'],
    mounted() {
        this.renderChart(this.chartData, this.options);
    },
};

```

And I'm calling it like this:

```
<my-bar-chart
                :chart-data="chartData"
                :options="options"/>
```

As I understand it, it shouldn't show any legend, but it still does.

### Actual Behavior
Legends are displayed anyway. It seems like filter is never being called (if I put console.log() statements in it, they don't appear in the browser's console).

### Environment
- vue.js version: 2.5.16
- vue-chart.js version: 3.3.1
- npm version: 5.6.0

**Comment by jaimesanz** [comment]
Ok so I was trying to recreate this in codepen, but it [actually works](https://codepen.io/anon/pen/MXREMx?editors=1010).

In the codepen, however, I'm setting `options` in _data_, while in my actual code my `options` is a _computed_ property (which I failed to mention before). 

I did this because I have multiple charts, and they all share most options, except the title. My idea was to have one computed 'options' object per chart, which were copies of an `options` object defined in the data, but with an added title. Something like [this](https://codepen.io/anon/pen/bKJYGM?editors=1010).

As you can see, filtering the legend doesn't work on that last codepen.

It appears, however, that the problem is not the fact that `options` is a computed property. The problem is in my implementation of it; in the way I'm making a copy of it.

If I change the implementation to use Object.assign, it [works as expected](https://codepen.io/anon/pen/JZVOGX?editors=1010).

I don't actually understand why this is what was causing the issue or [why this was the solution](https://pics.me.me/my-code-doesnvt-work-have-no-idea-why-my-code-14032928.png); I just stumbled upon the solution by trying to make a failing codepen D:

¿Am I missing something about computed properties in general?

**Comment by apertureless** [comment]
Hey @jaimesanz 

well this is quite easy and obvious 🙈 

```js
const copy = JSON.parse(JSON.stringify(this.options));
```

Your problem here is `JSON.stringify()` [1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)

Because this way this will work perfectly for a pure key/value object. But you have functions in your `this.options` object. If you `console.log` it out, you will see that your function is gone. So there is no more filter function available, because `stringify()` does not handle javascript functions.

`Object.assign()` however also can copy your function. If you console.log out your options after `Object.assign()` you will see that your `filter()` function is preserved.

:v:

**Comment by jaimesanz** [comment]
@apertureless thanks for the explanation!

**Comment by apertureless** [comment]
You're welcome!
