### ISSUE TITLE
Scatter example with HTML legend

### ISSUE THREAD

**Issue by OstapL** [apertureless/vue-chartjs#385]
Your work very cool, but can you create example with HTML legend?

**Comment by apertureless** [comment]
Well it is actually just this: https://www.chartjs.org/docs/latest/configuration/legend.html#html-legends

However right now you have to call it over the internal chart object.

```js
this.$data._chart.generateLegend()
```

With the upcoming version `3.4` I will make a wrapper around this, so you can call `this.generateLegend()`.
