### ISSUE TITLE
vue-chjartjs is not working with require js

### ISSUE THREAD

**Issue by bitakeyogesh** [apertureless/vue-chartjs#391]
I am trying to use vue-chartjs using requirejs but it's not working. In my application i am not using webapack, how to use vue-chartjs in gulp build system with requirejs.

### Expected Behavior
define( [ 'vue-chartjs' ], function( app, vueChart ) {
console.log(vueChart );
//vueChart should give the expected output
});

### Actual Behavior

define( [ 'vue-chartjs' ], function( app, vueChart ) {
console.log(vueChart );
//vueChart is undefined
});

### Environment
- vue.js version: 2.5.16
- vue-chart.js version: 3.3.2
- npm version: 5.5.1

**Comment by apertureless** [comment]
Please post a reproduction so I can look into it.

**Comment by apertureless** [comment]
closed due to inactivity
