### ISSUE TITLE
Show tooltip on linegraph when mouse is above/below data point

### ISSUE THREAD

**Issue by chovy** [apertureless/vue-chartjs#393]
### Expected Behavior

Tooltip shows when you rollover any point on the vertical grid (ie: you don't have to click the actual dot, just be directly above or below it).

### Actual Behavior

Tooltip only shows if you are directly over a point on a line graph

### Environment
- vue.js version: 2.5.16
- vue-chart.js version: 3.3.2
- npm version: 5.6.0

**Comment by apertureless** [comment]
Please check out the documentation: http://www.chartjs.org/docs/latest/configuration/tooltip.html

You can set `intersect: false` and play with the mode. I guess `mode: index` should do the trick.

**Comment by chovy** [comment]
That' didn't work.
