### ISSUE TITLE
Reactive vue-chartjs run in dev mode but production build freezes browser

### ISSUE THREAD

**Issue by Fenn-CS** [apertureless/vue-chartjs#395]
### Expected Behavior
Reactive chart that works on  `npm run dev` should work on production `npm run build`

### Actual Behavior
Reactive chart works on run dev but production export freezes browser.

### More Details

I am trying to create live chart with vuechartjs, after looking at several resources online I managed to put up something that works (on `npm run dev`)... However I noticed I was unable to things like `this._chart.update()` a method I found in online examples so I am forced to render the chart in the watch method. 

It works smoothly on dev but when the build (`npm run build`) is created the live chat does not work! I loads the initial values (0's) the browser starts complaining of a slow down which will eventually freeze the browser. Why this behavior?

**LineChart.js**

    import { Line } from 'vue-chartjs'
    
    export default {
      extends: Line,
      props: ['data', 'options'],
      mounted () {
        this.renderChart(this.data, this.options)
      },
      watch: {
        'data': {
          handler: function () {
            this.renderChart(this.data, this.options)
          }
        }
      }
    }

**Monitor.vue** (Where the live chart is observed)

    <template>
      <div class="data row">
        <section class="col-md-6">
          <h5>Consumption</h5>
          <line-chart :data="chartData" :options="chartOptions"></line-chart>
        </section>
        <section class="data col-md-6">
          <h5>Line Observation</h5>
          <bubble-chart ></bubble-chart>
        </section>
      </div>
    </template>
    
    <script>
    import LineChart from '../components/LineChart.js'
    import BubbleChart from '../components/BubbleChart.js'
    
    export default {
      components: { LineChart, BubbleChart },
      name: 'Monitor',
      mounted () {
        this.getLiveReadings()
      },
      data () {
        return {
          msg: 'Live Monitor',
          chartData: {
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            datasets: [
              {
                label: 'Meter 1',
                borderColor: '#649EB9',
                pointBackgroundColor: 'white',
                borderWidth: 1,
                pointBorderColor: '#649EB9',
                backgroundColor: 'transparent',
                data: [0, 0, 0, 0, 0, 0, 0]
              },
              {
                label: 'Meter 2',
                borderColor: '#249EBF',
                pointBackgroundColor: 'white',
                borderWidth: 1,
                pointBorderColor: '#249EBF',
                backgroundColor: 'transparent',
                data: [0, 0, 0, 0, 0, 0, 0]
              },
              {
                label: 'Meter 3',
                borderColor: '#FF0E00',
                pointBackgroundColor: 'white',
                borderWidth: 1,
                pointBorderColor: '#FF0E00',
                backgroundColor: 'transparent',
                data: [0, 0, 0, 0, 0, 0, 0]
              }
            ]
          },
          chartOptions: {responsive: true, maintainAspectRatio: false, minUnit: 10}
        }
      },
      methods: {
        getLiveReadings: function () {
          setInterval(() => {
            pushData(this.chartData.datasets[0].data)
            pushData(this.chartData.datasets[1].data)
            pushData(this.chartData.datasets[2].data)
          }, 5000)
        }
      }
    }
    
    function pushData (data) {
      data.push(Math.floor(Math.random() * 100) + 1)
      data.shift()
    }
    </script>
    
    
    <style scoped>
    h1, h2 {
      font-weight: normal;
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      display: inline-block;
      margin: 0 10px;
    }
    
    </style>

The Bubble chart works correctly both on dev and when build is created. What's suprising and more confusing is that the live chart does not even show signs of being laggy in dev mode. How do I improve this behavior? 

I posted on S. O (https://stackoverflow.com/questions/51580336/reactive-vue-chartjs-run-in-dev-mode-but-production-build-freezes-browser)

### Environment
- vue.js version: 2.9.6
- vue-chart.js version: 3.3.2
- npm version: 6.2.0

**Comment by apertureless** [comment]
Hey @Fenn-CS 

it is hard to debug it without any reproduction. Can you post a fiddle?

**Comment by Fenn-CS** [comment]
Hey @apertureless apparently using 

```
handler: function () {
        this.renderChart(this.data, this.options)
      }
```

Instead of 

```
handler: function () {
        this.$data._chart.update()
      }
```

Makes it really slow, so it appears there is a huge performance difference in both. Also I figured out my complain about not being about to use `this._chart.update()` has been updated to `this.$data._chart.update()` for the manipulation of the original chart.js object. 

At the end of the day, the handler function was taken of as after taking a closer look at the documentation I noticed it was not needed when a reactive mixin is present.

For reference here is my implementation :
https://github.com/Fenn-CS/ElecHub/blob/master/src/components/LineChart.js
 https://github.com/Fenn-CS/ElecHub/blob/master/src/components/Monitor.vue

**Comment by apertureless** [comment]
Yeah `update()` is more cost effective as it is an internal of chart.js to update the chart. However in some cases it is required to re-render the chart. That is more expensive as it trashes the chart instance and recreates everything.

**Comment by yasser17** [comment]
Same problem here! I'm using nuxtjs. When I run dev env the chart works fine, but when I run to production the browser freeze. 

this is my component

`<script>
import { Line, mixins } from 'vue-chartjs'

export default {
	extends: Line,
	mixins: [mixins.reactiveProp],
	props: {
		chartData: {
			type: Object,
			require: true,
			default: () => {},
		},
		options: {
			type: Object,
			default: null,
		},
	},
	mounted() {
		this.renderChart(this.chartData, this.options)
	},
}
</script>`
