### ISSUE TITLE
no access to chart data in legendCallback 

### ISSUE THREAD

**Issue by jamessouth** [apertureless/vue-chartjs#397]
### Expected Behavior
Passing in the chart as the argument gives you the nested config object, which in turn has the data object used to create the chart, with datasets and labels nested inside, from which the custom legend can be generated.  This is how I did it in another (non-vue) chart.js project.

### Actual Behavior
chart.config.data.datasets and .labels are empty.  My chart otherwise seems to work just fine, it renders correctly and is properly affected by my options object.

### wrapper.vue
```
<template>
  <div>
      <BarChart
      :options="chartOptions"
      :chart-data="chartData">
      </BarChart>
  </div>
</template>

<script>
import BarChart from './BarChart.vue';

export default {
  data() {
    return {
      chartData: null,
      chartOptions: {
        legendCallback(barChart) {
          console.log(barChart);  <-- barChart.config.data does not have the chart data/labels as expected
        },
        legend: {
          display: false,
        },
      },
    };
  },
  components: {
    BarChart,
  },
```

### BarChart.vue
```
<script>
import { Bar, mixins } from 'vue-chartjs';

const { reactiveProp } = mixins;

export default {
  extends: Bar,
  mixins: [reactiveProp],
  props: ['options'],
  mounted() {
    this.renderChart(this.chartData, this.options);
    this.$data._chart.generateLegend();
  },
  name: 'BarChart',
};
</script>
```

### Environment
- vue.js version: 2.5.16
- vue-chart.js version: 3.3.2
- npm version: 6.2.0

**Comment by jamessouth** [comment]
As a workaround, I moved the legendCallback out of the options object and into methods in the wrapper, then in my API call method, right after setting this.chartData with the API data, I call legendCallback with said data.  legendCallback then creates a ul and appends to the div holding the chart.

**Comment by sean-hill** [comment]
@apertureless I believe it only happens when using reactive `chart-data` with `reactiveProp`. I'm facing this same issue, where the `legendCallback` `chart` parameter is:

```
{
  datasets: [],
  labels: []
}
```
Instead of actually containing the data and labels.

**Comment by syntaxx101** [comment]
> @apertureless I believe it only happens when using reactive `chart-data` with `reactiveProp`. I'm facing this same issue, where the `legendCallback` `chart` parameter is:
> 
> ```
> {
>   datasets: [],
>   labels: []
> }
> ```
> Instead of actually containing the data and labels.

@sean-hill did you manage to get a work-around?

**Comment by syntaxx101** [comment]
> As a workaround, I moved the legendCallback out of the options object and into methods in the wrapper, then in my API call method, right after setting this.chartData with the API data, I call legendCallback with said data. legendCallback then creates a ul and appends to the div holding the chart.

@jamessouth could I please get sample code of what you did?

**Comment by sean-hill** [comment]
@syntaxx101 I do not 😞 I ended up not using the `legendCallback`.

**Comment by apertureless** [comment]
Can you post a reproduction? 
I will look into this.

**Comment by jamessouth** [comment]
@syntaxx101 and cc: @sean-hill  here is my project components folder: https://github.com/jamessouth/Vue-Project-9/tree/master/web-app-dashboard/src/components

the relevant components and their relationship:  BarDonut  ->  Wrapper  ->  Bar and Donut chart components.

BarDonut sets up the chart options and calls the API.  Wrapper takes the data and calls the `legendCallback` in a watcher, and the result is passed to the Bar/Donut charts along with the chart options.  Here is the live site:  https://jamessouth.github.io/Vue-Project-9/

**Comment by gtzures** [comment]
> @syntaxx101 and cc: @sean-hill here is my project components folder: https://github.com/jamessouth/Vue-Project-9/tree/master/web-app-dashboard/src/components
> 
> the relevant components and their relationship: BarDonut -> Wrapper -> Bar and Donut chart components.
> 
> BarDonut sets up the chart options and calls the API. Wrapper takes the data and calls the `legendCallback` in a watcher, and the result is passed to the Bar/Donut charts along with the chart options. Here is the live site: https://jamessouth.github.io/Vue-Project-9/

Hey @jamessouth, the above links seem dead. Any chance to get those code samples again?

**Comment by jamessouth** [comment]
@gtzures oops I changed the repo name:

https://github.com/jamessouth/dashboard/tree/master/src/components

https://jamessouth.github.io/dashboard/
