### ISSUE TITLE
Support Vue Router

### ISSUE THREAD

**Issue by kn7007** [apertureless/vue-chartjs#398]
When use vue-chartjs with nuxtjs (include vue router), if i click to new path and then return old path with chart, i get error "getContext is undefined". But if i refresh the page, it working properly. May be vue-chartjs not full supported for vue router. You have any solution for this?

### Environment
- vue.js version: 2.5.17
- vue-chart.js version: 3.4.0
- npm version: 5.6.0

**Comment by apertureless** [comment]
Please provide a reproduction (jsfiddle, codesandbox, glitch ...)
