### ISSUE TITLE
Change name of the render method to ensure compatiblity with Vue 2.0

### ISSUE THREAD

**Issue by LinusBorg** [apertureless/vue-chartjs#4]
Vue 2.0 introduces its own [`render()` function](http://rc.vuejs.org/guide/render-function.html) which allows to render vdom elements programatically (like Reactjs).

This will conflict with the render() method of this lib.

to ensure compatibility, a breaking change is required - renaming this method to something else, e.g. `renderChart()`

**Comment by apertureless** [comment]
Good point. There are also a few other points that needs to get changed to be fully compatible with vue 2

**Comment by LinusBorg** [comment]
There sure are.

**Comment by apertureless** [comment]
Working on it in the release/2.0 branch. 
Seems to be working for now, but needs more testing :) 

Will look into how to handle multiple releases, so people who are using vue 2.0 can use it, too.

**Comment by apertureless** [comment]
It is now installable over `npm i vue-chartjs@next`
