### ISSUE TITLE
Please update1.1.3 chartjs to 2.5.0

### ISSUE THREAD

**Issue by chenyulun** [apertureless/vue-chartjs#40]
Please update   Branch:release/1.1.3
 chartjs to 2.5.0

**Comment by apertureless** [comment]
It's updated.
You can update your vue-chartjs package to 1.1.4 or use the legacy tag.

`npm install vue-chartjs@legacy` 

`npm install vue-chartjs@1.1.4`

**Comment by chenyulun** [comment]
1.1.4  package.json 这个版本的依赖还是2.1.6
"dependencies": {
    "babel-runtime": "^6.0.0",
    "chart.js": "^2.1.6",
    "vue": "^1.0.21"
  },
???

**Comment by apertureless** [comment]
Oh yeah, it seems that yarn did not changed the version in package.json, weird.
But its fixed in `1.1.5`

**Comment by chenyulun** [comment]
yarn add chart.js@2.5.0 --dev   
by the way    (非常感谢你提供的这个项目)Thank you very much for your offer of this project

**Comment by apertureless** [comment]
Well I used `yarn upgrade-interactive` however it seemed to not change the version in package.json
