### ISSUE TITLE
Rounded corners for Vue.js

### ISSUE THREAD

**Issue by ande4559** [apertureless/vue-chartjs#401]
### Expected Behavior
I want to create rounded corners for my bar chart. but i dont know if this is possible in vue.js, i have seen some javascript options, but the problem is i render the chart on an other way than in js. So i want to ask where to apply the changes and can i make it work in Vue?
html

    <line-chart
                class="graph_donut"
                :chart-data="datacollection"
                :options="{
                  responsive: true,
                  maintainAspectRatio: false,
                  cutoutPercentage: 70,
                  legend:{display: false}}"
                  :styles="{height: '100%', width: '30%', position: 'relative', margin: '20px'}">
    </line-chart>

script

    
    fillData3 () {
      Promise.all([this.getStoreScore()]).then(([store]) => {
        this.datacollection3 = {
          labels: ['Man', 'Tirs', 'Ons', 'Tors', 'Fre', 'Lør', 'Søn'],
          datasets: [
            {
              type: 'line',
              yAxisID: 'rightSide',
              fill: false,
              borderColor: '#00C5C7',
              pointBorderWidth: 5,
              label: 'anmeldelser',
              backgroundColor: '#00C5C7',
              data: [
                200,
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage
              ]
            },
            {
              type: 'bar',
              label: 'Dårlig',
              backgroundColor: '#FF686E',
              borderWidth: 0,
              data: [store.amount.zero.percentage,
                store.amount.zero.percentage,
                store.amount.zero.percentage,
                store.amount.zero.percentage,
                store.amount.zero.percentage,
                store.amount.zero.percentage,
                store.amount.zero.percentage
              ]
            },
            {
              type: 'bar',
              label: 'Mangelfuld',
              backgroundColor: '#FFDC00',
              borderWidth: 0,
              data: [
                store.amount.one.percentage,
                store.amount.one.percentage,
                store.amount.one.percentage,
                store.amount.one.percentage,
                store.amount.one.percentage,
                store.amount.one.percentage,
                store.amount.one.percentage
              ]
            },
            {
              type: 'bar',
              label: 'Okay',
              backgroundColor: '#95DB6B',
              borderWidth: 0,
              data: [
                store.amount.two.percentage,
                store.amount.two.percentage,
                store.amount.two.percentage,
                store.amount.two.percentage,
                store.amount.two.percentage,
                store.amount.two.percentage,
                store.amount.two.percentage
              ]
            },
            {
              type: 'bar',
              label: 'God',
              backgroundColor: '#58BF5D',
              borderWidth: 0,
              data: [
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage,
                store.amount.three.percentage
              ]
            }
          ]
        }
      })
        }

my code^

the working example
https://codepen.io/jordanwillis/pen/jBoppb

### Actual Behavior
How and where should i put the functions/actions?

### Environment
- vue.js version: <newest>
- vue-chart.js version: <v2>
- npm version: <newest>

**Comment by apertureless** [comment]
Hey @ande4559 

Well, you can make custom modifications and custom charts in vue-chartjs, quite the same way as you would do in Chart.js.

This might help you: https://vue-chartjs.org/#/home?id=custom-new-charts

There are basically 4 steps.

## 1. Import Chart.js

In your `RoundedBarChart.vue` you have to import the Chart.js object. Because otherwise you will have no access to the functions provided by it.

```js
import Chart from 'chart.js'
```

## 2. Import the `generateChart` helper.
I provided a small helper to generate the chart components. You will use this later.

```js
import { generateChart } from 'vue-chartjs'
```

## 3. Make a custom chart.

You can then use the `extend()` options and controllers provided by chart.js. I guess it will be quite copy and paste from your codepen.

```js
/ 3. Extend on of the default charts
// http://www.chartjs.org/docs/latest/developers/charts.html
Chart.defaults.RoundedBar = Chart.defaults.Bar;
Chart.controllers.RoundedBar = Chart.controllers.bar.extend({ /* custom magic here */})
```

## 4. Generate your chart component

Then you can use the `generateChart` helper to generate a vue component.

```js
const RoundedBarChart = generateChart('rounded-bar', 'RoundedBar')
```

## 5. Use it

Then you can use it in your component like the default charts.

```js
export default {
	extends: RoundedBarChart,
	mounted () {
		this.renderChart(data, options)
	}
}
```

**Comment by ande4559** [comment]
Hey thanks for the answer, i have done this.

(images down under)

what is the next step and what do you say i should copy?



https://gyazo.com/77c46c478a706da8c8d1ce2669f18208

[https://i.gyazo.com/thumb/1200/77c46c478a706da8c8d1ce2669f18208-png.jpg]<https://gyazo.com/77c46c478a706da8c8d1ce2669f18208>

Gyazo<https://gyazo.com/77c46c478a706da8c8d1ce2669f18208>
gyazo.com
property=




https://gyazo.com/58516ad22baa85aeb7253ca6be187060

[https://i.gyazo.com/thumb/1200/58516ad22baa85aeb7253ca6be187060-png.jpg]<https://gyazo.com/58516ad22baa85aeb7253ca6be187060>

Gyazo<https://gyazo.com/58516ad22baa85aeb7253ca6be187060>
gyazo.com
property=




https://gyazo.com/1e5f946db11d79b9f4b55ca4661f5bc5

[https://i.gyazo.com/thumb/1200/1e5f946db11d79b9f4b55ca4661f5bc5-png.jpg]<https://gyazo.com/1e5f946db11d79b9f4b55ca4661f5bc5>

Gyazo<https://gyazo.com/1e5f946db11d79b9f4b55ca4661f5bc5>
gyazo.com
property=





https://gyazo.com/366ba72b5926aa416c0628e6d7c80024

[https://i.gyazo.com/thumb/1200/366ba72b5926aa416c0628e6d7c80024-png.jpg]<https://gyazo.com/366ba72b5926aa416c0628e6d7c80024>

Gyazo<https://gyazo.com/366ba72b5926aa416c0628e6d7c80024>
gyazo.com
property=






________________________________
Fra: Jakub <notifications@github.com>
Sendt: 10. august 2018 12:30
Til: apertureless/vue-chartjs
Cc: ande4559; Mention
Emne: Re: [apertureless/vue-chartjs] Rounded corners for Vue.js (#401)


Hey @ande4559<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fande4559&data=02%7C01%7C%7C4b7b3ee7c5cf4f6747e308d5febd1d68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636695010546157953&sdata=RYCIdiX%2BvguqwLcVam6Loo17y8jko9UyPT2Us2zk7ys%3D&reserved=0>

Well, you can make custom modifications and custom charts in vue-chartjs, quite the same way as you would do in Chart.js.

This might help you: https://vue-chartjs.org/#/home?id=custom-new-charts<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvue-chartjs.org%2F%23%2Fhome%3Fid%3Dcustom-new-charts&data=02%7C01%7C%7C4b7b3ee7c5cf4f6747e308d5febd1d68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636695010546157953&sdata=TEViC2ufCYcdx5JVxYCxe0nWzXUpbUm5D%2F8LYsFCrLM%3D&reserved=0>

There are basically 4 steps.

1. Import Chart.js

In your RoundedBarChart.vue you have to import the Chart.js object. Because otherwise you will have no access to the functions provided by it.

import Chart from 'chart.js'

2. Import the generateChart helper.

I provided a small helper to generate the chart components. You will use this later.

import { generateChart } from 'vue-chartjs'

3. Make a custom chart.

You can then use the extend() options and controllers provided by chart.js. I guess it will be quite copy and paste from your codepen.

/ 3. Extend on of the default charts
// http://www.chartjs.org/docs/latest/developers/charts.html
Chart.defaults.RoundedBar = Chart.defaults.Bar;
Chart.controllers.RoundedBar = Chart.controllers.bar.extend({ /* custom magic here */})

4. Generate your chart component

Then you can use the generateChart helper to generate a vue component.

const RoundedBarChart = generateChart('rounded-bar', 'RoundedBar')

5. Use it

Then you can use it in your component like the default charts.

export default {
        extends: RoundedBarChart,
        mounted () {
                this.renderChart(data, options)
        }
}

**Comment by apertureless** [comment]
Well, ... just the code related to the rounded borders from your codepen.


```js
Chart.helpers.drawRoundedTopRectangle = ...
Chart.elements.RoundedTopRectangle ...
Chart.defaults.roundedBar...
Chart.controllers.roundedBar...

```

If you have further questions StackOverflow may be the right choice.
As this is not really vue-chartjs related.

**Comment by ande4559** [comment]
Hello i have still not made i work.

if i create my diagram.js with


mport Chart from 'chart.js'
import { generateChart } from 'vue-chartjs'

Chart.defaults.RoundedBar = Chart.defaults.Bar
Chart.controllers.RoundedBar = Chart.controllers.bar.extend({
  draw () {
    my rounded corners things goes here
  }
})

const RoundedBarChart = generateChart('rounded-bar', 'RoundedBar')

export default {
  extends: RoundedBarChart,
  mounted () {
    this.renderChart(this.data, this.options)
  }
}


and then import this in my vue component like this



import Diagram from './js/diagram.js'


export default {
  name: 'dashboard',
  components: {
    Diagram
  }
  data () {
    return {
      selected: 1,
      datacollection: null,
    }
  },
async mounted () {
    await this.fillData()
}

fillData () {
      Promise.all([this.getStoreScore()]).then(([store]) => {
        this.datacollection = {
          labels: ['Dårlig', 'Mangelfuld', 'Okay', 'God'],
          datasets: [
            {
              curvature: 1,
              label: ['Dårlig', 'Mangelfuld', 'Okay', 'God'],
              backgroundColor: ['#FF686E', '#FFDC00', '#95DB6B', '#58BF5D'],
              borderWidth: 2,
              data: [20, 30, 20, 30]
      }
}


nothings happends or else it tells me some of my drawings dont exist.

best regards
Anders





________________________________
Fra: Jakub <notifications@github.com>
Sendt: 10. august 2018 12:30
Til: apertureless/vue-chartjs
Cc: ande4559; Mention
Emne: Re: [apertureless/vue-chartjs] Rounded corners for Vue.js (#401)


Hey @ande4559<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fande4559&data=02%7C01%7C%7C4b7b3ee7c5cf4f6747e308d5febd1d68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636695010546157953&sdata=RYCIdiX%2BvguqwLcVam6Loo17y8jko9UyPT2Us2zk7ys%3D&reserved=0>

Well, you can make custom modifications and custom charts in vue-chartjs, quite the same way as you would do in Chart.js.

This might help you: https://vue-chartjs.org/#/home?id=custom-new-charts<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvue-chartjs.org%2F%23%2Fhome%3Fid%3Dcustom-new-charts&data=02%7C01%7C%7C4b7b3ee7c5cf4f6747e308d5febd1d68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636695010546157953&sdata=TEViC2ufCYcdx5JVxYCxe0nWzXUpbUm5D%2F8LYsFCrLM%3D&reserved=0>

There are basically 4 steps.

1. Import Chart.js

In your RoundedBarChart.vue you have to import the Chart.js object. Because otherwise you will have no access to the functions provided by it.

import Chart from 'chart.js'

2. Import the generateChart helper.

I provided a small helper to generate the chart components. You will use this later.

import { generateChart } from 'vue-chartjs'

3. Make a custom chart.

You can then use the extend() options and controllers provided by chart.js. I guess it will be quite copy and paste from your codepen.

/ 3. Extend on of the default charts
// http://www.chartjs.org/docs/latest/developers/charts.html
Chart.defaults.RoundedBar = Chart.defaults.Bar;
Chart.controllers.RoundedBar = Chart.controllers.bar.extend({ /* custom magic here */})

4. Generate your chart component

Then you can use the generateChart helper to generate a vue component.

const RoundedBarChart = generateChart('rounded-bar', 'RoundedBar')

5. Use it

Then you can use it in your component like the default charts.

export default {
        extends: RoundedBarChart,
        mounted () {
                this.renderChart(data, options)
        }
}

**Comment by ande4559** [comment]
This is vue charts? I cant extend like vue-charts docs says

Sendt fra min iPhone

Den 21. aug. 2018 kl. 09.22 skrev Jakub <notifications@github.com<mailto:notifications@github.com>>:


Like I said, you should go to stackoverflow for this kind of questions. As it is not vue-chartjs related.

**Comment by devWaleed** [comment]
Opening this thread again because i am unable to export it as a generic chart to be reused.

I have tried to export like this:

export RoundedBarChart = generateChart('custom-line', 'roundedBar');

and in my original chart component, I have tried both ways:

Chart.defaults.roundedBar and my import this component into that component. Both ways i get either context not found or template missing etc.

Please show a way to export as global chart.

Thanks

**Comment by xoppyk** [comment]
If any need horizontal bar rounded...

<script>
/* eslint-disable prefer-destructuring */
/* eslint-disable camelcase */
/* eslint-disable no-underscore-dangle */
import Chart from 'chart.js';
import { generateChart, mixins } from 'vue-chartjs';
import ChartJsPluginDataLabels from 'chartjs-plugin-datalabels';

Chart.helpers.drawRoundedTopRectangle = function (ctx, x, y, width, height, radius) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  // top right corner
  ctx.lineTo(x + width - radius, y);
  ctx.quadraticCurveTo(x + width, y, x + width, y + radius);
  // bottom right	corner
  ctx.lineTo(x + width, y + height);
  // bottom left corner
  ctx.lineTo(x, y + height);
  // top left
  ctx.lineTo(x, y + radius);
  ctx.quadraticCurveTo(x, y, x + radius, y);
  ctx.closePath();
};

Chart.elements.RoundedTopRectangle = Chart.elements.Rectangle.extend({
  draw() {
    const { ctx } = this._chart;
    const vm = this._view;
    let left; let right; let top; let bottom; let signX; let signY; let borderSkipped; let
      radius;
    let { borderWidth } = vm;
    // Set Radius Here
    // If radius is large enough to cause drawing errors a max radius is imposed
    const cornerRadius = 10;

    if (!vm.horizontal) {
    // bar
      left = vm.x - vm.width / 2;
      right = vm.x + vm.width / 2;
      top = vm.y;
      bottom = vm.base;
      signX = 1;
      signY = bottom > top ? 1 : -1;
      borderSkipped = vm.borderSkipped || 'bottom';
    } else {
    // horizontal bar
      left = vm.base;
      right = vm.x;
      top = vm.y - vm.height / 2;
      bottom = vm.y + vm.height / 2;
      signX = right > left ? 1 : -1;
      signY = 1;
      borderSkipped = vm.borderSkipped || 'left';
    }

    // Canvas doesn't allow us to stroke inside the width so we can
    // adjust the sizes to fit if we're setting a stroke on the line
    if (borderWidth) {
    // borderWidth shold be less than bar width and bar height.
      const barSize = Math.min(Math.abs(left - right), Math.abs(top - bottom));
      borderWidth = borderWidth > barSize ? barSize : borderWidth;
      const halfStroke = borderWidth / 2;
      // Adjust borderWidth when bar top position is near vm.base(zero).
      const borderLeft = left + (borderSkipped !== 'left' ? halfStroke * signX : 0);
      const borderRight = right + (borderSkipped !== 'right' ? -halfStroke * signX : 0);
      const borderTop = top + (borderSkipped !== 'top' ? halfStroke * signY : 0);
      const borderBottom = bottom + (borderSkipped !== 'bottom' ? -halfStroke * signY : 0);
      // not become a vertical line?
      if (borderLeft !== borderRight) {
        top = borderTop;
        bottom = borderBottom;
      }
      // not become a horizontal line?
      if (borderTop !== borderBottom) {
        left = borderLeft;
        right = borderRight;
      }
    }

    ctx.beginPath();
    ctx.fillStyle = vm.backgroundColor;
    ctx.strokeStyle = vm.borderColor;
    ctx.lineWidth = borderWidth;

    // Corner points, from bottom-left to bottom-right clockwise
    // | 1 2 |
    // | 0 3 |
    const corners = [
      [left, bottom],
      [left, top],
      [right, top],
      [right, bottom],
    ];

    // Find first (starting) corner with fallback to 'bottom'
    const borders = ['bottom', 'left', 'top', 'right'];
    let startCorner = borders.indexOf(borderSkipped, 0);
    if (startCorner === -1) {
      startCorner = 0;
    }

    function cornerAt(index) {
      return corners[(startCorner + index) % 4];
    }

    // Draw rectangle from 'startCorner'
    let corner = cornerAt(0);
    let width; let height; let x; let y; let
      nextCornerId;
    let x_tl; let x_tr; let y_tl; let
      y_tr;
    let x_bl; let x_br; let y_bl; let
      y_br;
    ctx.moveTo(corner[0], corner[1]);

    for (let i = 1; i < 4; i++) {
      corner = cornerAt(i);
      nextCornerId = i + 1;
      if (nextCornerId === 4) {
        nextCornerId = 0;
      }

      width = corners[2][0] - corners[1][0];
      height = corners[0][1] - corners[1][1];
      x = corners[1][0];
      y = corners[1][1];

      radius = cornerRadius;

      // Fix radius being too large
      if (radius > Math.abs(height) / 2) {
        radius = Math.floor(Math.abs(height) / 2);
      }
      if (radius > Math.abs(width) / 2) {
        radius = Math.floor(Math.abs(width) / 2);
      }

      if (height < 0) {
      // Negative values in a standard bar chart
        x_tl = x;
        x_tr = x + width;
        y_tl = y + height;
        y_tr = y + height;

        x_bl = x;
        x_br = x + width;
        y_bl = y;
        y_br = y;

        // Draw
        ctx.moveTo(x_bl + radius, y_bl);
        ctx.lineTo(x_br - radius, y_br);
        ctx.quadraticCurveTo(x_br, y_br, x_br, y_br - radius);
        ctx.lineTo(x_tr, y_tr + radius);
        ctx.quadraticCurveTo(x_tr, y_tr, x_tr - radius, y_tr);
        ctx.lineTo(x_tl + radius, y_tl);
        ctx.quadraticCurveTo(x_tl, y_tl, x_tl, y_tl + radius);
        ctx.lineTo(x_bl, y_bl - radius);
        ctx.quadraticCurveTo(x_bl, y_bl, x_bl + radius, y_bl);
      } else if (width < 0) {
      // Negative values in a horizontal bar chart
        x_tl = x + width;
        x_tr = x;
        y_tl = y;
        y_tr = y;

        x_bl = x + width;
        x_br = x;
        y_bl = y + height;
        y_br = y + height;

        // Draw
        ctx.moveTo(x_bl + radius, y_bl);
        ctx.lineTo(x_br - radius, y_br);
        ctx.quadraticCurveTo(x_br, y_br, x_br, y_br - radius);
        ctx.lineTo(x_tr, y_tr + radius);
        ctx.quadraticCurveTo(x_tr, y_tr, x_tr - radius, y_tr);
        ctx.lineTo(x_tl + radius, y_tl);
        ctx.quadraticCurveTo(x_tl, y_tl, x_tl, y_tl + radius);
        ctx.lineTo(x_bl, y_bl - radius);
        ctx.quadraticCurveTo(x_bl, y_bl, x_bl + radius, y_bl);
      } else {
      // Positive Value
        ctx.moveTo(x + radius, y);
        ctx.lineTo(x + width - radius, y);
        ctx.quadraticCurveTo(x + width, y, x + width, y + radius);
        ctx.lineTo(x + width, y + height - radius);
        ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height);
        ctx.lineTo(x + radius, y + height);
        ctx.quadraticCurveTo(x, y + height, x, y + height - radius);
        ctx.lineTo(x, y + radius);
        ctx.quadraticCurveTo(x, y, x + radius, y);
      }
    }

    ctx.fill();
    if (borderWidth) {
      ctx.stroke();
    }
  },
});

Chart.defaults.RoundedBar = Chart.helpers.clone(Chart.defaults.horizontalBar);

Chart.controllers.RoundedBar = Chart.controllers.horizontalBar.extend({
  dataElementType: Chart.elements.RoundedTopRectangle,
});

// Chart.elements.Rectangle.prototype.draw = function draw() {

// };

Chart.defaults.global.plugins.datalabels.display = false;

const RoundedBarChart = generateChart('rounded-bar', 'RoundedBar');
const { reactiveProp } = mixins;

export default {
  components: { ChartJsPluginDataLabels },
  extends: RoundedBarChart,
  mixins: [reactiveProp],
  props: {
    options: {
      type: Object,
      default: null,
    },
  },
  watch: {
    options() {
      this._data._chart.destroy();
      this.renderChart(this.chartData, this.options);
    },
  },
  mounted() {
    this.renderChart(this.chartData, this.options);
  },
};
</script>

**Comment by tguimmaraess** [comment]
I know it's an issue from 2018 but this might help users running into the same issue.

For new versions of VueCharts and Vue 3, the priperty borderRadius works.

```
datasets: [
    {
      fill: false,
      borderColor: '#00C5C7',
      borderWidth: 4,
      borderRadius: 10,
  }
]
```
