### ISSUE TITLE
Chart not updating with Data set in a method

### ISSUE THREAD

**Issue by grogdonovich** [apertureless/vue-chartjs#406]
So I have this codepen I'm working on: 

https://codepen.io/PoasterToaster/pen/LBwdRx

You can select different pokemon at the bottom and a box populates with their information. You can see that the chart is instanced in an v-if box for the first time when one is selected, but this seems to be the problem. Since the data at that point is set, it never gets new information. If I try to give it a variable that is populated with data from the API feed, it can't load the data fast enough and breaks the canvas, so I have to hardcode in the data to pass to it, but I believe this means it never thinks it's getting new data passed to it, since that data I believe is parsed once the chart is loaded in. Any watcher I attach to the component never fires anything set to watch the data.

### Expected Behavior
Chart data should update every time a new option is selected according to the information of that option.

### Actual Behavior
Chart Data is only loaded for the initial option selected. It never updates when another option is set.

### Environment
- vue.js version: 2.5
- vue-chart.js version: 3.4

**Comment by apertureless** [comment]
Hey @grogdonovich 

hm your codepen seems broken.

Generally while working with api requests, you have to make sure, that the request is finished before passing your data to the chart. Otherwise the chart will break because of incomplete data.
