### ISSUE TITLE
Unable to refresh

### ISSUE THREAD

**Issue by mztlive** [apertureless/vue-chartjs#41]
### Expected Behavior
I want the chart to automatically refresh when the data changes to apply the new shape  E.g
```
//line-char.vue
<script>
    import {Line,mixins } from 'vue-chartjs'
    export default Line.extend({
        mixins:[mixins.reactiveProp],
        props: ["chartData", "options"],
        mounted () {
            this.renderChart(this.chartData, this.options)
        }
    })
</script>

//report.vue
<template>
    <line-chart :chartData="data"></line-chart>
</template>
<script>
    import LineChart from './charts/line-chart.vue'
    export default{
        data(){
            return {
                data : {
                    labels : ["January","February","March","April","May","June","July"],
                    datasets : [
                        {
                            backgroundColor:"rgba(1,12,3,0.3)",
                            label: 'GitHub Commits',
                            data : [28,48,40,19,96,27,100]
                        }
                    ]
                }
            }
        },
        created(){
            var vm = this;
            setInterval(function() {
                let temp = [];
                for(let i = 0; i< 7;i++){
                    temp.push(Math.ceil(Math.random()*100));
                }
                console.info(temp);
                vm.data.datasets[0].data = temp;
            }, 5000);
        },
        components:{
            LineChart
        }
    }
</script>
```
According to the documentation, I learned that using mixins can be refreshed, but the results of this code can not be expected.
### Actual Behavior
The result is that the data has changed and the graphics have not changed

### Environment
- OS: windows10 , chrome52

**Comment by apertureless** [comment]
# First

Does the chart even render properly? Because camelCase it not supported in props.
It should be

```javascript
<template>
    <line-chart :chart-data="data"></line-chart>
</template>
```

# Second

Try to change the data in `mounted()` it may be possible that because of [vue's lifecycle](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram) the data gets overwritten before the chart is rendered, thus the mixin which is only a watch on the the prop does not recognize the change in data.

**Comment by chenyulun** [comment]
`watch: {
            'chartData': function(){
                this.renderChart(this.Chartdata, this.options);
            }
        },`

**Comment by apertureless** [comment]
Closed due to inactivity.
