### ISSUE TITLE
Chart width not responsive inside grid css

### ISSUE THREAD

**Issue by mesqueeb** [apertureless/vue-chartjs#414]
### Expected Behavior

- When making the window bigger, chart should grow horizontally.
- When making the window smaller, chart should shrink horizontally.

### Actual Behavior

- ✅ When making the window bigger, chart _grows horizontally_.
- ❌ When making the window smaller, chart **does not shrink horizontally**.

### Codepen

I was able to reproduce my issue on Codepen. There must be something wrong with my CSS, but I'm not sure what. It's really straightforward grid css. **If you have any advice how to make the chart better responsive inside the grid, I'd be really grateful!**

https://codepen.io/mesqueeb/pen/xayNKK

### Environment
- vue.js version: 2.5.17
- vue-chart.js version: ^3.4.0

**Comment by apertureless** [comment]
This could be an issue with the core chart.js
You should raise the issue on the main repo.
