### ISSUE TITLE
LineOverLine custom chart in CodePen

### ISSUE THREAD

**Issue by mesqueeb** [apertureless/vue-chartjs#415]
I'm trying to implement the famous **LineWithLine** extension as per the Vue Chart documentation [here](https://vue-chartjs.org/#/home?id=custom-new-charts).

I tried to do this on the codePen, but it does not work:
https://codepen.io/mesqueeb/pen/vzQBJm?editors=0011

Is there any advice you can give on making **LineWithLine** work on Codepen?

#### PS:
On a vue file in my app it _does_ get loaded but I have other errors:
> Uncaught TypeError: Cannot read property 'top' of undefined
    at ChartElement.draw

To fix these I wanted to first try to make it work on the CodePen, then see where the problem is by changing the chart dataSets little by little.

**Comment by apertureless** [comment]
Hi @mesqueeb 

I don't really get your problem. The Codepen is working fine for me.

**Comment by mesqueeb** [comment]
@apertureless I'm not able to get the lineOverLine to show up (the vertical line on hover) on the codepen.

**Comment by apertureless** [comment]
<img width="983" alt="bildschirmfoto 2018-09-23 um 13 50 02" src="https://user-images.githubusercontent.com/4975917/45927725-9e9d1000-bf37-11e8-978d-0ce44e2a6862.png">

The vertical line is working fine for me.

**Comment by apertureless** [comment]
closed due to inactivity
