### ISSUE TITLE
Access to canvas style using reusable component

### ISSUE THREAD

**Issue by mauroalejandrojm** [apertureless/vue-chartjs#425]
### 
Hello guys, I am having a bad time trying to access to the canvas style to set gradients background for the plot and change the appearance of the canvas chart. I'm a beginner with vue.js, but I am trying to be as clean as posible with my code.

###
chart.vue
```
<script>
// https://codesandbox.io/embed/3j73wmjzq?module=%2Fsrc%2FApp.vue
import { Bar, mixins } from "vue-chartjs";
const { reactiveProp } = mixins;
export default {
  extends: Bar,
  mixins: [reactiveProp],
  props: ["chartData", "options"],
  mounted() {
    // this.chartData is created in the mixin.
    // If you want to pass options please create a local options object
    this.renderChart(this.chartData, this.options);
  }
};
</script>
```

component.vue
```
generatePlot() {
      this.chartData = {
        labels: this.$data.plotLabels,
        datasets: [
          {
            label: "Users",
            backgroundColor: "#42b983",
            hoverBackgroundColor: "#00695c",
            borderColor: "#0B5345",
            borderWidth: 1,
            data: this.$data.plotScores
          }
        ],
      };
      this.options = {
        reactive: true,
        responsive: true, 
        maintainAspectRatio: true,
        scales: {
          xAxes: [{
              stacked: true,
              gridLines: {display: false},
              maxBarThickness: 20
          }],
          yAxes: [{
              ticks: {
                  beginAtZero: true
              },
              gridLines: {display: false}
          }]
        }
      };
    }
```

### 
Labels and data are working well, the issue is related to the style using the custom chartjs component and modifying the style.
###

- vue.js version: <2.5.17>
- vue-chart.js version: <2.7.2>
- npm version: <6.4.1>

**Comment by mauroalejandrojm** [comment]
I solved with the canvas id property, now the problem is with the gradients for the plot chart following the previous structure of my code.

**Comment by apertureless** [comment]
You can access the `canvas` over the chartId with `document.querySelector` or the Vue.js way, over the `ref` attribute. `const canvas = this.$refs.canvas`

I've also wrote a tutorial some time ago about styling the charts with gradients:

https://hackernoon.com/creating-stunning-charts-with-vue-js-and-chart-js-28af584adc0a
