### ISSUE TITLE
Chart not resizing properly after window resize

### ISSUE THREAD

**Issue by AndreaRylander** [apertureless/vue-chartjs#426]
I have a simliar problem, I use jbaysolutions/vue-grid-layout and render a barchart insede one of the grid Items. When a grid item gets resized, I would like the bar chart to resize properly. It only resized to the new size after it get new data, so it naturally re-renders.
As I understand the chartjs docs, there is a plugin hook _resize_. But I dont really understand how to use it properly, can I invoke it somehow? Or is there another way to force the bar to resize?
Here is my code

grid component:
```javascript
<grid-layout :layout="widgetsz" :col-num="12" :row-height="30" :is-draggable="true" :isresizable="true" :vertical-compact="true" :margin="[10, 10]" :use-css-transforms="true" >
  <grid-item class="gridItem" v-for="widget in widgetsz" v-bind:key="widget.i">
     <disposition :globaldata="node.dispositions" :popdata="node.popdispositions" :h="(widget.h*30)*0.9" :w="widget.w"/>
     </grid-item>
  </grid-layout>
```

disposition.vue: 

```javascript
<div>
  <disposition-chart :styles="chartStyles" :chart-data="bardata" :width="w"  :options="options" />
</div>
```

```javascript
<script>
import { Bar,mixins } from 'vue-chartjs'
export default {
  extends: Bar,
  props: ['options', 'width'],
  mixins: [mixins.reactiveProp],
  mounted () { 
  this.addPlugin({
  id: 'plgin1',
  beforeUpdate(chart) {
    chart.config.data.labels.forEach(function (value, index, array) {
        var a = [];
        a.push(value.slice(0, 12));
        var i = 1;
        while(value.length > (i * 12)){
        	a.push(value.slice(i * 12, (i + 1) * 12));
            i++;
        }
        array[index] = a;
      })
    },
  })
    this.renderChart(this.chartData, this.options)
  },


}
</script>

**Comment by apertureless** [comment]
This will most likeley be a css issue.
The chart components needs to be `position: relative; height: 100%; width: 100%:`

https://codepen.io/apertureless/pen/jZOBeV

**Comment by sammandanu** [comment]
Hi guys, for those of you still wondering how to fix this issue, it happened to me too, and I finally found a solution. Add `maintainAspectRatio: false` to your chart options.
