### ISSUE TITLE
Disable floating point on Y axis.

### ISSUE THREAD

**Issue by hifall** [apertureless/vue-chartjs#428]
When I make a line chart, and there is only a data point with value smaller than 5, the Y axis displays floating point numbers like 1.0, 1.5, 2.0, etc. I would like it to display 1, 2, etc. since floating point doesn't make sense in my case. That is, hide the floating point numbers.

### Expected Behavior
There are integers only on the Y axis.

### Actual Behavior
There are floating point numbers on the Y axis.

### Environment
- vue.js version: 2.5.13
- vue-chart.js version: 3.1.0
- npm version: 5.6.0

**Comment by apertureless** [comment]
You can customize the labels of the axis and toolstips:

http://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats
