### ISSUE TITLE
Horizantal scroll on chart

### ISSUE THREAD

**Issue by bcmdevteam** [apertureless/vue-chartjs#429]
Hey,
I find this plugin very useful, I am using line chart, when lot of data is their then indicators and dated are overlapping.

can we add horizontal scroll so the will not be overlapped.

Thanks

### Environment
- vue.js version: <2>
- vue-chart.js version: latest
- npm version: latest

**Comment by apertureless** [comment]
You should post this on the core Chart.js repo.

vue-chartjs is only a wrapper, thus it can not add core features.
