### ISSUE TITLE
using object in props

### ISSUE THREAD

**Issue by ismaeladriano** [apertureless/vue-chartjs#430]
import { Line, mixins } from 'vue-chartjs'

const { reactiveProp } = mixins

export default {
  extends: Line,
  mixins: [reactiveProp],
  props: ['options'],
  mounted() {
    this.renderChart(this.chartData, this.options)
  }
}

Example object: ["R$ 79,76", "R$ 3.775,00", "R$ 3.470,00", "R$ 2.785,00"]

**Comment by apertureless** [comment]
Whats the issue here? Please clarify

**Comment by ismaeladriano** [comment]
The problem is that it is not possible to use string, in the charts, it follows the example of the last object.

this.dataCollectionMonetary = {
                labels: labelsColletion,
                datasets: [
                {
                    label: ['Day', "Year],
                    backgroundColor: #ccff90,
                    data: ["R$ 79,76", "R$ 3.775,00", "R$ 3.470,00", "R$ 2.785,00"]
                }
                ]
            }

**Comment by apertureless** [comment]
Sure you can not use strings as data.

It does not make sense to use strings as data in a chart. And was AFAIK never possible in chartjs > http://www.chartjs.org/docs/latest/getting-started/usage.html

If you want to have the `R$` before your numbers you can use the formatter / labels & tooltips options. AFAIK there is a callback for formatting your data. But it needs to be numbers / floats.
