### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by gregvissing** [apertureless/vue-chartjs#432]
### Expected Behavior
https://vue-chartjs.org/ Website should show up

### Actual Behavior
Blank screen

### Environment
Chrome v.69

**Comment by apertureless** [comment]
Yep seems to be an issue with `docute`.

However as the docs are migrated to vuepress already, I don't think it makes a lot of sense to work on the old ones. I guess I will merge the new docs this week, so they should be up soon.

**Comment by apertureless** [comment]
Fixed now
