### ISSUE TITLE
Chart isn't rendering inside of a @vue/vue-web-component-wrapper web component

### ISSUE THREAD

**Issue by michael-fearn** [apertureless/vue-chartjs#434]
I'm using vue-chartjs to build charts in a vue web component. 
When running the application with
 `vue-cli-service serve` 
everything works as expected, but the same application being built into a web component using:
`vue-cli-service build --target wc --name vue-chart-wc ./src/App.vue`
runs without error, creates the canvas the chart would normally exist in, but doesn't render the chart. 

https://github.com/michael-fearn/vue-webcomponent-chatjs

### Environment
- vue.js version: <2.5.17>
- vue-chart.js version: <3.4.0>
- npm version: <6.4.1>

**Comment by apertureless** [comment]
Hey @michael-fearn 

does any other errors are thrown?

**Comment by rahulshinde11** [comment]
I am facing the same issue. there are no errors
