### ISSUE TITLE
Example to create gradient background for chart from child component canvas context

### ISSUE THREAD

**Issue by maciz84** [apertureless/vue-chartjs#439]
### Expected Behavior
This question has been asked before at [https://stackoverflow.com/questions/51022003/vue-chartjs-create-gradient-background-for-chart-from-child-component-canvas](https://stackoverflow.com/questions/51022003/vue-chartjs-create-gradient-background-for-chart-from-child-component-canvas). However I think a lot of people would benefit from an example in the documentation somewhere.

The author in this article like me was 'confused' as to what was meant by "..pass in all data as props" . I still don't know what I need to do to get this working. My scenario is exactly the same as the author.

The actual reusable chart code is:

```import { Bar, mixins } from 'vue-chartjs';

export default {
    extends: Bar,
    gradient: null,
    mixins: [mixins.reactiveProp],
    props: ['chartData', 'options'],
    mounted() {

        var gradientStroke = this.$refs.canvas.getContext('2d').createLinearGradient(0, 230, 0, 50);

        gradientStroke.addColorStop(1, 'rgba(253,93,147,0.8)');
        gradientStroke .addColorStop(0, 'rgba(253,93,147,0)'); //blue colors

//I don't know what to do with it here. Because if the chart isn't reusable and I add my chartdata here it works fine. But I want it to be reusable

        this.renderChart(this.chartData, this.options);
        
    }
};
```
### Actual Behavior

Then in my parent code:

```this.myChartData = {
                labels: labels,
                datasets: [{
                    label: 'Name',
                    fill: true,
                    backgroundColor: '#ff5991',
                    hoverBackgroundColor: '#ff5991',
                    borderColor: '#ff5991',
                    borderWidth: 2,
                    borderDash: [],
                    borderDashOffset: 0.0,
                    data: chartdata
                }]
            };
```
Please can we add an example for this as I know this is for issues only but there isn't anyone or Gittur to talk to.

Many thanks

### Environment
- vue.js version: 2.5.17
- vue-chart.js version: 3.4.0
- npm version: -/-

**Comment by maciz84** [comment]
@apertureless this code looks great but to make i reactive do I need to add a watcher? BEcauseat the moment it doesn't update data when my api is finished making the call. If I hard code the values in the props on the chart component it works?

**Comment by apertureless** [comment]
Well, you *never* mentioned any api calls ;) 

You could just add a `v-if="loaded"` to your chart. So it only renders if your api call is finished

https://vue-chartjs.org/guide/#chart-with-api-data

However, please use stackoverflow for this kind of questions. The issues here are more for feature requests / bugs and not for "how do I do xxx"

**Comment by maciz84** [comment]
OK I get it, I do apologise but there isn't much help there sometimes. Anyway this would still be beneficial to have in the docs though

**Comment by maciz84** [comment]
I mean your code samples you gave me a few minutes ago not the v-if thing

**Comment by maciz84** [comment]
Thanks anyway

**Comment by Dudy83** [comment]
ok
