### ISSUE TITLE
How to align xAxis label at the bottom to vertically straight

### ISSUE THREAD

**Issue by rosnaib11** [apertureless/vue-chartjs#444]
Hi, is there a away to align this label straight? and how to keep it visible when resizing the page?

https://codepen.io/anon/pen/wQpRWQ

![image](https://user-images.githubusercontent.com/26837762/48826584-aea16680-eda5-11e8-8012-093c29237e0c.png)

**Comment by apertureless** [comment]
I guess this will help you:

https://stackoverflow.com/questions/35022830/chart-js-change-label-orientation-on-x-axis-for-line-charts
