### ISSUE TITLE
Error: [vuex] Do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by pablocattaneo** [apertureless/vue-chartjs#445]
Hi there!

I am using vuex in strict mode: https://vuex.vuejs.org/guide/strict.html
const actions = {
  menuOnResize ({ commit }) {
    if (!state.menuIsOpen) {
      window.addEventListener('resize', resizeThrottler, false)
    }
    
    function resizeThrottler () {
      commit('menuIsOpenOnResize')
    }
  }
}

When excute the action the console show me this error:

![image](https://user-images.githubusercontent.com/11772956/48917966-64cd8480-ee68-11e8-8726-2403646ded86.png)

I have three chart and all of them use the reactiveProp mixin

### Environment
- vue.js version: 2.5.17
- vue-chart.js version: 3.4.0
- npm version: 6.4.1

**Comment by apertureless** [comment]
Hi @pablocattaneo 

I can't see anything `vue-chartjs` related in your code.

Please provide a reproduction (webackbin/jsfiddle/codesandbox...)
