### ISSUE TITLE
Question: How to get the item I clicked on

### ISSUE THREAD

**Issue by NeilRShah** [apertureless/vue-chartjs#452]
First of all, thanks for making this. It's been very easy to use and get set up, and I appreciate it! 

I have a line graph, which is a component LineGraph.vue, and I use that components in one of my Views (single file component: Plan.vue). Everything is working properly. 

When I click a datapoint, I would like to get the X and Y value that datapoint returned to me. I have looked through your docs, the questions on this forum, and the ChartsJS docs and I am stuck! Any help would be appreciated! 

Just for reference, right now my data object, in Plan.vue looks like this:

```export default {
  components: { LineGraph },
  data () {
    return {
      lineGraphData: {
        datasets: [
             .... my data goes here ...
        ]
      },
      lineGraphOptions: {
        animation: false,
        onClick: (event) => {
          ... I don't know what to put in here to get the X and Y value of the click event. 
        },
        scales: {
          yAxes: [{
            ticks: {
              min: 0,
            }
          }],
          xAxes: [{
            type: 'time',
            time: {
              unit: 'month',
              unitStepSize: 1,
            }
          }],
        },
        fill: false,
        maintainAspectRatio: false,
      },
    }
  },
```

If you know what should go in the options onClick function that would return the X Y data, that would be amazing!

**Comment by apertureless** [comment]
Hi @NeilRShah 

this might help you: https://github.com/apertureless/vue-chartjs/issues/386
