### ISSUE TITLE
How to get rid of _meta object

### ISSUE THREAD

**Issue by agriboz** [apertureless/vue-chartjs#459]
```
<component
                v-if="chartComponent[i]"
                :is="chartComponent[i]"
                :chart-data="selectedItem[i].data"
                :options="selectedItem[i].options"
/>

addChart() {
  this.chartComponent[this.test] = () => {
          return import(`@/components/Charts/${
            this.selectedItem[this.test].type // bar
          }`)
        }
}
```
### Expected Behavior
I would like to save my chart collection to server, however it gives me an error. 
```_meta``` object is the reason for that.

### Actual Behavior
Getting rid of _meta object when you are using reactiveProp

[Screenshot](https://ibb.co/KKQTQmH)

### Environment
- vue.js version: <^3.4.0>
- vue-chart.js version: <^2.5.17>
- npm version: <5>

**Comment by apertureless** [comment]
Which error are you getting?

The `_meta` field is added by chart.js afaik. So nothing I can do here.

**Comment by apertureless** [comment]
Did you deleted the `_meta` key? 
I am not sure if this is a good idea, as it's coming from chart.js directly.

Why do you want to use the reactiveProp plugin? Do you have some live data that you want to show?

In most cases I guess it would be enough to call `this.$data._chart.update()` after changing data or passing new data.

You also should make sure, that your data is available as the chart renders. 
But I would need a reproduction to see where the error is.

**Comment by agriboz** [comment]
My data is ready before the chart render.
I do not have any live data, however, would like to load components when needed with Vue async components. 

```
<component
                v-if="chartComponent[i]"
                :is="chartComponent[i]"
                :chart-data="selectedItem[i].data"
                :options="selectedItem[i].options"
/>

// this.test is index of array
addChart() {
  this.chartComponent[this.test] = () => {
          return import(`@/components/Charts/${
            this.selectedItem[this.test].type // bar
          }`)
        }
}
```


[here is the demo](https://streamable.com/e2men)

**Comment by liuruidong1994** [comment]
l would like to async update data ,but something error because of ``` _meta.hidden```
![image](https://user-images.githubusercontent.com/7451379/51302460-6765e800-1a6d-11e9-9455-73ba2bef4b43.png)
datasets :
![image](https://user-images.githubusercontent.com/7451379/51302489-76e53100-1a6d-11e9-83f7-6156c889db85.png)
