### ISSUE TITLE
How can I get the Object of the chart

### ISSUE THREAD

**Issue by Biytes** [apertureless/vue-chartjs#461]
### Expected Behavior

I've read the document in [vue-chartjs official doc](https://vue-chartjs.org/guide/#troubleshooting)  

`watch: {
  chartData () {
    this.$data._chart.update()
  }
}
`
the _chart means the object of the chart, right?
From your example in this repository  
every type of chart, i just export it and made it a component
I don't know how to directly implement to its Object

I want my chart are convenient for users, they can easily change the labels or some options  by change the selected value
![_20190112105048](https://user-images.githubusercontent.com/18529350/51068368-fdf26d80-1657-11e9-9f30-342f73614845.png)
for that i have to always update my chart.

### Actual Behavior
when I use the code
`
watch: {
  chartData () {
    this.$data._chart.update()
  }
}
`
it goes wrong like TypeError: Cannot read property 'update' of undefined 
which means i havn't save the chart object to the data parameter, so i wonder how to get the Object of the chart

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: latest<latest>
- npm version: latest<latest>

**Comment by Biytes** [comment]
![_20190112110833](https://user-images.githubusercontent.com/18529350/51068554-6f332000-165a-11e9-8662-ac7d708ece35.png)
It's console.log(this.$data)

**Comment by Biytes** [comment]
there is no update()

**Comment by Biytes** [comment]
the function update ， how am i gonna use it
what kind of structure am i gonna pass, pleace

**Comment by apertureless** [comment]
Hey @Biytes 

`this.$data._chart` is the chart.js instance! And exposes all chart.js methods and events.

https://vue-chartjs.org/api/#chart-js-object

---

If you are unsure how your `chartData` object should look like, just check the [offical chart.js docs](https://www.chartjs.org/docs/latest/)

Your data should look like the data in the example.

```
 labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
```
