### ISSUE TITLE
How i can set the labels for height for bar chart? see attach

### ISSUE THREAD

**Issue by kkkkksenia** [apertureless/vue-chartjs#465]
###
![1](https://user-images.githubusercontent.com/46191929/51543059-bb0d7280-1e6d-11e9-9a7e-47a4f590fd32.png)
 Expected Behavior

**
### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Sorry I don't really understand whats your issue here. Can you please clarify?

**Comment by kkkkksenia** [comment]
Hello. I would like to add to the top of columns labels of their values. I
mean bar chart. For example, like on attach picture (6, 5, 1). Thank you
very

ср, 30 янв. 2019 г. в 11:51, Jakub <notifications@github.com>:

**Comment by handhikadj** [comment]
@kkkkksenia you can use chartjs-plugin-datalabels

**Comment by apertureless** [comment]
There is no option for that.
You have either to use [chartjs-plugin-datalabels](https://github.com/chartjs/chartjs-plugin-datalabels) or write your own plugin.

You have to get the context of the chart and canvas and then you can draw the values by yourself.
