### ISSUE TITLE
Chart IOS rendering problem

### ISSUE THREAD

**Issue by sergiottomas** [apertureless/vue-chartjs#471]
Hi, I'm creating a chart using you component but in IOS or devices with retina display, the chart is rending with wrong proportion, do you have ideia what happens?

Thanks.

**Comment by apertureless** [comment]
I guess this should help you https://www.chartjs.org/docs/latest/general/device-pixel-ratio.html?h=retina

**Comment by sergiottomas** [comment]
It's Worked, Thank you!
