### ISSUE TITLE
Cannot find example how to use gradient while using vuex and reactiveProps mixin

### ISSUE THREAD

**Issue by handhikadj** [apertureless/vue-chartjs#473]
I saw your repo how to use vuex with this package and it works like a charm but don't know how to integrate the stuffs with gradient color.

Please enlighten up this

### Environment
- vue.js version: 2.6.6
- vue-chart.js version: 3.4.0
- npm version: 5.6.0

**Comment by apertureless** [comment]
There is a tutorial on how to use gradients: https://hackernoon.com/creating-stunning-charts-with-vue-js-and-chart-js-28af584adc0a

It really depends on how modular and reusable your charts should be. 

If you are using only one dataset, you can for example just pass in the data and labels to your chart. And let the chart make the gradient by itself.

If you want to support multiple datasets, you will need to make a generator method, that generates the gradients and assigns them to the datasets.

```js
import {Line} from 'vue-chartjs'

export default LineChart {
  extends: Line,
  props: ['labels', 'chartdata'],
  data () {
    return {
      gradient: null
    }
  },
  mounted () {
    this.gradient = this.$refs.canvas.getContext('2d').createLinearGradient(0, 0, 0, 450)


    this.gradient.addColorStop(0, 'rgba(255, 0,0, 0.5)')
    this.gradient.addColorStop(0.5, 'rgba(255, 0, 0, 0.25)');
    this.gradient.addColorStop(1, 'rgba(255, 0, 0, 0)');
    



    this.renderChart({
      labels: this.labels
      datasets: [
        {
          label: 'Data One',
          borderColor: '#FC2525',
          pointBackgroundColor: 'white',
          borderWidth: 1,
          pointBorderColor: 'white',
          backgroundColor: this.gradient,
          data: this.chartdata
        }
      ]
    }, {responsive: true, maintainAspectRatio: false})

  }
})
```

**Comment by handhikadj** [comment]
chartData is already in the reactiveProps mixin, right? what I understand is we declare the `chart-data` and `options` in parent component at computed like:
```javascript
// chart-data props
computed: {
    dataBarHour() {
        return {
            labels: this.getBarHourLabels,   // from mapGetters
            datasets: [{
                data: this.getBarHourDatasets,
                backgroundColor: 'red',
                hoverBackgroundColor: 'red',
            }]
        }
    }
}
```

i am still not understand from your example snippet cause the reactive mixin's not included

**Comment by apertureless** [comment]
Yes, you are right, `chartData` comes with the reactive mixin.
However, you can trigger updates of the chart by yourself. It's quite flexible.

If you are using the mixin your chart data has to be the Chart.js data object. With labels, datasets etc. in it.

But you could also simply pass in your labels and data (if you have only one dataset)

Add a watcher on both and then trigger `this.$data._chart.update()`

**Comment by handhikadj** [comment]
I've added a button to repopulate the chart data, but it's not reactive.
https://codesandbox.io/s/zljw20zp0m

**Comment by apertureless** [comment]
I am not getting your point.

Yes, if you add two watchers to `chartLabels` and `chartData` you have to call the update method in both of them. As your chart needs to update on a change of the labels and data. 

As I did in my codesandbox example.

If you want to clean it up, you can make a mixin for that.

**Comment by handhikadj** [comment]
You can open my updated sandbox. Click the button. You can see nothing

**Comment by handhikadj** [comment]
issue's closed. switch to stackoverflow:
https://stackoverflow.com/questions/54743212/vue-chartjscannot-find-example-how-to-use-gradient-while-using-vuex-and-reacti/54782287#54782287

**Comment by handhikadj** [comment]
reopened, cause need this to be solved so badly
