### ISSUE TITLE
Drilldown support?

### ISSUE THREAD

**Issue by hifall** [apertureless/vue-chartjs#478]
Looks like drilldown is not yet supported. Any plan for it?

Drilldown lets you summarize, or group, data in a dimension and enable users to explore and analyze multiple levels of related data in other dimensions.

Check this drilldown demo: [https://www.highcharts.com/demo/column-drilldown](https://www.highcharts.com/demo/column-drilldown)

**Comment by apertureless** [comment]
Hi @hifall 

yes, drilldown would be nice. However, this is only a wrapper for [Chart.js](https://github.com/chartjs/chart.js) so any core feature request should go there ;)
