### ISSUE TITLE
Update Chart with computed property, how does reactiveData work?

### ISSUE THREAD

**Issue by royduin** [apertureless/vue-chartjs#479]
I'd like to update the chart data but I need to transform the data so I'm using a computed property. With that I can't use the `reactiveProp` as mentioned in the docs: https://vue-chartjs.org/guide/#updating-charts right? But how to use `reactiveData`?

I'm now using this:

```
import { HorizontalBar } from "vue-chartjs";

export default {
    extends: HorizontalBar,
    props: ["chartdata"],
    watch: {
        chartdata: function() {
            this.$data._chart.data.datasets = this.datasets;
            this.$data._chart.update();
        }
    },
    computed: {
        datasets: function() {
            let datasets = [];
            for (let key in this.chartdata) {
                datasets.push({
                    data: [this.chartdata[key]],
                    backgroundColor: "#123456"
                });
            }
            return datasets;
        }
    },
    mounted() {
        this.renderChart(
            {
                datasets: this.datasets
            },
            {
                ...
            }
        );
    }
};
```

Can this be done easier or cleaner?

**Comment by apertureless** [comment]
Hi @royduin 

the main difference between `reactiveProp` and `reactiveData` is that it will define `chartData` either as a prop or local data state.

The reason for this, is that in some cases, when you for example add more datasets, the chart can't just `update()` but has to be completely re-rendered.

So the mixin has to call `this.renderChart(data, options)` However, there is no way to check whats your chartdata variable names. So it has to define them by itself. 

Reactivity with chart.js is not that easy and there are way to many ways to pass in data and changing data. Thats why it is tricky to make a mixin for a more generic use.

But the watcher + `update()` or `renderChart()` is more or less the way to go.

**Comment by royduin** [comment]
Awesome, thank you for you quick reply @apertureless! So what I'm doing now is ok or better use `reactiveData`?

**Comment by apertureless** [comment]
It is okay! ReactiveData wouldn't help you that much tho.

**Comment by royduin** [comment]
Thanks, great to see a fast response time on an open source project. Thanks for doing this!

**Comment by dizid** [comment]
@royduin Hi Roy, 
Did you solve this? Would you be willing to share some code if you found a solution?
I am having the exact same 'challenge': vuefire data in copmputed properties.
The v-if="loaded" i couldn't get to work.
Leuke website heb je!

**Comment by royduin** [comment]
It's a while back, just looked up the code and it's the same.
