### ISSUE TITLE
Working with objects

### ISSUE THREAD

**Issue by xlcrr** [apertureless/vue-chartjs#48]
I am trying to populate a chart component dynamically with reference from a parent data object + mixins

Is there a way to pass a data Object to the methods eg. Labels to enumerate over my existing object of objects or do I have to build a custom solution to pass it an array? If not, this would be a really cool new feature that would really help build dynamic charts!

ps. I referenced this on [stack](http://stackoverflow.com/questions/42508978/working-with-data-objects-vue-chartjs) too but thought it might be worth bringing up as a feature request if it doesn't already exist

**Comment by apertureless** [comment]
Hey @xlcrr 

not sure if I understand what you're trying to achieve. 
Do you have any code snippets or examples?

**Comment by apertureless** [comment]
Cloesed due to inactivity. 
Reopen if you come back :)
