### ISSUE TITLE
Financial/OHLC chart

### ISSUE THREAD

**Issue by ehajri** [apertureless/vue-chartjs#481]
How to extend vue-chartjs to use Chart.js official financial chart?

https://www.chartjs.org/chartjs-chart-financial/

**Comment by ehajri** [comment]
I have cloned vue-chartjs' and Chart.js Financial Charting's repos, incorporated candlestick, and ohlc charts into vue-chartjs' BaseChart. Now I can use them similar to the officially supported ones.

**Comment by apertureless** [comment]
Hey @ehajri 

I think, there is no way to integrate the financial chart. Out of the box.
I can not find any installation instructions for it in the readme and it's not even properly released

> This module has not yet had its initial release and is not yet available on npm. 

`vue-chartjs` has some helpers for adding chart.js plugins, however it does not seem that the financial charts are plugins.

**Comment by ehajri** [comment]
That is correct.

I had to do the following:

1. Included financial chart source files into vue-chartjs
2. Had financial chart import chart.js, modify it, and export the object
3. vue-chartjs now uses the exported/modified version of chart.js

**Comment by walkercole** [comment]
@ehajri Could you show some example on how you achieved that code by chance? Looking to do the same thing but am not as experienced in chart.js

**Comment by walkercole** [comment]
@ehajri Thank you for such a prompt response, i'm eager to see! :)

**Comment by ehajri** [comment]
@walkercole give this a try: https://github.com/ehajri/vue-chartjs-financial

**Comment by walkercole** [comment]
@ehajri Above and beyond! Will give this a try shortly and hopefully get something together, Thanks a ton for providing such a good example :)
