### ISSUE TITLE
Connected Scatter chart example

### ISSUE THREAD

**Issue by naor10** [apertureless/vue-chartjs#485]
Hi,
The example here:
https://github.com/apertureless/vue-chartjs/blob/develop/src/examples/ScatterExample.js

Shows the Scatter as a single unconnected points.
How can I produce a connected Scatter chart?

Like this:
![image](https://user-images.githubusercontent.com/41241989/53943088-0483eb00-40c5-11e9-9b1d-6d7f267b1d16.png)

**Comment by apertureless** [comment]
Its working for me tho

https://codepen.io/apertureless/pen/zbzWEP

**Comment by apertureless** [comment]
Oh okay, nvm. the pen is using an older version of chart.js
Chart.js 2.7 removed the default line rendering in scatter charts.

https://github.com/chartjs/Chart.js/releases/tag/v2.7.0

However you just need to set `showLine: true` in the dataset properties:
https://codepen.io/apertureless/pen/KEqoRa

As the scatter chart has the same dataset properties as the linechart
https://www.chartjs.org/docs/latest/charts/line.html#dataset-properties

**Comment by naor10** [comment]
Working great, many thanks!
