### ISSUE TITLE
Drawing a chart of Parabolas

### ISSUE THREAD

**Issue by naor10** [apertureless/vue-chartjs#486]
Hi,

How can I draw a chart of this kind?

![123](https://user-images.githubusercontent.com/41241989/54201112-8d3fc400-44d5-11e9-91f9-d17c0aa857d2.png)

**Comment by apertureless** [comment]
Its not a supported chart.js type.
You may have to write your own type. However it depends on your data.

Maybe you can work with a linechart and play with the tension settings.

**Comment by naor10** [comment]
There is an option to draw a chart by a mathematical function:

![image](https://user-images.githubusercontent.com/41241989/54342200-87b4bc00-4644-11e9-8e07-b0fbdb829b65.png)

https://jsfiddle.net/j0hymmhc.

How can I scale it to see the whole Parabola?
