### ISSUE TITLE
Add src folder to package.json "files" and make main "src/index.js"

### ISSUE THREAD

**Issue by craigh411** [apertureless/vue-chartjs#49]
Could you add the `src` folder to `files` in `package.json`, at the moment it looks like the `dist` file includes Vue itself, which means I'm importing `Vue` twice, which I only realised when I updated to Vue 2.2.1 and vue devtools was detecting `Vue 2.1.10` from `vue-chartjs`. It's back to `2.2.1` now I've updated this package, but it looks like every time Vue realeses a new version I'm going to have to rely on you to do the same before I can update Vue in my app and that's a bit of a deal breaker.

Also,  it makes sense to have `src/index.js` as your `main` file as most of us are going to be using `browserify/vueify` or `webpack/vue-loader` setups, this way we can just  bundle the charts we need. I'm pretty sure you had it set up this way before and it worked great.

**Comment by apertureless** [comment]
Sounds reasonable.
Will change it.

**Comment by apertureless** [comment]
Fixed in `2.3.9`
