### ISSUE TITLE
Y-Axis Scale Label String does not update unless DataSet label changes

### ISSUE THREAD

**Issue by TheJaredWilcurt** [apertureless/vue-chartjs#490]
### Expected Behavior
Y-Axis label should change if a change occurs

### Actual Behavior
Doesn't

### Environment
- vue.js version: 2.6 (latest)
- vue-chart.js version: 3.4.2 (latest)
- npm version: N/A

* * *

We have a dropdown that lets you pick between `packets` and `mbps`. Changing from one to the other should update the Y-Axis label, and change the data being displayed. But the data labels of "Sent" and "Received" don't change. Because of this, the data changes, but the Y-Axis does not update to the correct label (packets or mpbs).

**Basic Example:**

* https://jsfiddle.net/6ksfpor8/3/

**Example with data changing:**

* https://jsfiddle.net/6ksfpor8/2/

The data changing does not trigger the Y-Axis labels to update either, it only occurs if the data label changes.

**Comment by apertureless** [comment]
I don't think that the options are reactive. I guess you will have to re-render the chart in order to see changes.
