### ISSUE TITLE
[Typescript + vue-class style components] Argument of type 'typeof UsageChart' is not assignable to parameter of type 'VueClass<Vue>'

### ISSUE THREAD

**Issue by santiagogdo** [apertureless/vue-chartjs#495]
Hello. I'm having an issue using the typescript sample that's in the docs. The compiler complains about types. Any ideas how can I fix this?

The code:

![image](https://user-images.githubusercontent.com/39063453/54958288-fc84d180-4f33-11e9-8d19-7dffb745f857.png)

Full error:

`Argument of type 'typeof UsageChart' is not assignable to parameter of type 'VueClass<Vue>'.
  Type 'typeof UsageChart' is not assignable to type 'VueConstructor<Vue>'.
    Types of parameters 'options' and 'options' are incompatible.
      Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> | undefined' is not assignable to type 'ThisTypedComponentOptionsWithArrayProps<Vue, Line, object, object, never> | undefined'.
        Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>' is not assignable to type 'ThisTypedComponentOptionsWithArrayProps<Vue, Line, object, object, never>'.
          Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>' is not assignable to type 'ComponentOptions<Vue, DataDef<Line, Record<never, any>, Vue>, object, object, never[], Record<never, any>>'.
            Type 'DefaultData<Vue>' is not assignable to type 'DataDef<Line, Record<never, any>, Vue>'.
              Type 'object' is not assignable to type 'DataDef<Line, Record<never, any>, Vue>'.
                Type 'object' is not assignable to type '(this: Readonly<Record<never, any>> & Vue) => Line'.
                  Type '{}' provides no match for the signature '(this: Readonly<Record<never, any>> & Vue): Line'.ts(2345)`

### Environment
- vue.js version: 2.6.8
- vue-chart.js version: 3.4.2
- npm version: 6.8.0

**Comment by apertureless** [comment]
Sorry, but I can't provide any help on this, as I am not using typescript and the examples are from other TS users.

But maybe someone else here can help you.

**Comment by schnetzi** [comment]
For me it is currently with the following configuration:
```
<script lang="ts">
import { Bar } from 'vue-chartjs';
import { Component, Vue } from 'vue-property-decorator';

@Component({
  extends: Bar,
})
export default class CommitChart extends Vue {
}
</script>
```

and I added the `renderChart`-type to the types.d.ts-file
```
declare module 'vue/types/vue' {
  interface Vue {
    [...]
    renderChart(chartData: any, options?: any): void;
  }
}
```

This works for me at the moment.

**Comment by Djaler** [comment]
You should use it like this:
```

<script lang="ts">
import { Bar } from 'vue-chartjs';
import { Component, Vue } from 'vue-property-decorator';

@Component({
  extends: Bar,
})
export default class CommitChart extends Bar {
}
</script>
```

**Comment by vivss** [comment]
To work around the error I've written my class as follows

```
import {Component, Vue, Prop} from 'vue-property-decorator';
import VueCharts from 'vue-chartjs';
import {Bar} from 'vue-chartjs';

@Component({
  extends: Bar,
})
export default class BarChart extends Vue {
  mounted () {
    // @ts-ignore
    this.renderChart({})
  }
}
```

**Comment by ctonsing** [comment]
> You should use it like this:
> 
> ```
> <script lang="ts">
> import { Bar } from 'vue-chartjs';
> import { Component, Vue } from 'vue-property-decorator';
> 
> @Component({
>   extends: Bar,
> })
> export default class CommitChart extends Bar {
> }
> </script>
> ```

@Djaler, for me this results in the following error: `Uncaught TypeError: Super expression must either be null or a function`.

The workarounds by @schnetzi and @vivss are working for now. I don't know enough yet to suggest a proper fix though...

**Comment by bobvandevijver** [comment]
I am seeing the same errors, and curious how @Djaler managed to get his example to work.

**Comment by RCVZ** [comment]
The solution that works for me is to extend the vue Mixins , like in the example below.
```
export default class DoughnutChart extends Mixins(Doughnut) {
}
</script>
```

**Comment by xorik** [comment]
@RCVZ thanks!

**Comment by darylteo** [comment]
The following worked for me too, conceptually similar, if using `vue-class-component` as opposed to `vue-property-decorator`.

```
    import {Component} from "vue-property-decorator";
    import {mixins} from "vue-class-component";
    import {Bar} from "vue-chartjs"; 

    @Component({
        name: "OverviewChart",
    })
    export default class OverviewChart extends mixins(Bar) {

    }
```

**Comment by alexeigs** [comment]
The provided solutions are incomplete. At least with my setup I always face one of the three issues:

- `export default class MyChart extends Vue<Bar>` results in a compiler warning  _No base constructor has the specified number of type arguments_ and doesn't infer the types, so no methods/props. I could declare them myself to get rid of the warning but again, just half a solution.

- `export default class MyChart extends Mixins(Bar)` results in the same as above with a slightly different compiler warning _Argument type Bar is not assignable to parameter type VueClass<unknown> _

- `export default class MyChart extends Bar` works perfectly for the compiler and types are available but at runtime, it crashes with the following error: _TypeError: Class extends value #<Object> is not a constructor or null_

Does any of these solutions work A-Z for you? Any ideas what may be missing?

**Comment by darylteo** [comment]
Maybe post the whole file @alexeigs.

**Comment by alexeigs** [comment]
> Maybe post the whole file @alexeigs.

@darylteo That's one version of what I've tried, obviously having played around with what to put in `@Component` and how to extend the class as outlined in my previous post.

Comment: There's no line drawn for me in "Line" chart, just dots... probably I still got the setup fundamentally wrong somehow(?).

```
<script lang="ts">
  import { Component, Mixins } from 'vue-property-decorator'
  import { Line } from 'vue-chartjs'

  @Component({
    extends: Line,
    mixins: [Line]
  })
    export default class ChartLine extends Mixins(Line) {

    mounted() {
      this.renderChart({
        labels: ['1', '2', '3', '4', '5', '6'],
          datasets: [
            {
              label: 'Chart',
              data: [300, 700, 500, 700, 200, 800],
            }
          ]
        }
      )
    }
  }
</script>
```

**Comment by darylteo** [comment]
That code compiles fine for me. So there might be a configuration issue. 

```
    "chart.js": "^2.9.2",
    "@types/chart.js": "^2.8.10",
```

Hope that helps.

**Comment by alexeigs** [comment]
@darylteo Strange, I have the same but still face the following two compiler issues.

![Screenshot 2019-11-28 at 19 54 09](https://user-images.githubusercontent.com/8920332/69827739-f8265c00-1218-11ea-9abf-58e8b1b5aa85.png)

![Screenshot 2019-11-28 at 19 54 26](https://user-images.githubusercontent.com/8920332/69827740-f8265c00-1218-11ea-892b-13000e2da2af.png)

**Comment by HoehensteigerGames** [comment]
I have now the same issue. My DahsboardBarCahrt.ts looks like this:
![grafik](https://user-images.githubusercontent.com/58444802/70656321-26189100-1c5a-11ea-9727-425d7b92806c.png)
And my Dashboard.vue looks like this:
![grafik](https://user-images.githubusercontent.com/58444802/70656359-36c90700-1c5a-11ea-8d6e-f25633bbf64c.png)

My question whats the correct way to solfe the type Problem:
![grafik](https://user-images.githubusercontent.com/58444802/70656456-67a93c00-1c5a-11ea-82a1-6945e735ccfb.png)

Thanks for help.

**Comment by andy2577** [comment]
@ HoehensteigerGames in your 'Dashboard' class try adding

constructor() {super);}

**Comment by standup75** [comment]
> constructor() {super);}

This is working. And it's awesome. but why is it working?

**Comment by lgarczyn** [comment]
Only typescript solution I found:

```ts
<template>
    <graph-comp ref="graph" />
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { Line } from 'vue-chartjs';

@Component({
    components: { 'graphComp': Line }
})
export default class CustomGraph extends Vue {

    constructor() {
        super();
    }

    mounted(): void {
        (this.$refs.graph as Line).renderChart({
            labels: ['1', '2', '3', '4', '5', '6'],
            datasets: [
                {
                    label: 'Chart',
                    data: [300, 700, 500, 700, 200, 800],
                }
            ]
        });
    }
}
</script>

```

**Comment by juanbrujo** [comment]
> ```ts
> (this.$refs.graph as Line).
> ```

this is gold, finally made it work, thanks.

**Comment by jcosta33** [comment]
I tried every single solution here and I keep getting this. Please kill me.

![image](https://user-images.githubusercontent.com/8978270/124600695-e5492400-de5e-11eb-9259-b1f2366c1148.png)

**Comment by lgarczyn** [comment]
@jcosta33 

First can you please keep the language somewhat respectful, no point in dropping slurs.

Second, the error you showed here is completely different, if you got it inside vue-chart-js it's probably because you didn't install ChartJS

**Comment by jcosta33** [comment]
I had to let out some steam, I'm sure you understand. And are you seriously suggesting I tried everything except actually installing the package?

**Comment by jcosta33** [comment]
FYI replacing those definitions with "any" fixes the build error but on the console there's still this:

![image](https://user-images.githubusercontent.com/8978270/124615135-df5a3f80-de6c-11eb-90f6-577a48936272.png)

**Comment by lgarczyn** [comment]
What I suggested was that you were missing a namespace, most probably because you had an incorrect combinations of vue-chart-js, chartjs or @types/chartjs or their versions.

Can you copy the appropriate lines of your package.json ?

**Comment by jcosta33** [comment]
You can forget about the Typescript issue I think, brute forcing "any" into any mention of the namespace Chart has worked. Here are all my dependencies:

```
  "dependencies": {
    "axios": "^0.21.1",
    "chart.js": "^3.4.1",
    "vue-chartjs": "^3.5.1",
    "core-js": "^3.15.2",
    "register-service-worker": "^1.7.2",
    "vue": "^2.6.14",
    "vue-class-component": "^7.2.6",
    "vue-property-decorator": "^8.5.1",
    "vue-router": "^3.5.2",
    "vuex": "^3.6.2",
    "vuex-class": "^0.3.2"
  },
```

**Comment by jcosta33** [comment]
I decided to start over in a separate environment. I 2 other vue apps I maintain, one of them has multiple libraries of all kinds, some of them importing using the "dumb" method (no lang=ts), others are fully typed, all of them worked. This one gave me a similar error, with the default setup suggested in the docs:

![image](https://user-images.githubusercontent.com/8978270/124758103-2821ff00-df26-11eb-8e50-a78448adf906.png)
