### ISSUE TITLE
passing data as prop and watchers

### ISSUE THREAD

**Issue by michaelAkrawi** [apertureless/vue-chartjs#499]
It seems like this topic discussed a lot but i still can't figure it out.
seems like in some of my charts the watcher is not getting triggered.

```
   extends: HorizontalBar,
   props: ["values", 'labels'],
   watch: {
      values: {
         handler(){
            this.render();
         },
         deep : true
      }
   },
   methods: {
      render() {

         this.renderChart({
            labels: this.labels,
            datasets: [
               {
                  label: label,
                  borderWidth: 1,
                  hoverBackgroundColor: ChartConfig.color.success,
                  hoverBorderColor: ChartConfig.color.success,
                  data: this.values
               }
            ]
         }, this.options)
      }
   },
```

this is my code. i did exactly the same with the Doughnut  chart without using the deep : true option and it worked just fine.
this my component code : 

`<poll-bar-chart :labels="answers" :values="answersData"></poll-bar-chart>`

im fetching data from an api and i checked the Vue developer tools and it seems like all the props are getting initialized just fine.

I read the docs and the limitations but still i can't find a way a round it.

**Comment by apertureless** [comment]
The code so far looks good.
As you only watching the data array, you don't need the `deep: true` option. It is only for deeply nested objects.

```js
watch: {
	values () {
		...
	}
}
```

Should be enough.

Can you post the code of the parent component? Maybe its something with, how you set your data / fetch it.

Btw. if you are only updating labels & data it should be enough to call `this.$data._chart.update()`. As it uses the internal chart.js update method to redraw the chart, without completely destroying the instance and re-creating the chart. May be a bit more performant.

**Comment by michaelAkrawi** [comment]
@apertureless thanks for the response.
i used the deep only because i did not what to do anymore :) i know you should use it only on nested objects and it's also has it's cost, anyway i will remove to from the code because as you can see it did not helped me.

ok so this is my view file and my definition for the Poll component (i changed the props names to match my js extended file)

the view:

`<Poll v-for="p in polls" :labels="p.answers" :values="p.data" :question="p.question"></Poll>`

 ```
data() {
    return {     
      polls: [] 
    };
  },

```
The poll component: 
```
<template>
  <app-card
    :heading="question"
    colClasses
    customClasses="mb-0 sales-widget"
    :fullScreen="true"
    :reloadable="true"
    :closeable="true"
  >
    <poll-bar-chart :labels="labels" :values="values"></poll-bar-chart>
  </app-card>
</template>

```

the only thing that is different from other charts component that do works is the v-for part
