### ISSUE TITLE
Use Vue.util.mergeOptions to merge default options with user's options

### ISSUE THREAD

**Issue by LinusBorg** [apertureless/vue-chartjs#5]
```js
methods: {
    render (data, options) {

      var mergedOptions = Vue.util.mergeOptions(this.options, options)

      const chart = new Chart(
        this.$els.canvas.getContext('2d'), {
          type: 'bar',
          data: data,
          options: mergedOptions
        }
      )
      chart.generateLegend()
    }
  }
```

This would allow users to override parts of the defaults without having to copy the rest of the defaults into their component to preserve them.

It would also be possible to introduce a 3rd argument as a flag to decide weither to override or not:
```js
 render (data, options, override = true) {
      var mergedOptions =  override ? options : Vue.util.mergeOptions(this.options, options)
```

**Comment by apertureless** [comment]
Thanks! 
I am gonna look into this.

**Comment by apertureless** [comment]
I've looked into mergeOptions(), but as far as I understand it, it is for merging vue instance options if they conflict with mixins.

> When a mixin and the component itself contain overlapping options, they will be “merged” using appropriate strategies. For example, hook functions with the same name are merged into an array so that all of them will be called. In addition, mixin hooks will be called before the component’s own hooks:

So its not merging simple javascript objects.

However it's a good idea to extend the defaultOptions. I will work on that.

But I don't really see a reason for the override property.

**Comment by LinusBorg** [comment]
Yeah I should have taken a closer look. for the most part, it would work but it would lead to unexpexetd behaviour when using certain vue-releated key names.

You could e.g. use `_.defaultsDeep()` or `_.merge()` from lodash.
