### ISSUE TITLE
Any way to pre-process chartData when using reactiveProp in the component that extends the Base components?

### ISSUE THREAD

**Issue by praveenpuglia** [apertureless/vue-chartjs#501]
I want to process the `chartData` that I get from the `reactiveProp` mixin before passing it on to the renderer for full update / render.

Example:
In the following example, I want to add `backgroundColor` to my `datasets` before being passed on to the renderer.

The `processedData` computed property returns the *enriched* datasets and then in `mounted` hook, I render the component with that data.

The first render works fine but then on updating data it gets lost because `dataHandler` calls `chart.update` with the raw, passed in `chartData`.

```ts
// Bar.ts
import baseOptions from '@/components/charts/base-config/bar';
import { PRIMARY_COLOR } from '@/components/charts/palette';
import { ChartDataSets, ChartOptions } from 'chart.js';
import { merge } from 'lodash';
import { Bar, mixins } from 'vue-chartjs';
import { mixins as classMixin } from 'vue-class-component';
import { Component, Prop } from 'vue-property-decorator';
const { reactiveProp } = mixins;
@Component({
  mixins: [reactiveProp]
})
export default class extends classMixin(Bar) {
  @Prop(Object) options: ChartOptions;
  /**
   * We don't want to specify how color palettes are going to be added
   * or other stupid things. So we take the raw data and enrich it.
   */
  get processedData() {
    const originalData = (this as any).chartData;
    const enrichedDatasets = originalData.datasets.map((set: ChartDataSets) => {
      set.backgroundColor = PRIMARY_COLOR;
      return set;
    });
    const updatedData = Object.assign({}, originalData, {
      datasets: enrichedDatasets
    });
    return updatedData;
  }

  /**
   * Creates a new options object by taking baseOptions and
   * then overriding things using the user provided options
   * via prop.
   */
  get mergedOptions() {
    return merge({}, baseOptions, this.options);
  }
  mounted() {
    this.renderChart(this.processedData, this.mergedOptions);
  }
}
```

I have a few options.

#### Do the data modification in the parent component that uses the `Bar` component.
This takes toll on reusability. I'll have to repeat the code in every place where `Bar`component is used.

#### Add my own watcher and mutate the prop itself.
Ugly, gets the job done but with ERRORs.
```ts
  @Watch('chartData')
  onDataChange(newData: any, oldData: any) {
    this.chartData = this.processedData;
  }
```

So what should I do now? Can you please suggest a way to achieve the same in a better way?

### Environment
- vue.js version: 2.5.22
- vue-chart.js version: 3.4.0
- npm version: 6.4.1

**Comment by apertureless** [comment]
Hi @praveenpuglia 
no thats not possible.

But you can easily add a watcher for chartData by yourself and then make any modifications you want, and then call `this.renderChart()` or `this.$chart.update()`
