### ISSUE TITLE
ChartArea object not available in charts

### ISSUE THREAD

**Issue by Kunoacc** [apertureless/vue-chartjs#508]
### Expected Behavior
ChartArea Object should be available on the chart object with adding plugins

### Actual Behavior
It isn't available

![image](https://user-images.githubusercontent.com/16244990/56456523-a99d0f00-6365-11e9-8d15-a34bb9d33be3.png)
On vue-chartjs

![image](https://user-images.githubusercontent.com/16244990/56456530-c3d6ed00-6365-11e9-89f8-ad267ecff514.png)
On vanilla chartjs.

### Environment
- vue.js version: 2.6.0
- vue-chart.js version: 3.4.2
- npm version: 6.7.0

**Comment by apertureless** [comment]
Hey @Kunoacc 

can you please describe your issue a bit more ? 
What is the chartArea object? Is it coming from a plugin? 
If yes, which plugin? How do you register the plugin? Are you registering it globally? Or only on a per chart basis locally?
