### ISSUE TITLE
How do I change the graph automatically in real time?

### ISSUE THREAD

**Issue by leejaenggu** [apertureless/vue-chartjs#509]
https://codepen.io/azs06/pen/KmqyaN?editors=1010

When I looked for the material, I found something like this.
What I want to do is to force the graph to automatically re-render when the data is randomly changed without pressing a button?

Please explain in source code. Help

**Comment by J3m5** [comment]
Hi, this is explained in the [docs](https://vue-chartjs.org/guide/#updating-charts), you must use the reactive mixin.
