### ISSUE TITLE
Inject chart IDs dynamically

### ISSUE THREAD

**Issue by dvago** [apertureless/vue-chartjs#510]
Given a list of "components" I would like to inject a chart for every single component specifying a generated ID (to avoid conflicts and pass the accessibility audit).

I was expecting to have a property to pass it but I can't find anything within the documentation of this wrapper, could you please help me?

### Actual Behavior
The default generates charts with 'line-chart' as ID

### Environment
- vue-chart.js version: 3.1.0

**Comment by apertureless** [comment]
https://vue-chartjs.org/api/#props

You can pass the id over the props.

`chart-id="some-chart-id`

**Comment by dvago** [comment]
Thank you! it worked, I did miss the property
