### ISSUE TITLE
Fill dataset index not working

### ISSUE THREAD

**Issue by baddy79** [apertureless/vue-chartjs#511]
### Expected Behavior
The documentation says the "fill" option allows absolute dataset index or relative dataset index by setting the index as follows.

{fill: '+2'} or {fill: 1} or  {fill: '-2'}

see chartjs documentation
https://www.chartjs.org/docs/latest/charts/area.html#filling-modes

### Actual Behavior
It's not working for me. I tried both positions, in "dataset" or globally in "option" as follows.
It works if I change the "fill" value to the boundaries like 'start', 'end' or 'origin', But it is not working for the index.

options: {
           elements: {
                line: {
                    fill: '-2'
                }
            }
}

I would appreciate any help.

### Environment
- vue.js version: 2.5.17
- vue-chart.js version: 3.4.2

**Comment by apertureless** [comment]
Can you please provide a reproduction link? 
Codepen / jsfiddle whatever.

**Comment by hugovicfortman** [comment]
How does one get the line chart to fill?
Adding `fill: true` in this dataset doesn't reflect.

https://codesandbox.io/s/github/apertureless/vue-chartjs/tree/main/sandboxes/line?file=/src/components/lineChart.ts

**Comment by DG3D** [comment]
> How does one get the line chart to fill? Adding `fill: true` in this dataset doesn't reflect.
> 
> https://codesandbox.io/s/github/apertureless/vue-chartjs/tree/main/sandboxes/line?file=/src/components/lineChart.ts

Like this : https://codesandbox.io/s/quizzical-sanderson-ltczrl

**Comment by habebit** [comment]
> How does one get the line chart to fill? Adding `fill: true` in this dataset doesn't reflect.
> 
> https://codesandbox.io/s/github/apertureless/vue-chartjs/tree/main/sandboxes/line?file=/src/components/lineChart.ts

You need to import `Filler` from 'chart.js' and you have to register it.

```js
import {  Chart as ChartJS, Title,  Tooltip, ..., **Filler** } from 'chart.js';
```

```js
ChartJS.register(Title, Tooltip, ..., **Filler**);
```

**Comment by hugovicfortman** [comment]
Thanks, I got it done.
I actually had to create my own wrapper around it because I wanted some level of control from other parts of a Nuxt project.
