### ISSUE TITLE
Rewrite reactive mixins

### ISSUE THREAD

**Issue by apertureless** [apertureless/vue-chartjs#513]
The reactive Mixins are currently the biggest pain point, as they produce the most issues here. Because of different side effects and edge cases where it does not properly work. 

Thus, it is a perfect candidate for a more robust rewrite. And more robust testing of the edge cases.

The first step would be to go through the issues related to the mixin and gather how people are updating their data and what the use cases are.

**Comment by datainvestor** [comment]
I think it is neccessary to somehow include chart.update() method present in the official ChartJS library, so that the chart can be updated without rerendering, which porbably causes some of the problems that are brought up here, including #618

**Comment by apertureless** [comment]
We make usage of `chart.update()`. But sadly it is not always as simpel. As far as I remember there were some use cases where `update()` did not worked. Might be if you adding new datasets or something along that line.

It is also not so easy to properly watch the data object, as it is quite huge.
