### ISSUE TITLE
onHover: this.$emit not work

### ISSUE THREAD

**Issue by thijscrombeen** [apertureless/vue-chartjs#516]
I'm trying to emit the value of the current hovered point and it's throwing an error.

Hover function in options:
```
onHover: (e, element) => {
      if (element && element.length > 0) {
        const item = this.chartData.datasets[0].data[element[0]._index];
        this.$emit('test', {});
      }
    },
```
My component declaration:
`export default class LineChart extends Vue<Line> {`

How I use the component + the event listener
```
<line-chart 
            @test="item = arguments[0]">
        </line-chart>
```

### Expected Behavior
event is sent to the parent.

### Actual Behavior
```
vue.esm.js?a026:2532 Uncaught TypeError: Cannot read property 'test' of undefined
    at LineChart.Vue.$emit (vue.esm.js?a026:2532)
    at Chart.onHover (line-chart.ts?f2b9:71)
```
It's strange because when I put the $emit in the mounted hook it works correctly.

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 3.4.2
- npm version: 5.6.0
- typescript: 2.9.2

**Comment by apertureless** [comment]
Can you please post your full code? Or post a simple reproduction?
It may be a scoping problem with `this`. Does `  const item = this.chartData.datasets[0].data[element[0]._index];` work out?
