### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by eakarpov** [apertureless/vue-chartjs#519]
```typescript
@Component
export class BarChart extends Bar {
    constructor(props: any) {
        super(props);
    }
    @Prop({ type: Object })
    public chartdata!: any;
    @Prop({ type: Object })
    public options!: any;

    public mounted() {
        this.renderChart(this.chartdata, this.options);
    }
}
```

### Expected Behavior
Rendering empty canvas on the screen.

### Actual Behavior

Getting runtime error: TypeError: Super expression must either be null or a function

### Environment
- vue.js version:2.6.10
- vue-chart.js version: 3.4.2
- npm version: 6.7.0

**Comment by jsamayoap** [comment]
I'm stuck in the same situation, did you solved it?

**Comment by eakarpov** [comment]
> I'm stuck in the same situation, did you solved it?

Better read docs... Component should extends the Vue class though Bar class is extended via vue "extends" prop.

```typescript
@Component({
    extends: Bar,
})
export class BarChart extends Vue<Bar> {
}
```
