### ISSUE TITLE
Adding static data and dynamic data at the same time. 

### ISSUE THREAD

**Issue by relax101** [apertureless/vue-chartjs#52]
Not sure if I missed something from the examples but I'm trying to have my labels/colors set (static) in my js page while having the data for it set (dynamically) in my vue page through props. Whenever I add in the labels to my js page and try to add in this.chartData as well, it breaks. Is there a way to do this that I'm missing? Thanks.

**Comment by apertureless** [comment]
Can you provide a code example please?

**Comment by relax101** [comment]
I think I actually just got it working. I've got to fix my watcher now since I didn't like the change but I was able to keep my labels and other datasets in my .js page and my actual chart data in my .vue page. 

Looks like this. 

**.js page code:** 

import { Pie, mixins } from 'vue-chartjs'

export default Pie.extend({
  mixins: [mixins.reactiveProp], 
  props: ["chartData"],
  watch: {
     chartData: {
      handler: function (val) {
      this._chart.update()
    }, 
      deep: true
    }
  },
  mounted () {  
   this.renderChart({
         labels: ['Very High', 'High', 'Moderate', 'Low', 'Very Low'],
         datasets: [
            {
               label: 'Data One',
               backgroundColor: ['blue','red','orange','green','purple'],
               data: this.chartData.data
            }
         ]
     }, {responsive: true, maintainAspectRatio: false})
  } 
})

**And where I add it in my .vue page code:** 

<script>
import Post from './Post.vue'
import axios from 'axios'
import store from './../vuex/store'
import chart from './../charts/BarExample'

export default {
  components: {
   chart 
  },
  data: function () {
    return {
      control: "blah",
      controls: [],
      name: '',
      description: '',
      modalitem: '',
      page: 1,
      limit: 25,
      skip: 0,
      isMore: true,
      veryhighcount: 0,
      highcount: 0,
      mediumcount: 0,
      lowcount: 0,
      verylowcount: 0,
      chartdata: {
         data: [10, 10, 15, 10, 10]
      }
    } 
  },
</script>

Is this how it's intended to work or should I be doing it differently?

**Comment by apertureless** [comment]
Well, the reactiveProp mixin, is not really made to watch only specific changed.
I would recommend you to implement the watcher by yourself. You can see the source here in git, and take only the parts that you need. Because this way you can compose your data better.

And then you only need to pass the pure data and not the whole object.


```javascript
import { Pie } from 'vue-chartjs'

export default Pie.extend({
  props: ["mychartdata"],
  watch: {
     mychartdata: {
      handler: function (val) {
      this._chart.update()
    }, 
      deep: true
    }
  },
  mounted () {  
   this.renderChart({
         labels: ['Very High', 'High', 'Moderate', 'Low', 'Very Low'],
         datasets: [
            {
               label: 'Data One',
               backgroundColor: ['blue','red','orange','green','purple'],
               data: this.mychartdata
            }
         ]
     }, {responsive: true, maintainAspectRatio: false})
  } 
})`
```


And in your vue:

```javascript
<template>
<chart :mychartdata="chartdata"></chart>
</template>
`

`<script>
import Post from './Post.vue'
import axios from 'axios'
import store from './../vuex/store'
import chart from './../charts/BarExample'

export default {
  components: {
   chart 
  },
  data: function () {
    return {
      control: "blah",
      controls: [],
      name: '',
      description: '',
      modalitem: '',
      page: 1,
      limit: 25,
      skip: 0,
      isMore: true,
      chartData: [10, 10, 15, 10, 10]
   
    } 
  },
</script>`
```
