### ISSUE TITLE
Bar chart is square

### ISSUE THREAD

**Issue by eakarpov** [apertureless/vue-chartjs#520]
```typescript
@Component({
    extends: Bar,
})
export class BarChart extends Vue<Bar> {
    public mounted() {
        if (this.$el.parentNode) {
            const node: any = this.$el.parentNode;
            node.style.height = '300px';
            node.style.width = '400px';
        }
        this.renderChart(
            this.chartdata,
            {
                responsive: true,
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                        },
                    }],
                },
            });
    }
}
```
### Expected Behavior
Height should be 300px, width - 400px

### Actual Behavior

Both heigh and width are 400px

### Environment
- vue.js version: 2.6.10
- vue-chart.js version: 3.4.2
- npm version: 6.7.0

**Comment by apertureless** [comment]
Why don't you use the props for width and height? 
https://vue-chartjs.org/api/#props

**Comment by eakarpov** [comment]
@apertureless 

I added additional props for width and height. It isn't clear though.

My code:
```typescript
@Component({
    extends: Bar,
})
export class BarChart extends Vue<Bar> {
    @Prop({ type: Object })
    public chartdata!: any;

    @Prop({ type: Object })
    public options!: any;

    @Prop({ type: String, default: '600px' })
    public width!: string;

    @Prop({ type: String, default: '200px' })
    public height!: string;

    constructor(props: any) {
        super(props);
    }

    public mounted() {
        this.renderChart(
            this.chartdata,
            {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                        },
                    }],
                },
            });
    }
}
```

I suppose the width and height should be 600px and 200px respectively. Though, opened dev tool in browser, I saw there were different values - 942 and 314. Why is it so different?

`<canvas id="bar-chart" width="942" height="314" class="chartjs-render-monitor" style="display: block; width: 942px; height: 314px;"></canvas>`

**Comment by apertureless** [comment]
You do **not** need to declare the props. As they are already declared. And they have default values.

https://github.com/apertureless/vue-chartjs/blob/develop/src/BaseCharts.js#L31-L37

Furthermore `300px` will not work. Check out the chart.js docs: https://www.chartjs.org/docs/latest/general/responsive.html

**Comment by eakarpov** [comment]
@apertureless 
But there is no information about what is declared inside BaseChart except two methods 

```typescript
export declare class BaseChart extends Vue {
  addPlugin (plugin?: string[]): void
  renderChart (chartData: any, options?: any): void
}
```

I should declare them in my class because there is no information about them in super class. I'll try now declare them declaratively (public width!: number).

**Comment by eakarpov** [comment]
I did not succeed in changing height and width outside the component via props. The same behavior as in the previous case.

```typescript
// BarChart.vue
@Component({
    extends: Bar,
})
export class BarChart extends Vue<Bar> {
    @Prop({ type: Object })
    public chartdata!: any;

    @Prop({ type: Object })
    public options!: any;

    public width!: number;
    public height!: number;

    constructor(props: any) {
        super(props);
    }

    public mounted() {
        this.renderChart(
            this.chartdata,
            {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                        },
                    }],
                },
            });
    }
}
// somewhere.vue
<BarChart :width="600" :height="200"/>
```

**Comment by apertureless** [comment]
As you want a fix width and height, you need to pass the `responsive: false` option. 
Otherwise, the chart will fill the outer container element.

**Comment by eakarpov** [comment]
Thanks! That's what I needed.
I did not suppose responsive flag is set true by default.

**Comment by apertureless** [comment]
I guess `chart.js` changed that some time ago, because if I recall that correctly, as I was writing this wrapper the default were set to false. I guess people demanded a responsive chart per default.
