### ISSUE TITLE
Bundle size!

### ISSUE THREAD

**Issue by kennyStarfisk** [apertureless/vue-chartjs#522]
I don't get why chart.js is bundled instead of chart.min.js on using webpack... 

![Screenshot 2019-05-27 at 13 12 28](https://user-images.githubusercontent.com/44225848/58416279-54999a80-8081-11e9-80ad-f01dc7e1b3f8.png)

**Comment by apertureless** [comment]
Chart.js is **not** bundled into `vue-chart.js`!
It is only a `peerDependency`, thats why **you** have to install chart.js on your own.

Thus it depends on your webpack config. You can / should minify **your** production bundle.
