### ISSUE TITLE
mouse position 

### ISSUE THREAD

**Issue by RezaErfani67** [apertureless/vue-chartjs#526]
mouse position not work correctly with tooltip...
look at pic...
![image](https://user-images.githubusercontent.com/24381986/59157579-45274200-8ac2-11e9-8f7c-f4d5f78bfbf8.png)

**Comment by apertureless** [comment]
Hi @RezaErfani67 

can you please describe your issue a bit more? It is not clear for me, what the issue is.

**Comment by RezaErfani67** [comment]
resolved.... i add css .body{zoom:83%} and this bug has been produced...
