### ISSUE TITLE
overlapping text in vue component for doughnut chart.js

### ISSUE THREAD

**Issue by maverickpravin** [apertureless/vue-chartjs#527]
### Expected Behavior

![Capture1](https://user-images.githubusercontent.com/11708491/59757945-75cd5f80-92aa-11e9-8181-1131f7793d06.PNG)

### Actual Behavior

![Capture](https://user-images.githubusercontent.com/11708491/59757856-4c143880-92aa-11e9-855e-86ba70b4b690.PNG)

I have a chart.js doughnut chart vue component as below

The problem is that when i use multiple chart instances the text in the middle overlap.

But they are overlapped. I tried changing titles pacing, but that didn't do anything. How can I fix this? I like to have control over the HTML / whatever which gets outputted to the label.

```
<script>
import { Doughnut } from "vue-chartjs";

export default {
  name: "doughnutChart",
  extends: Doughnut,
  props: {
    data1: {
      type: String,
      // default: function() {
      //   return;
      // }
    }
  },
  mounted() {
    var value = this.data1;
    var data = {
      labels: ["My val", ""]
    };
    this.renderChart(
      {
        datasets: [
          {
            borderWidth: 1,
            backgroundColor: ["#FF6384", "#AAAAAA"],
            hoverBackgroundColor: ["#FF6384", "#AAAAAA"],
            hoverBorderColor: ["#FF6384", "#ffffff"],
            data: [value, 100 - value]
          }
        ]
      },
      {
        responsive: true,
        maintainAspectRatio: true,
        legend: { display: false },
        cutoutPercentage: 70,
        elements: {
            center: {
                text: '50%'  //set as you wish
            }
        },
        tooltips: {
          filter: function(item, data) {
            var label = data.labels[item.index];
            if (label) return item;
          }
        }
      }
    );
    this.textCenter(value)
  },
  methods:{
    textCenter(val) {
      Chart.pluginService.register({
        beforeDraw: function(chart) {
          var width = chart.chart.width,
          height = chart.chart.height,
          ctx = chart.chart.ctx;

          ctx.restore();
          var fontSize = (height / 114).toFixed(2);
          ctx.font = fontSize + "em sans-serif";
          ctx.textBaseline = "middle";

           var text = val + "%",
              textX = Math.round((width - ctx.measureText(text).width) / 2),
              textY = height / 2;

              ctx.fillText(text, textX, textY);
              ctx.save();
            }
         });
        }
      }
   };
    </script>
```

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
I guess you have to register it as a local plugin.

**Comment by jeff-ofobrukweta** [comment]
> I guess you have to register it as a local plugin.

yea you would have to as @apertureless  said earlier so that it would not always add the custom plugin for this in the global chart.js instance all through the lifecycle of the app. something in vue like this below ,bear in mind am using  vue-chartjs.I hope this helps.
mounted() {
    const customPlugin = (chart) => {
      const { width, height, ctx } = chart.chart;

      ctx.restore();
      const fontSize = (height / 114).toFixed(2);
      ctx.font = `${fontSize}rem sans-serif`;
      ctx.textBaseline = "middle";

      const text = "75%";
      const textX = Math.round((width - ctx.measureText(text).width) / 2);
      const textY = height / 2;

      ctx.fillText(text, textX, textY);
      ctx.save();
    };
    this.addPlugin(ChartDataLabels);
    this.addPlugin({
      id: "my-plugin",
      beforeDraw: customPlugin
    });

    this.renderChart(this.chartData, this.options);
  },

**Comment by Derricknjoroge** [comment]
Has anyone found a solution for this? In vue 3

**Comment by germanvolpi** [comment]
> ¿Alguien ha encontrado una solución para esto? En vue 3

?????
