### ISSUE TITLE
Line Chart did not render after the modal reopen. Only renders after page reload

### ISSUE THREAD

**Issue by ositowang** [apertureless/vue-chartjs#528]
### Expected Behavior
The Line Chart render after the the modal reopen

### Actual Behavior
The Line Chart render for the first time when I opened the modal. However, when I open the modal again. The Line Chart would not render. I check with the debugger. The `this.renderChart(this.chartData, this.chartOptions);` has been triggerred, but nothing render on the view.

### Environment
- vue.js version: 2.6.10
- vue-chart.js version: 3.4.2
- npm version: v10.16.0

### some code example here
```typescript
//base linchart component
import { mixins } from 'vue-class-component';
import { Component, Watch } from 'vue-property-decorator';
import { Line, mixins as chartJsMixins } from 'vue-chartjs';
import { ChartData, ChartOptions } from 'chart.js';

@Component({
  name: "LineChart",
  props: {
    chartData: {
      type: Object as () => ChartData,
      default: null
    },
    chartOptions: {
      type: Object as () => ChartOptions,
      default: null
    }
  },
  mixins: [chartJsMixins.reactiveProp]
})
export default class LineChart extends mixins(Line) {
  chartOptions!: ChartOptions;
  chartData!: ChartData;

  mounted () {
    this.renderChart(this.chartData, this.chartOptions);
  }  
}


//wrapper component for the base line chart
<template>
  <div>
    <line-chart :chart-data="chartData" :chart-options="opt"/>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import LineChart from "./LineChart.vue";
import { ChartData, ChartOptions, Point } from "chart.js";
@Component({
  name: "ReferenceChart",
  components: {
    LineChart
  },
  props: {
    propsChartData: {},
    opts: {}
  }
})
export default class ReferenceChart extends Vue {
  defaultOpts = {
    responsive: true,
    animation: { duration: 0 },
    maintainAspectRatio: false,
    spanGaps: true,
    showLines: true,
    lineTension: 0,
    elements: {
      point: { radius: 0 }
    },
    scales: {
      xAxes: [
        {
          type: "linear",
          display: true,
          scaleLabel: {
            display: true,
            labelString: "whatever"
          }
        }
      ],
      yAxes: [
        {
          display: true,
          scaleLabel: {
            display: true,
            labelString: "whatever"
          }
        }
      ]
    }
  };

  get opt(): ChartOptions {
    return Object.assign({}, this.$props.opts, this.defaultOpts);
  }

  get chartData(): ChartData {
    let dataList: Array<Point> = Object.entries(this.$props.propsChartData)
      .map(item => {
        return {
          x: parseFloat(item[0]),
          y: item[1] as number
        };
      })
      .sort((point1, point2) => point1.x - point2.x);
    return {
      datasets: [
        {
          borderColor: "#4bb2c5",
          fill: false,
          lineTension: 0,
          data: dataList
        }
      ]
    };
  }
}
</script>

//how i use it in the view
<reference-chart :propsChartData="latestData" ref="referenceChart"></reference-chart>
```
![image](https://user-images.githubusercontent.com/26860856/59774931-4a348000-927e-11e9-9284-7db4c85ed783.png)

It seems the base component gets the data and the `renderChart()` has been called. However, the chart did not render.

**Comment by ositowang** [comment]
Some updates here. I have done some experienments and inspection after submitting this issue. It seems that the chart has been drawn, but the height and width has been set to 0px. After manually changed the width and height, the chart shows up.  
It seems there are some issues regarding the rendering sequence of the modal and the chart so that the canvas can't get rendered properly.

**Comment by ositowang** [comment]
Just in case anyone who faces the same problem here, I solved this issue by manually setting the sytles of the line chart, so the line chart has its height and width when it renders

**Comment by apertureless** [comment]
@ositowang 

It depends on how your modal work.
If you are using `v-show` for your modal, every component inside your modal will be mounted and rendered. Thus your chart gets also mounted and rendered. But as the outer container (modal) is hidden with `v-show` it's height and width are 0.

So your canvas size will also be 0. However, the canvas will not magically adjust its size if the modal content is shown. The canvas only grabs once the size and applies it.

Most of the time a proper fix is to use `v-if`. Because `v-if` will destroy and mount the componentes inside.

**Comment by ositowang** [comment]
@apertureless 
Thank you for your explanation. It took me several hours to figure out the cause of the problem. I think it is worth mentioning in somewhere in the documentation cuz in many cases we use modal from third-party libraries and they hide the internal mechanism. And if it is possible, we'd better let them know the cause.
