### ISSUE TITLE
How to call method:fillData() from export default

### ISSUE THREAD

**Issue by dan-arsenault** [apertureless/vue-chartjs#529]
I have the ReactiveExample demo working :)
I have a grpc-web client.js running which needs to call fillData().
Is it possible to call the fillData() method from an external JS file?

export default {
  extends: Bar,
  mixins: [reactiveData],
  data: () => ({
    chartData: '',
    options: {
      responsive: true,
      maintainAspectRatio: false
    }
  }),
  created () {
    this.fillData()
  },
  mounted () {
    this.renderChart(this.chartData, this.options)
    _**//setInterval(() => {
    //  this.fillData()
    //}, 1000)**_
  },
  methods: {
    fillData () { ... }
  }
}

Instead of setInterval, how can I access/call method:fillData()?

**Comment by danzimal** [comment]
This seems to work.
I created a setData method which essentially stores the data so the chart can pick it up.

ReactiveExample.methods.setData([getRandomInt(),getRandomInt()]);

import { Bar } from '../BaseCharts'
import { reactiveData } from '../mixins'

**var data = [];**

export default {
  extends: Bar,
  mixins: [reactiveData],
  data: () => ({
    chartData: '',
    options: {
      responsive: true,
      maintainAspectRatio: false
    }
  }),
  created () {
    this.fillData()
    **this.setData()**
  },

  mounted () {
    this.renderChart(this.chartData, this.options)
    setInterval(() => {
      try { this.fillData() }
      catch {}
    }, 1000)
  },

  methods: {
    fillData () {
      try {
        this.chartData = {
          labels: ['label1', 'label2'],
          datasets: [
            {
              label: 'Data One',
              backgroundColor: '#f87979',
              data: [data[0], data[1]]
            }
          ]
        }
      }
      catch {
      }
    },
    **setData(d) {
      data = d;
    },**
  }
}
