### ISSUE TITLE
Show something when the pie is empty

### ISSUE THREAD

**Issue by crow1796** [apertureless/vue-chartjs#531]
### Expected Behavior
Show something like 'No Data' when the pie is empty or the values are all zeroes like, [0. 0. 0]

### Actual Behavior
It only shows the labels at the top and an empty space below it http://prntscr.com/oaifen

### Environment
- vue.js version: 2.6.10
- vue-chart.js version: 3.4.2
- npm version: 6.17.1

**Comment by apertureless** [comment]
This is not related to vue-chartjs. As it is only a wrapper for [Chart.js](https://github.com/apertureless/vue-chartjs)

Thus any core features should be reported there.
