### ISSUE TITLE
Custom tooltips position and missing caret

### ISSUE THREAD

**Issue by dstearle** [apertureless/vue-chartjs#535]
### Expected Behavior

- Tooltips should have caret
- Set tooltip position to side or below datapoint

### Actual Behavior

- Tooltip caret disappears when using custom tooltips
- No way to get caret back
- Vague documentation on how to position the tooltips in relation to datapoint. I know it can be done but I am at a loss as to how it is done.

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Hi @dstearle 

please keep in mind, that `vue-chartjs` is only a vue wrapper for `chart.js` for an easier and faster quick start. 

Thus, the documentation only refers to the vue specific areas. Does not make sense for me to maintain a copy of chart.js documentation.

Thus, if you're lacking any information always head out to the official chart.js documentation: https://www.chartjs.org/docs/latest/configuration/tooltip.html

There you will find any information about the tooltips and how to position them.

There are many different options like `caretSize`, `caretPadding` etc. which you can play with.

> Tooltip caret disappears when using custom tooltips

So you providing custom data to the tooltip callback ? This should not remove the caret. I am using custom tooltip callbacks at http://npm-stats.org/#/vue-chartjs

Feel free to post a small reproduction of your issue. However, I don't think it is related to `vue-chartjs` or its implementaion. 

It could be a bug in `chart.js` itself. So you should maybe head over to their repo :)

**Comment by dstearle** [comment]
Thanks I will take a look over at the original repo next. I have messed with caret size before but I was never able to get a caret.
