### ISSUE TITLE
Bar Chart not plotting as expected

### ISSUE THREAD

**Issue by WillGoldstein** [apertureless/vue-chartjs#538]
### Expected Behavior
I have set up my vue bar chart like this:

![image](https://user-images.githubusercontent.com/20759342/62059016-7255be00-b1f0-11e9-8ad5-659af9038d05.png)
![image](https://user-images.githubusercontent.com/20759342/62059031-784b9f00-b1f0-11e9-8390-a5a65c0e0f91.png)

But what is happening is the data is getting plotted left right in order it is found in the array in `datasets`, meaning that `[0]` gets plotted first, `[1]` gets next, etc, and the `x` value I gave to the data point is disregarded. The x-values do match the labels, and they are all in a format readable by moment.js.

### Actual Behavior

Data points plot on the x-axis as defined in their data object.

### Environment
- vue.js version: 2.6.6
- vue-chart.js version: ^3.4.2
- npm version: 6.9.0

**Comment by WillGoldstein** [comment]
I tried updating my data structure to mimic what is shown in the [docs](https://www.chartjs.org/docs/2.7.2/axes/cartesian/time.html#time-cartesian-axis)

```
data: [{
    x: new Date(),
    y: 1
}, {
    t: new Date(),
    y: 10
}]
```

where a given data point may look like:

![image](https://user-images.githubusercontent.com/20759342/62060088-7edb1600-b1f2-11e9-8f71-6edf4a4ee574.png)

where `t` is `moment(v.date).format(dateformat)` (date format may be 'YYYY', 'YYYY-MM', or 'YYYY-MM-DD' in my case.

**Comment by WillGoldstein** [comment]
Here's a codepen example where if you randomly remove some data points, you get really weird looking charts:

https://codepen.io/rw152/pen/vogowE

![image](https://user-images.githubusercontent.com/20759342/62072513-cb334f80-b20c-11e9-822c-a160f47e8f71.png)

**Comment by WillGoldstein** [comment]
Note: I solved this by ensuring my data points always have a y = `0` for a given x-axis value that would otherwise be omitted.

In other words, instead of:

```
data: [
          {x:'2019-07-02',y:8},
          {x:'2019-07-03',y:8},
          {x:'2019-07-05',y:8},
          {x:'2019-07-06',y:10},
	]
```
I loop through and make sure it looks like:

```
data: [
          {x:'2019-07-02',y:8},
          {x:'2019-07-03',y:8},
          {x:'2019-07-04',y:0},
          {x:'2019-07-05',y:8},
          {x:'2019-07-06',y:10},
	]
```

It's too bad that's the solution because it feels like what should be unnecessary looping and pain.

**Comment by apertureless** [comment]
Seems more like a limitation of Chart.js itself.

**Comment by WillGoldstein** [comment]
Ah far enough @apertureless - should I make this issue in chart js repo instead?
