### ISSUE TITLE
Docs examples for Pie are missing, if I import the hole package what shoud I put in the template engine  i.e<pie-chart /> ?>

### ISSUE THREAD

**Issue by YeisonHunt** [apertureless/vue-chartjs#548]
### Expected Behavior

More examples

### Actual Behavior

Just one example with Bar but with Pie it doesn't work,

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
There are several examples in the [README](https://github.com/apertureless/vue-chartjs/blob/develop/README.md) and in the [Docs](https://vue-chartjs.org/guide/#examples)

There are also examples for every chart in the source https://github.com/apertureless/vue-chartjs/tree/develop/src/examples

The steps are always the same for every chart type. Like explained here:

https://vue-chartjs.org/guide/#creating-your-first-chart
