### ISSUE TITLE
Documentation? Passing props fails to map properly

### ISSUE THREAD

**Issue by ajt001** [apertureless/vue-chartjs#549]
### Expected Behavior
Following the documentation here: https://vue-chartjs.org/guide/#chart-with-api-data , what results is that chartdata and options are not passed properly. You can see the chartdata and options are nested one-deep??

### Actual Behavior
<img width="347" alt="image" src="https://user-images.githubusercontent.com/39484953/64416777-2e04ea00-d0db-11e9-9ac4-bb652af88455.png">
<img width="390" alt="image" src="https://user-images.githubusercontent.com/39484953/64416917-69071d80-d0db-11e9-9ad6-7ae3c8bf23b7.png">
<img width="485" alt="image" src="https://user-images.githubusercontent.com/39484953/64417011-9eac0680-d0db-11e9-9c71-e1d3f24727cb.png">

### Environment
- vue.js version: 3.10.0
- vue-chart.js version: 3.4.2
- npm version: 6.11.2

**Comment by apertureless** [comment]
Please provide a codepen / codesandbox or any other *runable* reproduction.
