### ISSUE TITLE
How to give a space between graph and legend?

### ISSUE THREAD

**Issue by joaovjusto** [apertureless/vue-chartjs#550]
I want to give a space because of the datalabels plugin going over the legend...

Example: 

![Screen Shot 2019-09-11 at 5 56 03 PM](https://user-images.githubusercontent.com/39304654/64734841-cf19e900-d4bd-11e9-9b82-8536d77dec24.png)

**Comment by apertureless** [comment]
https://stackoverflow.com/questions/42585861/chart-js-increase-spacing-between-legend-and-chart

**Comment by JoshuaRobertson** [comment]
> https://stackoverflow.com/questions/42585861/chart-js-increase-spacing-between-legend-and-chart

Hi @apertureless, which comment or solution works from this Stackoverflow? Appreciate I'm quite late to this thread but I've tried them and can't get any to work. Could you create a Codepen with an example please?

**Comment by apertureless** [comment]
Hey! The SO thread and this issue are quite old. So I am not sure which solution will work for you.
The issue however, is more chart.js related then vue-chartjs. You may hop over to the core chart.js repo or their discord maye to get more help.
