### ISSUE TITLE
Why chart.js is not a direct dependency of vue-chartjs?

### ISSUE THREAD

**Issue by lwxbr** [apertureless/vue-chartjs#552]
I didn't understood why chart.js is not a dependency of vue-chartjs and you have to install them separately. You can use vue-chartjs without chart.js? There are another bindings?

**Comment by apertureless** [comment]
It is a `peerDependency` which means, that you have to install it yourself. 
Which sounds weird at first, but makes totally sense if you think about it.

As vue-chartjs is only a wrapper of chart.js is just a quite high abstraction of some logic. Most chart configuration is over the datasets or options, which you pass in. 

If it were a dependency, I would need to update periodically the `package.json` to match the current version. 

This way, as a peerDependency you can install also specific versions of chartjs that will mostly work with vue-chartjs on top. If chart.js got an update you can update it yourself, if you need it. 

It is quite common practice to use `peerDependencies` for this kind of "plugins".
It provides a lot of flexibility.
