### ISSUE TITLE
Reset Zoom

### ISSUE THREAD

**Issue by ddiegommachado** [apertureless/vue-chartjs#554]
Hi everyone! 

Don't understand how to make this. Someone help me?

Got it! Should have read the doc more carefully before I ask. This works for me:  this.$data._chart.resetZoom();

_Originally posted by @ppirrip in https://github.com/apertureless/vue-chartjs/issues/94#issuecomment-432423535_

**Comment by datainvestor** [comment]
I tried this:
<q-btn @click="this.$data._chart.resetZoom()">Reset Zoom</q-btn>
However I get the following error:
`TypeError: Cannot read property '_data' of null`

Everytime I click on that button. Any idea why this might be happening?

**Comment by apertureless** [comment]
`this.$data._chart` is only available inside your chart component. 
And only after the chart component is mounted.

**Comment by datainvestor** [comment]
So how it is possible to create a button that resets the chart?
Like for instance here:
https://codepen.io/sergwx/pen/gERwrM

**Comment by chloehabitat** [comment]
Did you manage to solve this? I have the same problem
