### ISSUE TITLE
Horizontal bar chart displays backwards

### ISSUE THREAD

**Issue by theaarontaylor** [apertureless/vue-chartjs#556]
### Expected Behavior
Bars should go right

### Actual Behavior
Bars go left, over labels
![Screen Shot 2019-09-26 at 7 19 40 PM](https://user-images.githubusercontent.com/7313352/65706245-b5b69680-e092-11e9-9dd0-f64c60ecb15f.png)

Has anyone encountered this before? Or is this a ChartJs issue?

### Environment
- vue.js version: 2.6.10
- vue-chart.js version: 3.4.2
- npm version: 6.9.0

**Comment by apertureless** [comment]
Well... let me check my 🔮 .....

Without any example code, it's hard to tell ;)
Please provide a codepen or jsfiddle for reproduction, then we can see where the issue is.
