### ISSUE TITLE
Treemap

### ISSUE THREAD

**Issue by alc32** [apertureless/vue-chartjs#560]
How to extend vue-chartjs to use Chart.js Treemap?

https://github.com/kurkle/chartjs-chart-treemap

**Comment by spocock** [comment]
This approach worked with vue-chartjs v3 and v4, but at v5 `generateChart()` has been replaced by `createTypedChart()` (see [here](https://vue-chartjs.org/migration-guides/#api-changes)) which errors with `"tree-map" is not a registered controller.`
