### ISSUE TITLE
Big bundle size

### ISSUE THREAD

**Issue by bagaskarala** [apertureless/vue-chartjs#561]
How to get small bundled dependencies? i think it still huge size

### Actual Behavior
<img width="307" alt="chart js bundle" src="https://user-images.githubusercontent.com/14112952/66995722-ad81d200-f0f9-11e9-9a91-3997e76f9127.png">

### Environment
- vue.js version: 2.6.10
- vue-chart.js version: 3.4.2
- npm version: 6.4.1

**Comment by bagaskarala** [comment]
so in my screenshot it use nonminified chart.js? so how i point to chart.min.js?

**Comment by apertureless** [comment]
Well it depends if you are analyzing your development build or your production build.

In general (depending on your webpack.conf) you will minify your production build. 
And then you have to analyze it and see if chart.js really is that big.

You can point it in the alias section.


Just take a look at this issue: https://github.com/apertureless/vue-chartjs/issues/124
