### ISSUE TITLE
Add note or annotation in Chart.js

### ISSUE THREAD

**Issue by phuclh** [apertureless/vue-chartjs#563]
How can I add note or annotation in ChartJs. Something like this:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/a5FJq.png

I tried some keywords `ChartJs annotation` or `ChartJs note` but could not find any plugin or document about that.

Thank you!

**Comment by apertureless** [comment]
https://github.com/chartjs/chartjs-plugin-annotation
