### ISSUE TITLE
LineChart seems opaque when using with Vuetify's dark theme

### ISSUE THREAD

**Issue by rtadewald** [apertureless/vue-chartjs#565]
When I create a LineChart with Vuetify's dark theme, the graph appears opaque. How can I change it?
<img width="1440" alt="Captura de Tela 2019-10-25 às 23 02 57" src="https://user-images.githubusercontent.com/22618324/67612728-a010bb80-f77b-11e9-9038-70f951b7e873.png">

**Comment by apertureless** [comment]
Pass other line options in? Different color maybe.

https://www.chartjs.org/docs/latest/charts/line.html?h=line%20color

**Comment by rtadewald** [comment]
Hello, @apertureless , thanks for you help.

borderColor didn`t worked, actually, it changes the color of the line, not the axis.
I cant find the right parameter.
