### ISSUE TITLE
how to use the result of generateLegend()

### ISSUE THREAD

**Issue by upadhb** [apertureless/vue-chartjs#566]
Not sure if this is the right place to ask this question, so I apologize if I have submitted it to the wrong forum. 

Referring to the following example from coding reference of vue-chartjs, I wanted to know how I could use the 'htmlLegend'. Will it print inside the canvas (that would be amazing) or is this something that a wrapper component would utilize to create a html block for legend?

![image](https://user-images.githubusercontent.com/17695919/67721204-fa8c6080-f9a3-11e9-8031-5a47907c54bb.png)

**Comment by apertureless** [comment]
This will output you the HTML for the legend. You can control the output via the `legendCallback` 

https://www.chartjs.org/docs/latest/configuration/legend.html#html-legends

**Comment by upadhb** [comment]
Thank you @apertureless 
I have a method on the canvas to download it locally as png, but I don't know how to get the html output of legendCallback to be a part of the canvas. Is that possible?

**Comment by apertureless** [comment]
Not sure about this. I mean you can use the "build-in" legend. The `generateLegend()` output is if, you want to palce the legend outside of the canvas.

But you should head over to [Chart.js repo](https://github.com/chartjs/Chart.js) as it's more related directly to chart.js and not so much to vue-chartjs.
