### ISSUE TITLE
npm outdated -> chart.js | Current -> 2.8.0 | Wanted -> 2.9.1

### ISSUE THREAD

**Issue by renatodolce** [apertureless/vue-chartjs#569]
### Expected Behavior
npm update success

### Actual Behavior
vue-chartjs@3.4.2 requires a peer of chart.js@>= 2.5 <= 2.8 but none is installed. You must install peer dependencies yourself.

### Environment
- vue.js version: 2.6.10
- vue-chart.js version: 3.4.2
- npm version: 5.6.0

**Comment by mark1282** [comment]
I was hoping someone would be having this issue too. I wonder when an update will be available.

**Comment by apertureless** [comment]
Well, it's not really an issue. I have to test the new version of chart.js and update the peerDependency. 

However, the nice thing about peerDepedencies is, that you can decide what version you want. So if you install the latest chart.js version, it should work with `vue-chartjs` (expect there is a breaking change in chart.js) 

npm is throwing out only a warning, which should not have any effect on the usage.
