### ISSUE TITLE
Lines are looking weird.

### ISSUE THREAD

**Issue by shakee93** [apertureless/vue-chartjs#57]
![image](https://cloud.githubusercontent.com/assets/14835725/23756321/50656840-0509-11e7-9eaa-46c90066cd80.png)

i have updated the plugin to latest version from older version. i have noticed the lines are looking weired.. do you have any idea why this has happened ? what am i missing ?

Thanks

### Environment
- vue.js version:  2.2.1
- vue-chart.js version: 2.5.0

**Comment by apertureless** [comment]
- What was the previous version you had installed?
- Have you tried deleting node_modules and install again?
- Have you tried setting the borderWidth?

**Comment by shakee93** [comment]
- the previous version is 2.5.0
- yes i have tried that
- yes tried border width

still the same 

![image](https://cloud.githubusercontent.com/assets/14835725/23809504/ef55b69a-05f3-11e7-90b1-7af8afcc06f2.png)

**Comment by apertureless** [comment]
Well, *looking weird* is a bit of a unspecific term.

I guess you mean that the border of the linechart, is cut off on the bottom?
Well I guess thats a normal behaviour of chart.js 

If you check out the chart.js docs http://www.chartjs.org/ the line example also has cut off borders.

You can try to play with some settings maybe add some spacing but I don't think this is related to `vue-chartjs`.  You could create an issue on the [chart.js](https://github.com/chartjs/Chart.js/issues) lib. Maybe people there know a workaround for that.
