### ISSUE TITLE
Charts destroyed before router transition ends

### ISSUE THREAD

**Issue by laygir** [apertureless/vue-chartjs#579]
Hi! 👋 

I have a router-view wrapped with a transition and each time I change routes, before I leave the page, charts are being destroyed, resulting in a sudden disappearance and it's not nice :)

Is there a specific reason for such behavior, or if it would be possible to improve this?

Would changing the following beforeDestroy hook to destroyed fix the issue? 

https://github.com/apertureless/vue-chartjs/blob/7efc3b3c53191334e1896d0bcbe464a6a5fc2b88/src/BaseCharts.js#L82

**This is how I use router view with a transition**
`    <transition :name="viewTransition">
        <router-view/>
    </transition>
`

Cheers!

**Comment by laygir** [comment]
Helloo?

**Comment by blaadje** [comment]
same issue

**Comment by vladi-strilets** [comment]
Same issue
