### ISSUE TITLE
Inconsistency between Vue.component and import

### ISSUE THREAD

**Issue by UglyHobbitFeet** [apertureless/vue-chartjs#581]
I am trying to get a chart that uses both bars and lines.  I have a working example that uses the 

    Vue.component('test-chart', {
      extends: VueChartJs.HorizontalBar,

here:

https://codepen.io/uglyhobbitfeet/pen/LYYqeeg

However, If i take the SAME CODE and copy/paste it into the format that uses

    import { HorizontalBar } from 'vue-chartjs';
    export default {
      extends: HorizontalBar,
       data: () => ({
        chartData: {
          datasets: [{
           // same data copy & pasted from codepen
          }],
        },
       chartOptions: {
           // same data copy & pasted from codepen
       },
      mounted() {
        this.$nextTick(() => {
          this.renderChart(this.chartData, this.chartOptions);
        });
  },

the bars show up as expected but:
 - the line is not drawn, and 
 - the x-axis shows incorrect values when the line is 'visible' in the legend (aka The text 'Line1' does not have a strikethrough in the legend). Using the example data in the codepen, the x-axis will display (negative)-$200,000,000 though (positive)1,800,000,000

Both versions use the latest vue-chart-js (3.5.0) and chart-js (2.9.3). Note that the code does use the newer floating-bars feature from chartjs (https://www.chartjs.org/docs/latest/charts/bar.html#data-structure), but since it works in the codepen I wasn't sure if this was the issue.

**Comment by apertureless** [comment]
So what you mean is that, if you are using global components `Vue.component()` vs. Single File Components you are getting different results?

Well, in both cases it should work the same. Are you using webpack ?

Btw. you can also use normal Bar charts for mixed charts: https://www.chartjs.org/docs/latest/charts/mixed.html

**Comment by UglyHobbitFeet** [comment]
I believe that is what I'm saying, yes. 

I'm not explicitly using webpack but may be through other dependencies like vuetify, vuex, etc.

I can't use normal bar charts for this particular example as I need floating-bars since I have x number of bars that need full height and variables widths in tandem with a line chart
https://github.com/chartjs/Chart.js/issues/6733

I'm not sure how to make a single file components example in codebox, which is why I didn't provide one

**Comment by UglyHobbitFeet** [comment]
FWIW since I don't have a codepen for Single File components here is how it's set up (using Vuetify).

MyVuetifyComponent.vue
```
<template>
  <v-card>
    <v-card-text>
      <div style="max-width:600px;max-height:400px;">
        <Test-Chart></Test-Chart>
      </div>
    </v-card-text>
  </v-card>
</template>

<script>
import TestChart from '@/TestChart.vue';

export default {
  components: {
    TestChart,
  },
};
</script>
```
TestChart.vue
```
<script>
import { HorizontalBar } from 'vue-chartjs';

export default {
  extends: HorizontalBar,
  data: () => ({
    chartData: {
      datasets: [{
        label: 'Bar1',
        data: [[1300000000, 1310000000]],
      }, {
        label: 'Bar2',
        data: [[1400000000, 1410000000]],
      }, {
        label: 'Bar3',
        data: [[1500000000, 1510000000]],
      }, {
        backgroundColor: 'rgb(75, 192, 192, 0.5)',
        borderColor: 'rgb(75, 192, 192)',
        borderWidth: 1,
        data: [[1230000000, -280], [1440000000, -350], [1750000000, -60]],
        fill: false,
        label: 'Line1',
        pointRadius: 10,
        showLines: true,
        type: 'line',
        yAxisID: 'line',
      }],
    },
    chartOptions: {
      datasets: {
        horizontalBar: {
          backgroundColor: 'rgba(0,255,0,0.2)',
          barPercentage: 1,
          borderColor: 'rgba(0,255,0,1)',
          borderWidth: 1,
          categoryPercentage: 1,
          yAxisID: 'bar',
        },
      },
      maintainAspectRatio: true,
      responsive: true,
      scales: {
        xAxes: [{
          // gridLines: {
          //   color: 'yellow',
          //   zeroLineColor: 'green',
          // },
          ticks: {
            beginAtZero: false,
            callback: v => `$${v}`,
            // fontColor: 'blue',
            minRotation: 0,
            maxRotation: 0,
            // zeroLineColor: 'green',
          },
          type: 'linear',
        }],
        yAxes: [{
          id: 'bar',
          position: 'right',
          type: 'category',
          stacked: true,
          labels: [''],
          offset: true,
        }, {
          id: 'line',
          position: 'left',
          labels: ['foo'],
          // gridLines: {
          //   color: 'blue',
          //   zeroLineColor: 'green',
          // },
          ticks: {
            callback: v => `${v} wq`,
            max: -25,
            maxRotation: 0,
            min: -425,
            minRotation: 0,
            stepSize: 25,
            // zeroLineColor: 'green',
          },
        }],
      },
      title: {
        display: true,
        text: 'Banana Hammock',
      },
    },
  }),
  mounted() {
    this.$nextTick(() => {
      this.renderChart(this.chartData, this.chartOptions);
    });
  },
};
</script>
<style>
  canvas {
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
  }
</style>

```

**Comment by UglyHobbitFeet** [comment]
Update: Got it working by changing the line data from [[xNum,yNum]] to [{x:xNum,y:yNum}]

However, it should be working with either format as you can see the [[]] notation works fine in the codepen.

**Comment by apertureless** [comment]
Will look into it.

**Comment by apertureless** [comment]
Well, both version give me the exact same output:

https://codesandbox.io/s/vuechartjs-by5zp

No matter if you register the chart globally `Vue.component()` or using a single file component.

**Comment by UglyHobbitFeet** [comment]
You may want to reconsider closing this issue... I noticed your examples did not render the line. I am providing one which does.

https://codepen.io/uglyhobbitfeet/pen/PooLgev

**Comment by apertureless** [comment]
Updated the codesandbox: https://codesandbox.io/s/vuechartjs-by5zp

They were not showing the charts because of wrong dataset format for the line chart.

However, both act exactly the same.
