### ISSUE TITLE
local chart plugin

### ISSUE THREAD

**Issue by marjoforcado** [apertureless/vue-chartjs#588]
According to Chartjs documentation importing when you import:
`import ChartDataLabels from 'chartjs-plugin-datalabels';`

Into your Vue component it is registered globally. Is there a way for me to unregister this using custom charts?

**Comment by marjoforcado** [comment]
I figure that I don't really need to have a local plugin. I can just hide the `datalabel`.

**Comment by riderx** [comment]
i would love to have local plugin

**Comment by apertureless** [comment]
@riderx 

You can pass the plugins over the `plugins` prop. https://vue-chartjs.org/api/
Then they only registered to the chart you are passing them.

However, this might not work for all plugins. Because some third party chartjs plugins prefer to register themself globally.
