### ISSUE TITLE
child._updateFromParent is not a function

### ISSUE THREAD

**Issue by whatya** [apertureless/vue-chartjs#59]
### Expected Behavior
child._updateFromParent is not a function

### Actual Behavior
i pasted the demo example to my project and got this error,(the bar was displayed normaly)

### Environment
- vue.js version: <newest>
- vue-chart.js version: <newest>
- npm version: <newest>

**Comment by apertureless** [comment]
Hey @whatya ,
please provide a minimal repo for reproduction. Or a jsfiddle.

Never had this message before, so I can't really tell why it appears.
What is you vue version? And what is your vue-chartjs version you are using?
