### ISSUE TITLE
this.$data._chart.update(); does not update the dataset label colour

### ISSUE THREAD

**Issue by DM2489** [apertureless/vue-chartjs#592]
Today I cam across a weird bug where some chart types are not updating the dataset label colour when `this.$data._chart.update();` is called. Well, they are updating, but they are always one colour behind...

The following charts **show** this bug:

- Bar
- Horizontal Bar
- Doughnut
- Pie
- Polar Area
- Bubble

The following charts **do not show* this bug:
- Line
- Radar
- Scatter

Gif below:

![vuechartjs](https://user-images.githubusercontent.com/40390596/72547667-f9711e00-3884-11ea-98ae-490f313ab900.gif)

### Expected Behavior

`this.$data._chart.update();` should update the dataset label for all charts.

### Actual Behavior

The above chart types do not update the dataset label colour.

### Workarounds

Calling `this.renderChart(this.chartData,this.options)` instead of `this.$data._chart.update();` works.
Double calling `this.$data._chart.update();` also works!

Seems to me like the label colour is being set after the `update()` method has done its thing for some charts.

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 3.5.0

**Comment by apertureless** [comment]
Thanks for the issue. I will look into it. However, the `update()` method is the native one provided by `Chart.js`. May be a bug in its core.

**Comment by DM2489** [comment]
@apertureless Thanks for the quick response. I just did a quick rollback on the ChartJs package from 2.9.3 to 2.8.0 and it works as expected, so it looks like the core library is at fault like you say. I'll open a ticket up over there. Feel free to close this as an upstream issue!

**Comment by DM2489** [comment]
Opened this as an issue at ChartJs here: https://github.com/chartjs/Chart.js/issues/6968

**Comment by apertureless** [comment]
Awesome! Thanks! 🙏
