### ISSUE TITLE
"TypeError: Cannot read property 'getContext'

### ISSUE THREAD

**Issue by SvenSchwertner** [apertureless/vue-chartjs#594]
**Expected Behavior**
Expect chart to render in the browser.
Ich weis das es bereits hier einen Ähnlichen Fehler gab jedoch hilft mir die Lösung nicht weiter.

**Actual Behavior**
Error in console and nothing renders to the page.

Ich habe mit `vue create` ein Projekt erstellt und die App.vue wie folgt geändert:

**App.vue**

![Appvue_Image](https://user-images.githubusercontent.com/46284124/72835463-0ded5600-3c8b-11ea-8976-f71fad555087.PNG)

Im Browser bekomme ich folgende Fehlermeldung:

![Brwoser_Fehler](https://user-images.githubusercontent.com/46284124/72835610-53aa1e80-3c8b-11ea-8723-2df45d9564e0.PNG)

**Comment by apertureless** [comment]
You should check out the [Getting Started Guide](https://vue-chartjs.org/guide/#creating-your-first-chart)

You are simply using the lib in a wrong way.
