### ISSUE TITLE
Chart js: chart trying to mutate store state outside mutation when I do logout, they are not related with reference 

### ISSUE THREAD

**Issue by samvelian13** [apertureless/vue-chartjs#596]
### Expected Behavior

How fix mutate state outside in mutations handlers error when I want to redirect in other page.
I've tried to destroy chart in beforeBestroy parent lifecycle but it is not work.

**this is the screenshot of that error**
[https://gyazo.com/36763a48916ff7ded97267b1d289529d](url)
### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by samvelian13** [comment]
> ### Expected Behavior
> How fix mutate state outside in mutations handlers error when I want to redirect in other page.
> I've tried to destroy chart in beforeBestroy parent lifecycle but it is not work.
> 
> **this is the screenshot of that error**
> [https://gyazo.com/36763a48916ff7ded97267b1d289529d](url)
> 
> ### Actual Behavior
> ### Environment
> * vue.js version: latest
> * vue-chart.js version: latest
> * npm version: latest

**Comment by samvelian13** [comment]
???????????

**Comment by apertureless** [comment]
Well, don't mutate the state ¯\_(ツ)_/¯

Chart.js will internally change the object, thus you should not store the whole chartData object in your vuex store. 

But, ... it's hard to tell without a reproduction. And without seeing any code. So it would be great if you could create a small codepen / jsfiddle with a reproduction.

**Comment by samvelian13** [comment]
I don't mutate the store myself and don't use the mixins that in the docs. I could send you the part of codes that you need to check

**Comment by samvelian13** [comment]
the chart show normally in the dashboard, when I'm clicking in the logout I only mutate the auth module state and redirect user to the login page, during of this I get this error.

**Comment by samvelian13** [comment]
https://gyazo.com/77abb77b281e5c45ba87ce26a303c118
this is my line chart component

**Comment by samvelian13** [comment]
this is the parent component where reportChartData is the data that is coming from store
https://gyazo.com/30b8efbb581e20c0193afd8f16587307

I found one solution for this, I try to clean the reportChartData from the store in before destroy lifecycle and it's work, but I think it's not best solution for that
