### ISSUE TITLE
Cannot modify styling using options

### ISSUE THREAD

**Issue by JonathanTroyer** [apertureless/vue-chartjs#60]
### Expected Behavior

When passing option data such as

`
options: {
    responsive: true,
    maintainAspectRatio: false,
    legend: {
        display: true,
        labels: {
            fontSize: '1em',
            fontFamily: "'Roboto' sans-serif",
            fontColor: "#000"
        }
    }
`

in the options parameter of `renderChart()` for those styling options to be honored.

### Actual Behavior

All styling follows the default styling, which is not configurable (or at least I couldn't find how to do so).
While in the area, being able to modify the global style would be fantastic.

### Environment
- vue.js version: 2.2.2
- vue-chart.js version: 2.5.1
- ~~npm version: 3.10.10~~
- yarn version: 0.21.3

**Comment by apertureless** [comment]
Well, you can modify the styling options.
But your options object is simply wrong. Please check the [Chart.js docs](http://www.chartjs.org/docs/#chart-configuration-legend-label-configuration)

`fontSize` for example accepts only a number. You can't pass '1em' to it.
If you pass a valid `options` object to it, it will work 😄 

![preview image](https://i.imgur.com/qXoTjFV.png)
