### ISSUE TITLE
Getting specific, selected id on multi-dataset

### ISSUE THREAD

**Issue by adamfriedland** [apertureless/vue-chartjs#600]
I have certain charts that I've implemented that contain multiple datasets. When triggering an `onclick` event, is there a way to distinguish which dataset is picked?

Environment
vue.js version: 2.6.10
vue-chart.js version: 3.5.0
npm version: 6.12.0

**Comment by apertureless** [comment]
Well, as this is not specific with `vue-chartjs` please consider checking out the Chart.js repo or stackoverflow, you will mostly find your answers there.

https://stackoverflow.com/questions/43085672/chart-js-multiple-dataset
