### ISSUE TITLE
Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by LorhanSohaky** [apertureless/vue-chartjs#609]
```vue
<script>
import { Line, mixins } from "vue-chartjs";
const { reactiveProp } = mixins;

export default {
  extends: Line,
  mixins: [reactiveProp],
  props: ["options"],
  mounted() {
    this.renderChart(this.chartData, this.options);
  }
};
</script>

<style></style>
```

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 3.5.0
- npm version: 6.13.4

**Comment by apertureless** [comment]
Please provide a reproduceable example. 
Errorrs are mostly related to code outside of the chart component.

**Comment by LorhanSohaky** [comment]
Repo https://github.com/pwn2winctf/NIZKCTF-js/blob/develop/frontend/src/views/Rank.vue

**Comment by apertureless** [comment]
Might be related to the API.

https://vue-chartjs.org/guide/#chart-with-api-data

**Comment by LorhanSohaky** [comment]
oooh, thanks !! I will try your suggestion
