### ISSUE TITLE
Examples doesn't work

### ISSUE THREAD

**Issue by eduardor2k** [apertureless/vue-chartjs#610]
### Expected Behavior
https://3m1lm.csb.app/

### Actual Behavior
Data is not rendered

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 2.9.3
- npm version: ?

**Comment by apertureless** [comment]
Please provide a reproduceable example as code. 
It seems that you are not passing the data to the chart component.

Your `<RandomChart/>` has the `datacollection` property.
But your `<LineChart/>` you have `chartdata` which is `undefined`. 
And you have `chart-data` which holds the values from `datacollection`.

So I guess something is wrong with your data passing.

**Comment by natsu90** [comment]
I'm still trying to figure out how the example works, and seeing @eduardor2k example also doesn't work, any kind soul can give us a working example in a snippet, i will very much appreciate it.

**Comment by apertureless** [comment]
Well, there should be plenty of examples:

- **Documentation**: https://vue-chartjs.org/guide/#examples
- **Example in source**: https://github.com/apertureless/vue-chartjs/tree/develop/src/examples
- **Source of Demo page**: https://github.com/apertureless/vue-chartjs-demo
