### ISSUE TITLE
Please add ctx support

### ISSUE THREAD

**Issue by ayophanz** [apertureless/vue-chartjs#612]
### Expected Behavior
Please add ctx support

### Actual Behavior
ctx not on documentation

### Environment
- vue.js version: latest
- vue-chart.js version: latest
- npm version: latest

**Comment by apertureless** [comment]
What do you mean with ctx support? Access to the canvas?
You have access to the canvas over `this.$refs.canvas` 

https://vue-chartjs.org/api/#canvas

**Comment by ayophanz** [comment]
Thanks, I am creating and label inside the horizontal bar, do you any working example for ctx/canvas

**Comment by apertureless** [comment]
Check out the main Chart.js repo. There are several examples on how to use ctx to create additional functionallity.
