### ISSUE TITLE
Updating options does not update chart

### ISSUE THREAD

**Issue by datainvestor** [apertureless/vue-chartjs#618]
I'm trying to make the chart update itself like in this example https://www.chartjs.org/samples/latest/scriptable/pie.html
Where you click on toggle donut/pie and it changes from donut to pie chart.
So the pure ChartJS code is as per ChartJS github:
```
		function togglePieDoughnut() {
			if (chart.options.cutoutPercentage) {
				chart.options.cutoutPercentage = 0;
			} else {
				chart.options.cutoutPercentage = 50;
			}
			chart.update();
		}
```

However in Vue I tried doing this way:

```
      doughoptions: {
        borderWidth: "10px",
        hoverBackgroundColor: "red",
        hoverBorderWidth: "10px",
        responsive: true,
        maintainAspectRatio: false,
        title: {
          display: true,
          text: "Outstanding"
        },
        cutoutPercentage: 0
      },
```

And created a method:

```
    togglePieDoughnut() {
    this.doughoptions.cutoutPercentage = 50;
    }
```

In the same component:

`<Donut :chartData="dough" :options="doughoptions"></Donut>`

And in the `Donut` component i put reactive mixin:
```
<script>
import { Doughnut, mixins } from "vue-chartjs";
const { reactiveProp } = mixins;

export default {
  extends: Doughnut,
  props: ["options"],
  mixins: [reactiveProp],
  mounted() {
    // this.chartData is created in the mixin.
    // If you want to pass options please create a local options object
    this.renderChart(this.chartData, this.options);
  },
};
</script>
```

However even tough the options objects seems to be updated the chart does not update. I wonder what Im missing? 
You can see this problem here:
https://codesandbox.io/s/vue-chartjs-demo-jqk2h?file=/src/App.vue

EDIT: Added codesandbox link

**Comment by apertureless** [comment]
Sorry, I am currently quite busy. 
In general, the provided mixin only adds a watcher to `chartData` not to the `options` object. 

Thus if you're changing the options the chart will not update. If you want reactive options you have to add a watcher yourself and call the `update()` method.

**Comment by Baltimer** [comment]
Hello @apertureless,
I've some issue related with this, but in my case I've a watcher working to the chartData property, but I'm unable to acces the _chart property in order to call the `update()` method...

In the Vue DevTools the _chart property appears as "Unknown Component". It's quite strange since the chart is working, and I can redraw the chart with the new values.. But what I need is to append some extra data using the "linear" animation.

Maybe I'm missing something in between? 

Thank you!
