### ISSUE TITLE
Does it have support for chartjs plugins?

### ISSUE THREAD

**Issue by sumant4ssm** [apertureless/vue-chartjs#620]
### Expected Behavior
I am using plugin [Plugin](https://emn178.github.io/chartjs-plugin-labels/samples/demo/
)
my code looks like this ` this.options = {
        responsive: true,
        maintainAspectRatio: false,
        devicePixelRatio: 2,
        tooltips: {
          enabled: true,
        },
        title: {
          display: true,
          text: 'Thread state %',
          position: 'bottom',
          fontSize: 20,
        },
        plugins: {
          labels: [
            {
              render: 'label',
              position: 'outside',
            },
            {
              render: 'percentage',
            },
          ],
        },
      };`

### Actual Behavior

I should be able to show % in Pie chars arcs

### Environment
- vue.js version: <2.6.10>
- vue-chart.js version: <3.5.0>
- npm version: <version here>

**Comment by apertureless** [comment]
You can add local plugins with `addPlugin` https://vue-chartjs.org/api/#addplugin

or use the plugins prop: https://vue-chartjs.org/api/#props
