### ISSUE TITLE
Y-axes Scale issue with decimal stepSize

### ISSUE THREAD

**Issue by evertdausy1** [apertureless/vue-chartjs#624]
### Expected Behavior
I have a line chart that will have on the Y-axes a min value of 1.0 and a max value of 3.3. I need 10 ticks. So tick size = (3.3 - 1.0) / 10 = 0.23. So I would expect 10 labels on my y axes.

### Actual Behavior
I'm only getting like 6 or 7 labels and the tick size is completely off. I was trying to find what the issue is, and I came upon this fix in chart.js. https://github.com/chartjs/Chart.js/pull/6966. I think these are related.

`ticks: {
          min: 1, //minimum tick
          stepSize: 0.23,
          maxTicksLimit: 10,
          max: 3.3,
}`

I added the max ticks limit just to test, it should not be needed in the scenario I think.

![scales_issue](https://user-images.githubusercontent.com/62487517/84863987-39c40a80-b076-11ea-85ff-b55c5c50f2b9.PNG)

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 1.0.5
- npm version: 6.13.4

**Comment by apertureless** [comment]
Sorry to close this, but its not related to `vue-chartjs` as this is only a wrapper for [Chart.js](https://github.com/chartjs/Chart.js) so you might want to check out the main documentation or the main repo.

**Comment by evertdausy1** [comment]
Can I just update chart.js? Because this should be fixed in the latest version.

**Comment by apertureless** [comment]
Yes, as Chart.js is only a peerDependency, you can simply update chart.js and it should work.
