### ISSUE TITLE
Uncaught (in promise) DOMException: The object could not be cloned.

### ISSUE THREAD

**Issue by raisonon** [apertureless/vue-chartjs#625]
Bit stumped, but getting this in console when using this package.. Working fine but not sure what creating this.

Read in other issues this can happen if methods attached to object, but don't believe this is the case.

`Uncaught (in promise) DOMException: The object could not be cloned.`

<img width="378" alt="image" src="https://user-images.githubusercontent.com/2080025/84883848-f3c47200-b088-11ea-9bff-8faaab1b5d64.png">

My component:
```
<script>
import VueCharts from "vue-chartjs";
import { HorizontalBar, mixins } from "vue-chartjs";
const { reactiveProp } = mixins;
export default {
    extends: HorizontalBar,
    mixins: [reactiveProp],
    props: {
        height: Number,
        chartData: Object,
    },
    mounted() {
        // Overwriting base render method with actual data.
        this.renderChart(this.chartData, {
            responsive: true,
            maintainAspectRatio: false,
        });
    },
};
</script>
```

**Comment by apertureless** [comment]
If you import with `import { HorizontalBar, mixins } from "vue-chartjs";` You don't need to import `import VueCharts from "vue-chartjs";`.

Also not sure why you have a `height` as a prop. 
You also do not need to define `chartData` as a prop. This will be automatically defined by the mixin.

And you should define a `options` object for the chart options. Because the watcher will sometimes depending on the changes, re-render the chart and call

```js
this.renderChart(this.chartData, this.options)
```

After cleanup:

```js
<script>
import { HorizontalBar, mixins } from "vue-chartjs";
const { reactiveProp } = mixins;
export default {
    extends: HorizontalBar,
    mixins: [reactiveProp],
    data: () => ({
     options: { responsive: true, maintainAspectRatio: false }
    }),
 
    mounted() {
        // Overwriting base render method with actual data.
        this.renderChart(this.chartData, this.options);
    },
};
</script>
```

You also should maybe post the parent component. 99% of the time the error is in the parent component and not the chart component itself :)

**Comment by raisonon** [comment]
Thanks for the help @apertureless - just implemented and code cleaner now. Really helpful

However, still get the same error...

Doesn't seem connected to error, but I'm passing height prop in as otherwise I was unable to get the chart element to fill the height of parent div... 

My parent component as you suggested. Appreciate any feedback:

```
<template>
    <div>
        <snapshot-bar-chart
            :height="300"
            class="relative h-50"
            :chartData="chartDataBar"
        ></snapshot-bar-chart>
    </div>
</template>

<script>
export default {
    layout: require("@/layouts/dashboard").default,
    props: {
        user: Object,
        group: Object,
        groupshot: Object,
        chartDataBar: Object,
        chartDataDo: Object,
    },
    methods: {
        updateSelectedGroupshot(event) {
            this.$inertia.replace(this.$route("group.show", this.group.id), {
                data: { groupshotId: event.target.value },
            });
        },
    },
};
</script>
```

**Comment by apertureless** [comment]
You do not need to define the height prop, it is already defined. https://vue-chartjs.org/api/#props

Well, the parent component does not help either. Need to go deeper :D 

You could try to remove the reactive mixin and see if it works then.
Might be an issue how you're passing the data or the lack of default data for the props.

If you are getting your data from an API you also need to make sure, the chart gets initially only rendered after your data is present. 

https://vue-chartjs.org/guide/#chart-with-api-data

However, a small reproduction (jsfiddle/codesandbox) would be nice. Your code looks okay so far.

**Comment by raisonon** [comment]
Thanks for the pointer @apertureless -- I'm using this inertiajs.com and it seems that it is to do with the XHR request arriving after the component is loaded. I'm not sure solution yet, but suspect it is to be found in triggering a loaded state change once XHR received from inertia...
