### ISSUE TITLE
Change legend position

### ISSUE THREAD

**Issue by techerudite-kashyap** [apertureless/vue-chartjs#629]
### Expected Behavior
Currently there is no option to change the legend position.

### Actual Behavior
There should be an option to change legend position.

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <6.14.4>

**Comment by apertureless** [comment]
https://www.chartjs.org/docs/latest/configuration/legend.html

**Comment by techerudite-kashyap** [comment]
> https://www.chartjs.org/docs/latest/configuration/legend.html

I tried that, does not seem to be working.

**Comment by consciousnessdev** [comment]
I has changed to this options:
```
options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: true,
            position: top,
            align: 'start',
          }
        }
      },
```
but still not changed position @apertureless
