### ISSUE TITLE
Options not updated when Data & options change

### ISSUE THREAD

**Issue by AurelienMendes** [apertureless/vue-chartjs#636]
Hey,

I use VueJs 2 with VueX, VueRouter.

I write a component 
```javascript
<script>
import { Radar, mixins } from 'vue-chartjs'
const { reactiveProp } = mixins
import zoom from 'chartjs-plugin-zoom'

export default {
  extends: Radar,
  mixins: [reactiveProp],
  props: {
    employee: {
      type: Object,
      default: () => {}
    },
    chartData: {
      type: Object,
      default: null
    },
    options: {
      type: Object,
      default: null
    }
  },
  mounted () {
    this.addPlugin(zoom);
    this.renderChart(this.chartData, this.options)
  },
}
</script>
```

and in a Parent component I use it like this :
```javascript
...
              <vs-col
                v-for="chart in multipleCharts"
                :id="`chart-job-${chart.job.id}`"
                :key="`chart-job-${chart.job.id}`"
                vs-justify="center"
                vs-align="center"
                vs-w="6"
                class="mt-6"
              >
                <rating-chart
                  :employee="employee"
                  class="rating"
                  :options="chart.options"
                  :chartData="chart.data"
                />
              </vs-col>
...
import RatingChart from '@/components/RatingChart'
import { mapGetters, mapState } from 'vuex'
import Multiselect from 'vue-multiselect'
import ratingChartsHelper from '@/mixins/ratingChartsHelper'
import hexToRgba from 'hex-to-rgba'

const randomColor = require('randomcolor')

export default {
  components: {
    Multiselect,
    RatingChart
  },

  computed: {
    multipleCharts() {
       const charts = []
       this.jobs.forEach(job => {
         charts.push({
           data:job.data,
           options:job.options,
         })
       })
    },
  },
```

This way, I create multiple charts on the same page.

When I load the load the page the first time all data /options (charts' titles) are OK. 
But when I go to a page which updates the VueX store data and then, back to my charts page, the charts data is OK, but the charts' options are not updated. Indeed, since my options change, I would expect to see the charts' titles change also but that's not the case (old/previous titles are displayed).

Do you understand why ? Is it the right way to do multiple charts within the same component ?
With some console.log(), when I back to the charts page, it seems that _multipleCharts_ is modified after the RatingChart component is mounted ... if it's true, how can I manage that since I have multiple charts not defined on local props ?

Thanks

**Comment by apertureless** [comment]
https://vue-chartjs.org/guide/#options

The `options` object is not reactive inside chart.js. 
You might want to add your own watcher on the `options` and then call `update()` on the chart instance.
