### ISSUE TITLE
📝 Translate documentation

### ISSUE THREAD

**Issue by apertureless** [apertureless/vue-chartjs#64]
Would need some help with the translation of the docs.
I will soon translate it into german. However I think chinese would be also great, as there is a big vue community there.

Simply check out [docute](https://github.com/egoist/docute) and submit a PR ;)
And please pick the right README in the `/docs` folder

## Lanuages

- [ ] German
- [x] Chinese
- [x] Japanese
- [x] Indonesian
- [x] Brazilian Portuguese
- [x] Russian
- [x] French
- [ ] ???

**Comment by cdubant** [comment]
@apertureless French?

**Comment by apertureless** [comment]
@cdubant sure, why not :)

**Comment by Pokom** [comment]
Are you accepting any help with fixing grammatical issues within the English documentation? I just started using the project(I've used ChartJS quite a bit), and have noticed a few sections that could use some updates to be a bit clearer.

**Comment by apertureless** [comment]
Sure! Feel free so submit a PR :)

**Comment by euledge** [comment]
@apertureless  Hi I'll challenge translate to Japanese.

There are places where can not  understand, so please explain.

Explanation of Different Builds#Webpack 2

``` markdown
This way you three shaking will work.
```

**Comment by apertureless** [comment]
Ups, got a typo there. 
I meant "This way your [tree shaking](https://webpack.js.org/guides/tree-shaking/) will work."

Tree shaking is implemented in webpack 2 and rollup and remove unused es6 modules from your build

**Comment by kimuraz** [comment]
Translate Readme into brazilian portuguese.
https://github.com/apertureless/vue-chartjs/pull/110

**Comment by apertureless** [comment]
Awesome @kimuraz ! Thanks a lot!

**Comment by tesarwijaya** [comment]
hello @apertureless i can help translating to indonesian.

**Comment by apertureless** [comment]
@tesarwijaya cool! that would be awesome!

**Comment by tesarwijaya** [comment]
working on progress.

**Comment by dhelic98** [comment]
@apertureless Hello, I would like to translate it to Bosnian since there are some developer from my country who are not really comfortable with English language

**Comment by apertureless** [comment]
@dhelic98 sure!

**Comment by sasalx** [comment]
@apertureless I can help with Turkish translation.

**Comment by huangche007** [comment]
@apertureless I can help with Chinese translation

**Comment by apertureless** [comment]
@sasalx 
Cool! Go ahead :)

@huangche007 
Thanks! But there is already an chinese one http://vue-chartjs.org/#/zh-cn/
