### ISSUE TITLE
Multiple charts on one page

### ISSUE THREAD

**Issue by SelfhostedPro** [apertureless/vue-chartjs#641]
### Expected Behavior
Interacting with a chart will only affect that specific chart

### Actual Behavior
Interacting with a chart affects all charts on a page

![yacht-chart-filtering](https://user-images.githubusercontent.com/66331933/93653754-286d0000-f9cf-11ea-82b1-c0571819106f.gif)

### Environment
- vue.js version: vue@2.6.11
- vue-chart.js version: vue-chartjs@3.5.0
- chart.js version: chart.js@2.9.3
- npm version: 6.14.7
  
Here is the code for my chart component:
```
<script>
import { mixins, Bar } from "vue-chartjs"; // We specify what type of chart we want from vue-chartjs and the mixins module
const { reactiveProp } = mixins;
export default {
  extends: Bar, //We are extending the base chart class as mentioned above
  mixins: [reactiveProp],
  props: {
    chartdata: {
      type: Object,
      default: null,
    },
  },
  data() {
    return {
      options: {
        responsive: true,
        animation: {
          duration: 0,
        },
        scales: {
          yAxes: [
            {
              ticks: {
                beginAtZero: true,
                stepSize: 1,
                min: 0,
                max: 100,
                maxTicksLimit: 5
              },
            },
          ],
        },
      },
    };
  },
 mounted() {
    this.renderChart(this.chartData, this.options);
  },
};
</script>
```
Here is the code for the page I'm rendering them on:
https://github.com/SelfhostedPro/Yacht/blob/master/frontend/src/views/Home.vue
(I would paste it but it's quite long)

**Comment by SelfhostedPro** [comment]
Just wanted to ping you guys about this as it's still occurring though now at leas it filters all of them for the same thing.

**Comment by apertureless** [comment]
Well, its hard to reproduce. 
Multiple charts can be controlled tho: https://codesandbox.io/s/boring-thompson-ddl5g?file=/src/App.vue

**Comment by SelfhostedPro** [comment]
Hmmm. I have the same settings you do for the chart (separate id and data) but still no luck. Any ideas as far as troubleshooting goes?

**Comment by croftman** [comment]
Did you try to add a unique ID on the chart? You can use the chartId prop, by default multiple charts on the same page have same id

**Comment by jTiKey** [comment]
@apertureless your example basically shows that both charts have the same values (while they should have different)
@croftman didn't help.

**Comment by SelfhostedPro** [comment]
> Did you try to add a unique ID on the chart? You can use the chartId prop, by default multiple charts on the same page have same id

I believe this was the solution. (Sorry, it’s been a while since I resolved the issue)
