### ISSUE TITLE
Pie Chart Color

### ISSUE THREAD

**Issue by Kamran95** [apertureless/vue-chartjs#650]
### Expected Behavior

Each pie should have different color
### Actual Behavior

All Pie in Pie chart have same color

### In Component

```
<script>
import { Pie } from 'vue-chartjs'

export default {
  extends: Pie,
  props: ['chartdata', 'options'],
  mounted () {
    this.renderChart(this.chartdata, this.options)
  }
}
</script>
```
  
## Data Passed
```
   chartdata: {
      labels: ['January', 'February'],
      datasets: [
        {
          label: 'Data One',
          backgroundColor: '#f87979',
          data: [40, 20]
        }
      ]
    },
    options: {
      
      responsive: true,
      maintainAspectRatio: false
    }
    };

```

**Comment by apertureless** [comment]
https://www.chartjs.org/docs/latest/


Just check out the docs man.

You are passing *1* backgroundColor to your chart and expect that it has different colors? 

Either dont pass any colors to the chart or pass enough colors to fill all your different pie pieces.

**Comment by rmad17** [comment]
I am passing an array and yet it picks the same color.
