### ISSUE TITLE
Broken when upgrade chart.js from 2.9.3 to 2.9.4

### ISSUE THREAD

**Issue by BangNguyen1992** [apertureless/vue-chartjs#657]
### Actual Behavior
After I upgrade chart.js to 2.9.4, some configs in the tick option don't work anymore, it seems to get overwritten by chartjs options

For example:
```
ticks: {
    callback: (value, index, values) => `£ ${value}`,
},
```
return the value only, it doesnt include the £.

### Environment
- vue.js version: 2.6.12
- vue-chart.js version: 3.5.1
- chart.js version: 2.9.4
- npm version: 6.12.1

**Comment by apertureless** [comment]
Well the options get just passed to chart.js
Have you checked if the callback maybe changed in that chart.js version?

Not much I can do here.

**Comment by simonbrunel** [comment]
@apertureless FYI, I just found out that https://github.com/chartjs/Chart.js/pull/7918 introduced a breaking change for reactive chart config or config containing reactive objects. Once merged, reactive objects are not anymore enumerable  thus can't be iterated (`Object.keys()` returning an empty array). This can break some Vue.js integrations, such as the datalabels plugin Vuepress docs.
