### ISSUE TITLE
How to use without babel/webpack?

### ISSUE THREAD

**Issue by jlippold** [apertureless/vue-chartjs#66]
So I'm running vue without compilation, no webpack babel browserify etc.
Is there a way to include this as a plain old `<script src=''>` tag?

Thanks!

**Comment by apertureless** [comment]
Mh I guess you can use it over `unpkg`. 
The bundled dist file, should include everything you need. However, I've never tested it 🙈 

https://unpkg.com/vue-chartjs/dist/vue-chartjs.js

**Comment by jlippold** [comment]
Nahh I can't get that to work. I think its needs a shim or something.

**Comment by apertureless** [comment]
Ok, will take a look and see if I can change the webpack conf to generate a browser valid build.

**Comment by apertureless** [comment]
It should work now ! ;)

Have fun! 🚀

**Comment by jlippold** [comment]
Hey @apertureless thanks for this, I assume I just src="https://unpkg.com/vue-chartjs@2.5.3/dist/vue-chartjs.js" and I'm good?

**Comment by apertureless** [comment]
Yep, there is also a minified version:

`https://unpkg.com/vue-chartjs@2.5.3/dist/vue-chartjs.min.js`

**Comment by jlippold** [comment]
sweet 🥇
