### ISSUE TITLE
any plan to support vue3

### ISSUE THREAD

**Issue by EslamNemr** [apertureless/vue-chartjs#661]
### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Yes. Plans are there. https://github.com/apertureless/vue-chartjs/issues/637

However, currently I don't have any time. As soon as I find some time I will work in chartjs v3 support and vue 3 support.

**Comment by bci24** [comment]
any updates ? :)
