### ISSUE TITLE
Passing an option as a prop for a plugin

### ISSUE THREAD

**Issue by ruimgbarros** [apertureless/vue-chartjs#663]
Hi everyone,

I'm sorry for opening an issue for something that probabily is something that I'm doing wrong, but I'm completly lost.
I need my line chart to have a different colour everytime it passes a value in Y. I've found [this plugin](https://github.com/bbc/Chart.Bands.js) that does the job. But I'm having some issues when trying to use my options prop.

If I create a var with the values for that plug in it seams to work. Example:

`
 export default {
  extends: Line,
  mixins: [mixins.reactiveProp],
  props: ["chartData", "options"],
  mounted() {
    this.addPlugin(bands);

    var options = {
      bands: [
        {
          from: 0,
          to: 100,
          yValue: 10,
          color: "blue",
          backgroundColor: "rgba(255, 99, 71, 0.6)",
        },
      ],
    };

    this.renderChart(this.chartData, options);
  },
};

`

But if the same exact data is delivered using a prop, I get the following warning on my console:

`ConfigError: The Chart.Bands.js plugin config requires a yValue`

I'm not really sure why... Shouldn't be the same?

**Comment by apertureless** [comment]
https://vue-chartjs.org/guide/#options

The options are not reactive. And the mixins sometimes has to do a full re-render. Thus it is calling `this.renderChart(this.chartData, this.options)` However your options are only a local variable and `this.options` is in your case undefined.

Just move the options into your data() functions and it should be fine.
