### ISSUE TITLE
Suppress events from reactiveProp and reactiveData

### ISSUE THREAD

**Issue by maxh-** [apertureless/vue-chartjs#665]
I have a couple of reactive charts mounted which use the reactiveProp mixin. The consequence is that when I edit a value which triggers a chart update, my event log looks something like this:

![image](https://user-images.githubusercontent.com/5717121/99660436-aba7e200-2a62-11eb-8a17-e1b03bca2574.png)

I'm not interested in those events and it makes debugging harder, so an option to suppress them would be great. If it should be implemented I could try my hand at a PR?

**Comment by jwloqwe** [comment]
Hi, is the issue above solved yet? because I am also having the same problem

**Comment by apertureless** [comment]
It is not considered an issue.
