### ISSUE TITLE
Cannot get annotation plugin to work.

### ISSUE THREAD

**Issue by dankell** [apertureless/vue-chartjs#666]
I am trying to get the chartjs-plugin-annotation working in my test project [here](https://codesandbox.io/s/throbbing-grass-z4zsr?file=/src/components/BarChart.vue)

Here is my Barchart.vue file, which is how I understand the plugin should be registered
```
<script>
import { Bar, mixins } from "vue-chartjs";
import chartJsPluginAnnotation from "chartjs-plugin-annotation";
const { reactiveProp } = mixins;

export default {
  extends: Bar,
  mixins: [reactiveProp],
  props: ["chartData", "options"],
  mounted() {
    this.addPlugin(chartJsPluginAnnotation);
    this.renderChart(this.chartData, this.options);
  },
};
</script>
```
This is the template for the parent component:
```
<template>
  <div class="small">
    <button @click="fillData()">Randomize</button>
    <bar-chart
      v-if="loaded"
      :chart-data="chartData"
      :options="chartOptions"
    />
  </div>
</template>
```
And this options from the `data()` section of the same component
```
data () {
    return {
      chartOptions: {
        responsive: true,
        tooltips: {
          mode: 'index',
          intersect: true
        },
        scales: {
          xAxes: [{
            id: 'time-axis',
            type: 'time',
            stacked: true,
            offset: true,
            time: {
              unit: 'week',
              tooltipFormat: 'll',
              unitStepSize: 1
            },
            scaleLabel: {
              display: true,
              labelString: 'Date'
            }
          }],
          yAxes: [{
            stacked: true
          }]
        },
        annotation: {
          drawTime: 'afterDatasetsDraw',
          annotations: [{
            id: 'vline',
            type: 'line',
            mode: 'vertical',
            scaleID: 'x-axis-0',
            value: '2020-09-05',
            borderColor: 'black',
            borderWidth: 5,
            label: {
              backgroundColor: 'red',
              content: 'Test Label',
              enabled: true
            }
          }]
        }
      },
      chartData: null
    }
  },
```

The data renders correctly and redraws on the "randomize" button as I need it to, however the annotation is not drawn.

Ideally I need the annotations to be re-rendered when the data is randomized, hence the "setAnnotation" commented out on line 115, but at the moment I'm not getting a static line at all.

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 3.5.1
- chart.js version: 2.9.4
- npm version: 6.14.8

**Comment by apertureless** [comment]
Your problem seems to be with your annotation configuration.
If I copy the config from the official codepen: https://codepen.io/compwright/full/mmQMrZ/

It works.
https://codesandbox.io/s/happy-brook-34hi8?file=/src/components/BarChart.vue:52-87

**Comment by dankell** [comment]
Thanks for the help. This is getting weird... I can see where my mistake was on the previous sandbox and have got this sandbox working as I want (with the static line, not rendered each time).

I downloaded the code from the sandbox and tried to run it on my local setup and no annotations.

I've downgraded from node 14 to node 12 to see if that is the difference, with no change.

Local setup is Node 12.20 (was 14.15.1), Webstorm 2020.2.4, Windows 10 1909.

The thing is I came to vue-chartjs as I was having problems with using annotations natively...

**Comment by dankell** [comment]
@apertureless I've been looking and looking and cannot work out what is happening. The code on codesandbox shows the annotation that I would expect.

However as soon as I run it locally (either Webstorm on Windows or MS Code on Mac OS) the annotation disappears.

I've created a repo of my project to see if anyone can spot what's going wrong

https://github.com/dankell/vue-chart-js

**Comment by apertureless** [comment]
Well, sorry but I can't give you any support on third party plugins.

> The thing is I came to vue-chartjs as I was having problems with using annotations natively...

Well, vue-chartjs is only a wrapper around chart.js and adds some boilerplate setup. 
So if you have problems getting the plugin to work with chart.js, then using vue-chartjs won't solve the problem.

**Comment by RanoKim** [comment]
@dankell 
https://stackoverflow.com/questions/64878459/annotation-dont-show-in-vue-chartjs/65769130#65769130
Hope it helps you.

**Comment by dankell** [comment]
@RanoKim I can confirm that reverting ChartJS back to version 2.9.3 solves the issue.

**Comment by apertureless** [comment]
You may want to report this in the anootation plugin repo, as it seems to be a chart.js compatibility issue.

**Comment by dankell** [comment]
Will do. Also trying to see whether I can identify what changed to cause the break.

**Comment by 8infiniteuniverse** [comment]
myChart.value.$.ctx
myChart.value.$.exposed.chart
