### ISSUE TITLE
Add angle labels around polar chart in vue-chartjs

### ISSUE THREAD

**Issue by dtnguyn** [apertureless/vue-chartjs#667]
I was looking around to find a way to add the label for the angles around polar chart (like 0, 45, 90, ... 360) but I couldn't find a way to do that. I just wonder if this feature is supported in vue-chartjs?

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
`vue-chartjs` is only a wrapper for [Chart.js](https://github.com/chartjs/Chart.js). Thus we only have the features the core chart.js has.

IMO this is not natively supported. But as Chartjs is working with a canvas object (you have access to it in vue-chartjs over this.$refs.canvas) you can extend it and build this functionallity.

I would recommend to check out the Chart.js repo / issues. Maybe someone already did it and can give you a starting point or maybe there is even a chart.js plugin for it.
