### ISSUE TITLE
How to use plugins?

### ISSUE THREAD

**Issue by Torone** [apertureless/vue-chartjs#668]
### Expected Behavior
By looking at the documentation I cannot find a way to use plugins: https://www.chartjs.org/docs/latest/developers/plugins.html

How can I use the feature?

### Actual Behavior
There is not way to use it... Or at least I don't know how...

Thanks

**Comment by apertureless** [comment]
You can use either the [addPLugin()](https://vue-chartjs.org/api/#addplugin) method or the [plugins](https://vue-chartjs.org/api/#props) prop.

However, some chart.js plugins register themself globally on import. Then you don't need to do anything.

**Comment by Torone** [comment]
Awesome! I got it and managed to do it! Thanks for the hint @apertureless !
