### ISSUE TITLE
Updating datasets

### ISSUE THREAD

**Issue by Zenthae** [apertureless/vue-chartjs#669]
Do i have to recreate the whole data object each time i want to update the data of datasets ? like when using filter + filtered data, can't i just tell the chart to update each time a computed property for the filter is updated ?

**Comment by Zenthae** [comment]
closing since no news, and switching to billboard.js, so not relevant anymore

**Comment by apertureless** [comment]
Don't really get your question.
You can use the mixins if you need reactivity and they will re-render the chart if your data object changes.

https://vue-chartjs.org/guide/#updating-charts

Or you can add your own watcher to your dataset and call the update / re-render your chart.
