### ISSUE TITLE
Provide Screenshots of Charts

### ISSUE THREAD

**Issue by radiantone** [apertureless/vue-chartjs#670]
### Expected Behavior
- Actually to see the charts

### Actual Behavior
- Not a single visible chart on the docs website. What do they look like?

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
https://github.com/apertureless/vue-chartjs#available-charts

**Comment by radiantone** [comment]
Ok, but nothing on this site, which is where most of the interest lay
https://vue-chartjs.org/guide/

thanks
