### ISSUE TITLE
[Help] hide yaxis when click Legend

### ISSUE THREAD

**Issue by augustine-lin** [apertureless/vue-chartjs#672]
How could I do this in the vue-chartjs ?

https://stackoverflow.com/questions/40006970/hide-y-axis-labels-when-data-is-not-displayed-in-chart-js

**Comment by apertureless** [comment]
Pretty much the same way?

You can add callback functions to the options in vue-chartjs, too.

**Comment by augustine-lin** [comment]
@apertureless Maybe I just use wrong way.  It just won't work.
How to make the defaultLegendClickHandler and toggleYaxis  work ?
Please, can you give me some help ?

https://codesandbox.io/s/v-chartjs-hide-yaxis-6o8ko?file=/src/App.vue

**Comment by lennaht** [comment]
This worked for me:
```js
legend: {
    onClick: function(e, legendItem) {
        const { datasetIndex } = legendItem;

        this.chart.data.datasets[datasetIndex].hidden = !this.chart.data.datasets[datasetIndex].hidden;
        this.chart.options.scales.yAxes[datasetIndex].display = !this.chart.options.scales.yAxes[datasetIndex].display;
                            
        this.chart.update();
    }
}
```
Put it into the options object.

**Comment by augustine-lin** [comment]
@lennaht thank you it work!
