### ISSUE TITLE
removePlugin method

### ISSUE THREAD

**Issue by gauravmak** [apertureless/vue-chartjs#675]
Hey,

I couldn't find `removePlugin()` method. Open to add that to the package?

Our use case: When the user wants to print the chart, we add the `chartjs-plugin-datalabels` plugin to display labels of the pie chart and rerender it. After the print, we wish to remove the plugin and rerender it again.

**Comment by antoinebeneteau** [comment]
Up

**Comment by apertureless** [comment]
Well you could pass the plugin as a prop and then remove it in the parent component.
`plugins` is just an array holding multiple plugins if you pass them and pass it to the chart.js init.

There is no `removePlugin` becuase there would be no way to know which plugin to remove if you have multiple ones.
