### ISSUE TITLE
Chart not updated when reactiveProp chart-data changes

### ISSUE THREAD

**Issue by Rednas83** [apertureless/vue-chartjs#677]
### Expected Behavior
Chart is updated when reactiveProp chart-data changes

### Actual Code/Behavior
![image](https://user-images.githubusercontent.com/25219229/103923501-78560b00-5115-11eb-9e0d-4ea90169d59a.png)

### Environment
- nuxt: "^2.14.12",
- vue: 2.6.11
- @vue/cli 4.3.1
- vue-chartjs: "^3.5.1"
- chart.js: "^2.9.4"
- yarn: 1.23.0-20210103.1434 (yarn2 will be supported with nuxt3)

**Comment by Rednas83** [comment]
@apertureless Any idea what I am doing wrong? 

Can you perhaps create a codepen with a working example?

**Comment by thieums** [comment]
Hello, i'm experiencing the same issue.
Could not update the charts (with mixin or prop/watch) when chartdata is updated.
The only way to force a re render is to change the browser size.
        "admin-lte": "^3.0.5",
        "chart.js": "^2.9.4",
        "popper.js": "^1.16.1",
        "sweetalert": "^2.1.2",
        "vue": "^2.6.11",
        "vue-chartjs": "^3.5.1",
        "vue-sweetalert2": "^3.0.5",
        "vuelidate": "^0.7.6",
        "vuex": "^3.6.2"
Documentation is not very clear as "mutation" is recommanded over "data push".
In my mind mutation = vuex.
Thank you.

**Comment by matiasfanger** [comment]
Did you fixed it? Im having exactly the same issue. I think the problem is nuxt but idk.

You can put a v-if in the chart component and when you update the chart data u can do something like this:
```js
this.chartRender = false
setTimeout(() => this.chartRender= true, 0);
```

**Comment by Rednas83** [comment]
To re-render your chart you can also update the key when the data changes. This is of course just a workaround.

Something like:
```
<template>
  <div>
    <chartjs :chart-data="data" class="a-5 h-4/5 w-4/5" :key="updated" />
    <button @click="addData(10)">AddData</button>
  </div>
</template>

<script>
import chartjs from "../components/vue-formulate/chartjs.vue"
export default {
  components: { chartjs },
  methods: {
    addData(iValue) {
      this.data.datasets[0].data.push(iValue)
      this.data.labels.push(iValue)
      this.updated++
    },
  },
  data() {
    return {
      updated: 0,
      data: {
        labels: ["January", "February"],
        datasets: [
          {
            label: "Data One",
            backgroundColor: "#f87979",
            data: [40, 20],
          },
        ],
      },
    }
  },
}
</script>
```

**Comment by digitalkaoz** [comment]
@Rednas83 thanks that worked, but this avoids the smooth transition between the different data sets...i dont know why this doesnt work?

`this.$refs.canvas.$data._chart.update()`

where the `canvas` ref is on the `vue-chartjs-component`

**Comment by eriksvedenlund** [comment]
Using key remounts the chart and calls renderChart each time. So it's essentially creating a new chart each time instead of updating it. That's why you don't see a smooth transition
@apertureless Is there an actual solution to this problem or is this workaround really the best solution?

**Comment by nickbien** [comment]
Thanks @Rednas83 !! worked for me!

**Comment by Rednas83** [comment]
For vue3/typescript users you can also consider 
https://github.com/J-T-McC/vue3-chartjs
