### ISSUE TITLE
Bar Chart Not Appear when its value is so low

### ISSUE THREAD

**Issue by HuongSakada** [apertureless/vue-chartjs#680]
### Expected Behavior
I want to show any indicator or the value for the user to view or to hover(show the tooltip) when the value of the chart is so low compare to others.

Example:
```javascript
datasets: [
  {
     backgroundColor: ['red', 'green'],
     data: [345678909765456787654345676567, 40]
  }
]
```

So from this example, I can see the green chart and I can hover to see the tooltip.

### Actual Behavior
For now, I can even see the chart or do the hover to see the tooltip.

Do we have any solution for it?

### Environment
- vue.js version: `2.6.11`
- vue-chart.js version: `3.5.1`
- chart.js version: `2.9.0`
- npm version: `6.14.5`

**Comment by mathiash98** [comment]
I would guess this is best fit for the https://github.com/chartjs/Chart.js repository or stackoverflow. Vue-chartjs is just a wrapper for the chartjs.
And please produce a working sample in https://codesandbox.io/s with the same packages displaying the issue.

**Comment by apertureless** [comment]
Well, sure. If you want to show actual numbers with a linear scale / axis, and have to number where one is extermly huge and one very small, this cant work. If you generate `%` out of the numbers to calucalte the height of bars, at some point the samll number will go against 0 (0.00000000000x) however, we have only full pixels to display.

What you can try out is a logarithmic scale / axis. This should solve your problem.
 (https://www.chartjs.org/docs/master/axes/cartesian/logarithmic/)
