### ISSUE TITLE
Fails to update correctly with annotate plugin

### ISSUE THREAD

**Issue by glennpierce** [apertureless/vue-chartjs#682]
I am using the ChartAnnotation plugin but I am having trouble with it displaying when the chart data or options are updated.

My test case is available at

https://github.com/glennpierce/vue-chartjs-test

I installed the plugin like

```
export default {
  extends: Bar,
  mixins: [reactiveProp],
  plugins: [ChartAnnotation],
  props: ["chartData", "options"],
  mounted() {
    this.renderChart(this.chartData, this.options);
  },
};
```
When the data re renders I would expect the annotation to rerender.

### Actual Behavior

The graph displays fine with the annotation (a strait horizontal line) when the data and options are first set.
However,if I modify the data or options to something else the annotation is remove and does not show again.

For example 
In the mounted function of my App I do

this.data = this.data2;
this.title = 'test2';

The graph re renders but the annotation line disappears even though it is still present in the options passed.

The annotation is set to draw after the data. Ie set to afterDatasetsDraw

I am guessing this is a issue with vue-chartjs rather than the annotation plugin.

Thanks

### Environment
vue": "^2.6.11",
"vue-chartjs": "^3.5.1",
"chart.js": "^2.9.4",
"chartjs-plugin-annotation": "^0.5.7",

**Comment by apertureless** [comment]
```
plugins: [ChartAnnotation],
```

I don't think this will have any effect. There is no custom plugin attribute in your component root instance.

You can either use the [plugins](https://vue-chartjs.org/api/#props) prop or the [addPlugin](https://vue-chartjs.org/api/#addplugin) method. However some chartjs plugins register themself globally on import.

**Comment by glennpierce** [comment]
I have tried the plugins prop as well but don't think that's it because the annotation does seem to load. 
It is only when I retouch the data or options that the annotation gets removed so I know the plugin is loaded.

Could it be  that the ChartOptions interface does not include an annotations field ?
I am not 100% of how vue reactive stuff works :)

**Comment by glennpierce** [comment]
Actually maybe it is due to the fact I can't change options.

For example If I have the following.

Why is it when I do
` this.data = this.data2; `
in mounted the graph updates.
However,  `this.title = 'test2' `which is referenced in chartOptions() does not update the title.

I though options should be reactive as well ? 

```
<template>
  <v-app>
    <v-main>
      <v-card width="800">
        <InternalBarChart plugins="ChartAnnotation"
          :chart-data="chartData()"
          :options="chartOptions()"
        />
      </v-card>
    </v-main>
  </v-app>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import InternalBarChart from '@/components/InternalBarChart.js';

export interface IDataPoint {
  x: any;
  y: number;
}

@Component({
  components: {InternalBarChart},
})
export default class App extends Vue {
  private data: object[] = [{ x: 0, y: 1 }, { x: 1, y: 0 }, { x: 2, y: 2 }, { x: 3, y: 2.5 }];
  private data2: object[] = [{ x: 0, y: 1 }, { x: 1, y: 0.4 }, { x: 2, y: 0.1 }, { x: 3, y: 0.6 }];
  private title = 'test1';

  public mounted() {
    this.data = this.data2;
    this.title = 'test2';
  }

  private chartOptions(): object {
    const self = this;
    return {
      title: {
        display: true,
        text: self.title,
      },
      display: true,
      responsive: false,
    };
  }

  private chartData(): object {
    const self = this;
    const datasets = [];

    datasets.push({
      label: 'Testing',
      data: self.data,
      fill: false,
      borderWidth: 1,
    });

    return {
      datasets: datasets,
    };
  }
}
</script>

<style lang="less">

</style>

```

**Comment by apertureless** [comment]
No, the chart options are not reactive.

https://vue-chartjs.org/guide/#troubleshooting
