### ISSUE TITLE
Chart fails to show inside a Vuetify v-dialog UI component

### ISSUE THREAD

**Issue by sinjiya** [apertureless/vue-chartjs#687]
When importing a Vue-chart  as a component to show inside  a Vuetify Dialog UI component, the vue-chart won't show.

### Environment
- vue.js version: @vue/cli 4.4.6
- vue-chart.js version: 3
- chart.js version: v2.9.4
- npm version: 6.14.5
- Vuetify version:  v2.3.10

**Comment by tobinstultiens** [comment]
Have you attempted setting responsive to false since this resolved it for me.
Another way to resolve this is by passing a styling in which you set the height by adding this you can ignore the responsive setting.
![image](https://user-images.githubusercontent.com/22025068/109501490-f1c80500-7a97-11eb-8b10-471f9b64616c.png)

**Comment by apertureless** [comment]
The canvas element that chart.js is using, is not responsive. Thus if you are using v-show the component will be mounted, but its height will be 0, becuase of the display: none.

If you're using v-if the component will be unmounted / mounted. Thus if it is mounted it will have a proper height.

I guess the dialog is always mounted and just "showing" its content. Thus it will be initially a height of 0.

You can rework it, so the component is properly unmounted or pass additional styling (fix height).

**Comment by sinjiya** [comment]
Thanks.  Set  **responsive: true**  works for me. Since my chart data is dynamically queried. I need to add a  **watch** and a **method**,
otherwise,  my barchart component with an id prop **&lt;Barchart :id="rpt.id" /&gt;** won't  respond to different rpt.id. 

```
methods: {
      getChartData(id){
        axios.get('getChartData.php?id='+ id)
          .then( r => {
            this.chartData.labels = r.data.labels;
            this.chartData.datasets[0].data = r.data.Series1;
            this.chartData.datasets[1].data = r.data.Series2;
            this.renderChart(this.chartData, this.options)
          })
      }
    },
mounted() {
      this.getChartData(this.id);
    },
watch:{
    id(id){  
          this.getChartData(id);  
    }

}
```
