### ISSUE TITLE
what browsers it support? Does it supports localization

### ISSUE THREAD

**Issue by rutup** [apertureless/vue-chartjs#692]
### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
@rutup 

This is only a vuejs wrapper for [Chart.js](https://www.chartjs.org/).
So you might want to take a look at their official page.

As you provide most labels yourself, localization should not be a problem I guess.
