### ISSUE TITLE
min max   in ticks

### ISSUE THREAD

**Issue by Xaaalera** [apertureless/vue-chartjs#694]
### Expected Behavior
min max   in ticks must be reactive 

### Actual Behavior
min max   in ticks not reactive 

### Environment
- vue.js version: 2.6
- vue-chart.js version: 3.5.1
- chart.js version: 2.9.4
- npm version: 7.0.8
  

Hello , i have a bug or no... idk.
 i have options 
```js
     chartoptionsSetter(){
            if(!this.dataChart){
                return {};
            }
            let chartOpts = {
                responsive: true,
                maintainAspectRatio: false,
                tooltips: {
                    mode: 'index'
                },
                scales: {
                    yAxes: [
                        {
                        id: 'A',
                        type: 'linear',
                        position: 'left',
                        display: true,
                    }, {
                        id: 'B',
                        type: 'linear',
                        position: 'right',
                        display: true,
                        ticks: {
                            beginAtZero: true,
                            max : Math.round((Math.max.apply(null, this.chartData.datasets[0].data) * 2) / 10) * 10, //ога костылик
                            min : 0,
                            // max: Math.random()
                            // stepSize: 20
                        }
                    }]
                }
            };
            return chartOpts;
```
I use reactive mixins and 2 axes.
 If you do not specify min max in ticks  this fine , but  see how it work:
fine:
![image](https://user-images.githubusercontent.com/10559079/113473782-66fe6f80-9474-11eb-8ab2-fe8a3c751e61.png)

not fine:
![image](https://user-images.githubusercontent.com/10559079/113473794-7bdb0300-9474-11eb-935b-ff0ec67e509e.png)

you can see   max = 10 
but  chart not rerender him, иге if we look at the left side  She re-rendered , because she not have  min-max value.
How i can fix this is problem ? 
Sry for my english.

**Comment by dragoonzx** [comment]
Have same problem

**Comment by dragoonzx** [comment]
But seems duplicating https://github.com/apertureless/vue-chartjs/issues/530
