### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by matystu** [apertureless/vue-chartjs#699]
Hey, do you have in plan to support Vue 3 (along with chart.js 3)? Thanks

**Comment by Gregory-Han** [comment]
Angular & React Chart.js were upgraded v3.2.
Please upgrade for v3.x...
If you will not upgrade plan, answer for it.

**Comment by SirMishaa** [comment]
The support of Vue 3 is becoming more and more important.

It's a bit of a staple, more and more people are migrating to Vue 3 for the performance boost and various new features.

I think it's time to offer official support for Vue 3, especially since people in the community have already started to provide workarounds.

**Comment by meteortears** [comment]
Request support for vue3

**Comment by ajerez** [comment]
+1

**Comment by ellogwen** [comment]
+1

**Comment by craigrileyuk** [comment]
> It's the least what you could do for a library with so many user and contributors. It's a lack of professionalism, some people need this library to works with Vue 3 to update their projects.

No. The least they could do for your entitled self is nothing. You haven't paid for this library, it doesn't look like you've contributed to it in any way, shape or form.

Nobody "owes" you anything simply because you decided to use a free open-source project. Grow up.

**Comment by JakeAtTurner** [comment]
> > It's the least what you could do for a library with so many user and contributors. It's a lack of professionalism, some people need this library to works with Vue 3 to update their projects.
> 
> No. The least they could do for your entitled self is nothing. You haven't paid for this library, it doesn't look like you've contributed to it in any way, shape or form.
> 
> Nobody "owes" you anything simply because you decided to use a free open-source project. Grow up.

I like your reply better!

**Comment by SirMishaa** [comment]
> > It's the least what you could do for a library with so many user and contributors. It's a lack of professionalism, some people need this library to works with Vue 3 to update their projects.
> 
> No. The least they could do for your entitled self is nothing. You haven't paid for this library, it doesn't look like you've contributed to it in any way, shape or form.
> 
> Nobody "owes" you anything simply because you decided to use a free open-source project. Grow up.

In fact, I could do a PR. 

But I won't do a PR for someone that refuse to give clear information about what is going on or who does ask for help.

Just because a project is open source doesn't mean you can't provide information or respond to a little message to inform people. Of course, it's free and it's voluntary work, but I think there is still a certain attitude to have. Which is not the case here unfortunately.

It's sad but with this kind of attitude, I'd rather make a fork or go to an alternative than make a pull request and contribute. 
Best regards.

**Comment by apertureless** [comment]
Well, I've commented already on multiple issues and sticky threads about the current status and situation.
https://github.com/apertureless/vue-chartjs/issues/729  https://github.com/apertureless/vue-chartjs/issues/695  https://github.com/apertureless/vue-chartjs/issues/637 and some others. 

The bottom line is, that I have currently a lot of work and very little free time that I can spend on open source. 
Even tho vue-chartjs have over 100k monthly downloads and is used by a lot of other products / projects, I make 0 $ out of it. So obviously I prioritize my day work. And as I currently not using vue-chartjs in any of my day work projects I can only work in my free time on it.

And there are some big tasks to do like the migration to chartjs 3 and later a vue 3 version. And these changes are not simple one-liners, they require some heavy refactoring and time, which I currently can not spare. 

Even tho, many contributors are listed in the repository you also have to keep in mind that 98% of the contributions here, are based on documentation changes. There were only very little code contributions in the past from other people. Mostly Typescript related things, which I am very happy about.

Currently some very nice people offered help in maintaining and like you see in the commits there is movement. However there are a lot of baseline tasks to be done first, before new features / migrations can take place.

**Comment by SirMishaa** [comment]
Okay, it's already much clearer, thanks for the information.

I'll try to make a pull request if I have some time in a few weeks.

**Comment by thabarbados** [comment]
A new version [4.0.0](https://github.com/apertureless/vue-chartjs/releases/tag/v4.0.0) of vue-chartjs with Vue 3 support is already available on npm.
