### ISSUE TITLE
whene install witch npm show warning

### ISSUE THREAD

**Issue by mohsenmehri6101** [apertureless/vue-chartjs#700]
hi . for install i,m use webpack ( webpack default in laravel version 7 laravel 7) . when i,m install vue-chartJs with npm , i have error : 

           WARNING in ./node_modules/vue-chartjs/es/BaseCharts.js 62:32-37
           "export 'default' (imported as 'Chart') was not found in 'chart.js'
          @ ./node_modules/vue-chartjs/es/index.js
          @ ./resources/npm_/plugins/vuejs/vueManage.js
          @ ./resources/npm_/app.js
          @ multi ./resources/npm_/app.js ./resources/npm_/app.scss

**Comment by kalyncoose** [comment]
I have the same issue running `chart.js:3.2.1` and `vue-chartjs:3.5.1`
```
 warning  in ./node_modules/vue-chartjs/es/BaseCharts.js

"export 'default' (imported as 'Chart') was not found in 'chart.js'
```

**Comment by apertureless** [comment]
Chart.js 3 is currently not supported. You have to use 2.9.4 until next release.
