### ISSUE TITLE
Using vue component as custom tooltip

### ISSUE THREAD

**Issue by dextersiah** [apertureless/vue-chartjs#702]
I was wondering is it possible to render a custom tooltip using a vue component instead of writing it from JS? I'm trying to have a router-link within the custom tooltip which will lead to other pages.

Currently I am testing the custom tooltip from the codes in the docs [here](https://www.chartjs.org/docs/2.9.4/configuration/tooltip.html#external-custom-tooltips)

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 3.5.1
- chart.js version: 2.9.4
- npm version: 6.14.11

**Comment by apertureless** [comment]
Hey, not really sure if this would work. I guess rather not. 
I am not exactly sure how the tooltips work internally, but I guess if you pass in a vue component it maybe will be injected somehow and not properly rendered. 

You could maybe ask this in the official chart.js repo.

**Comment by dextersiah** [comment]
I see.....okay will do thanks
