### ISSUE TITLE
Chart Type declaration conflict.

### ISSUE THREAD

**Issue by katastrofix** [apertureless/vue-chartjs#704]
### Expected Behavior
I am trying to build my application.

### Actual Behavior
I am getting these errors when building my application

>ERROR in C:/dev/projects/work/cloud-app-web/node_modules/vue-chartjs/types/components.d.ts(7,27):
7:27 Cannot find namespace 'Chart'.
    5 | export declare class BaseChart extends Vue {
    6 |   addPlugin (plugin?: object): void
  > 7 |   renderChart (chartData: Chart.ChartData, options?: Chart.ChartOptions): void
      |                           ^
    8 | }
    9 | 
ERROR in C:/dev/projects/work/cloud-app-web/node_modules/vue-chartjs/types/components.d.ts(7,54):
7:54 Cannot find namespace 'Chart'.
    5 | export declare class BaseChart extends Vue {
    6 |   addPlugin (plugin?: object): void
  > 7 |   renderChart (chartData: Chart.ChartData, options?: Chart.ChartOptions): void
      |                                                      ^
    8 | }
    9 | 
ERROR in C:/dev/projects/work/cloud-app-web/node_modules/vue-chartjs/types/mixins.d.ts(5,14):
5:14 Cannot find namespace 'Chart'.
    3 | 
    4 | export declare class ReactiveDataMixin extends Vue {
  > 5 |   chartData: Chart.ChartData;
      |              ^
    6 | }
    7 | 
    8 | export declare class ReactivePropMixin extends Vue {
ERROR in C:/dev/projects/work/cloud-app-web/node_modules/vue-chartjs/types/mixins.d.ts(9,23):
9:23 Cannot find namespace 'Chart'.
     7 | 
     8 | export declare class ReactivePropMixin extends Vue {
  >  9 |   readonly chartData: Chart.ChartData;
       |                       ^
    10 | }
    11 | 

By looking around I saw that when trying to go to the chart.js declaration ,for example, in the mixins.d.ts , there were two declarations
![image](https://user-images.githubusercontent.com/19610831/121780846-d8604a00-cbaa-11eb-89bc-cde8f98ccf7a.png)

When I manually changed the import path from 

`import 'chart.js';`
to
`import '../../@types/chart.js/index';`

everything worked fine, so I think it imports the wrong module.

Could I have done something wrong in my configuration for this conflict to occur?

### Environment
- vue.js version: 2.6.14 
- vue-chart.js version: 3.5.1
- chart.js version: 3.3.2
- types/chart.js 2.9.32
- npm version: 6.13.4

**Comment by victorgarciaesgi** [comment]
vue-chartjs only support Charts.js 2.x version, for 3.x version i advise you to use [vue-chart-3](https://github.com/victorgarciaesgi/vue-chart-3)
