### ISSUE TITLE
Question: how to update plugin text?

### ISSUE THREAD

**Issue by qiquanlu** [apertureless/vue-chartjs#712]
### Expected Behavior
I follow [this stackoverflow ](https://stackoverflow.com/questions/60928670/vue-chartjs-doughnut-chart-with-text-in-the-middle) added center text to doughnut chart.

my center text is calculated from chart data,
I'm expecting center text will be updated when data changes.

### Actual Behavior

I recreated a sample repository to demo my issue, please find [here](https://github.com/qiquanlu/vue-chartjs-nuxt-question)

the doughnut chart changes as I click the update button, however centered text won't get updated.

Please help to point out where I did wrong, thanks

### Environment
- vue.js version: <version 2.6.14 / nuxt.js version 2.15.7>
- vue-chart.js version: <version 3.5.1>
- chart.js version: <version 2.9.4>
- npm version: <version 7.15.1>

**Comment by Ribeiro-Tiago** [comment]
I had the same need some time ago, to update the center text based on which section of the section was hovered. 

I'm not sure if it's the correct way, but the way I got around this was via a plugin that has a default value for the center text that gets updated on hover

I have a js component for donut charts because I use a couple of them, it has a couple things but the necessary ones are these:

My stuff has extra functionality but here's just the basic to get it to work

``` JavaScript
// the plugin
function centerTextPlugin(centerTextFunction) {
  const vm = this

  return {
    id: 'centerText',
    afterDraw: function (chart) {
      const ctx = chart.ctx

      ctx.restore()

      const fontFamily = 'Lato, Helvetica Neue, Arial, sans-serif'
      ctx.font = `18px ${fontFamily}`
      ctx.textBaseline = 'middle'

      const { width, height, chartArea } = chart

      const { key, value, keyColor } = vm.hoverElem
      const labelY = height / 2 - (height - chartArea.bottom)
      let valueOffset = 10

      ctx.fillStyle = getFillStyle(keyColor)

      ctx.fillText(
        value,
        Math.round((width - ctx.measureText(value).width) / 2),
        labelY + valueOffset,
      )

      ctx.save()
    },
  }
}
```


```JavaScript
// donut chart component
import { Doughnut, mixins } from 'vue-chartjs'

export default {
  extends: Doughnut,
  mixins: [mixins.reactiveProp, ChartMixin],
  props: {
    defaultCenterText: { type: Object, default: undefined },
  },
  data() {
    return { hoverElem: this.defaultCenterText }
  },
  computed: {
    // on my case this is computed because it merges the default options i have
    // with possible custom options that can be passed to this component
    chartOptions() {
      const vm = this

      return {
        tooltips: {
          enabled: false,
          custom: function (tooltip) {
            // custom tooltip configs ƒrom https://www.chartjs.org/docs/latest/configuration/tooltip.html#external-custom-tooltips
        
			// values gotten from tooltip / bodyLines variables
            vm.onHover({ key, value, keyColor })
          }
        },  
      },
    },
  },
  watch: {
    defaultCenterText(elem) {
      this.hoverElem = elem
    },
  },
  methods: {
    onHover(payload) {
      this.hoverElem = payload
    },
    onExit() {
      this.hoverElem = this.defaultCenterText
    },
  }
  onMount() {
    this.addPlugin(centerTextPlugin.bind(this)(this.centerTextFunction))
  }
}
```

```JavaScript
// component that uses mixin
<template>
  <donut-chart 
    :chartData="<the chart data object>" 
    :defaultCenterText="{ 
      key: <for me this is a hardcoded string>, 
      value: <whatever variable / value that display in the center text by default>,
      keyColor: <optional string that determines the color of the default value>
    }"
  />
</template

<script>
  import DonutChart from 'path/to/SwDonutChart'
  export default {
    components: { DonutChart },
  }
</script>
```

**Comment by qiquanlu** [comment]
I finally get it behave as I wanted, by deleting all previous plugin, and add new one,  not sure if this is the proper way to do it.

      for (const key in this.plugins) {
        delete this.plugins[key];
      }
