### ISSUE TITLE
can't show the full tooltip in line graph

### ISSUE THREAD

**Issue by amantiwari1** [apertureless/vue-chartjs#713]
### Expected Behavior
show fully tooltip info

### Actual Behavior
can't show the full tooltip image below for example due to the cut in the border
![image](https://user-images.githubusercontent.com/53963065/129487833-3e75d600-3d06-4000-9581-1a038fd88166.png)

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 3.5.0
- chart.js version: 2.9.4
- npm version: 6.14.13

**Comment by kantaphit** [comment]
you need to add padding 

exam:     options: { 
                  layout: {
                     padding: {
                        left: 40,
                        right: 40,
                        top: 40,
                        bottom: 40,
                       },
                  },
               }

more information : https://www.chartjs.org/docs/2.9.4/configuration/layout.html?h=padding
