### ISSUE TITLE
Conditional Rendering Issue

### ISSUE THREAD

**Issue by sell** [apertureless/vue-chartjs#716]
```js
<template v-if="!loaded">
      <line-chart
        :chart-data="[1, 2, 3, 4, 5]"
        :chart-labels="['00-00-0000', '00-00-0000', '00-00-0000', '00-00-0000', '00-00-0000',]"
      />
</template>

<template v-if="loaded">
      <line-chart
        :chart-data="chartData"
        :chart-labels="chartLabels"
      />
</template>
```

### Expected Behavior
Render the first set of placeholder data while loading data then show the other chart with the actualy data after loading.

### Actual Behavior
Doesn't follow the v-else condition, it just keeps the dummy data. 

#### My only work around was by doing
```js
<div>
    <line-chart
       v-if="!loaded"
        :chart-data="[1, 2, 3, 4, 5]"
        :chart-labels="['00-00-0000', '00-00-0000', '00-00-0000', '00-00-0000', '00-00-0000',]"
     />
</div>

<div>
    <line-chart
       v-if="loaded"
        :chart-data="chartData"
        :chart-labels="chartLabels"
    />
</div>
```

### Environment
- vue.js version: 2
- vue-chart.js version: ^3.5.1
- chart.js version: ^2.9.4
- npm version: 7.19.1

**Comment by Ribeiro-Tiago** [comment]
Have you tried having the dummy data in the chartData and chartLabels ? I'm not sure if those are computed props or data, but assuming they're data start initialize them with as
```JavaScript
data(){
  return {
    chartData: [1, 2, 3, 4, 5],
    chatLabels: ['00-00-0000', '00-00-0000', '00-00-0000', '00-00-0000', '00-00-0000']
  }
}
```
which then gets updated where you have the `loaded = true`

and then in your template you could just have 
```html
<div>
  <line-chart 
    :chart-data="chartData"
    :chart-labels="chartLabels"
  />
</div>
```

**Comment by apertureless** [comment]
Guess you need to provide unique ids to the chart. https://vue-chartjs.org/api/#props
Which is the id for the canvas object.

**Comment by sell** [comment]
@Ribeiro-Tiago Not sure, why I didn't think about this at first lol. Although, after attempting to do this it's still not updating and only showing the dummy data.

**Comment by Ribeiro-Tiago** [comment]
Without more information about how your component I don't really know how to help. Have you tried using `this.$forceUpdate()` after loading the data ?

**Comment by sell** [comment]
> Without more information about how your component I don't really know how to help. Have you tried using `this.$forceUpdate()` after loading the data ?

Sorry about that, here is a reproduction: https://codesandbox.io/s/red-brook-l0w1l

**Comment by Ribeiro-Tiago** [comment]
Could you also show how you're assigning the values that come from what I assume is your request to the `this.chartLabels` and `this.chartData`

**Comment by sell** [comment]
hmm, not sure what you mean exactly. What I showed is basically what I am doing expect it's from an api, well my backend.

**Comment by apertureless** [comment]
If you changing data on the fly, the chart won't magically update.
You have either call `this.$data._chart.update()` after you mutate the data or you can try the reactive mixins, which will try to do this automatically for you.

The reason is, that chart.js is not reactive and this is only a wrapper for it.

**Comment by sell** [comment]
> If you changing data on the fly, the chart won't magically update.
> You have either call `this.$data._chart.update()` after you mutate the data or you can try the reactive mixins, which will try to do this automatically for you.
> 
> The reason is, that chart.js is not reactive and this is only a wrapper for it.

I see, I went with this method because he mentioned it to me and sounded correct.

**Comment by sell** [comment]
> Guess you need to provide unique ids to the chart. https://vue-chartjs.org/api/#props
> Which is the id for the canvas object.

Back to this, I gave them both unique id's I can see them changing in the dev tools, but the data still isn't being updated. I might just have to stick to my original solution which is kind of junky in my opinion but it works. The saying is `if it's not broke, don't fix it` lol 😆

**Comment by apertureless** [comment]
> I see, I went with this method because he mentioned it ([#716 (comment)](https://github.com/apertureless/vue-chartjs/issues/716#issuecomment-909021847)) to me and sounded correct.

Well, it is not a wrong solution.It is event he prefered one. Dont see a reason to have two chart instances just because you want dummy data, before the real one comes from the api request. 

It is just not complete. Because you have to manually tell chart.js to update, so it re-renders. Just changing the data.

> Back to this, I gave them both unique id's I can see them changing in the dev tools, but the data still isn't being updated. 

So, the first placeholder component is properly unmounted and the new one is mounted?
Are two canvas elements present?

**Comment by Ribeiro-Tiago** [comment]
> hmm, not sure what you mean exactly. What I showed is basically what I am doing expect it's from an api, well my backend.

@sell In your codepen example, you're just assigned the reversed dummy data and not whatever the api returns.

> If you changing data on the fly, the chart won't magically update.

@apertureless even so, in the example in the description it should update, because he's not changing the data of the chart per say, he's rendering an entirely new chart based on the value of `loaded`

I had forgotten about this but indeed. @sell if you want the data to update on the fly, you have the include the reactive prop mixins. 
I also have line charts and I have a reusable component for it (as I also have some options that are common across multiple line chart components): 
```JavaScript
// lineChart.js

import { Line, mixins } from 'vue-chartjs'

export default {
  extends: Line,
  mixins: [mixins.reactiveProp],
  // other stuff that's specific to my needs
}
```
```Vue
// component that uses the line chart
<template>
   <line-chart :chartData="chartData" />
</template>

<script>
import LineChart from "path/to/lineChart.js"

export default { 
  components: { Linechart }
}
</script>
```

> original solution which is kind of junky in my opinion but it works

@sell you also have the possibility of showing a loading indicator of some sort while data is being loaded rather than dummy data, that's what I do

**Comment by sell** [comment]
> Well, it is not a wrong solution.It is event he prefered one. Dont see a reason to have two chart instances just because you want dummy data, before the real one comes from the api request.

Yeah, I wasn't aware of that and it didn't work at first because I wasn't aware you had to practically reinitialize the chart. I never insisted his answer was wrong, it just didn't work in my case.

I would like to thank you for your work and effort on this package and to whom else helped with this package.

**Comment by sell** [comment]
> @sell you also have the possibility of showing a loading indicator of some sort while data is being loaded rather than dummy data, that's what I do

oh this would be nice, I don't see an option on the docs. Would I achieve this with css or is there another way and I am just blind?

**Comment by sell** [comment]
> You have either call `this.$data._chart.update()` after you mutate the data or you can try the reactive mixins, which will try to do this automatically for you.

👏 FInally got it, so `this.$data._chart.update()` wasn't updating the chart. I had to destory (`this.$data._chart.destroy()`) the chart then render the chart again.

**Comment by Ribeiro-Tiago** [comment]
> oh this would be nice, I don't see an option on the docs. Would I achieve this with css or is there another way and I am just blind?

no, something you'd have to do yourself as chartjs doesn't have support for it, a simple `v-if="loaded" > render chart; v-else > render loading component`
