### ISSUE TITLE
Support for Area Chart

### ISSUE THREAD

**Issue by dttvn0010** [apertureless/vue-chartjs#717]
### Expected Behavior
- Be able to use Area chart

### Actual Behavior
- Area chart not supported

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 3.5.1
- chart.js version: 2.9.4
- npm version: 6.14.14
  
Correct me if I am wrong but Area charts are currently not supported. If this is true, this will be quite strange given the fact that Area charts are very popular (while the Polar Area charts are less popular but are supported)

**Comment by apertureless** [comment]
Well this is only a wrapper for [Chart.js](https://www.chartjs.org/docs/2.9.4/charts/area.html) and thus it supports all chart types that chart.js supports.

If you check out the documentation (note that vue-chartjs supports only chartjs < 3) https://www.chartjs.org/docs/2.9.4/charts/area.html

You will see that the line chart also can be used as an area chart.

**Comment by dttvn0010** [comment]
Thanks
