### ISSUE TITLE
TypeError: child._updateFromParent is not a function

### ISSUE THREAD

**Issue by ChenSunMoon** [apertureless/vue-chartjs#72]
### Expected Behavior
在mint-ui组件Tabbar使用报这个错

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
¯\_(ツ)_/¯

**Comment by SummyGitHub** [comment]
我也遇到这个问题，检查后发现，如果提供给图标的数据是静态的，则不会报这种错误，如果是动态获取数据，则报错child._updateFromParent is not a function

**Comment by apertureless** [comment]
ping @ChenSunMoon

**Comment by apertureless** [comment]
#closed due to inactivity
