### ISSUE TITLE
Chart is undefined

### ISSUE THREAD

**Issue by DvirH** [apertureless/vue-chartjs#721]
### Expected Behavior
this.$data._chart = new Chart(this.$refs.canvas.getContext('2d')
Chart should be defined

### Actual Behavior
Chart is undefined

on the BaseChart.js file I've noticed that import Chart from chart.js.
It should be import {Chart} from chart.js

### Environment
- vue.js version: 12.6.1
- vue-chart.js version: 3.5.1
- chart.js version: 3.5.1
- npm version: 6.13.4

**Comment by hardyjoshua** [comment]
It doesn't support chart.js v3. You have to install chart.js v2. i.e npm install chart.js@2.9.4
When do you plan to upgrade to V3? I wanna use new chart options of v3.

**Comment by LePashtet** [comment]
> * vue.js version: 12.6.1

Unbelievable
