### ISSUE TITLE
Current status of MomentJS

### ISSUE THREAD

**Issue by theonelucas** [apertureless/vue-chartjs#726]
Hi, what's the current status of momentjs, is it trivial to replace it with date-fns or even remove it entirely without having access to webpack? I'm using NuxtJS and don't want to eject my entire configuration just to be able to remove momentjs. Is there any way to use [this adapter](https://github.com/chartjs/chartjs-adapter-date-fns) with vue-chartjs?

### Expected Behavior
Do not import momentjs

### Actual Behavior
Importing momentjs

**Comment by apertureless** [comment]
Haven't tried this adapter.
You should just try it out and import the chart and adapter in your component.
In general: The current status of momentjs is, that vue-chartjs is simply a wrapper of chart.js 
So I don't implement any additional functionality.
