### ISSUE TITLE
Stacked Bar/Line?

### ISSUE THREAD

**Issue by xXxcb** [apertureless/vue-chartjs#741]
Is it possible to get the Stcked Bar Line Chart in a vue project? 

### Environment
![Screen Shot 2021-12-21 at 9 10 09 PM](https://user-images.githubusercontent.com/23020371/147023254-a5314d31-c405-4b66-b264-fe07462b3cf8.png)

- vue.js version: 2.6.14
- vue-chart.js version: 3.5.1
- chart.js version: 3.6.2
- npm version: 7.22.0

**Comment by apertureless** [comment]
Yes it is. https://www.chartjs.org/docs/2.9.4/charts/mixed.html?

https://github.com/apertureless/vue-chartjs/issues/123
https://github.com/apertureless/vue-chartjs/issues/29

Basically you use the `extend` for one chart type and in your data you define antoher one.

**Comment by xXxcb** [comment]
Thank you! And I 'm sorry for the duplicate post.
