### ISSUE TITLE
Can't get chartjs-plugin-datalabels works

### ISSUE THREAD

**Issue by HELMAB** [apertureless/vue-chartjs#744]
### Expected Behavior
I want to use `chartjs-plugin-datalables` with bar

I have been created `BartChart.js` in `components/chartjs` directory

```js
import { Bar, mixins } from 'vue-chartjs'
const { reactiveProp } = mixins

import chartjsPluginDatalables from 'chartjs-plugin-datalabels'

export default {
    extends: Bar,
    mixins: [reactiveProp],
    props: ['options'],
    mounted () {
        this.addPlugin(chartjsPluginDatalables)
        this.renderChart(this.chartData, this.options)
    }
}
```
and then use it in my `App.vue`

```vue
<template>
  <div>
    <div class="small" v-if="chartData">
      <bar-chart :chart-data="chartData"></bar-chart>
      <button @click="fillData()">Randomize</button>
    </div>
  </div>
</template>

<script>
import BarChart from './components/chartjs/BarChart'

export default {
  name: 'App',
  components: {
    BarChart
  },
  data () {
    return {
      chartData: null
    }
  },
  mounted () {
    this.fillData()
  },
  methods: {
    fillData () {
      this.chartData = {
        labels: ['12/21', '01/22'],
        datasets: [
          {
            label: 'Custer 01',
            backgroundColor: '#f87979',
            data: [this.getRandomInt(), this.getRandomInt()]
          }, {
            label: 'Custer 02',
            backgroundColor: '#4A7B36',
            data: [this.getRandomInt(), this.getRandomInt()]
          }
        ],
      }
    },
    getRandomInt () {
      return Math.floor(Math.random() * (50 - 5 + 1)) + 5
    }
  }
}
</script>

<style>
.small {
  max-width: 600px;
  margin:  150px auto;
}
</style>
```

and I hope it's running without any issue but

### Actual Behavior

I got the error:
![Screen Shot 2022-01-07 at 11 17 00 AM](https://user-images.githubusercontent.com/15307857/148491847-24cbb428-cbde-4496-a9c9-cab065115fab.png)

### Environment
- vue.js version: ^2.6.11
- vue-chart.js version: ^3.5.1
- chart.js version: ^2.9.4
- npm version: 6.14.15
- node version: v14.18.1
- chartjs-plugin-datalabels version: ^2.0.0

![Screen Shot 2022-01-07 at 11 29 56 AM](https://user-images.githubusercontent.com/15307857/148491924-4c13e323-bcc8-4bf3-b123-89e8d166ba3c.png)
  
What am I definitely missing?

**Comment by apertureless** [comment]
Its a problem with the plugin https://github.com/chartjs/chartjs-plugin-datalabels/issues/264

**Comment by HELMAB** [comment]
Thanks, @apertureless 

it works with `chartjs-plugin-datalabels@1`
