### ISSUE TITLE
Errors in docs example

### ISSUE THREAD

**Issue by Aleksandr-JS-Developer** [apertureless/vue-chartjs#756]
### Expected Behavior
Creating a Graph from Documentation
From => [here](https://vue-chartjs.org/guide/#example)

### Actual Behavior
Got error and empty canvas
**[Vue warn]: Invalid prop: type check failed for prop "chartData". Expected Object, got Null 
found in LineChart**

After the change: "datacollection: null" => "datacollection: {}" in RandomChart.vue, got another error:

**[Vue warn]: Error in mounted hook: "TypeError: chart_js__WEBPACK_IMPORTED_MODULE_0__.default is not a constructor"**
**found in LineChart**

### Environment
- vue.js version: **2.6.1**
- vue-chart.js version: **3.5.1**
- chart.js version: **3.7.1**
- npm version: **6.14.11**

**Comment by scil** [comment]
same error.
```
vue.esm.js:628 [Vue warn]: Error in mounted hook: "TypeError: __WEBPACK_IMPORTED_MODULE_0_chart_js___default.a is not a constructor"

found in

---> <ChartLine> at Assets/vue/components/charts/line.vue
       <Root>
```

from `new __WEBPACK_IMPORTED_MODULE_0_chart_js___default.a` in vue-chartjs.js
```
      renderChart: function renderChart(data, options) {
        if (this.$data._chart) this.$data._chart.destroy();
        if (!this.$refs.canvas) throw new Error('Please remove the <template></template> tags from your chart component. See https://vue-chartjs.org/guide/#vue-single-file-components');
        this.$data._chart = new __WEBPACK_IMPORTED_MODULE_0_chart_js___default.a(this.$refs.canvas.getContext('2d'), {
          type: chartType,
          data: data,
          options: options,
          plugins: this.$data._plugins
        });
      }
    },
```

my code
```
<script>
import { Line, mixins } from 'vue-chartjs'
const { reactiveProp } = mixins

export default {
  name: "chart-line",
  extends: Line,
  mixins: [reactiveProp],
  props: ['options'],
  mounted () {
    // this.chartData is created in the mixin.
    this.renderChart(this.chartdata, this.options)
  }
}
</script>

<style>
</style>
```

**Comment by scil** [comment]
now i use [vue-chart-3](https://github.com/victorgarciaesgi/vue-chart-3) which support vue2

```
npm i vue-chart-3@legacy
npm i @vue/composition-api
```

vue demo:
Vue 2 + composition API: [CodeSandbox demo Vue 2 + composition](https://codesandbox.io/s/vue-chart-3-vue-2-mw54f?file=/src/App.vue)

for me, this demo should add an extra line code `import { Chart, registerables } from 'chart.js';Chart.register(...registerables);`.
