### ISSUE TITLE
Elements type bar is possibly undefined

### ISSUE THREAD

**Issue by tempre** [apertureless/vue-chartjs#770]
### Expected Behavior

``` options: {
      default() {
          return {
              responsive: true,
              maintainAspectRatio: false,
              elements: {
                  bar: {
                      backgroundColor: colorize(false),
                      borderColor: colorize(true), 
                      borderWidth: 2,
                  }
              }
          }
      }
  }
```
Should color the bar chart appropriately, along with the border, and border width.

### Actual Behavior

Currently the chart displays the default color as if it is ignoring the elements clause.

The block above is working for Line, Pie and Radar of course with their differences regarding the bar clause.

It seems I could be missing something or that this is a missing piece.

### Environment
- vue.js version: <2.6.13>
- vue-chart.js version: <3.4.1>
- chart.js version: <2.9.4>
- npm version: <8.5.2>

**Comment by tempre** [comment]
Note, these are the options passed on renderChart.

**Comment by apertureless** [comment]
Hey @tempre 

well, vue-chartjs is only passing the options directly to chart.js
So it might be, that your configuration is not right.

I think you can either pass the the styling in the dataset options https://www.chartjs.org/docs/2.9.4/charts/bar.html#styling
Or maybe you need to use the `rectangle` https://www.chartjs.org/docs/2.9.4/configuration/elements.html#rectangle-configuration

But it may be better if you ask directly in the chart.js community.

**Comment by tempre** [comment]
Hey,

Thank you for this, rectangle was exactly what I needed my assumption for the type bar being a element originated from this example.
https://www.chartjs.org/docs/latest/samples/scriptable/bar.html

Nonetheless, I should have dug deeper on my end.

**Comment by apertureless** [comment]
Ah yeah, with the next v4 release we support chartjs 3.x and then it should be possible!
