### ISSUE TITLE
404 on https://unpkg.com/vue-chartjs/dist/vue-chartjs.min.js

### ISSUE THREAD

**Issue by michaelwood** [apertureless/vue-chartjs#781]
### Expected Behavior

Using vue-chartjs via https://unpkg.com/vue-chartjs/dist/vue-chartjs.min.js  loads vue-chartjs (as per https://vue-chartjs.org/guide/#browser )

### Actual Behavior
https://unpkg.com/vue-chartjs/dist/vue-chartjs.min.js  as of today returns 404 not found:

`Cannot find "/dist/vue-chartjs.min.js" in vue-chartjs@4.0.1`

Is this to do with the breaking change of 3.5.1 to 4.0.1 ?

**Comment by thabarbados** [comment]
@michaelwood you can find a solution here https://github.com/apertureless/vue-chartjs/issues/780#issue-1182836718
