### ISSUE TITLE
Plugins not working in v4

### ISSUE THREAD

**Issue by mgrsskls** [apertureless/vue-chartjs#782]
### Expected Behavior

Plugins should be executed when passing to a chart component via `:plugins="plugins"`.

### Actual Behavior

Plugins are not executed.

I think this is because plugins is not added to the chart configuration here: https://github.com/apertureless/vue-chartjs/blob/5c9a69c8ea18909f3633d91b480302fbc86591f3/src/BaseCharts.ts#L125-L132
As you can see on https://www.chartjs.org/docs/latest/developers/plugins.html, `plugins` should be an array in the configuration object (second param).

Or am I missing something?

Thanks a lot!

### Environment
- vue.js version: 2.6.14
- vue-chart.js version: 4.0.1
- chart.js version: 3.7.1
- npm version: - (yarn @ 1.22.18)

**Comment by apertureless** [comment]
@mgrsskls 

`getChartOptions` should handle that.
https://github.com/apertureless/vue-chartjs/blob/5c9a69c8ea18909f3633d91b480302fbc86591f3/src/utils.ts#L80-L99

Which plugins are you trying to use? 
Are you sure that these plugins work with chart.js 3+ ?

**Comment by mgrsskls** [comment]
Hi together, thanks for the quick response!

I am using a custom plugin, completely reduced it just for the case of debugging this.

I'm a little bit confused right now, but I'm also not a chart.js expert, so maybe I'm also completely on the wrong track… but here is a minimal repo: https://github.com/mgrsskls/vue-chartjs From my understanding you should get an alert, but that's not the case. I tried both cases: passing a `plugins` object directly to the `vue-chartjs` component and passing `plugins` in the chart options.

When I look at https://www.chartjs.org/docs/latest/developers/plugins.html, the plugins should be passed as an **_array_** via the chart options. The `getChartOptions` method returns an object though.

**Comment by thabarbados** [comment]
@mgrsskls  thanks for your repo. Yes, it's my mistake. Sorry. 
Plugins should be an array of this type https://github.com/chartjs/Chart.js/blob/c057c96693819b41e7b89860f916c0aa361bafa5/types/index.esm.d.ts#L805.
I will fix this soon.

**Comment by jrahim54** [comment]
@thabarbados how does the new version support plugins like https://www.chartjs.org/chartjs-plugin-annotation/latest/ ? When I tried to register it to Chartjs I get a maximum call stack exceeded error.

**Comment by thabarbados** [comment]
@jrahim54 I need some time to understand why this is happening. After that, I will release a bug fix or make a new feature with support for such plugins.

**Comment by mgrsskls** [comment]
> @mgrsskls thanks for your repo. Yes, it's my mistake. Sorry.

No need to be sorry! :) Thanks for the quick fix, works for me!

**Comment by thabarbados** [comment]
Hey @jrahim54 . After version [4.0.4](https://github.com/apertureless/vue-chartjs/releases/tag/v4.0.4) vue-chartjs works with chartjs-plugin-annotation without errors. You can check [here](https://codesandbox.io/s/reverent-allen-s394h2?file=/src/components/Bar.vue)

**Comment by batchor** [comment]
I'm still having the type error with "chartjs-plugin-annotation": "^3.0.1", "chart.js": "^4.4.3", and "vue-chartjs": "^5.3.1".

```
const options  = {
  plugins: {
    annotation: {
      annotations: {
        line1: {
          type: 'line',
          yMin: 60,
          yMax: 60,
          borderColor: 'rgb(255, 99, 132)',
          borderWidth: 2,
        }
      }
    }
  }
};


<template>
  <Bar id="bar" :options="options" :data="data" />
</template>
```
