### ISSUE TITLE
Set chart width without affecting labels

### ISSUE THREAD

**Issue by rzb** [apertureless/vue-chartjs#79]
More like a chart.js specific question, but perhaps there's a cleaner solution using this wrapper.

Is there a way to set chart width without affecting its labels?

The following chart root node has a max-width of 300px. But I want the labels to fill out the whole div.

![Image of rzb](https://i.imgur.com/D64Addt.png)

I could decouple the labels from chart.js and render them as html, but then I'd give up chart.js built-in interactive features.

**Comment by apertureless** [comment]
I don't think that this is possible.
You have two options with chart.js

1. Pass `responsive: false` to the options and set a fix width and height to the canvas over the props
2. With `responsive: true` the canvas and chart will resize based on the outer container.

However in both versions, you are changing the size of the canvas element. And the labels are rendered in the canvas. And as far as I know there is no way of only resizing the chart inside the canvas. But you should maybe check out the chart.js docs for this.

However, you could like you said extract the legend and render it as html. This way you would lose the filtering features, however I think you could probably add click listeners by hand and do the interactive filtering. But I am not sure about this. You have to check out the chart.js hooks and functions.
