### ISSUE TITLE
Doughnut with text in the middle

### ISSUE THREAD

**Issue by rzb** [apertureless/vue-chartjs#80]
I'd like to achieve this:

https://jsfiddle.net/cmyker/ooxdL2vj/

But haven't found a way to register a plugin.

**Comment by rzb** [comment]
Never mind. I noticed later that `this._chart` is available only after rendering and that Chart is global.

**Comment by apertureless** [comment]
Sadly Chart.js is kind of limited if you want to work with the labels and positions of text. 
It is a highly requested feature to render the labels inside a doughnut or have connected lines between the chart and the open label.

There is also [ECharts](https://github.com/Justineo/vue-echarts) which seem to have more features in this directions.

**Comment by El4a** [comment]
@rzb so did you find a good solution? I need the same :)

**Comment by egeersoz** [comment]
@rzb Can you elaborate on your solution please?

**Comment by chhumsina** [comment]
If someone still search for:
https://gist.github.com/chhumsina/9bcc54851d19123d4a849432696f4bda
![Capture](https://user-images.githubusercontent.com/3894767/77449751-f1090680-6e24-11ea-9160-ed91bac01866.PNG)
