### ISSUE TITLE
[Bug]:  Generating charts in for loop not working as expected

### ISSUE THREAD

**Issue by jrahim54** [apertureless/vue-chartjs#800]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

When generating a list of graphs in a for loop, only the very last one is being generated.

```
          <div v-for="graph in graphs" :key="graph.title">
            <ChartLine
              :chartId="graph.title" class="chart"
              :chart-data="graph"></ChartLine>
          </div>
```

In the above the ChartLine component implements the LineChart below, but only the very last graph is generated and displayed, this was working in version 3.5.12 but not anymore. Below is my template for the chart. 

```
<template>
  <new-chart
    :chart-options="chartOptions"
    :chart-data="computedChartData"
    :chart-id="chartId"
    :dataset-id-key="chartId"
    :plugins="plugins"
    :css-classes="cssClasses"
    :styles="styles"
    :width="width"
    :height="height"
  />
</template>
```

### Reproduction

https://codesandbox.io/s/distracted-currying-jq6bh1?file=/src/App.vue

### chart.js version

v3.7.1

### vue-chartjs version

v4.0.4

**Comment by zbateson** [comment]
This is happening to me too having two charts on the same page.  I scoured through the documentation trying to figure out if I missed something and couldn't find anything obvious.

**Comment by apertureless** [comment]
Have you tried passing a unique `chart-id` ?

**Comment by zbateson** [comment]
I did, yes

**Comment by zbateson** [comment]
Here's some more info if it helps:

``` <bar-chart
          :chart-data="programChartData"
          :chart-options="programOptions"
          chart-id="program-chart"
          :styles="{ height: '500px', position: 'relative' }"
        ></bar-chart>
```

Second:
``` <bar-chart
          :chart-data="totalsChartData"
          :chart-options="totalsOptions"
          chart-id="totals-chart"
          :styles="{ height: '500px', position: 'relative' }"
        ></bar-chart>
```

In developer tools I can see both 'canvas' elements have different IDs:

``` 
<div class="" style="height: 500px; position: relative;"><canvas id="program-chart" style="box-sizing: border-box;" width="400" height="400"></canvas></div>
```

```
<div class="" style="height: 500px; position: relative;"><canvas id="totals-chart" style="display: block; box-sizing: border-box; height: 500px; width: 920px;" width="920" height="500"></canvas></div>
```

For some reason the height of the first one doesn't get set correctly (viewport is 920).

I removed all options I had set (including 'responsive: true' and it still happens).

**Comment by thabarbados** [comment]
@jrahim54 @zbateson Can you provide a repo of your error? In my [sandbox](https://codesandbox.io/s/xenodochial-wave-grm6d8), charts in a loop are drawn without errors

**Comment by zbateson** [comment]
Hi @thabarbados -- thanks, I've copied what you've done and moved it over to recreate the issue.  Looks like it might be 'legacy'/vue 2 related.

https://codesandbox.io/s/vue-chartjs-legacy-issue-2ntnh9
