### ISSUE TITLE
How can you change legend label colour?

### ISSUE THREAD

**Issue by xlcrr** [apertureless/vue-chartjs#81]
The default is brown

Is there a way to change this? 

Thanks

**Comment by apertureless** [comment]
You can pass the `defaultFontColor` in the options.

Check out the Chart.js documentation for more info: http://www.chartjs.org/docs/#chart-configuration-colors

**Comment by xlcrr** [comment]
Solved this without actually passing the options object, just a legend object

eg 

this.renderChart(data,
  {
// options
    legend: {
       labels: {
         fontColor: '#ffffff'
      }
   }
}

**Comment by geek4ctrl** [comment]
Does the solution work on your side?

**Comment by xlcrr** [comment]
Hi @geek4ctrl yes it works. Can we help?

**Comment by asadbr** [comment]
![image](https://user-images.githubusercontent.com/60221314/132015751-fe01234f-459d-40c8-9a65-3d4d8fbff293.png)
guys how to change the background color of it 
but the background color of graph should not change

**Comment by natBizitza** [comment]
> ![image](https://user-images.githubusercontent.com/60221314/132015751-fe01234f-459d-40c8-9a65-3d4d8fbff293.png) guys how to change the background color of it but the background color of graph should not change

Just in case someone is still looking for the answer:

Use [fillStyle](https://www.chartjs.org/docs/latest/configuration/legend.html#legend-item-interface:~:text=Legend%20Item%20Interface) to change the fill of the legend box.
