### ISSUE TITLE
[Bug]: npm doesn't install 4.0.7 version

### ISSUE THREAD

**Issue by sushant-repo** [apertureless/vue-chartjs#832]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

vue-chartjs@4.0.5 has issue with chart.destroy() due to a typo. This issue seems to be resolved in latest update. However, trying to install latest versions using npm doesn't install version 4.0.7 rather keeps installing 4.0.5.

### Reproduction

npm i vue-chartjs@latest 

### chart.js version

3.7.1

### vue-chartjs version

4.0.5

**Comment by thabarbados** [comment]
Hey @sushant-repo. On the [npm](https://www.npmjs.com/package/vue-chartjs), we see 3,436 downloads of version 4.0.7.  Users can download the latest release. Can you try updating the library again?
