### ISSUE TITLE
[Bug]: cdn vue-chartjs.min.js now that does not work.

### ISSUE THREAD

**Issue by k-brahma** [apertureless/vue-chartjs#836]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

hi, https://unpkg.com/vue-chartjs/dist/vue-chartjs.min.js returns the result below:

status code: 404
Cannot find "/dist/vue-chartjs.min.js" in vue-chartjs@4.0.7

the japanese guide page for vue-chartjs shows cdn scripts below:

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>  
<script src="https://unpkg.com/vue-chartjs/dist/vue-chartjs.min.js"></script>

but latter does not works.

https://vue-chartjs.org/ja/guide/
https://github.com/apertureless/vue-chartjs/blob/ea8a7fb184a68861b16f836590cf0b44e2fca55c/website/src/ja/guide/index.md

i guess now that cdn installation has disabled, as in not japanese but english guide page (https://vue-chartjs.org/guide/) it looks like the section for cdn installation disappeared.

but i want to use it via cdn.
are there any way to manage this issue?

regards,

### Reproduction

https://github.com/apertureless/vue-chartjs/search?q=min.js

### chart.js version

v2.7.1

### vue-chartjs version

v4.0.7

**Comment by thabarbados** [comment]
Hey, @k-brahma, maybe this [solution](https://github.com/apertureless/vue-chartjs/issues/780#issue-1182836718) will help you?

**Comment by k-brahma** [comment]
thank you.

the solution below works.
https://github.com/apertureless/vue-chartjs/issues/780#issuecomment-1080406087

**Comment by fdarling** [comment]
I would like to use `vue-chartjs` with Vue 3 in CDN mode. This works with the older Vue 2 and `vue-chartjs` v3.4.0, as shown here:

https://gist.github.com/sundlee/ddf5c875de98310721ac838767bedf56

And while Vue 3 itself works in CDN mode, `vue-chartjs` v5.2.0 doesn't seem to as the `dist` files hosted on CDNs have `import`/`export` syntax and are not meant to be used directly from browsers. The older style `vue-chartjs.min.js` file is missing from the `dist` directory...

Related issues:

* https://github.com/apertureless/vue-chartjs/issues/780
* https://github.com/apertureless/vue-chartjs/issues/202
* https://github.com/apertureless/vue-chartjs/issues/836 (this one)
