### ISSUE TITLE
[Bug]: Adding fill property to Dataset in LineChart does not work

### ISSUE THREAD

**Issue by oliverpaulsen** [apertureless/vue-chartjs#851]
### Would you like to work on a fix?

- [x] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Current behaviour:
Adding a fill property (with the value "origin") to a Dataset does nothing. (Context: LineChart)

```
datasets: [
        {
          label: "Data One",
          backgroundColor: "#f87979",
          data: [40, 39, 10, 40, 39, 80, 40],
          fill: "origin"
        }
```

I expected the area below the line to be filled as it is described here
 https://www.chartjs.org/docs/latest/charts/line.html (it also works in the sandbox on the page)

Any Idea what the problem might be? Am I missing something?
I am happy to make a PR if you can point me in the right direction!

### Reproduction

https://codesandbox.io/s/hidden-http-lip51z?file=/src/components/lineChart.ts

### chart.js version

v3.7.1

### vue-chartjs version

v4.1.0

**Comment by lol2x** [comment]
chart.js 3 is ESM tree shakeable and Filling LineChart requires the Filler plugin so you have to register it manually.
like this:
https://codesandbox.io/s/shy-bush-fp3ug4?file=/src/components/lineChart.ts
