### ISSUE TITLE
[Bug]: Cannot set `backgroundColor` of radar chart

### ISSUE THREAD

**Issue by alokVishu** [apertureless/vue-chartjs#867]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

In your current demo, you have passed background colors in datasets but it's not applied.

it works when you use `import "chartjs/auto";`  but it increases the bundle size.

Please let me know how to make it work with background color in the tree-shaking method.

### Reproduction

https://codesandbox.io/s/github/apertureless/vue-chartjs/tree/main/sandboxes/radar?file=/src/components/radarChart.ts

### chart.js version

^3.8.0

### vue-chartjs version

^4.1.1

**Comment by apertureless** [comment]
With backgroundColor, you mean the fill of the area that the lines making?
https://www.chartjs.org/docs/latest/getting-started/integration.html#bundlers-webpack-rollup-etc

You see all modules there.

Have you tried importing the `Filler` module ?
