### ISSUE TITLE
Unable to add to material-vue layout

### ISSUE THREAD

**Issue by delaneyj** [apertureless/vue-chartjs#87]
### Expected Behavior
Able to add to [Material Vue Layout](https://vuematerial.github.io/#/ui-elements/layout)

### Actual Behavior
Have a test graph based on the examples called MonthlyGraph that shows up fine
```        
        <monthly-income />
        <md-layout md-gutter>
          <md-layout>
            Foo
          </md-layout>
          <md-layout>
            Bar
          </md-layout>
        </md-layout>
```
![a](https://cloud.githubusercontent.com/assets/438252/24520779/881606ce-153e-11e7-9b5a-23bb631fb80a.png)

Replacing the `Foo` with `<monthly-income />` updates properly in dev mode.
![b](https://cloud.githubusercontent.com/assets/438252/24520837/be953c1a-153e-11e7-9ccc-b108a875706f.png)

However on a refresh of the page the graph disappears
![c](https://cloud.githubusercontent.com/assets/438252/24520921/067f93ea-153f-11e7-90ae-288999591e4e.png)

Also tried changing to use :width and :height props with no further success

### Environment
- vue.js version: 2.2.6
- vue-chart.js version: 2.5.6
- npm version: 4.1.2

**Comment by apertureless** [comment]
Hi @delaneyj 
mh never used vue material layout.

Does any error get thrown?

**Comment by delaneyj** [comment]
No @apertureless, no errors, nothing, just blank div the right size.

**Comment by apertureless** [comment]
Can you provide a small jsfiddle / codepen ? Hard to say whats the problem without seeing any code :)

**Comment by apertureless** [comment]
@delaneyj bump?
