### ISSUE TITLE
[Bug]: Pie Chart custom tooltip label callback not firing on first load

### ISSUE THREAD

**Issue by madebycaliper** [apertureless/vue-chartjs#900]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

When the chart first loads it shows the standard label despite a custom pie tooltip being passed. If I modify the Vue component and save, the HMR / reload triggers the label to work as expected.

Things I've tried:
- initializing the data / Chart in every Vue lifecycle hook
- updating the `chartData` to try triggering a reload
- updating the ChartJs overrides _after_ registering the elements
- a bunch of other random attempts to fix

## Video (takes a few seconds for HMR to hit)
![Screen Shot 2022-07-27 at 15 19 53](https://user-images.githubusercontent.com/5473496/181356827-2924709c-e6c4-4ff8-81fa-324f73d064c2.gif)

### Reproduction

https://codesandbox.io/s/vue2-pie-chartjs-repro-y6kjrr?file=/src/components/Pie.vue

### chart.js version

3.8.0

### vue-chartjs version

4.1.1

**Comment by Arantiryo** [comment]
Hi @madebycaliper 👋 

Have you tried just passing the `tooltip` options to `chartOptions.plugins`? I've modified the original example to do it this way and it seems to be working just as expected (here's a link to [code sandbox](https://codesandbox.io/s/vue2-pie-chartjs-repro-forked-2ftsi1?file=/src/components/Pie.vue:1218-1230)).
