### ISSUE TITLE
[Bug]: Type error with props

### ISSUE THREAD

**Issue by cawa-93** [apertureless/vue-chartjs#906]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I took [one of your examples](https://codesandbox.io/s/github/apertureless/vue-chartjs/tree/main/sandboxes/doughnut) and moved the data outside of the component to get it through props. Now, for some reason I'm getting a type error in `doughnutChart.ts`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-qby8dn?file=src/components/doughnutChart.ts

### chart.js version

v3.9.1

### vue-chartjs version

v4.1.1

**Comment by Arantiryo** [comment]
Hi @cawa-93 👋 

The error reads: 
```
Types of property 'plugins' are incompatible.
  Type 'Plugin<"doughnut", AnyObject>[] | undefined' is not assignable to type 'Plugin<"doughnut", AnyObject>[]'.
    Type 'undefined' is not assignable to type 'Plugin<"doughnut", AnyObject>[]'.(2769)
```

Which is Typescript saying that `props.chartData` might be `undefined`. You can can tell the compiler explicitly that this variable has a value and is not undefined by using an exclamation mark: `chartData: props.chartData!,`.

Hope that clears things up.
