### ISSUE TITLE
[Bug]: Line disappears on Scatter chart when LineTension is set

### ISSUE THREAD

**Issue by jmuronis** [apertureless/vue-chartjs#907]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I'm noticing in my own project and the example linked from vue-chartjs.org/examples/ that when showLine is true and then trying to set a lineTension value that the line disappears completely. 

I've tried these same settings on chartjs.org and they work fine.

### Reproduction

https://codesandbox.io/s/github/apertureless/vue-chartjs/tree/main/legacy/sandboxes/scatter

### chart.js version

3.9.1

### vue-chartjs version

4.1.1

**Comment by Arantiryo** [comment]
Hi @jmuronis 👋 

Thanks for bringing this up! You also need to import and register `Filler` for `lineTension` to work.
