### ISSUE TITLE
[Bug]: Search in documentation does not work

### ISSUE THREAD

**Issue by LeeLenaleee** [apertureless/vue-chartjs#908]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

If you put any text in the search box it returns that it can't find it

### Reproduction

https://vue-chartjs.org/guide/#creating-your-first-chart

### chart.js version

-

### vue-chartjs version

-

### Possible solution

Indexing needs to be fixed I guess

**Comment by dangreen** [comment]
@apertureless Hi. Would you please share access to the Algolia dashboard? I maybe know what the problem is.

**Comment by apertureless** [comment]
@dangreen there is no agolia dashboard, because it is using https://docsearch.algolia.com/ .
I will check maybe the API key expired.

**Comment by dangreen** [comment]
@apertureless You can use the email which was used in the application to login/register in algolia - vue-chartjs project will be shown in the dashboard.

**Comment by apertureless** [comment]
aah, yeah I kinda missed the migration email.  🙈

**Comment by dangreen** [comment]
@apertureless I think you also should manually trigger reindex in the dashboard.

**Comment by apertureless** [comment]
@dangreen yeah I had to update and migrate the crawler config. Should be working now.
