### ISSUE TITLE
Error when building: 'This dependency was not found: chartjs'

### ISSUE THREAD

**Issue by weislanes** [apertureless/vue-chartjs#91]
### Expected Behavior

When building, Vue builds and vue-chartjs causes no problems.

### Actual Behavior

I see an error: 
````
This dependency was not found:

* chart.js in ./~/vue-chartjs/es/BaseCharts/Bar.js, ./~/vue-chartjs/es/BaseCharts/Doughnut.js and 6 others
````
I have installed chartjs as well using npm (based on what I can understand from your latest release ntoes, this is required) and the issue is still occurring. 

Any ideas?

### Environment
- vue.js version: 2.2.6
- vue-chart.js version: 2.6.0
- npm version: latest

**Comment by apertureless** [comment]
Did you have vue-chartjs installed before? And upgraded to the latest version? Tried to delete the node modules folder and reinstall?

Whats your build setup? Webpack 2?

**Comment by treaves** [comment]
Make sure you install chart.js, not chartjs.  Two different things.

**Comment by apertureless** [comment]
Closed due to inactivity.
