### ISSUE TITLE
[Bug]: error TS2724: '"vue"' has no exported member named 'ShallowRef'.

### ISSUE THREAD

**Issue by yoonchulkoh** [apertureless/vue-chartjs#911]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

The following typescript error occurred.

```
Error: node_modules/vue-chartjs/dist/types.d.ts(3,87): error TS2724: '"vue"' has no exported member named 'ShallowRef'. Did you mean 'shallowRef'?
```

ShallowRef has been supported since version 3.2.24, so lower versions will result in an error.
https://github.com/vuejs/core/blob/main/CHANGELOG.md#3224-2021-12-06

### Reproduction

Use version 3.2.20 of Vue

### chart.js version

3.9.1

### vue-chartjs version

4.1.1

### Possible solution

Change the supported version of Vue to 3.2.24 or higher.

**Comment by dangreen** [comment]
Currently, we don't use this type at all
