### ISSUE TITLE
[Bug]: Filling option for Line Chart not working

### ISSUE THREAD

**Issue by philmuze** [apertureless/vue-chartjs#914]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I would like to fill the area below the line in the line chart but the option `fill: 'origin'`seems not to be working. 

ChartJS Filling modes: https://www.chartjs.org/docs/2.9.4/charts/area.html#filling-modes 

Added the styling like this:

```js
    const chartData = {
      labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
      datasets: [
        {
          label: 'Data One',
          backgroundColor: '#f87979',
          fill: 'origin', // not working
          data: [40, 39, 10, 40, 39, 80, 40]
        }
      ]
    }
```

Checked it back on the ChartsJS docs https://www.chartjs.org/docs/latest/samples/line/styling.html. I was able to use the fill option.

![Screenshot 2022-09-01 at 11 59 34](https://user-images.githubusercontent.com/1415444/187887725-fe77470a-239e-479f-ae23-ad3f59a5ec6f.jpg)

So yeah, I'm little bit confused where this issue may occur. I checked a little bit the vue-chartjs code and the options are just props I guess. Maybe you have an idea how to get it working. Thanks!

### Reproduction

https://codesandbox.io/s/busy-ace-p9n70i?file=/src/components/lineChart.ts

### chart.js version

v3.9.1

### vue-chartjs version

v4.1.1

**Comment by manusanchev** [comment]
I had the same problem, you have to register the `Filler` plugin

**Comment by philmuze** [comment]
@manusanchev awesome! It's working. Thanks.
