### ISSUE TITLE
[Bug]: Chart Option not working in Nuxtjs

### ISSUE THREAD

**Issue by geofany** [apertureless/vue-chartjs#927]
### Current and expected behavior

plugins/chart/bar.js
![carbon (6)](https://user-images.githubusercontent.com/37582643/192270354-b5e1b6de-ba58-444d-bd59-5949b452f7c6.png)

chart.vue
![carbon (5)](https://user-images.githubusercontent.com/37582643/192270402-6e08f77c-3775-4501-82a7-ed432acb3d99.png)

Result : 
![image](https://user-images.githubusercontent.com/37582643/192269543-fb7fd531-1154-4ad2-82ad-280aa713f14e.png)

legend and gridLines still there

### chart.js version

v3.9.1

### vue-chartjs version

v4.1.1

**Comment by apertureless** [comment]
https://www.chartjs.org/docs/latest/configuration/legend.html

```js
options.plugins.legend = false
```

**Comment by geofany** [comment]
there is migration Guide for v.3.x
https://www.chartjs.org/docs/latest/getting-started/v3-migration.html

and it's work for me
![carbon (7)](https://user-images.githubusercontent.com/37582643/192274888-0c17bc0a-cd96-4360-918d-78bd4895082d.png)
