### ISSUE TITLE
Not understanding options

### ISSUE THREAD

**Issue by treaves** [apertureless/vue-chartjs#93]
I'm trying to set custom options on a chart.  I had tried passing them in as an option, but, that didn't work.  So to make things simple for testing, I just used an in-line object.

    mounted() {
      // Overwriting base render method with actual data.
      this.renderChart(this.chartData, {
        elements: {
          backgroundColor:    'rgba(102,255,102,0.5)',
          line:               {
            backgroundColor:  '#1d3',
            borderColor:      '#1d3'
          }
        }
      })
    }

None of these three options is making any difference.  It looks to be the correct format as per the Chart.js documentation, and passing it is as per the vue-chartjs documentation.

Am I doing something incorrectly?  Any help appreciated.

### Environment
- vue.js version: 2.2.6
- vue-chart.js version: 2.6.0
- npm version: 4.1.2

**Comment by apertureless** [comment]
There is no `elements` object in the global options. Neither a `line` object. 
If you want to set the color of the linechart line, you can set it in the datasets. 

Check out the [dataset structure](http://www.chartjs.org/docs/#line-chart-dataset-structure) or the [examples](https://github.com/apertureless/vue-chartjs/blob/develop/src/examples/LineExample.js). I also wrote a tutorial on [more advanced stylings](https://hackernoon.com/creating-stunning-charts-with-vue-js-and-chart-js-28af584adc0a)

The global options are for things like the grid, xaxis, yaxis, labels, legend, tooltips and so on. Some default options are set in the [base charts](https://github.com/apertureless/vue-chartjs/blob/develop/src/BaseCharts/Line.js#L41-L58)

**Comment by treaves** [comment]
Thanks for the link, I'll check it out.

http://www.chartjs.org/docs/#chart-configuration-element-configuration

Is that not the correct documentation?

**Comment by treaves** [comment]
Oh, and this is a radar chart.  Don't know that makes a difference.

**Comment by Pokom** [comment]
@treaves 
I would first ask if you are having issues to please duplicate the issue in [codepen](http://codepen.io/) or some other site where we can test it out, make alterations, correct and then respond. If you need help doing this, let me know. This will make this process much easier, as we do not want to generate long email chains for use case issues like this. Pop into gitter if you can as well, I'm normally on it or will respond in a respectful time. 

The issue you're having is simply a naming issue. When you pass in options, you pass it in without a root element like so:

```` javascript
import { Pie, mixins } from 'vue-chartjs'

const { reactiveProp } = mixins
const defaults = {
  responsive: true,
  maintainAspectRatio: false,
  animation: {
    duration: 0
  }
}

export default Pie.extend({
  mixins: [reactiveProp],
  props: ['options'],
  mounted () {
    this.renderChart(this.chartData, this.options || defaults)
  }
})
````
Please post a codepen or similar type of example if you're still having difficulties!

**Comment by apertureless** [comment]
Oh now I see.  :bulb: 

Well in Chart.js there are two ways of make settings. One way is over the `options` and one way is over the `Chart.global.defaults` .

If you check out the documentation for the [Legend](http://www.chartjs.org/docs/#chart-configuration-legend-configuration) for example there is a note

> The legend configuration is passed into the options.legend namespace. The global options for the chart legend is defined in Chart.defaults.global.legend.

Everything whats defined or available over `options.xyz` can be passed in the `renderChart()` method as the second parameter.  For example settings for the axis, labels, tooltips etc. 

But this is only on a per chart basis. Or better said on a per chart instance basis.  The `Chart.global.defaults` should be like the name says, the defaults for all instances.


However what you're trying to do it to set the *global.defaults* of the chart element. 
But to set them, you will need to access the `Chart` instance. To be honest, I never tried to overwrite the global defaults. But you can try it like in the docs:

` Chart.defaults.global.elements.backgroundColor = 'rgba(102,255,102,0.5)'`

But you have to do it, in for example the `mounted()` or `created()` hook of your component. __Before__ you call `renderChart()`

The `Chart` object is the one imported with `import Chart from 'chart.js'` in the base charts. So you have full access to this one.

**Comment by treaves** [comment]
@apertureless No, I'm not trying to change the global options.  Just for this chart.  I should have pasted http://www.chartjs.org/docs/#radar-chart-chart-options instead.  It states elements.line, which looks to me like the options object should have an elements object which should have a lines object.

@Pokom I'll recreate this in codepen and post a link.

**Comment by apertureless** [comment]
@treaves oh true. there is a options.elements :see_no_evil: 

I guess the problem is the backgroundColor you placed inside the elements object. 
You should check the valid objects in the chartjs docs.

No problems with line.borderWidth and line.borderColor tho,

https://codepen.io/apertureless/pen/qmZjrV?editors=1010

**Comment by treaves** [comment]
O.K. the codepen helped me figure it out.  I hand't used that before.  

Thanks all.
