### ISSUE TITLE
vue-chartjs V4 with mixed chart type using Typescript

### ISSUE THREAD

**Issue by mcelligottnick** [apertureless/vue-chartjs#935]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

Trying to use a mixed chart but can't find a way to implement. Have looked at;

- [123](https://github.com/apertureless/vue-chartjs/issues/123) - But I get `Bar.extend` is not a function
- [29](https://github.com/apertureless/vue-chartjs/issues/29) - But I get `Chart.Bar.extend` is not a function

I'm not able to see a way to do this with V4 and TS.

### Describe the solution you'd like

Ability to create new custom mixed chart.

**Comment by mcelligottnick** [comment]
Okay got this working by;

- Using the regular Bar component
- Ensuring I registered the regular BarController and BarElement needed for the Bar component, but then also the LineController to handle the line type dataset
- Don't use any specific typing for the datasets, ie ChartData<'bar'>

**Comment by ArturoTorresMartinez** [comment]
> Okay got this working by;
> 
> * Using the regular Bar component
> * Ensuring I registered the regular BarController and BarElement needed for the Bar component, but then also the LineController to handle the line type dataset
> * Don't use any specific typing for the datasets, ie ChartData<'bar'>

Howdy, I know this is solved but could I see a snippet of your solution?

**Comment by mcelligottnick** [comment]
@ArturoTorresMartinez this is very stripped down and not exactly working, but this should give you an idea. Note the main thing you have to populate is the `datasets` array.

```
<template>
	<Bar
		v-if="activities.length > 0"
		:chart-data="chartData.data"
		:chart-options="chartData.options"
		:height="200"
	/>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Bar } from 'vue-chartjs';
import { Chart, BarElement, LineController } from 'chart.js';

Chart.register(BarElement, LineController);

export default defineComponent({
	components: { Bar },
	computed: {
		chartData() {
			// can't get any correcty typings working here, I think because
			// we are using a mixed chart type
			const d = {
				data: {
					datasets: [],
				},
				options: {
					scales: {
						monetary: {
							position: 'right',
							ticks: {
								beginAtZero: true,
							},
							title: {
								display: true,
								text: 'Monetary',
							},
						},
						acc: {
							position: 'left',
							ticks: {
								beginAtZero: true,
							},
							grid: {
								// only want the grid lines for one axis to show up
								drawOnChartArea: false, 
							},
							title: {
								display: true,
								text: 'Accumulative',
							},
						},
					},
				},
			} as any;
			return d;
		},
	},
});
</script>
```

**Comment by ArturoTorresMartinez** [comment]
@mcelligottnick I cannot thank you enough for taking the time to send this, it worked for me.
AND on Thanksgiving 🦃 

You are my hero, thanks 🙇

**Comment by mcelligottnick** [comment]
I'm glad mate!

**Comment by ArturoTorresMartinez** [comment]
A last note I'd like to add for anyone looking into this in the future, in case anyone is using the legacy version for Vue 2 
(`import { Pie, Bar } from "vue-chartjs/legacy";`) as I am, is to also make sure you're importing `LineElement`, and `PointElement` in addition to the already mentioned `LineController` from `chart.js` to avoid that infinite loop error.

Hope that helps someone else too
