### ISSUE TITLE
[Bug]: Custom charts do not call draw() function

### ISSUE THREAD

**Issue by Shujee** [apertureless/vue-chartjs#937]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I have followed the steps described in the docs on how to create a custom chart. My custom controller class inherits from `BubbleController` (I'm using Vue 3 with TypeScript and Vite). After much hassle, I have finally made it to the point where it actually displays bubbles in the output, but it doesn't seem to call my override of the `draw()` function. I have placed a few `console.log()` calls at the very start of the `draw()` function, but those lines are not hit.

I then checked the online example of custom charts and interestingly, even the example in the docs is suffering from the same problem. The [custom chart example](https://codesandbox.io/s/github/apertureless/vue-chartjs/tree/main/sandboxes/custom) does not call the draw() function. I added a few `console.log()` calls here too, but there is no output in the output console. Also, there is no "line with line" as suggested by the class name.

### Reproduction

https://codesandbox.io/s/github/apertureless/vue-chartjs/tree/main/sandboxes/custom?file=/src/components/customChart.ts

### chart.js version

v3.9.1

### vue-chartjs version

v4.1.2

**Comment by LukasOchmann** [comment]
I have the same issue

**Comment by dangreen** [comment]
@Shujee  @LukasOchmann Hi. Here is fixed example: https://github.com/apertureless/vue-chartjs/blob/main/sandboxes/custom/src/components/LineWithLineChart.ts
