### ISSUE TITLE
Zoom And Pan Options in Vue Charts

### ISSUE THREAD

**Issue by arunrreddy** [apertureless/vue-chartjs#94]
This would be a handy enhancement. There is a repo called which does exactly this - chartjs-plugin-zoom.js(https://github.com/chartjs/chartjs-plugin-zoom). 
This feature would be good if it was integrated for Vue for both the axes of a chart.

**Comment by apertureless** [comment]
Well, vue-chart.js is only a wrapper for Chart.js 
So functions like this would be rather an imporvement for chart.js

However as we are using Chart.js under the hood, you can use any chart.js plugins available! So you can also use the `chartjs-plugin-zoom`

**Comment by arunrreddy** [comment]
I had tried to incorporate it but it did not work.

**Comment by apertureless** [comment]
Well for me its working :see_no_evil: 

https://codepen.io/apertureless/full/KmWmKp/

**Comment by lionel-bijaoui** [comment]
Here is an example of incorporation into a webpack project :  
```js
import { Line, mixins } from 'vue-chartjs';
import zoom from 'chartjs-plugin-zoom';
const { reactiveProp } = mixins;

export default Line.extend({
    mixins: [reactiveProp],
    props: ['options'],
    mounted() {
        this.addPlugin(zoom);
        // this.chartData is created in the mixin
        this.renderChart(this.chartData, this.options);
    }
});
```

**Comment by vlad909** [comment]
@lionel-bijaoui, tnx very much :)

**Comment by ppirrip** [comment]
hi, chartjs-plugin-zoom works well with my vue-chart.js setup, however, I have some problem with resetting the zoom (resetZoom()). From the [example](https://github.com/chartjs/chartjs-plugin-zoom/blob/master/samples/zoom-time.html), I need to access to the chart object (window.myLine = new Chart(ctx, config)) to access the function (e.g. window.myLine.resetZoom()), but I have no idea how. Anyone encounter this before?

**Comment by nauhalf** [comment]
> Here is an example of incorporation into a webpack project.
> Very basic example from the [quick start](http://vue-chartjs.org/#/home?id=quick-start):
> 
> ```js
> // CommitChart.js
> import { Bar } from 'vue-chartjs'
> import zoom from 'chartjs-plugin-zoom';
> 
> export default Bar.extend({
>   mounted () {
>     this.addPlugin(zoom);
>     // Overwriting base render method with actual data.
>     this.renderChart(data, options)
>   }
> })
> ```
> 
> Very basic example with reactive data from the [doc](http://vue-chartjs.org/#/home?id=example):
> 
> ```js
> import { Line, mixins } from 'vue-chartjs';
> import zoom from 'chartjs-plugin-zoom';
> const { reactiveProp } = mixins;
> 
> export default Line.extend({
>     mixins: [reactiveProp],
>     props: ['options'],
>     mounted() {
>         this.addPlugin(zoom);
>         // this.chartData is created in the mixin
>         this.renderChart(this.chartData, this.options);
>     }
> });
> ```
> 
> Don't forget to add the options !

@lionel-bijaoui I try this method, it works on zoom and pan. But my ticks yAxes callback not working. It reset to default after first time zoom.

Before Zoom
![image](https://user-images.githubusercontent.com/43662706/97822315-0d88ed80-1ce8-11eb-9424-4633dd06a297.png)
 
After Zoom
![image](https://user-images.githubusercontent.com/43662706/97822355-2d201600-1ce8-11eb-8246-02585da65370.png)

This is my options
`extraOptions: {
          responsive: true,
          hoverMode: "index",
          stacked: false,
          elements: {
            line: {
              tension: 0
            }
          },
          scales: {
            yAxes: [
              {
                ticks: {
                  callback: label => numeral(label).format("0.00 a")
                }
              }
            ]
          },
          tooltips: {
            callbacks: {
              label: function(tooltipItem, data) {
                    var label = data.datasets[tooltipItem.datasetIndex].label || '';

                    if (label) {
                        label += ': ';
                    }
                    label += numeral(tooltipItem.yLabel).format("0.00 a");
                    return label;
                }
            }
          },
          plugins: {
            zoom: {
              pan: {
                enabled: true,
                mode: "x" // is panning about the y axis neccessary for bar charts?
              },
              zoom: {
                enabled: true,
                mode: "x",
                sensitivity: 2
              }
            }
          }
        }`


Is it bug from zoom plugin or vue-chartjs ? Thank you

**Comment by vbersier** [comment]
I have the same issue as @nauhalf . My options in terms of scales seem to be completely lost after the first interaction with the chart (zoom or pan). I believe this is because the plugin calls the chart update method but doesn't pass the options object defined in the component's data (like we're supposed to do with Vue). Any way to make this work or is it a lost cause?

**Comment by nauhalf** [comment]
@vbersier After many tried, I found that in only lost the callback on new version library. I change the version of the libraries like this.

vue-chart-js: ^3.5.0
chart.js: ^2.9.3
chartjs-plugin-zoom: ^0.7.7

I hope it works well for you too.

**Comment by vbersier** [comment]
Thanks @nauhalf , since I could not really wait I implemented my own zoom function with sliders next to the axes but maybe that will help developers figure out what changed.
