### ISSUE TITLE
Support for chart.js@4

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [apertureless/vue-chartjs#940]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

Not sure if there's something more needed than just updating peer dep version in https://github.com/apertureless/vue-chartjs/blob/main/package.json#L74 and dep version in https://github.com/apertureless/vue-chartjs/blob/main/package.json#L100

EDIT: Sorry, I mistakenly checked the checkbox above

**Comment by apertureless** [comment]
https://www.chartjs.org/docs/latest/migration/v4-migration.html

From the migration guide, it does not look like any breaking changes happend in terms of chart initialization etc.

**Comment by dangreen** [comment]
@apertureless Chart.js has become an ESM-only package. We need to make vue-chartjs also ESM-only. I'll take care of it.

**Comment by bobvandevijver** [comment]
Well, if you ignore the peer dependency warning it just works fine 😃

**Comment by euoia** [comment]
Indeed, `npm install --force` - vue-chartjs seems to work. with Chart.js v4.
