### ISSUE TITLE
[Bug]: TypeScript mismatch with time carthesian axis

### ISSUE THREAD

**Issue by Drillan767** [apertureless/vue-chartjs#945]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

First of all: the library itself **works**, the issue only concerns the format that vue-chartjs  expects.

I'm building a small projects that displays data in 3 different graphs, and the project uses Vue 3 with typescript.

I use the Pie, (stacked vertical) Bars and Line. For both Line and Bars, I use time carthesian axis to show my data according to their creation date. However, it fails on build because `chart-data` expects the data attribute to be an array of numbers, but I give it the following format:

```
{
    label: string,
    backgroundColor: string,
    data: {
        x: string,
        y: string,
    }[]
}
```

The graphs display without trouble, but I get errors when building it because of this problem.

### Reproduction

https://codesandbox.io/s/smoosh-shape-ug1dld

Check the file `/src/components/barChart.ts` line 94 for the issue.

### chart.js version

3.9.1

### vue-chartjs version

4.1.2

### Possible solution

Allow both `number[]` and something such as `{x: string, y: string}[]` as possible parameters. Apologies, I'm not very fluent in TypeScript yet so I'm not really precise.

**Comment by apertureless** [comment]
Looks like you can set Objects as data https://www.chartjs.org/docs/latest/general/data-structures.html#object
And also custom objects where you specify parsing options: https://www.chartjs.org/docs/latest/general/data-structures.html#object-using-custom-properties

Need to update our ts types for this.

**Comment by dangreen** [comment]
@Drillan767 Hi. It's not a problem with vue-chartjs, if you try to set type directly, you are also will get an error, so it is a problem in Chart.js types, not in vue-chartjs

```ts
const chartData: ChartData<'bar'> = {...}
```

**Comment by P4sca1** [comment]
Chart.js typings expect datasets to be of type `number[]` or something similar, depending on the chart type, by default.
However, this can be easily changed, e.g.:

```ts
ChartData<'line', { x: string; y: number | null }[]>
```

**Comment by nakai-omer** [comment]
> Chart.js typings expect datasets to be of type `number[]` or something similar, depending on the chart type, by default. However, this can be easily changed, e.g.:
> 
> ```ts
> ChartData<'line', { x: string; y: number | null }[]>
> ```

@P4sca1 Can you please elaborate on how this can easily be changed? I am currently getting a typescript error for my data prop, and inside vue-chartjs i don't see an option to change the type of the data prop:
![image](https://user-images.githubusercontent.com/108797279/234269553-cb848c57-a4de-489c-8b79-7c078766c9cd.png)

Seems to be hardcoded inside vue-chartjs:
```
export declare const Line: TypedChartComponent<"line", (number | import("chart.js").Point | null)[], unknown>;
```
Which means the data can only be, number | point | null

**Comment by P4sca1** [comment]
vue-chartjs does not allow to change the chart data type, which is why you get the error. This looks like a bug / unsupported feature of vue-chartjs.

**Comment by laventnc** [comment]
seems like this should be reopened. pretty annoying that the most common chart use case (historical data with string x data), causes an error in typescript.

it honestly seems like more of a chartjs issue: https://github.com/chartjs/Chart.js/issues/11611

**Comment by dsvgl** [comment]
Same thing here. I typed the data to fit my needs. But Typescript complains about `:data` on `<Line>` then.
Can this be fixed?
