### ISSUE TITLE
[Bug]: Still problem with Vue 2.7

### ISSUE THREAD

**Issue by frufin** [apertureless/vue-chartjs#975]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

HI,
I'm using vue-cli & Vue 2.7.10
Both vue-chartjs & chart.js successefully installed using Yarn

I get an error trying to import vue-chartjs from a component:

`import { Bar } from 'vue-chartjs'`

=>

```
Failed to compile.

./src/components/main/views/server/Status.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/main/views/server/Status.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'vue-chartjs' in '/Users/fredericrufin/Sites/webapachekit/src/components/main/views/server'
```

### Reproduction

Failed to compile.  ./src/components/main/views/server/Status.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/main/views/server/Status.vue?vue&type=script&lang=js&) Module not found: Error: Can't resolve 'vue-chartjs' in '/Users/fredericrufin/Sites/webapachekit/src/components/main/views/server'

### chart.js version

4.0.1

### vue-chartjs version

5.0.1

**Comment by dotob** [comment]
same here

**Comment by apertureless** [comment]
As vue-chartjs 5 is esm only, have you set your project type to module in package.json ? 
https://vue-chartjs.org/migration-guides/#esm

**Comment by dangreen** [comment]
@frufin @dotob Hi. I can offer 3 options here:

1) Migrate to ESM, as @apertureless said
2) [Configure webpack](https://github.com/chartjs/Chart.js/issues/10911#issuecomment-1326714877)
3) Soon, Chart.js will be released with restored CommonJS support. We will restore CommonJS support too, so you can wait for the release with it.

**Comment by frufin** [comment]
Hi @apertureless & @dangreen 
I suspected this problem...

- Setting "type":"module" inside package.json does nothing through my actual workflow (vue-cli, webpack4)
- i'm pulling my hair trying to configure webpack resolve/conditionNames

Unless you have a solution to propose, I think I'll have to downgrade charts.js and vue-chartjs while waiting for commonJS support...

**Comment by frufin** [comment]
Seems to work using version 5 from CDN

**Comment by dangreen** [comment]
@frufin Hi. Chart.js v4.1 and vue-chartjs v5.1 were released with restored CommonJS support.

https://vue-chartjs.org/migration-guides/#esm

**Comment by nthungdev** [comment]
> @frufin Hi. Chart.js v4.1 and vue-chartjs v5.1 were released with restored CommonJS support.
> 
> https://vue-chartjs.org/migration-guides/#esm

Works for me now. Thank you very much!
