### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hekep** [apertureless/vue-chartjs#976]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Chrome error message:

runtime-core.esm-bundler.js:228 TypeError: Cannot read properties of undefined (reading 'map')
    at setDatasets (index.js:55:1)
    at cloneData (index.js:78:1)
    at renderChart (index.js:124:1)
    at runtime-core.esm-bundler.js:2739:1
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2713:1)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:343:1)
    at flushJobs (runtime-core.esm-bundler.js:397:1)
logError @ runtime-core.esm-bundler.js:228

Firefox errormessage is:
14:28:53.294 TypeError: nextDatasets is undefined
    setDatasets index.js:55
    cloneData index.js:78
    renderChart index.js:124
    createHook runtime-core.esm-bundler.js:2739
    callWithErrorHandling runtime-core.esm-bundler.js:157
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    __weh runtime-core.esm-bundler.js:2713
    flushPostFlushCbs runtime-core.esm-bundler.js:343
    flushJobs runtime-core.esm-bundler.js:397
    promise callback*queueFlush runtime-core.esm-bundler.js:282
    queuePostFlushCb runtime-core.esm-bundler.js:304
    queueEffectWithSuspense runtime-core.esm-bundler.js:1585
    scheduler runtime-core.esm-bundler.js:1820
    triggerEffect reactivity.esm-bundler.js:397
    triggerEffects reactivity.esm-bundler.js:387
    triggerRefValue reactivity.esm-bundler.js:1011
    effect reactivity.esm-bundler.js:1137
    triggerEffect reactivity.esm-bundler.js:397
    triggerEffects reactivity.esm-bundler.js:382
    triggerRefValue reactivity.esm-bundler.js:1011
    effect reactivity.esm-bundler.js:1137
    triggerEffect reactivity.esm-bundler.js:397
    triggerEffects reactivity.esm-bundler.js:382
    triggerRefValue reactivity.esm-bundler.js:1011
    set value reactivity.esm-bundler.js:1048
    finalizeNavigation vue-router.mjs:3334
    pushWithRedirect vue-router.mjs:3207
    promise callback*pushWithRedirect vue-router.mjs:3174
    push vue-router.mjs:3099
    install vue-router.mjs:3530
    use runtime-core.esm-bundler.js:4381
    start client-entry.js:116
    4043 client-entry.js:161
    promise callback*4043/< client-entry.js:159
    promise callback*4043 client-entry.js:135
    Webpack 5
runtime-core.esm-bundler.js:228

### Reproduction

could not reproduce this publicliy

### chart.js version

4.0.1

### vue-chartjs version

5.0.1

### Possible solution

It looks like empty object is passed to vue-charts.

Make more foolproof, give better errormessage

**Comment by hekep** [comment]
Hello:

So here it is reproduced:
https://codesandbox.io/s/sleepy-http-jw68t7?file=/src/pages/Index.vue
Error message is:
```
setDatasets@webpack-internal:///./node_modules/vue-chartjs/dist/index.js:73:5
cloneData@webpack-internal:///./node_modules/vue-chartjs/dist/index.js:93:16
renderChart@webpack-internal:///./node_modules/vue-chartjs/dist/index.js:139:41
createHook/</<@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:2865:44
callWithErrorHandling@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:286:22
callWithAsyncErrorHandling@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:295:42
injectHook/hook.__weh@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:2839:55
flushPostFlushCbs@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:469:47
flushJobs@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:523:26
```

**Comment by apertureless** [comment]
Adding a `v-if="v-if="myAppGraphData"` to your `<Bar>` component should fix your issue. (And setting the initial value to null) 
`const myAppGraphData = ref(null);`

You are initializing your variable as an empty object. And only setting the data in the mounted hook. So basically you are trying to mount the chart with no data. Chartjs will try to get the datasets, but the object that is passed is empty. And it breaks.

After then in mounted it sets the data but then its already to late.

**Comment by dangreen** [comment]
@hekep Hi. `datasets` property in `data` is required.

**Comment by hekep** [comment]
Thanks for all the replies.  
I am relatively new to Vue and Charts. 
I wish it was more foolproof.

My understaning has been, that when I  define something

```
const myAppGraphData =  ref(null)
```
then the  data type should not change later, example  ` ref({}) `.

Initial data suppose to be null ( or empty object ) , because, the chart data that wibe provided by API call/response.

**Comment by apertureless** [comment]
If you have an api call, you most likely have a loading state. Which you can set.

```js
const loading = ref(false)

loading.value = true
await fetch('....')
loading.value = false
```

Then you can have a `v-if="!loading"` on your chart. 

The chart will be rendered and mounted, before the mounted() hook finishes. So your problem was, that you was trying to init the chart with an empty object for data. Which will not work. 

So you need to make sure that the chart renders only if you have all your data in place. How you achieve this, is your responsibility.
