### ISSUE TITLE
Why do I need both vue-chartjs chart.js?

### ISSUE THREAD

**Issue by kodekrendel** [apertureless/vue-chartjs#98]
Your documentation says: `yarn add vue-chartjs chart.js`

Why do I need to install both?

**Comment by kodekrendel** [comment]
Ok I read. As always @apertureless has it's own way :smile:

**Comment by apertureless** [comment]
@kodekrendel  
Well because this way chart.js is **not** bundled the lib. The advantage is, that if theres a new version of chart.js gets released you could use it without waiting for me, to update the dependencies.

**Comment by OmgImAlexis** [comment]
@apertureless is there really a need for the lib to be left out though? The docs make it seem like you should be able to just add this package and be done with it.

> If you are working with Vue.js 2+ simple run:
> `yarn add vue-chartjs`
>
> If you are using vue 1.x please use the legacy tag. However the vue 1 version is not maintained anymore.
> `yarn add vue-chartjs@legacy`

**Comment by apertureless** [comment]
@OmgImAlexis 

Oh yeah thats an error in the docs. In the earlier versions of `vue-chartjs` Chart.js got bundled into it. Thats why you only needed to install `vue-chartjs`. Later as chart.js got added as a peerDependency you need to install it explicitly.

However in the vue 1.x version it is still bundled into it.
