### ISSUE TITLE
[Bug]:  'chartData' is declared here

### ISSUE THREAD

**Issue by bkawakami** [apertureless/vue-chartjs#984]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

So, I don't know why, but when I tried using any kind of chart, my Vue 3 + Vite show me this errors.

<img width="918" alt="Screenshot 2022-12-22 at 14 57 08" src="https://user-images.githubusercontent.com/1881935/209197019-68953642-c4c3-4e3d-b738-18531b4b607f.png">

### Reproduction

Create a simples version of Vue 3 + Vite, and try use vue-chartjs

### chart.js version

v4.1.1

### vue-chartjs version

v5.1.0

**Comment by bkawakami** [comment]
Oh, additionally, I correctly add the imports.

```vue
<script setup lang="ts">
import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Title,
    Tooltip,
    Legend,
    BarElement
} from 'chart.js'
import { ref, watch } from 'vue'
import { BaseRequest } from "@/services/BaseRequest"
import { Line, Bar } from 'vue-chartjs'

ChartJS.register(
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Title,
    Tooltip,
    Legend,
    BarElement
)
</script>
```

**Comment by dangreen** [comment]
@bkawakami Hi. Please provide repo with minimal reproduction.

**Comment by dangreen** [comment]
Closed due to inactivity.
