### ISSUE TITLE
[Bug]: Tooltips -> callbacks not working in v4!

### ISSUE THREAD

**Issue by mirzobedil** [apertureless/vue-chartjs#986]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

![image](https://user-images.githubusercontent.com/45965774/209464790-d3864eaa-790c-43ed-a24e-ead3e47f6eac.png)
I'm using v4 version of package and vue3, tooltips -> callbacks not working!

### Reproduction

https://stackblitz.com/edit/github-kwanbh-qgmzmz?file=src%2FchartConfig.ts

### chart.js version

v3.9.1

### vue-chartjs version

v4.1.1

**Comment by dangreen** [comment]
@mirzobedil Hi. There are no `tooltips` options. There is tooltip plugin options: 

https://www.chartjs.org/docs/latest/configuration/tooltip.html#tooltip-configuration

```
export const options = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    tooltip: {
      callbacks: {
        label: function (tooltipItem) {
          return '0';
        },
      },
    },
  }
};
```
