### ISSUE TITLE
Implement custom event

### ISSUE THREAD

**Issue by frufin** [apertureless/vue-chartjs#987]
### What problem are you trying to solve?

I need to catch dbclick events on line points.
This is possible from chart.js defining a 'customEventListener' plugin,  but how to do using the vue-chartjs syntax ?

### Describe the solution you'd like

```
plugins:
   { customEventListener: {
        afterEvent: (chart, evt, opts) => {
             if (evt.event.type !== 'dblclick') {
                return
             }
              console.log(evt.event.type, evt.event.x, evt.event.y)
            },
        },
 },
```

Thanks !

**Comment by dangreen** [comment]
@frufin Hi. Chart components have the `plugins` prop. You'll be able to pass your plugin there.

https://vue-chartjs.org/api/
