### ISSUE TITLE
It seems that the reactiveProp couldn't let the chart update itself

### ISSUE THREAD

**Issue by daiyanze** [apertureless/vue-chartjs#99]
### Expected Behavior
update chart when data changes

### Actual Behavior
`
Throws error:
[Error] TypeError: undefined is not an object (evaluating 'element._view.skip')
`

After I looked for it on google, it's said that chart.update is never called when data changes. 
I think the problem happens in watch, because it seems the handler is never called.
``` javascript
watch: {
  'chartData': {
     handler: {
      ...
     }
   ...
  }
}
```
Thank you.

### Environment
- vue.js version: 2.2.6
- vue-chart.js version: 2.6.1
- npm version: 4.2.0

**Comment by apertureless** [comment]
Please provide a codepen oder jsfiddle for reproduction.
It rather seems that there is a problem with the dataset or options.

**Comment by apertureless** [comment]
Closed due to inactivity.
