### ISSUE TITLE
[Bug]: Uncaught Error: Cannot find module 'vue-chartjs'

### ISSUE THREAD

**Issue by jquirogaa** [apertureless/vue-chartjs#990]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I am trying to use this library migrating from `vue-chartjs-3`. Followed the migrating doc but nothing happens except for the error

![image](https://user-images.githubusercontent.com/95649309/210159748-67833d97-116d-43b5-b7ff-14d2d56a1df2.png)

```
<template>
  <Line v-if="chartData" ref="chartRef" :data="chartData" :options="options" />
</template>

<script>
import { defineComponent, ref } from "vue";
import { Line } from 'vue-chartjs';
import { Chart, registerables } from "chart.js";
import { useStore } from "vuex";
import ChartDataLabels from "chartjs-plugin-datalabels";

......
```

### Reproduction

I don't think I can provide such a repo

### chart.js version

4.1.1

### vue-chartjs version

5.1.0

### Possible solution

No idea to be honest. I already tried the migration thing to use it but I haven't made it yet!

**Comment by jquirogaa** [comment]
I am using Vue3

**Comment by dangreen** [comment]
@jquirogaa Hi. Please provide repo with minimal issue reproduction.

**Comment by kltb** [comment]
I got a different error when using vue-chartjs 5.2.0 but upgrading to use webpack5 in my project fixed the issue
