### ISSUE TITLE
[Bug]: On multiple datasets, datasets 1+n get redrawn on every update

### ISSUE THREAD

**Issue by HOTAPIYC** [apertureless/vue-chartjs#991]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

## Current Behavior

I have a line chart with multiple datasets. Now the following issues can be observed:

- When dataset 0 is updated, the chart adjusts as expected, however at the same time all other datasets are redrawn, regardless whether they changed or not
- When dataset 1 changes and dataset 0 remains static, the chart of dataset 0 remains as it is, however instead of just readjusting the chart, the chart of dataset 1 and the charts of all other datasets are redrawn

I hope this is understandable, you can assign the periodically updated `values1` in the reproduction sample to the different datasets to see what I mean.

The same behavior can be observed for barcharts aswell as far as I could see. The constant redrawing animation is really annoying and makes it impossible to use these charts for data that is frequently updated.

## Expected

When a set of values changes for a dataset, only this dataset is updated and the others are not touched. Additionally the chart is not completely redrawn everytime but simply adjusts to the new values.

This seems not to be an issue with Chart.js, see the vanilla solution here:

https://codesandbox.io/s/chart-js-update-vanilla-68t5dy?file=/index.html

This behavior is also true for the latest version of `vue-chartjs`, however I was not able to use this package with codesandbox.io. Therefore I referenced only the versions here that I could use in the reproduction sample. This might be another issue to have a look into.

### Reproduction

https://codesandbox.io/s/chart-js-update-vue-chartjs-28jths?file=/src/App.vue

### chart.js version

3.9.1

### vue-chartjs version

4.1.2

**Comment by dangreen** [comment]
@HOTAPIYC Hi. Please use the `label` property to identify each dataset: https://codesandbox.io/s/chart-js-update-vue-chartjs-forked-cnlz58?file=/src/App.vue

in v5 you can pass a custom name property with the `datasetIdKey` component prop: https://vue-chartjs.org/api/#props
