### ISSUE TITLE
[Bug]: Options API reactivity

### ISSUE THREAD

**Issue by ph1823** [apertureless/vue-chartjs#992]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Current:

I get a error when I put new data on my dataset using Option API

Firefox: Uncaught InternalError: too much recursion
Edge: Uncaught RangeError: Maximum call stack size exceeded

Behavior: No recursion or max stack size error using option API

### Reproduction

https://github.com/ph1823/vuechartjs-bug

### chart.js version

v4.1.1

### vue-chartjs version

v5.1.0

### Possible solution

I have dont realy ideas how to fix this.
Maybe by changing the watching in option api.
The only thing I know is that I migrated this component to Composition API and that work.

I use Vue JS 3.2.45

**Comment by dangreen** [comment]
@ph1823 Hi. You shoudn't mutate data from computed properties. Move all data which you want to mutate into the `data() {}`

**Comment by ph1823** [comment]
> @ph1823 Hi. You shoudn't mutate data from computed properties. Move all data which you want to mutate into the `data() {}`

Same problem, i move chartData in "computed" because i see this on your document.
But the problem is same, Whether they put me in "" or in "data"

I have update my exemple. 
I have ask this problem on stackoverflow on December, but no reply :(
I am sorry if its not a reall bug

**Comment by dangreen** [comment]
@ph1823 just replace `mounted` with `created`

https://vuejs.org/api/options-lifecycle.html#created
